/-
Chambers slice of the StabilityCondition audit, split out so concurrent
branches append to different files (#480). See the umbrella file for the contract and reading guide.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition

/-! ## Charge-vanishing walls, regular loci, and chambers -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.stabilityChargeFamily
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.stabilityChargeFamily_charge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.chargeZeroLocus
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.chargeZeroLocus_eq_family_zeroLocus
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.mem_chargeZeroLocus_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.chargeRegularLocus
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.mem_chargeRegularLocus_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.chargeRegularLocus_antitone
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.chargeRegularLocus_univ
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.chargeRegularLocus_eq_compl_iUnion
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.combined_smul_mem_chargeZeroLocus_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.image_chargeZeroLocus_smul
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.image_chargeZeroLocus_gltilde
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.combined_smul_mem_chargeRegularLocus_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.image_chargeRegularLocus_smul
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.ChargeChamber
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.chargeChamberOf

/-! ## Topology of walls and finite regular loci -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.continuous_chargeAt_of_mem_range
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.continuous_chargeAt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.isClosed_chargeZeroLocus
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.isOpen_chargeRegularLocus

/-! ## Symmetry actions on regular loci and chambers -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.IsAutStable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.isAutStable_univ
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.IsAutStable.inter
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.ChargeZero.IsAutStable.image_lam
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.chargeRegularLocusMulAction
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.chargeRegularLocusContinuousConstSMul
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.chamberSmul
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.chamberHomeomorph
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.chamberStabilizer
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.chamberActionHom
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.combinedActionKernel_le_chamberActionHom_ker
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.effectiveChamberActionHom
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.effectiveCombinedChamberMulAction
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.GroupAction.effectiveCombinedChamber_smul_coe
