/-
Constant-sheaf/pullback slice of the StabilityCondition audit, split out so concurrent
branches append to different files (#480). See the umbrella file for the contract and
reading guide.
-/
import DerivedAlgGeo.CategoryTheory.Sites.Sheaves.ConstantPullback

/-! ## The pullback of a constant sheaf is constant (#572 step 3)

`Sheaf.H` is `Ext` out of the constant sheaf, so this is the half of the cohomology comparison
that moves the constant sheaf across `f⁻¹ ⊣ f_*`.
-/

#print axioms CategoryTheory.sheafPushforwardΓIso
#print axioms CategoryTheory.constantSheafCompSheafPullbackIso

-- Auto-generated by Lean from `HasGlobalSectionsFunctor`, which this file is the first in the
-- tree to use; the sweep counts it as public, so it is registered here rather than left to
-- push the ratchet.
#print axioms CategoryTheory.HasGlobalSectionsFunctor.congr_simp
