/-
Categorical and stability families slice of the StabilityCondition audit,
split out so concurrent branches append to different files (#480). Geometric
family records are owned by
`AlgebraicGeometryAudit/StabilityConditionFamilies.lean`.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition
import DerivedAlgGeo.CategoryTheory.Bicategory.Functor.Cat.Transport
import DerivedAlgGeo.CategoryTheory.Bicategory.Functor.Cat.ObjectProperty.UniversallyStable
import DerivedAlgGeo.CategoryTheory.Triangulated.FourierMukai
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearYoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearCoyoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.GrothendieckGroup.EulerForm
import DerivedAlgGeo.LinearAlgebra
open CategoryTheory.Triangulated

/-! ## Neutral categorical family interfaces -/

#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.mk.inj
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.fibers
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.fiberPreadditive
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.fiberZero
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.fiberShift
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.fiberShiftAdditive
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.fiberPretriangulated
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pullAdditive
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pullCommShift
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pullTriangulated
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.Fiber
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pull
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pullIdIso
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pullCompIso
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pullK₀
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pullK₀_of
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pullK₀_id
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.pullK₀_comp
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.ofFunctor
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.constant
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.CompatibleClassMaps
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.CompatibleClassMaps.pull_compatible
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.CompatibleClassMaps.class_pull
#print axioms CategoryTheory.Triangulated.Families.TriangulatedFiberFamily.CompatibleClassMaps.constant

/-! ## Abstract Definition 20.5/21.15 family interfaces -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.classMap_compatible
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.charge_compatible
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.preimageData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.slicing_compatible
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.phase_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.preimageData_comp
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.preimageData_pullComp
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.preimage_pullComp
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.slicing_compatible_comp
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.slicing_compatible_pullComp
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.phase_iff_comp
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.class_pull
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.charge_pull
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.constant
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.FiberPreStabilityBaseChangeData.class_mem_semistableClasses_pull
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.CategoricalOrdinaryFiberStabilityInFamiliesData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.CategoricalOrdinaryFiberStabilityInFamiliesData.ordinary
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.CategoricalOrdinaryFiberStabilityInFamiliesData.baseChange
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.CategoricalOrdinaryFiberStabilityInFamiliesData.toDeformationInputConditions
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.CategoricalOrdinaryFiberStabilityInFamiliesData.class_mem_semistableClasses_pull
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.CategoricalOrdinaryFiberStabilityInFamiliesData.commonCharge_pull

/-! ## Geometric affine bounded-above projective locus -/

#print axioms CategoryTheory.Pseudofunctor.equivalenceTransportFunctor
#print axioms CategoryTheory.Pseudofunctor.equivalenceTransportCompIso
#print axioms CategoryTheory.Pseudofunctor.equivalenceTransportIdIso
#print axioms CategoryTheory.Pseudofunctor.equivalenceTransport_associativity
#print axioms CategoryTheory.Pseudofunctor.equivalenceTransport_leftUnitality
#print axioms CategoryTheory.Pseudofunctor.equivalenceTransport_rightUnitality
#print axioms CategoryTheory.Pseudofunctor.ObjectProperty.universallyStable
#print axioms CategoryTheory.Pseudofunctor.ObjectProperty.universallyStable_isClosedUnderIsomorphisms
#print axioms CategoryTheory.Pseudofunctor.ObjectProperty.universallyStable_isClosedUnderMapObj
#print axioms CategoryTheory.Pseudofunctor.ObjectProperty.universallyStable_le_self
#print axioms CategoryTheory.Pseudofunctor.ObjectProperty.le_universallyStable
#print axioms CategoryTheory.Pseudofunctor.ObjectProperty.universallyStable_eq_self
#print axioms CategoryTheory.Triangulated.Slicing.preimageData_equivalence
#print axioms CategoryTheory.Triangulated.Slicing.preimage_equivalence_P
#print axioms CategoryTheory.Abelian.image.congr_simp
#print axioms CategoryTheory.Functor.IsLeftTExact.isGE_map
#print axioms CategoryTheory.Functor.IsRightTExact.isLE_map
#print axioms CategoryTheory.Functor.IsTExact.toIsLeftTExact
#print axioms CategoryTheory.Functor.IsTExact.toIsRightTExact
#print axioms CategoryTheory.Limits.imageSubobject.congr_simp
#print axioms CategoryTheory.ObjectProperty.FullSubcategory.mk.hcongr_5
#print axioms CategoryTheory.ObjectProperty.ιOfLE.congr_simp
#print axioms CategoryTheory.Pretriangulated.shortComplexOfDistTriangle.congr_simp
#print axioms CategoryTheory.ShortComplex.LeftHomologyData.ofHasKernelOfHasCokernel.congr_simp
#print axioms CategoryTheory.ShortComplex.RightHomologyData.ofHasCokernelOfHasKernel.congr_simp
#print axioms CategoryTheory.ShortComplex.ShortExact.fIsKernel.congr_simp
#print axioms CategoryTheory.ShortComplex.ShortExact.gIsCokernel.congr_simp
#print axioms CategoryTheory.Subobject.isoOfEqMk.congr_simp
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.mk.inj
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.ChargeProbe
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.ChargeProbe.IsLocallyConstant
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.UniversallyLocallyConstantCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.OpenLocusProbe
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.OpenLocusProbe.IsOpen
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.UniversalOpenness
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.GenericSemistabilityProbe
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.GenericSemistabilityProbe.IsGenericallyOpen
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.UniversalGenericOpenness
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.DedekindHNProblem
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.IntegratesAfterDedekindBaseChange
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakDedekindHNProblem
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakIntegratesAfterDedekindBaseChange
#print axioms CategoryTheory.Moduli.BoundednessProblem
#print axioms CategoryTheory.Moduli.UniversalBoundedness
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.OrdinaryDefinition20_5Conditions
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakDefinition20_5Conditions
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryStabilityInFamiliesData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryDeformationInputConditions
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryDeformationInputConditions.bounded
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryDeformationInputConditions.dedekindHN
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryDeformationInputConditions.openness
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryDeformationInputConditions.uniformSupport
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.ordinaryFiberSemistableClasses
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.mem_ordinaryFiberSemistableClasses_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.class_mem_ordinaryFiberSemistableClasses
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberUniformQuadraticSupportData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberUniformQuadraticSupportData.charge_compatible
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberUniformQuadraticSupportData.quadratic
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberUniformQuadraticSupportData.fiber
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberUniformQuadraticSupportData.reindex
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.ordinaryFiberUniformQuadraticSupportData_constant
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.ordinaryFiberUniformQuadraticSupportData_punit
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberStabilityInFamiliesData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberStabilityInFamiliesData.definition20_5
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberStabilityInFamiliesData.charge_compatible
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberStabilityInFamiliesData.uniformSupport
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberStabilityInFamiliesData.bounded
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberStabilityInFamiliesData.toOrdinaryStabilityInFamiliesData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberStabilityInFamiliesData.toDeformationInputConditions
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberStabilityInFamiliesData.fiberSupport
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Families.OrdinaryFiberStabilityInFamiliesData.quotientCharge_mkQ
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.HasGaussianRationalValues
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.hasGaussianRationalValues_zero
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakChargeProbe
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakChargeProbe.toChargeProbe
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakSemistabilityProbe
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakSemistabilityProbe.toGenericProbe
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakDefinition20_5ClauseZero
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakDefinition20_5ClauseZero.reindex
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakQuotientQuadraticSupportData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.quotientUniformQuadraticSupportData_reindex
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.Families.WeakStabilityInFamiliesData
