/-
The reusable categorical root for finite filtrations.  It is intentionally independent of the
geometric almost-disconnected consumer in the AlgebraicGeometry audit.
-/
import DerivedAlgGeo.CategoryTheory.FiniteFiltration

#print axioms CategoryTheory.FiniteExactTower
#print axioms CategoryTheory.FiniteExactTower.length
#print axioms CategoryTheory.FiniteExactTower.object
#print axioms CategoryTheory.FiniteExactTower.inclusion
#print axioms CategoryTheory.FiniteExactTower.graded
#print axioms CategoryTheory.FiniteExactTower.projection
#print axioms CategoryTheory.FiniteExactTower.zero
#print axioms CategoryTheory.FiniteExactTower.shortExact
#print axioms CategoryTheory.FiniteExactTower.mk.inj
#print axioms CategoryTheory.FiniteExactTower.mk.sizeOf_spec
#print axioms CategoryTheory.FiniteExactTower.step
#print axioms CategoryTheory.FiniteExactTower.step_shortExact
#print axioms CategoryTheory.FiniteExactTower.diagram
#print axioms CategoryTheory.FiniteExactTower.diagram_obj
#print axioms CategoryTheory.FiniteExactTower.diagram_map_succ
#print axioms CategoryTheory.FiniteExactTower.toTop
#print axioms CategoryTheory.FiniteExactTower.toTop_last
#print axioms CategoryTheory.FiniteExactTower.inclusion_toTop
#print axioms CategoryTheory.FiniteExactTower.map
#print axioms CategoryTheory.FiniteExactTower.map_length
#print axioms CategoryTheory.FiniteExactTower.map_object
#print axioms CategoryTheory.FiniteExactTower.map_graded
#print axioms CategoryTheory.FiniteExactTower.map_id
#print axioms CategoryTheory.FiniteExactTower.map_comp
#print axioms CategoryTheory.FiniteFiltration
#print axioms CategoryTheory.FiniteFiltration.toFiniteExactTower
#print axioms CategoryTheory.FiniteFiltration.initialIsZero
#print axioms CategoryTheory.FiniteFiltration.terminalIso
#print axioms CategoryTheory.FiniteFiltration.mk.inj
#print axioms CategoryTheory.FiniteFiltration.mk.sizeOf_spec
#print axioms CategoryTheory.FiniteFiltration.step
#print axioms CategoryTheory.FiniteFiltration.step_shortExact
#print axioms CategoryTheory.FiniteFiltration.inclusion_mono
#print axioms CategoryTheory.FiniteFiltration.projection_epi
#print axioms CategoryTheory.FiniteFiltration.diagram
#print axioms CategoryTheory.FiniteFiltration.toObject
#print axioms CategoryTheory.FiniteFiltration.inclusion_toObject
#print axioms CategoryTheory.FiniteFiltration.toObject_zero
#print axioms CategoryTheory.FiniteFiltration.map
#print axioms CategoryTheory.FiniteFiltration.map_length
#print axioms CategoryTheory.FiniteFiltration.map_object
#print axioms CategoryTheory.FiniteFiltration.map_graded
#print axioms CategoryTheory.FiniteFiltration.map_id
#print axioms CategoryTheory.FiniteFiltration.map_comp
#print axioms CategoryTheory.FiniteFiltration.pullbackObject
#print axioms CategoryTheory.FiniteFiltration.pullbackInclusion
#print axioms CategoryTheory.FiniteFiltration.pullbackInclusion_fst
#print axioms CategoryTheory.FiniteFiltration.pullbackInclusion_fst_assoc
#print axioms CategoryTheory.FiniteFiltration.pullbackInclusion_snd
#print axioms CategoryTheory.FiniteFiltration.pullbackInclusion_snd_assoc
#print axioms CategoryTheory.FiniteFiltration.pullbackInclusion_mono
#print axioms CategoryTheory.FiniteFiltration.pullbackProjection
#print axioms CategoryTheory.FiniteFiltration.pullbackProjection_epi
#print axioms CategoryTheory.FiniteFiltration.pullback_zero
#print axioms CategoryTheory.FiniteFiltration.pullback_exact
#print axioms CategoryTheory.FiniteFiltration.pullbackTower
#print axioms CategoryTheory.FiniteFiltration.pullbackTower_length
#print axioms CategoryTheory.FiniteFiltration.pullbackTower_object
#print axioms CategoryTheory.FiniteFiltration.pullbackTower_graded
#print axioms CategoryTheory.FiniteFiltration.pullbackTowerInitialKernelFork
#print axioms CategoryTheory.FiniteFiltration.pullbackTowerInitialIsLimit
#print axioms CategoryTheory.FiniteFiltration.pullbackTowerTerminalIso
#print axioms CategoryTheory.FiniteFiltration.pullbackTowerTerminalIso_hom
#print axioms CategoryTheory.FiniteFiltration.refinementInitialIso
#print axioms CategoryTheory.FiniteFiltration.refinementTerminalIso
#print axioms CategoryTheory.FiniteFiltration.refinementInitialIso_hom_inclusion
