/-
Foundation slice of the StabilityCondition audit, split out so concurrent
branches append to different files (#480). See the umbrella file for the contract and reading guide.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition
import DerivedAlgGeo.CategoryTheory.Triangulated.FourierMukai
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearYoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearCoyoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.GrothendieckGroup.EulerForm
import DerivedAlgGeo.CategoryTheory.GrothendieckGroup
import DerivedAlgGeo.CategoryTheory.Triangulated.GrothendieckGroup.HeartComparison
import DerivedAlgGeo.LinearAlgebra
open CategoryTheory.Triangulated

/-! ## Owner-controlled Bridgeland foundation (#226) -/

#print axioms CategoryTheory.Triangulated.PostnikovTower
#print axioms CategoryTheory.Triangulated.PostnikovTower.length
#print axioms CategoryTheory.Triangulated.PostnikovTower.factor
#print axioms CategoryTheory.Triangulated.PostnikovTower.factors
#print axioms CategoryTheory.Triangulated.PostnikovTower.isZero_of_length_zero
#print axioms CategoryTheory.Triangulated.ExtensionClosure
#print axioms CategoryTheory.Triangulated.ExtensionClosure.mono
#print axioms CategoryTheory.Triangulated.ExtensionClosure.hom_eq_zero
#print axioms CategoryTheory.Triangulated.ExtensionClosure.ofIso
#print axioms CategoryTheory.Triangulated.ExtensionClosure.ofPostnikovTower
#print axioms CategoryTheory.Triangulated.ExtensionClosure.instIsClosedUnderIsomorphisms
#print axioms CategoryTheory.Triangulated.ExtensionClosure.le_of_closed
#print axioms CategoryTheory.Triangulated.HNFiltration
#print axioms CategoryTheory.Triangulated.Slicing
#print axioms CategoryTheory.Triangulated.Slicing.ext
#print axioms CategoryTheory.Triangulated.Slicing.ext_iff
#print axioms CategoryTheory.Triangulated.Slicing.zero_mem_of_isZero
#print axioms CategoryTheory.Triangulated.Slicing.shift
#print axioms CategoryTheory.Triangulated.Slicing.unshift

/-! ## Owner-controlled Grothendieck and pre-stability foundation (#228) -/

#print axioms CategoryTheory.GrothendieckPresentation
#print axioms CategoryTheory.GrothendieckPresentation.relationSubgroup
#print axioms CategoryTheory.GrothendieckPresentation.Group
#print axioms CategoryTheory.GrothendieckPresentation.instAddCommGroupGroup
#print axioms CategoryTheory.GrothendieckPresentation.of
#print axioms CategoryTheory.GrothendieckPresentation.of_relation
#print axioms CategoryTheory.GrothendieckPresentation.IsAdditive
#print axioms CategoryTheory.GrothendieckPresentation.lift
#print axioms CategoryTheory.GrothendieckPresentation.lift_of
#print axioms CategoryTheory.GrothendieckPresentation.hom_ext
#print axioms CategoryTheory.GrothendieckPresentation.hom_ext_iff
#print axioms CategoryTheory.GrothendieckPresentation.induction_on
#print axioms CategoryTheory.GrothendieckPresentation.isAdditive_of

/-! ## The Grothendieck group of an abelian category

`abelianPresentation` instantiates the generic presentation at short exact sequences.
`of_isZero`, `of_iso` and `of_shortExact` are **theorems** here: the three fields that
several structures in this repository carried as data (`map_zero`, `map_iso`,
`additive`) are exactly this universal property written out longhand.
-/

#print axioms CategoryTheory.abelianPresentation
#print axioms CategoryTheory.K₀Ab
#print axioms CategoryTheory.K₀Ab.of
#print axioms CategoryTheory.K₀Ab.of_shortExact
#print axioms CategoryTheory.K₀Ab.of_isZero
#print axioms CategoryTheory.K₀Ab.of_zero
#print axioms CategoryTheory.K₀Ab.of_iso
#print axioms CategoryTheory.K₀Ab.lift
#print axioms CategoryTheory.K₀Ab.lift_of
#print axioms CategoryTheory.K₀Ab.hom_ext
#print axioms CategoryTheory.K₀Ab.hom_ext_iff
#print axioms CategoryTheory.GrothendieckPresentation.map
#print axioms CategoryTheory.GrothendieckPresentation.map_of
#print axioms CategoryTheory.GrothendieckPresentation.IsAdditive.of_relationMap
#print axioms CategoryTheory.GrothendieckPresentation.map_id
#print axioms CategoryTheory.GrothendieckPresentation.map_comp
#print axioms CategoryTheory.Triangulated.triangulatedPresentation
#print axioms CategoryTheory.Triangulated.K₀
#print axioms CategoryTheory.Triangulated.K₀.of
#print axioms CategoryTheory.Triangulated.K₀.of_triangle
#print axioms CategoryTheory.Triangulated.K₀.of_zero
#print axioms CategoryTheory.Triangulated.K₀.of_iso
#print axioms CategoryTheory.Triangulated.K₀.of_isZero
#print axioms CategoryTheory.Triangulated.K₀.of_shift_one
#print axioms CategoryTheory.Triangulated.K₀.of_shift_neg_one
#print axioms CategoryTheory.Triangulated.IsTriangleAdditive
#print axioms CategoryTheory.Triangulated.instIsAdditiveSubtypeTriangleMemSetDistinguishedTrianglesTriangulatedPresentationOfIsTriangleAdditive
#print axioms CategoryTheory.Triangulated.K₀.lift
#print axioms CategoryTheory.Triangulated.K₀.lift_of
#print axioms CategoryTheory.Triangulated.K₀.hom_ext
#print axioms CategoryTheory.Triangulated.K₀.hom_ext_iff
#print axioms CategoryTheory.Triangulated.K₀.of_postnikovTower_eq_sum
#print axioms CategoryTheory.Triangulated.classOf
#print axioms CategoryTheory.Triangulated.classOf_id
#print axioms CategoryTheory.Triangulated.classOf_isZero
#print axioms CategoryTheory.Triangulated.classOf_triangle
#print axioms CategoryTheory.Triangulated.classOf_iso
#print axioms CategoryTheory.Triangulated.classOf_shift_one
#print axioms CategoryTheory.Triangulated.classOf_shift_neg_one
#print axioms CategoryTheory.Triangulated.classOf_postnikovTower_eq_sum
#print axioms CategoryTheory.Triangulated.K₀.isTriangleAdditive_map
#print axioms CategoryTheory.Triangulated.K₀.map
#print axioms CategoryTheory.Triangulated.K₀.map_of
#print axioms CategoryTheory.Triangulated.K₀.map_id
#print axioms CategoryTheory.Triangulated.K₀.map_comp
#print axioms CategoryTheory.Triangulated.K₀.map_congr
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.charge
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.charge_def
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.compat
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.charge_isZero
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.charge_congr
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.charge_postnikovTower_eq_sum
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.ext
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.ext_iff
#print axioms CategoryTheory.Triangulated.PreStabilityCondition
#print axioms CategoryTheory.Triangulated.preStabilityCondition_compat_apply

/-! ## Owner-controlled local finiteness and stability conditions (#229) -/

#print axioms CategoryTheory.Triangulated.Slicing.intervalProp
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.ι
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_of_isZero
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_containsZero
#print axioms CategoryTheory.Triangulated.Slicing.IsAdmissibleSubobject
#print axioms CategoryTheory.Triangulated.Slicing.AdmissibleSubobject
#print axioms CategoryTheory.Triangulated.Slicing.IsAdmissiblyArtinian
#print axioms CategoryTheory.Triangulated.Slicing.IsAdmissiblyNoetherian
#print axioms CategoryTheory.Triangulated.Slicing.IsFiniteLength
#print axioms CategoryTheory.Triangulated.admissibleSubobjectOrderIso
#print axioms CategoryTheory.Triangulated.admissibleSubobjectOrderIso_wellFoundedLT_iff
#print axioms CategoryTheory.Triangulated.admissibleSubobjectOrderIso_wellFoundedGT_iff
#print axioms CategoryTheory.Triangulated.Slicing.IsLocallyFinite
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.ext
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.ext_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition
#print axioms CategoryTheory.Triangulated.stabilityCondition_compat_apply

/-! ## Owner slicing phase bounds and filtration operations (#231) -/

#print axioms CategoryTheory.Triangulated.Slicing.shift_nat
#print axioms CategoryTheory.Triangulated.Slicing.unshift_nat
#print axioms CategoryTheory.Triangulated.Slicing.shift_int
#print axioms CategoryTheory.Triangulated.HNFiltration.phiPlus
#print axioms CategoryTheory.Triangulated.HNFiltration.phiMinus
#print axioms CategoryTheory.Triangulated.HNFiltration.phase_mem_range
#print axioms CategoryTheory.Triangulated.HNFiltration.phiMinus_le_phiPlus
#print axioms CategoryTheory.Triangulated.HNFiltration.ofIso
#print axioms CategoryTheory.Triangulated.Slicing.leProp
#print axioms CategoryTheory.Triangulated.Slicing.gtProp
#print axioms CategoryTheory.Triangulated.Slicing.ltProp
#print axioms CategoryTheory.Triangulated.Slicing.geProp
#print axioms CategoryTheory.Triangulated.Slicing.leProp_isClosedUnderIsomorphisms
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_isClosedUnderIsomorphisms
#print axioms CategoryTheory.Triangulated.Slicing.ltProp_isClosedUnderIsomorphisms
#print axioms CategoryTheory.Triangulated.Slicing.geProp_isClosedUnderIsomorphisms
#print axioms CategoryTheory.Triangulated.Slicing.leProp_of_isZero
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_of_isZero
#print axioms CategoryTheory.Triangulated.Slicing.ltProp_of_isZero
#print axioms CategoryTheory.Triangulated.Slicing.geProp_of_isZero
#print axioms CategoryTheory.Triangulated.Slicing.leProp_mono
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_anti
#print axioms CategoryTheory.Triangulated.Slicing.ltProp_mono
#print axioms CategoryTheory.Triangulated.Slicing.geProp_anti
#print axioms CategoryTheory.Triangulated.Slicing.leProp_of_ltProp
#print axioms CategoryTheory.Triangulated.Slicing.geProp_of_gtProp
#print axioms CategoryTheory.Triangulated.Slicing.ltProp_of_intervalProp
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_of_intervalProp
#print axioms CategoryTheory.Triangulated.Slicing.hom_eq_zero_of_phase_gap
#print axioms CategoryTheory.Triangulated.Slicing.intervalHom_eq_zero
#print axioms CategoryTheory.Triangulated.Slicing.leProp_of_triangle
#print axioms CategoryTheory.Triangulated.Slicing.ltProp_of_triangle
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_of_triangle
#print axioms CategoryTheory.Triangulated.Slicing.geProp_of_triangle
#print axioms CategoryTheory.Triangulated.Slicing.exists_cutoff_truncation
#print axioms CategoryTheory.Triangulated.Slicing.exists_cutoff_truncation_in_interval
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_gt_of_gtProp
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_ge_of_geProp
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_le_of_leProp
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_lt_of_ltProp
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_of_gtProp_ltProp
#print axioms CategoryTheory.Triangulated.Slicing.zero_of_gtProp_leProp
#print axioms CategoryTheory.Triangulated.Slicing.zero_of_geProp_ltProp
#print axioms CategoryTheory.Triangulated.HNFiltration.zero
#print axioms CategoryTheory.Triangulated.HNFiltration.single
#print axioms CategoryTheory.Triangulated.HNFiltration.semistable_of_length_one
#print axioms CategoryTheory.Triangulated.HNFiltration.prefix
#print axioms CategoryTheory.Triangulated.HNFiltration.prefix_φ
#print axioms CategoryTheory.Triangulated.HNFiltration.appendFactor
#print axioms CategoryTheory.Triangulated.HNFiltration.appendLengthOne
#print axioms CategoryTheory.Triangulated.HNFiltration.appendLengthOne_phase_bounds
#print axioms CategoryTheory.Triangulated.HNFiltration.ofTriangleThirdZero
#print axioms CategoryTheory.Triangulated.HNFiltration.exists_of_distinguished_triangle
#print axioms CategoryTheory.Triangulated.HNFiltration.exists_of_distinguished_triangle_phase_bounds
#print axioms CategoryTheory.Triangulated.HNFiltration.exists_split_at_cutoff
#print axioms CategoryTheory.Triangulated.Deformation.ThinStrictFiniteLength
#print axioms CategoryTheory.Triangulated.Deformation.ThinStrictFiniteLength.of_finiteLength
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.exists_semistable_strictQuotient_le_phase
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.id_of_semistable
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.epi
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.strict
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.phase_le
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.factor_of_phase_eq
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.precomposeIso
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.of_strictEpi_factor
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.phase_le_of_strictQuotient
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.isSemistable_of_strictQuotient_phase_eq
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.factor_of_strictQuotient_phase_eq
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.comp_of_destabilizing_semistable_subobject
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.exists_strictMDQ
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.kernelSubobject_ne_bot_of_not_semistable
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.kernelSubobject_isLimitKernelFork
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.strictShortExact_kernelSubobject
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.kernelSubobject_ne_top_of_strictEpi_nonzero
#print axioms CategoryTheory.Triangulated.Deformation.Subobject.map_eq_mk_comp
#print axioms CategoryTheory.Triangulated.Deformation.Subobject.mapUnderlyingIso
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.phase_cokernel_kernelSubobject
#print axioms CategoryTheory.Triangulated.Deformation.IsStrictMDQ.phase_lt_of_strictQuotient_of_kernel
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.hn_exists_of_quotientLowerBound
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.hn_exists
#print axioms CategoryTheory.Triangulated.HNFiltration.shift
#print axioms CategoryTheory.Triangulated.HNFiltration.shift_phiPlus
#print axioms CategoryTheory.Triangulated.HNFiltration.shift_phiMinus
#print axioms CategoryTheory.Triangulated.HNFiltration.n_pos
#print axioms CategoryTheory.Triangulated.HNFiltration.exists_nonzero_factor
#print axioms CategoryTheory.Triangulated.HNFiltration.dropFirst
#print axioms CategoryTheory.Triangulated.Slicing.exists_hn_nonzero_first
#print axioms CategoryTheory.Triangulated.HNFiltration.dropLast
#print axioms CategoryTheory.Triangulated.Slicing.exists_hn_nonzero_last
#print axioms CategoryTheory.Triangulated.Slicing.exists_hn_nonzero_boundaries
#print axioms CategoryTheory.Triangulated.HNFiltration.firstFactor_hom_chain_eq_zero
#print axioms CategoryTheory.Triangulated.HNFiltration.firstFactor_isZero_of_hom_eq_zero
#print axioms CategoryTheory.Triangulated.HNFiltration.phiPlus_le_of_firstFactor_nonzero
#print axioms CategoryTheory.Triangulated.HNFiltration.phiPlus_eq_of_firstFactors_nonzero
#print axioms CategoryTheory.Triangulated.HNFiltration.lastFactor_isZero_of_hom_eq_zero
#print axioms CategoryTheory.Triangulated.HNFiltration.phiMinus_le_of_lastFactor_nonzero
#print axioms CategoryTheory.Triangulated.HNFiltration.phiMinus_eq_of_lastFactors_nonzero
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_eq
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_eq
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_le_phiPlus
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_eq_of_semistable
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_eq_of_semistable
#print axioms CategoryTheory.Triangulated.Slicing.exists_hn_intrinsic_width
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_mono
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_intersection
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_widen
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_lt_of_intervalProp
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_gt_of_intervalProp
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_gt_of_intervalProp
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_lt_of_intervalProp
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_of_intrinsic_phases
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_iff_intrinsic_phases
#print axioms CategoryTheory.Triangulated.Slicing.intrinsic_phases_mem_interval
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_of_phiMinus_gt
#print axioms CategoryTheory.Triangulated.Slicing.geProp_of_phiMinus_ge
#print axioms CategoryTheory.Triangulated.Slicing.leProp_of_phiPlus_le
#print axioms CategoryTheory.Triangulated.Slicing.ltProp_of_phiPlus_lt
#print axioms CategoryTheory.Triangulated.Slicing.ltProp_of_leProp_of_lt
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_lt_of_triangle_with_leProp
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_gt_of_triangle_with_gtProp
#print axioms CategoryTheory.Triangulated.Slicing.first_intervalProp_of_triangle
#print axioms CategoryTheory.Triangulated.HNFiltration.phaseShift
#print axioms CategoryTheory.Triangulated.Slicing.phaseShift
#print axioms CategoryTheory.Triangulated.Slicing.phaseShift_gtProp_zero
#print axioms CategoryTheory.Triangulated.Slicing.phaseShift_gtProp
#print axioms CategoryTheory.Triangulated.Slicing.phaseShift_leProp_zero
#print axioms CategoryTheory.Triangulated.Slicing.phaseShift_leProp
#print axioms CategoryTheory.Triangulated.Slicing.phaseShift_ltProp_zero
#print axioms CategoryTheory.Triangulated.Slicing.phaseShift_ltProp
#print axioms CategoryTheory.Triangulated.Slicing.phaseShift_geProp_zero
#print axioms CategoryTheory.Triangulated.Slicing.phaseShift_geProp
#print axioms CategoryTheory.Triangulated.Slicing.leProp_shift
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_shift
#print axioms CategoryTheory.Triangulated.Slicing.ltProp_shift
#print axioms CategoryTheory.Triangulated.Slicing.geProp_shift
#print axioms CategoryTheory.Triangulated.Slicing.leProp_of_hn
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_of_hn
#print axioms CategoryTheory.Triangulated.Slicing.ltProp_of_hn
#print axioms CategoryTheory.Triangulated.Slicing.geProp_of_hn
#print axioms CategoryTheory.Triangulated.Slicing.leProp_of_semistable
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_of_semistable
#print axioms CategoryTheory.Triangulated.Slicing.exists_phase_truncation
#print axioms CategoryTheory.Triangulated.Slicing.exists_phase_truncation_zero
#print axioms CategoryTheory.Triangulated.Slicing.exists_dual_phase_truncation
#print axioms CategoryTheory.Triangulated.Slicing.exists_upper_boundary_triangle
#print axioms CategoryTheory.Triangulated.Slicing.exists_lower_boundary_triangle
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_of_upper_boundary_triangle
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_of_lower_boundary_triangle
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_of_triangle
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_implies_leftHeart
#print axioms CategoryTheory.Triangulated.Slicing.toDualTStructure
#print axioms CategoryTheory.Triangulated.Slicing.toDualTStructure_heart_iff
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_implies_rightHeart
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toLeftHeart
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toRightHeart
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_gt_of_triangle_with_geProp
#print axioms CategoryTheory.Triangulated.Slicing.third_intervalProp_of_triangle
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_of_mono_leftHeart
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_of_epi_rightHeart
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasKernel
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasKernels
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasCokernel
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasCokernels
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toLeftHeartKernelIso
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toRightHeartCokernelIso
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toLeftHeartKernelIso_hom_comp_ι
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toRightHeartCokernelIso_π_comp_hom
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.strictMono_of_mono_toRightHeart
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.strictEpi_of_epi_toLeftHeart
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.mono_toRightHeart_of_strictMono
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.epi_toLeftHeart_of_strictEpi
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.comp_strictMono
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.comp_strictEpi
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.strictEpi_of_comp_strictEpi
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_isClosedUnderIsomorphisms
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toLeftHeart_preservesKernel
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toRightHeart_preservesCokernel
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_isClosedUnderBinaryProducts
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_isClosedUnderFiniteProducts
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasFiniteProducts
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasBinaryBiproducts
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasFiniteBiproducts
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasEqualizers
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasCoequalizers
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasPullbacks
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_hasPushouts
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toLeftHeart_preservesFiniteLimits
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toRightHeart_preservesFiniteColimits
#print axioms CategoryTheory.Triangulated.Slicing.intervalCat_quasiAbelian
#print axioms CategoryTheory.Triangulated.IsStrict
#print axioms CategoryTheory.Triangulated.IsStrictMono
#print axioms CategoryTheory.Triangulated.IsStrictEpi
#print axioms CategoryTheory.Triangulated.isStrictEpi_of_isColimitCokernelCofork
#print axioms CategoryTheory.Triangulated.isStrictMono_of_isLimitKernelFork
#print axioms CategoryTheory.Triangulated.IsStrictEpi.isColimitCokernelCofork
#print axioms CategoryTheory.Triangulated.IsStrictMono.isLimitKernelFork
#print axioms CategoryTheory.Triangulated.IsStrictEpi.normalEpi
#print axioms CategoryTheory.Triangulated.IsStrictMono.normalMono
#print axioms CategoryTheory.Triangulated.isStrictMono_of_isIso
#print axioms CategoryTheory.Triangulated.isStrictEpi_of_isIso
#print axioms CategoryTheory.Triangulated.IsStrictEpi.isIso
#print axioms CategoryTheory.Triangulated.IsStrictMono.isIso
#print axioms CategoryTheory.Triangulated.isStrictEpi_of_normalEpi
#print axioms CategoryTheory.Triangulated.isStrictMono_of_normalMono
#print axioms CategoryTheory.Triangulated.IsStrictEpi.regularEpi
#print axioms CategoryTheory.Triangulated.IsStrictEpi.strongEpi
#print axioms CategoryTheory.Triangulated.IsStrictMono.regularMono
#print axioms CategoryTheory.Triangulated.IsStrictMono.strongMono
#print axioms CategoryTheory.Triangulated.isStrictMono_kernel
#print axioms CategoryTheory.Triangulated.isStrictEpi_cokernel
#print axioms CategoryTheory.Triangulated.StrictShortExact
#print axioms CategoryTheory.Triangulated.IsStrictEpi.strictShortExact_kernel
#print axioms CategoryTheory.Triangulated.QuasiAbelian
#print axioms CategoryTheory.Triangulated.isStrict_of_abelian
#print axioms CategoryTheory.Triangulated.isStrictMono_of_mono
#print axioms CategoryTheory.Triangulated.isStrictEpi_of_epi
#print axioms CategoryTheory.Triangulated.strictShortExact_of_shortExact
#print axioms CategoryTheory.Triangulated.IsStrictSubobject
#print axioms CategoryTheory.Triangulated.isStrictSubobject_iff
#print axioms CategoryTheory.Triangulated.StrictSubobject
#print axioms CategoryTheory.Triangulated.isStrictArtinianObject
#print axioms CategoryTheory.Triangulated.IsStrictArtinianObject
#print axioms CategoryTheory.Triangulated.isStrictNoetherianObject
#print axioms CategoryTheory.Triangulated.IsStrictNoetherianObject
#print axioms CategoryTheory.Triangulated.isStrictArtinianObject_of_isArtinianObject
#print axioms CategoryTheory.Triangulated.isStrictNoetherianObject_of_isNoetherianObject
#print axioms CategoryTheory.Triangulated.isArtinianObject_of_isStrictArtinianObject
#print axioms CategoryTheory.Triangulated.isNoetherianObject_of_isStrictNoetherianObject
#print axioms CategoryTheory.Triangulated.subobjectImageOfFullFaithful
#print axioms CategoryTheory.Triangulated.subobjectImageOfFullFaithful_injective
#print axioms CategoryTheory.Triangulated.subobjectImageOfFullFaithful_monotone
#print axioms CategoryTheory.Triangulated.Finite.subobject_of_fullFaithful_preservesMono
#print axioms CategoryTheory.Triangulated.isArtinianObject_of_fullFaithful_preservesMono
#print axioms CategoryTheory.Triangulated.isNoetherianObject_of_fullFaithful_preservesMono
#print axioms CategoryTheory.Triangulated.strictSubobjectImageOfFullFaithful
#print axioms CategoryTheory.Triangulated.strictSubobjectImageOfFullFaithful_monotone
#print axioms CategoryTheory.Triangulated.strictSubobjectImageOfFullFaithful_injective
#print axioms CategoryTheory.Triangulated.isStrictArtinianObject_of_fullFaithful_map_strictMono
#print axioms CategoryTheory.Triangulated.isStrictNoetherianObject_of_fullFaithful_map_strictMono
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.finite_subobject_of_leftHeart
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.isArtinianObject_of_leftHeart
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.isNoetherianObject_of_leftHeart
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.isStrictArtinianObject_of_rightHeart
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.isStrictNoetherianObject_of_rightHeart
#print axioms CategoryTheory.Triangulated.IsStrictFiniteLengthObject
#print axioms CategoryTheory.Triangulated.IsFiniteLengthObject
#print axioms CategoryTheory.Triangulated.isStrictFiniteLengthObject_iff
#print axioms CategoryTheory.Triangulated.IsStrictFiniteLengthObject.isStrictArtinianObject
#print axioms CategoryTheory.Triangulated.IsStrictFiniteLengthObject.isStrictNoetherianObject
#print axioms CategoryTheory.Triangulated.IsStrictFiniteLengthObject.mk'
#print axioms CategoryTheory.Triangulated.IsFiniteLengthObject.isArtinianObject
#print axioms CategoryTheory.Triangulated.IsFiniteLengthObject.isNoetherianObject
#print axioms CategoryTheory.Triangulated.IsFiniteLengthObject.mk'
#print axioms CategoryTheory.Triangulated.isStrictFiniteLengthObject_of_finite_subobjects
#print axioms CategoryTheory.Triangulated.isStrictFiniteLengthObject_of_isFiniteLengthObject
#print axioms CategoryTheory.Triangulated.isStrictFiniteLengthObject_iff_isFiniteLengthObject
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.isStrictSubobject_of_isAdmissible
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.admissibleToStrictSubobject
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.isAdmissiblyArtinian_of_isStrictArtinian
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.isAdmissiblyNoetherian_of_isStrictNoetherian
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.isFiniteLength_of_isStrictFiniteLength
#print axioms CategoryTheory.Triangulated.Slicing.IsLocallyFinite.of_strictFiniteLength
#print axioms CategoryTheory.Triangulated.Slicing.IsLocallyFinite.of_finiteSubobjects
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.strictShortExact_of_distinguished
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.exists_distinguished_of_shortExact_toLeftHeart
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.exists_distinguished_of_strictShortExact
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.strictShortExact_iff_exists_distinguished
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.K₀_of_strictShortExact
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.strictShortExact_inclusion
#print axioms CategoryTheory.Triangulated.HNFiltration.appendStrictFactor
#print axioms CategoryTheory.Triangulated.TStructure.exists_distinguished_triangle_of_heart_epi
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_mem_enveloped_branch
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_gt_of_geProp
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_lt_of_leProp
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.intervalProp_of_skewedSemistable_upper_target
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.intervalProp_of_skewedSemistable_lower_target
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedPred_of_target_transport
#print axioms CategoryTheory.Triangulated.Slicing.toTStructure
#print axioms CategoryTheory.Triangulated.Slicing.toTStructure_heart_iff
#print axioms CategoryTheory.Triangulated.Slicing.toTStructure_bounded

/-! ## Owner relative phase geometry (#236) -/

#print axioms CategoryTheory.Triangulated.Deformation.relativePhase
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_mem_Ioc
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_polar
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_of_ray
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_zero
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_neg
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_add_two
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_eq_of_mem
#print axioms CategoryTheory.Triangulated.Deformation.im_sq_le_norm_sub_one_sq_mul
#print axioms CategoryTheory.Triangulated.Deformation.abs_sin_arg_le_norm_sub_one
#print axioms CategoryTheory.Triangulated.Deformation.sin_abs_eq_abs_sin
#print axioms CategoryTheory.Triangulated.Deformation.abs_arg_one_add_lt
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_perturbation
#print axioms CategoryTheory.Triangulated.Deformation.SectorFiniteLength
#print axioms CategoryTheory.Triangulated.Deformation.WideSectorFiniteLength
#print axioms CategoryTheory.Triangulated.Deformation.exists_wideSectorRadius
#print axioms CategoryTheory.Triangulated.Deformation.exists_sectorRadius
#print axioms CategoryTheory.Triangulated.Deformation.rotatedIm
#print axioms CategoryTheory.Triangulated.Deformation.rotatedIm_polar
#print axioms CategoryTheory.Triangulated.Deformation.rotatedIm_eq_norm_mul_sin
#print axioms CategoryTheory.Triangulated.Deformation.rotatedIm_eq_zero_of_relativePhase_eq
#print axioms CategoryTheory.Triangulated.Deformation.rotatedIm_neg_of_relativePhase_lt
#print axioms CategoryTheory.Triangulated.Deformation.rotatedIm_pos_of_relativePhase_gt
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_gt_of_rotatedIm_pos
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_lt_of_rotatedIm_neg
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_seesaw
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_seesaw_strict
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_seesaw_dual
#print axioms CategoryTheory.Triangulated.rotatedIm_charge_eq_sum
#print axioms CategoryTheory.Triangulated.rotatedIm_charge_neg_of_hn
#print axioms CategoryTheory.Triangulated.rotatedIm_charge_pos_of_hn
#print axioms CategoryTheory.Triangulated.Slicing.rotatedIm_charge_neg_of_interval
#print axioms CategoryTheory.Triangulated.Slicing.rotatedIm_charge_pos_of_interval
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.charge
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.phase
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.ChargeNe
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.phase_congr
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.phase_iso
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.charge_triangle
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.phase_seesaw
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.phase_seesaw_strict
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.IsSemistable
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.IsSemistable.phase_le_of_quotient_triangle
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.IsSemistable.phase_mem_Ioc
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.IsSemistable.charge_polar
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.IsSemistable.ofIso
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.IsSemistable.ofCompatibleInterval
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.subobject_isZero_iff_eq_bot
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.subobject_not_isZero_of_ne_bot
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.subobject_arrow_strictMono
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.strictShortExact_cokernel
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.liftSub
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.liftSub_le
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.liftSub_ne_bot
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.liftSub_lt
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.liftSub_arrow_strictMono
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.phase_liftSub
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.exists_phase_gt_strictSubobject_of_not_semistable
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.exists_first_strictShortExact_of_not_semistable
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.pullbackProjection_strictEpi
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.bot_arrow_strictMono
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.pullbackArrow_strictMono
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.le_pullbackCokernel
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.ofLE_pullbackProjection_eq_zero
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.lt_pullbackCokernel_of_ne_bot
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.pullbackCokernel_ne_top
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.cokernel_not_isZero_of_ne_top
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.cokernelPullbackIso
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.charge_cokernelPullback
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.phase_cokernelPullback
#print axioms CategoryTheory.Triangulated.Deformation.SkewedStabilityFunction.phase_cokernel_lt_of_phase_gt_strictSubobject
#print axioms CategoryTheory.Triangulated.Deformation.SemistableChargeBound
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_charge_eq
#print axioms CategoryTheory.Triangulated.Deformation.perturbedCharge_ne_zero
#print axioms CategoryTheory.Triangulated.Deformation.skewedStabilityFunctionOfBound
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_perturbation_of_charge
#print axioms CategoryTheory.Triangulated.Deformation.stabilitySeminorm
#print axioms CategoryTheory.Triangulated.Deformation.charge_norm_pos
#print axioms CategoryTheory.Triangulated.Deformation.ratio_le_stabilitySeminorm
#print axioms CategoryTheory.Triangulated.Deformation.stabilitySeminorm_nonneg
#print axioms CategoryTheory.Triangulated.Deformation.stabilitySeminorm_zero
#print axioms CategoryTheory.Triangulated.Deformation.stabilitySeminorm_neg
#print axioms CategoryTheory.Triangulated.Deformation.stabilitySeminorm_add_le
#print axioms CategoryTheory.Triangulated.Deformation.semistableChargeBound_of_stabilitySeminorm_le
#print axioms CategoryTheory.Triangulated.Deformation.semistableChargeBound_toReal
#print axioms CategoryTheory.Triangulated.Deformation.skewedStabilityFunctionOfSeminormLtOne
#print axioms CategoryTheory.Triangulated.Deformation.relativePhase_perturbation_of_stabilitySeminorm
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_of_isZero
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_isClosedUnderIsomorphisms
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.exists_deformedPred_witness
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_charge_ne
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_charge_polar
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_intrinsic_phase_window
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtGen
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLeGen
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtGen
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_mono
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred_mono
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_of_deformedLtPred
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred_anti
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_shift_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_of_shift_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_shift_neg_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred_shift_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred_shift_neg_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_shift_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_shift_neg_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred_shift_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred_shift_neg_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred_shift_one_same
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_shift_neg_one_same
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred_shift_neg_one_same
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred_of_triangle_obj₃
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_of_triangle_obj₁
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred_of_triangle_obj₁
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_intrinsic_deformed_gap
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedPred_large_gap
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedPred_gap
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedCuts_gap
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_skewed_small_gap
#print axioms CategoryTheory.Triangulated.midpoint_branch_contains
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_sub_lt_of_stabilitySeminorm
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_mem_interval_of_stabilitySeminorm
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_mem_lower_branch
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_mem_upper_branch
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_mem_expanded_interval
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_eq_of_mem_branch
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.charge_ne_of_interval
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_eq_of_common_interval
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_of_subinterval
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_eq_of_target_envelope
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_rewitness_subinterval
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_of_nested_interval
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_of_controlled_subinterval
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_on_witness_intersection
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_common_refinement
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_rewitness_nested_interval
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewed_phiPlus_le
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewed_phiMinus_ge
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_intrinsic_bounds
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_geProp
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_leProp
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedPred_intervalProp
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.intervalProp_of_deformed_hn
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred_gtProp
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_leProp
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred_ltProp
#print axioms CategoryTheory.Triangulated.Slicing.mem_phaseShiftHeart_of_intrinsic_bounds
#print axioms CategoryTheory.Triangulated.Slicing.mem_phaseShiftHeart_of_intervalProp
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_leProp_of_phaseShiftHeart
#print axioms CategoryTheory.Triangulated.Slicing.geProp_leProp_of_phaseShiftHeart
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_leProp_of_intrinsic_bounds
#print axioms CategoryTheory.Triangulated.midpoint_left_target_thin
#print axioms CategoryTheory.Triangulated.midpoint_right_target_thin
#print axioms CategoryTheory.Triangulated.midpoint_image_window_thin
#print axioms CategoryTheory.Triangulated.Slicing.mem_phaseShiftHeart_of_midpoint_left
#print axioms CategoryTheory.Triangulated.Slicing.mem_phaseShiftHeart_of_midpoint_right
#print axioms CategoryTheory.Triangulated.Slicing.exists_heart_image_factorisation_windows
#print axioms CategoryTheory.Triangulated.slicingDist
#print axioms CategoryTheory.Triangulated.slicingDistTerm_le
#print axioms CategoryTheory.Triangulated.phiPlusDist_le
#print axioms CategoryTheory.Triangulated.phiMinusDist_le
#print axioms CategoryTheory.Triangulated.slicingDist_self
#print axioms CategoryTheory.Triangulated.slicingDist_symm
#print axioms CategoryTheory.Triangulated.slicingDist_triangle
#print axioms CategoryTheory.Triangulated.instPseudoEMetricSpaceSlicing
#print axioms CategoryTheory.Triangulated.abs_phiPlus_sub_lt_of_slicingDist
#print axioms CategoryTheory.Triangulated.abs_phiMinus_sub_lt_of_slicingDist
#print axioms CategoryTheory.Triangulated.intervalProp_of_semistable_slicingDist
#print axioms CategoryTheory.Triangulated.slicingDist_le_of_phase_bounds
#print axioms CategoryTheory.Triangulated.Deformation.basisNhd
#print axioms CategoryTheory.Triangulated.Deformation.mem_basisNhd_iff
#print axioms CategoryTheory.Triangulated.Deformation.self_mem_basisNhd
#print axioms CategoryTheory.Triangulated.Deformation.StabilityCondition.WithClassMap.topologicalSpace
#print axioms CategoryTheory.Triangulated.Deformation.basisNhd_isOpen_generator
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedHN_exists_in_cut_strip
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedHN_exists_of_bounded_cuts
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedHN_exists
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedSlicing
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedSlicing_isLocallyFinite
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformed
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.slicingDist_deformed_le
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.exists_with_Z_mem_basisNhd
#print axioms CategoryTheory.Triangulated.K₀.of_shift_int
#print axioms CategoryTheory.Triangulated.instWellFoundedLTStrictSubobjectOfIsStrictArtinianObject
#print axioms CategoryTheory.Triangulated.instWellFoundedGTStrictSubobjectOfIsStrictNoetherianObject
#print axioms CategoryTheory.Triangulated.Slicing.zero_of_geProp_ltProp_at
#print axioms CategoryTheory.Triangulated.HNFiltration.chain_obj_gtProp
#print axioms CategoryTheory.Triangulated.HNFiltration.chain_obj_leProp
#print axioms CategoryTheory.Triangulated.Slicing.geProp_of_semistable
#print axioms CategoryTheory.Triangulated.HNFiltration.prefix_phiMinus
#print axioms CategoryTheory.Triangulated.Slicing.exists_split_at_cutoff
#print axioms CategoryTheory.Triangulated.HNFiltration.prefix_phiMinus_gt
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_iso
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_iso
#print axioms CategoryTheory.Triangulated.Slicing.semistable_of_HN_all_eq
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_of_postnikovTower
#print axioms CategoryTheory.Triangulated.Slicing.semistable_of_triangle
#print axioms CategoryTheory.Triangulated.Slicing.phiMinus_triangle_le
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_triangle_le
#print axioms CategoryTheory.Triangulated.Slicing.intervalProp_chain_of_postnikovTower
#print axioms CategoryTheory.Triangulated.Slicing.exists_split_at_cutoff_with_upper_bound
#print axioms CategoryTheory.Triangulated.HNFiltration.isZero_factor_zero_of_hom_eq_zero
#print axioms CategoryTheory.Triangulated.Slicing.semistable_of_phiPlus_eq_phiMinus
#print axioms CategoryTheory.Triangulated.Slicing.leProp_zero
#print axioms CategoryTheory.Triangulated.Slicing.phiPlus_eq_phiMinus_of_semistable
#print axioms CategoryTheory.Triangulated.Slicing.zero_of_geProp_ltProp_general
#print axioms CategoryTheory.Triangulated.HNFiltration.isZero_factor_last_of_hom_eq_zero
#print axioms CategoryTheory.Triangulated.Slicing.zero_of_gtProp_leProp_general
#print axioms CategoryTheory.Triangulated.Slicing.gtProp_zero
#print axioms CategoryTheory.Triangulated.TStructure.heart_biprod
#print axioms CategoryTheory.Triangulated.TStructure.truncGE_map_comp_descTruncGE_assoc
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toRightHeart_faithful
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toLeftHeart_full
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toLeftHeart_faithful
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.toRightHeart_full
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.inclusion
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.isStrictFiniteLength_of_isFiniteLength
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.isAdmissibleSubobject_of_isStrictSubobject
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.admissibleStrictSubobjectOrderIso
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.strictShortExact_pullback_left
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.strictShortExact_pullback_right
#print axioms CategoryTheory.Triangulated.Deformation.Slicing.IntervalCat.strictShortExact_of_kernel_strictEpi
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_gt_of_geProp_of_phase_range
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_of_interval_inclusion
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_of_target_subinterval
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_of_target_envelope
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedPred
#print axioms CategoryTheory.Triangulated.Slicing.IntervalCat.isLimitKernelForkOfDistinguished
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.phase_seesaw_dual
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_of_upper_inclusion
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_of_lower_inclusion
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedSemistable_of_target_triangleTest
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.phase_add_lt_of_le_of_lt
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.phase_lt_upper_of_destabilizing_subobject
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.comp_mdq_of_destabilizing_with_quotient_bound
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_enveloped_semistable
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.exists_strictSubobject_of_phiPlus_gt
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.exists_strictMDQ_with_quotient_bound
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_gt_of_strictQuotient_inner
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.skewedPhase_lt_of_phiPlus_lt
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hn_exists_with_phiPlus_reduction
#print axioms CategoryTheory.Triangulated.HNFiltration.firstFactor_phiPlus_le_target
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.semistable_has_deformedHN
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.interior_has_enveloped_HN_skewed
#print axioms CategoryTheory.Triangulated.HNFiltration.target_phiMinus_le_lastFactor
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.interior_has_enveloped_HN
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.exists_deformedCut_triangle_of_hn
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.semistable_mem_deformedLt
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.semistable_has_tight_deformedHN
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.semistable_mem_deformedGt
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.exists_global_deformedCut_triangle
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.isZero_of_deformedGtLe
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedGtLe
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedHN_of_cut_window
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedSlicing_P
#print axioms CategoryTheory.Triangulated.interval_strictFiniteLength_of_inclusion
#print axioms CategoryTheory.Triangulated.intervalInclusion_map_strictMono
#print axioms CategoryTheory.Triangulated.intervalSubobject_arrow_strictMono
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformed_intervalProp_subset_old_wide
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformed_Z
#print axioms CategoryTheory.Triangulated.sector_bound'
#print axioms CategoryTheory.Triangulated.stabilitySeminorm_bound_real
#print axioms CategoryTheory.Triangulated.stabilitySeminorm_lt_top_of_near
#print axioms CategoryTheory.Triangulated.finiteSeminormSubgroup
#print axioms CategoryTheory.Triangulated.norm_Z_le_of_tau_semistable
#print axioms CategoryTheory.Triangulated.norm_sum_exp_ge_cos_mul_sum
#print axioms CategoryTheory.Triangulated.stabilitySeminorm_le_of_near
#print axioms CategoryTheory.Triangulated.finiteSeminormSubgroup_eq_of_basisNhd
#print axioms CategoryTheory.Triangulated.intrinsicPhaseBounds_of_semistable_slicingDist
#print axioms CategoryTheory.Triangulated.stabilitySeminorm_lt_top_of_same_Z
#print axioms CategoryTheory.Triangulated.finiteSeminormSubgroup_eq_of_same_Z
#print axioms CategoryTheory.Triangulated.sector_bound
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.false_of_all_hn_phases_below
#print axioms CategoryTheory.Triangulated.gt_phases_of_gtProp
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.phiMinus_le_le_phiPlus
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.phase_eq_of_same_Z
#print axioms CategoryTheory.Triangulated.phiPlus_le_of_leProp
#print axioms CategoryTheory.Triangulated.im_divided_of_semistable
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.P_of_Q_of_P_semistable
#print axioms CategoryTheory.Triangulated.eq_of_pos_mul_exp_eq
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.false_of_all_hn_phases_above
#print axioms CategoryTheory.Triangulated.bridgeland_lemma_6_4
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.false_of_gt_and_le_phases
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.false_of_hn_phases_le_with_lt
#print axioms CategoryTheory.Triangulated.basisNhd_mono
#print axioms CategoryTheory.Triangulated.exists_basisNhd_subset_basisNhd
#print axioms CategoryTheory.Triangulated.linearInterpolationZ_zero
#print axioms CategoryTheory.Triangulated.basisNhd_self
#print axioms CategoryTheory.Triangulated.linearInterpolationZ_sub
#print axioms CategoryTheory.Triangulated.exists_local_lift_sameComponent_in_basisNhd
#print axioms CategoryTheory.Triangulated.wideSectorFiniteLength_mono
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.exists_epsilon0_sixteenth
#print axioms CategoryTheory.Triangulated.linearInterpolationZ_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.eq_of_same_Z_near
#print axioms CategoryTheory.Triangulated.linearInterpolationZ
#print axioms CategoryTheory.Triangulated.basisNhd_subset_connectedComponent_small
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformation
#print axioms CategoryTheory.Triangulated.stabilitySeminorm_smul_complex
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.eq_of_same_Z_of_mem_basisNhd
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.exists_eq_Z_and_mem_basisNhd_of_stabilitySeminorm_lt_sin
#print axioms CategoryTheory.Triangulated.stabilitySeminorm_dominated_of_basisNhd
#print axioms CategoryTheory.Triangulated.linearInterpolationZ_sub_sub
#print axioms CategoryTheory.Triangulated.stabilitySeminorm_smul
#print axioms CategoryTheory.Triangulated.stabilitySeminorm_center_dominates_of_basisNhd
#print axioms CategoryTheory.Triangulated.Z_mem_finiteSeminormSubgroup
#print axioms CategoryTheory.Triangulated.exists_basisNhd_subset_connectedComponent
#print axioms CategoryTheory.Triangulated.basisNhdFamily
#print axioms CategoryTheory.Triangulated.stabilitySeminorm_dominated_of_connected
#print axioms CategoryTheory.Triangulated.eq_zero_of_stabilitySeminorm_toReal_eq_zero
#print axioms CategoryTheory.Triangulated.exists_basisNhd_subset_of_mem_nhds
#print axioms CategoryTheory.Triangulated.eq_zero_of_vanishes_on_cl
#print axioms CategoryTheory.Triangulated.finiteSeminormSubgroup_eq_of_connected
#print axioms CategoryTheory.Triangulated.stabilityCondition_isOpen_connectedComponent
#print axioms CategoryTheory.Triangulated.exists_basisNhd_subset_of_mem_open
#print axioms CategoryTheory.Triangulated.isTopologicalBasis_basisNhd
#print axioms CategoryTheory.Triangulated.ComponentTopologicalLinearLocalModel
#print axioms CategoryTheory.Triangulated.componentSeminormTopology_eq_normTopology
#print axioms CategoryTheory.Triangulated.componentSeminormBall
#print axioms CategoryTheory.Triangulated.componentSeminormTopology
#print axioms CategoryTheory.Triangulated.componentNorm_equivalent_of_mem_component
#print axioms CategoryTheory.Triangulated.componentSeminormSubgroup
#print axioms CategoryTheory.Triangulated.isTopologicalBasis_componentSeminormBasis
#print axioms CategoryTheory.Triangulated.componentZMap
#print axioms CategoryTheory.Triangulated.componentTopologicalLinearLocalModel
#print axioms CategoryTheory.Triangulated.componentSeminormBasis
#print axioms CategoryTheory.Triangulated.componentSeminorm_lt_top_of_mem_component
#print axioms CategoryTheory.Triangulated.componentRep
#print axioms CategoryTheory.Triangulated.componentSeminormBall_eq_ball
#print axioms CategoryTheory.Triangulated.componentNormedAddCommGroup
#print axioms CategoryTheory.Triangulated.componentNorm
#print axioms CategoryTheory.Triangulated.componentNormedSpace
#print axioms CategoryTheory.Triangulated.ComponentTopologicalLinearLocalModel.chargeMap
#print axioms CategoryTheory.Triangulated.componentStabilityCondition
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.CentralChargeIsLocalHomeomorphOnConnectedComponents
#print axioms CategoryTheory.Triangulated.componentZ_mem
#print axioms CategoryTheory.Triangulated.mk_componentRep
#print axioms CategoryTheory.Triangulated.centralChargeIsLocalHomeomorphOnConnectedComponents
#print axioms CategoryTheory.Triangulated.componentAddGroupNorm
#print axioms CategoryTheory.Triangulated.StabilityFunction.shortExact_of_mono
#print axioms CategoryTheory.Triangulated.mem_semiClosedUpperHalfPlane_of_arg_pos
#print axioms CategoryTheory.Triangulated.arg_le_of_cross_nonneg
#print axioms CategoryTheory.Triangulated.inf_le_arg_sum_of_semiClosedUpperHalfPlane
#print axioms CategoryTheory.Triangulated.cross_pos_of_arg_lt
#print axioms CategoryTheory.Triangulated.cross_nonneg_of_arg_le
#print axioms CategoryTheory.Triangulated.arg_sum_le_sup_of_semiClosedUpperHalfPlane
#print axioms CategoryTheory.Triangulated.sum_mem_semiClosedUpperHalfPlane
#print axioms CategoryTheory.Triangulated.StabilityFunction.isSemistable_cokernel_mapMono_iff
#print axioms CategoryTheory.Triangulated.StabilityFunction.Subobject.ofLE_map_comp_mapMonoIso_hom
#print axioms CategoryTheory.Triangulated.StabilityFunction.Subobject.mapMonoIso
#print axioms CategoryTheory.Triangulated.StabilityFunction.Subobject.map_eq_mk_mono
#print axioms CategoryTheory.Triangulated.StabilityFunction.exists_hn_with_last_phase_of_semistable
#print axioms CategoryTheory.Triangulated.StabilityFunction.append_hn_filtration_of_mono
#print axioms CategoryTheory.Triangulated.StabilityFunction.Subobject.cokernelMapMonoIso
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase_cokernel_mapMono_eq
#print axioms CategoryTheory.Triangulated.interval_thinFiniteLength_of_inclusion_strict
#print axioms CategoryTheory.Triangulated.intervalInclusion_isAdmissibleSubobject
#print axioms CategoryTheory.Triangulated.interval_finiteLength_of_inclusion
#print axioms CategoryTheory.Triangulated.autFunctor_isAdmissibleSubobject
#print axioms CategoryTheory.Triangulated.chargeHom_norm_le_of_intrinsic_width
#print axioms CategoryTheory.Triangulated.Tilting.TStructure.triangleLTGE_iso_of_amp_negOne_zero
#print axioms CategoryTheory.Triangulated.Tilting.originalHeartCohNegOneIsoOfAmplitude
#print axioms CategoryTheory.Triangulated.Tilting.originalHeartCohZeroIsoOfAmplitude
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.observableStabilityFunctionOnHeart_phase_le_phiPlus
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.observableStabilityFunctionOnHeart_phase_eq_of_mem_P
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.observableStabilityFunctionOnHeart_isSemistable_of_mem_P
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseIndex
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseIndex_le_of_lt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseBase_add_one
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseIndex_eq_zero_of_mem_Ioc
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseBase_mem
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseBase
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseIndex_lt_phase
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseBase_eq_of_mem_Ioc
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phase_le_phaseIndex_add_one
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseBase_add_phaseIndex
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseIndex_add_one

#print axioms CategoryTheory.Triangulated.semiClosedUpperHalfPlane
#print axioms CategoryTheory.Triangulated.semiClosedUpperHalfPlane_ne_zero
#print axioms CategoryTheory.Triangulated.arg_pos_of_mem_semiClosedUpperHalfPlane
#print axioms CategoryTheory.Triangulated.StabilityFunction
#print axioms CategoryTheory.Triangulated.StabilityFunction.ext
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase_pos
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase_le_one
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase_mem_Ioc
#print axioms CategoryTheory.Triangulated.StabilityFunction.IsSemistable
#print axioms CategoryTheory.Triangulated.StabilityFunction.IsStable
#print axioms CategoryTheory.Triangulated.StabilityFunction.exists_destabilizing_of_not_semistable
#print axioms CategoryTheory.Triangulated.StabilityFunction.charge_eq_of_iso
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase_eq_of_iso
#print axioms CategoryTheory.Triangulated.StabilityFunction.isSemistable_of_iso
#print axioms CategoryTheory.Triangulated.StabilityFunction.isSemistable_iff_of_iso
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.n
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.chain
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.chain_bot
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.chain_top
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.chain_strictMono
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.factor_semistable
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.factor_phase
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.nonempty
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phase
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phiPlus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phiMinus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phase_mem_range
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phiMinus_le_phiPlus
#print axioms CategoryTheory.Triangulated.StabilityFunction.HasHNProperty
#print axioms CategoryTheory.Triangulated.StabilityFunction.subobject_isZero_iff_eq_bot
#print axioms CategoryTheory.Triangulated.StabilityFunction.subobject_ne_bot_of_not_isZero
#print axioms CategoryTheory.Triangulated.StabilityFunction.subobject_not_isZero_of_ne_bot
#print axioms CategoryTheory.Triangulated.StabilityFunction.subobject_top_ne_bot_of_not_isZero
#print axioms CategoryTheory.Triangulated.StabilityFunction.subobject_ofLE_bot
#print axioms CategoryTheory.Triangulated.StabilityFunction.subobjectCokernelBotIso
#print axioms CategoryTheory.Triangulated.StabilityFunction.cokernel_not_isZero_of_ne_top
#print axioms CategoryTheory.Triangulated.StabilityFunction.imageSubobject_epi_comp
#print axioms CategoryTheory.Triangulated.StabilityFunction.imageSubobject_eq_top_of_epi
#print axioms CategoryTheory.Triangulated.StabilityFunction.pullback_obj_injective_of_epi
#print axioms CategoryTheory.Triangulated.im_nonneg_of_mem_semiClosedUpperHalfPlane
#print axioms CategoryTheory.Triangulated.add_mem_semiClosedUpperHalfPlane
#print axioms CategoryTheory.Triangulated.phaseCross
#print axioms CategoryTheory.Triangulated.phaseCross_eq_norm_mul_sin
#print axioms CategoryTheory.Triangulated.phaseCross_nonneg_of_arg_le
#print axioms CategoryTheory.Triangulated.arg_le_of_phaseCross_nonneg
#print axioms CategoryTheory.Triangulated.phaseCross_pos_of_arg_lt
#print axioms CategoryTheory.Triangulated.arg_lt_of_phaseCross_pos
#print axioms CategoryTheory.Triangulated.arg_add_le_max
#print axioms CategoryTheory.Triangulated.arg_add_lt_max
#print axioms CategoryTheory.Triangulated.min_arg_le_arg_add
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase_le_max_of_shortExact
#print axioms CategoryTheory.Triangulated.StabilityFunction.min_phase_le_of_shortExact
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase_le_of_epi
#print axioms CategoryTheory.Triangulated.StabilityFunction.hom_eq_zero_of_semistable_phase_gt
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase_cokernel_ofLE_congr
#print axioms CategoryTheory.Triangulated.StabilityFunction.isSemistable_cokernel_ofLE_congr
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.n_eq_one_of_semistable
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.isSemistable_of_n_eq_one
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.n_eq_one_iff_isSemistable
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.two_le_n_of_not_isSemistable
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.le_of_arrow_comp_cokernel_zero
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.pullback_cokernel_bot_eq
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.card_subobject_cokernel_lt
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.le_pullback_cokernel
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.ofLE_pullbackπ_cokernel_eq_zero
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.shortExact_ofLE_pullbackπ_cokernel
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.charge_pullback_eq_add
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.pullback_imageSubobject_eq
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.charge_cokernel_pullback_eq
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phase_cokernel_pullback_eq
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.cokernelPullbackIso
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.tail
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.tail_n
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.transport_n
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.n_eq
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.le_of_ofLE_comp_cokernel_zero
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.hom_eq_zero_to_factor
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.le_chain_of_semistable_phase_gt
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.eq_bot_of_semistable_phase_gt_phiPlus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.chain_one_ne_bot
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phase_chain_one
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.chain_one_isSemistable
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phiPlus_eq
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.chain_one_eq
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.semistable_phase_le_phiPlus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.le_chain_one_of_semistable_phase_eq_phiPlus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.chain_one_maximal_semistable_phase
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.hom_eq_zero_to_semistable_of_phase_lt_phiMinus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phiMinus_eq
#print axioms CategoryTheory.Triangulated.StabilityFunction.phiPlus
#print axioms CategoryTheory.Triangulated.StabilityFunction.phiMinus
#print axioms CategoryTheory.Triangulated.StabilityFunction.maxDestabilizingSubobject
#print axioms CategoryTheory.Triangulated.StabilityFunction.maxDestabilizingSubobject_eq_filtration
#print axioms CategoryTheory.Triangulated.StabilityFunction.maxDestabilizingSubobject_ne_bot
#print axioms CategoryTheory.Triangulated.StabilityFunction.maxDestabilizingSubobject_isSemistable
#print axioms CategoryTheory.Triangulated.StabilityFunction.maxDestabilizingSubobject_eq_top_iff_isSemistable
#print axioms CategoryTheory.Triangulated.StabilityFunction.destabilizingQuotient
#print axioms CategoryTheory.Triangulated.StabilityFunction.isZero_destabilizingQuotient_iff_isSemistable
#print axioms CategoryTheory.Triangulated.StabilityFunction.destabilizingQuotient_not_isZero_of_not_isSemistable
#print axioms CategoryTheory.Triangulated.StabilityFunction.destabilizingShortComplex
#print axioms CategoryTheory.Triangulated.StabilityFunction.destabilizingShortComplex_shortExact
#print axioms CategoryTheory.Triangulated.StabilityFunction.charge_eq_maxDestabilizingSubobject_add_destabilizingQuotient
#print axioms CategoryTheory.Triangulated.StabilityFunction.phiPlus_eq_filtration
#print axioms CategoryTheory.Triangulated.StabilityFunction.phase_maxDestabilizingSubobject
#print axioms CategoryTheory.Triangulated.StabilityFunction.le_maxDestabilizingSubobject_of_semistable_phase_eq_phiPlus
#print axioms CategoryTheory.Triangulated.StabilityFunction.phiMinus_eq_filtration
#print axioms CategoryTheory.Triangulated.StabilityFunction.phiMinus_le_phiPlus
#print axioms CategoryTheory.Triangulated.StabilityFunction.isSemistable_iff_phiPlus_eq_phiMinus


/-! ## Slope stability as a stability function

Rank and degree data give the charge `-degree + i * rank`, and that charge is a
`StabilityFunction`: μ-slope stability is not a parallel theory but an instance
of the interface the phase and Harder–Narasimhan machinery is already built on.
`phase_le_iff_slope_le` is the order bridge. -/

#print axioms CategoryTheory.Triangulated.SlopeData
#print axioms CategoryTheory.Triangulated.SlopeData.mk.inj
#print axioms CategoryTheory.Triangulated.SlopeData.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.SlopeData.rank
#print axioms CategoryTheory.Triangulated.SlopeData.degree
#print axioms CategoryTheory.Triangulated.SlopeData.rank_nonneg
#print axioms CategoryTheory.Triangulated.SlopeData.rank_zero
#print axioms CategoryTheory.Triangulated.SlopeData.degree_zero
#print axioms CategoryTheory.Triangulated.SlopeData.rank_iso
#print axioms CategoryTheory.Triangulated.SlopeData.degree_iso
#print axioms CategoryTheory.Triangulated.SlopeData.rank_additive
#print axioms CategoryTheory.Triangulated.SlopeData.degree_additive
#print axioms CategoryTheory.Triangulated.SlopeData.degree_pos_of_rank_zero
#print axioms CategoryTheory.Triangulated.SlopeData.charge
#print axioms CategoryTheory.Triangulated.SlopeData.charge_re
#print axioms CategoryTheory.Triangulated.SlopeData.charge_im
#print axioms CategoryTheory.Triangulated.SlopeData.charge_mem_semiClosedUpperHalfPlane
#print axioms CategoryTheory.Triangulated.SlopeData.toStabilityFunction
#print axioms CategoryTheory.Triangulated.SlopeData.toStabilityFunction_charge
#print axioms CategoryTheory.Triangulated.SlopeData.slope
#print axioms CategoryTheory.Triangulated.SlopeData.phaseCross_charge
#print axioms CategoryTheory.Triangulated.SlopeData.charge_ne_zero_of_rank_pos
#print axioms CategoryTheory.Triangulated.SlopeData.arg_pos_of_rank_pos
#print axioms CategoryTheory.Triangulated.SlopeData.phase_le_iff_slope_le

/-! ## The two classes at a phase cutoff

`T β` and `F β` for a stability function, and what the Harder–Narasimhan
machinery already gives: intrinsic membership, trivial intersection, and
Hom-vanishing to a semistable target. Not yet a torsion pair — see the module
docstring for the two steps still missing. -/

#print axioms CategoryTheory.Triangulated.StabilityFunction.hnTors
#print axioms CategoryTheory.Triangulated.StabilityFunction.hnFree
#print axioms CategoryTheory.Triangulated.StabilityFunction.isZero_mem_hnTors
#print axioms CategoryTheory.Triangulated.StabilityFunction.isZero_mem_hnFree
#print axioms CategoryTheory.Triangulated.StabilityFunction.mem_hnTors_iff_forall
#print axioms CategoryTheory.Triangulated.StabilityFunction.mem_hnFree_iff_forall
#print axioms CategoryTheory.Triangulated.StabilityFunction.isZero_of_mem_hnTors_of_mem_hnFree
#print axioms CategoryTheory.Triangulated.StabilityFunction.hom_eq_zero_of_mem_hnTors_of_semistable

/-! ## Monotonicity of the extremal phases, and Hom-vanishing in general

`φ⁺` cannot rise along a monomorphism and `φ⁻` cannot fall along an
epimorphism. Applied to the image of a map — a quotient of the source and a
subobject of the target — the two bound `T β`'s Hom into `F β` to zero, which
is the Hom-vanishing half of Bridgeland's torsion pair. -/

#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.exists_epi_to_semistable_phase_phiMinus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phiPlus_le_of_mono
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.phiMinus_le_of_epi
#print axioms CategoryTheory.Triangulated.StabilityFunction.hom_eq_zero_of_mem_hnTors_of_mem_hnFree

/-! ## Cutting an HN filtration, and the splitting at a cutoff

`tail` generalizes to `tailAt`, which cuts above any index; `restrict` is the
other half, the chain below an index as a filtration of the term there; `ofIso`
transports a filtration along an isomorphism. Cutting at the crossing index
named by `exists_crossIndex` puts every object in a short exact sequence with a
sub in `T β` and a quotient in `F β`. -/

#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.tailAt
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.tailAt_n
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.tailAt_phase
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.tailAt_phiPlus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.tailAt_phiMinus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.restrictChain
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.restrictChain.congr_simp
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.map_restrictChain
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.restrictChain_le
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.restrict
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.restrict_n
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.restrict_phiPlus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.restrict_phiMinus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.ofIso
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.ofIso_phiPlus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.ofIso_phiMinus
#print axioms CategoryTheory.Triangulated.AbelianHNFiltration.exists_crossIndex
#print axioms CategoryTheory.Triangulated.StabilityFunction.hnTors_of_iso
#print axioms CategoryTheory.Triangulated.StabilityFunction.hnFree_of_iso
#print axioms CategoryTheory.Triangulated.StabilityFunction.exists_subobject_hnTors_cokernel_hnFree
#print axioms CategoryTheory.Triangulated.StabilityFunction.exists_shortExact_hnTors_hnFree

/-! ## Where the rank-zero objects go

The charge `-degree + i·rank` puts a nonzero object of rank zero on the negative
real axis, so its phase is one. Rank zero passes to every Harder--Narasimhan
factor, so `φ⁻` is one too and such an object is torsion at every cutoff below
one -- the torsion sheaves, in the geometric case. -/

#print axioms CategoryTheory.Triangulated.SlopeData.rank_eq_zero_of_shortExact
#print axioms CategoryTheory.Triangulated.SlopeData.phase_eq_one_of_rank_zero
#print axioms CategoryTheory.Triangulated.SlopeData.mem_hnTors_of_rank_zero

/-! ## A phase cutoff, read as a slope cutoff

`Cutoff.lean` cuts by a phase; Bridgeland's §6 cuts by a slope. `phase_le_iff_slope_le` relates
the two orders but only between two OBJECTS, so nothing turned a cutoff into a slope, and every
case of Lemma 6.2 needs exactly that. `slopeOfPhase β = -cot(πβ)` is the translation: the charge
`-degree + i·rank` puts a positive-rank object in the open upper half plane, testing against the
ray at angle `πβ` is `phaseCross` with `cos(πβ) + sin(πβ)·i`, and that computes to
`rank·cos(πβ) + degree·sin(πβ)`, whose positivity is `-cot(πβ) < degree/rank` after dividing by
`rank·sin(πβ) > 0`. The hypotheses `0 < β < 1` and `0 < rank` are the geometry's own: the first
makes `sin(πβ) > 0`, the second is why rank-zero objects go through `mem_hnTors_of_rank_zero`
instead.
-/

#print axioms CategoryTheory.Triangulated.slopeOfPhase
#print axioms CategoryTheory.Triangulated.SlopeData.lt_phase_iff_slopeOfPhase_lt
#print axioms CategoryTheory.Triangulated.SlopeData.phase_le_iff_le_slopeOfPhase

/-! ## `K₀Ab` producers and the heart comparison (K₀ unification)

`liftOf` is the universal property in the form producers want: additivity supplied as a
proof, with `map_zero` and `map_iso` following. `toAmbient` is the comparison
`K₀Ab 𝒜 →+ K₀ C` — the map, not the isomorphism `K(𝒜) ≅ K(D)` that the pin does not
provide and that nothing here assumes.
-/

#print axioms CategoryTheory.K₀Ab.liftOf
#print axioms CategoryTheory.K₀Ab.liftOf_of
#print axioms CategoryTheory.Triangulated.TStructure.shortExactToTriangle
#print axioms CategoryTheory.Triangulated.TStructure.toAmbient_isAdditive
#print axioms CategoryTheory.K₀Ab.toAmbient
#print axioms CategoryTheory.K₀Ab.toAmbient_of

/-! ## Positivity relative to a class datum

The abelian and ambient theories differ only in which objects the condition speaks about
and which group carries the classes. `ClassDatum` makes those the parameters, so there is
one structure at two class data rather than two structures with the same fields, and
`IsStabilityCharge.weak` is proved once for every datum.
-/

#print axioms CategoryTheory.Triangulated.closedUpperHalfPlane
#print axioms CategoryTheory.Triangulated.semiClosedUpperHalfPlane_subset_closed
#print axioms CategoryTheory.Triangulated.ClassDatum
#print axioms CategoryTheory.Triangulated.ClassDatum.mk
#print axioms CategoryTheory.Triangulated.ClassDatum.mk.inj
#print axioms CategoryTheory.Triangulated.ClassDatum.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.ClassDatum.Relevant
#print axioms CategoryTheory.Triangulated.ClassDatum.cl
#print axioms CategoryTheory.Triangulated.IsPositive
#print axioms CategoryTheory.Triangulated.IsStabilityCharge
#print axioms CategoryTheory.Triangulated.IsWeakStabilityCharge
#print axioms CategoryTheory.Triangulated.IsStabilityCharge.weak
#print axioms CategoryTheory.Triangulated.StabilityFunctionOn
#print axioms CategoryTheory.Triangulated.StabilityFunctionOn.mk
#print axioms CategoryTheory.Triangulated.StabilityFunctionOn.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityFunctionOn.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityFunctionOn.mk.congr_simp
#print axioms CategoryTheory.Triangulated.StabilityFunctionOn.Z
#print axioms CategoryTheory.Triangulated.StabilityFunctionOn.nonzero_mem
#print axioms CategoryTheory.Triangulated.WeakStabilityFunctionOn
#print axioms CategoryTheory.Triangulated.WeakStabilityFunctionOn.mk
#print axioms CategoryTheory.Triangulated.WeakStabilityFunctionOn.mk.inj
#print axioms CategoryTheory.Triangulated.WeakStabilityFunctionOn.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.WeakStabilityFunctionOn.Z
#print axioms CategoryTheory.Triangulated.WeakStabilityFunctionOn.nonzero_mem
#print axioms CategoryTheory.Triangulated.StabilityFunctionOn.toWeak
#print axioms CategoryTheory.Triangulated.StabilityFunctionOn.toWeak_Z
#print axioms CategoryTheory.Triangulated.abelianDatum
#print axioms CategoryTheory.Triangulated.abelianDatum_cl
#print axioms CategoryTheory.Triangulated.abelianDatum_relevant

/-! ## `StabilityFunction`, restated over `K₀Ab`

`map_zero`, `map_iso` and `additive` are theorems now, not fields; the names and argument
shapes are unchanged so consumers are untouched.
-/

#print axioms CategoryTheory.Triangulated.StabilityFunction.charge_apply
#print axioms CategoryTheory.Triangulated.StabilityFunction.map_zero
#print axioms CategoryTheory.Triangulated.StabilityFunction.map_iso
#print axioms CategoryTheory.Triangulated.StabilityFunction.additive

/-! ## `SlopeData` and `MukaiChargeData`, collapsed onto `K₀Ab`

`SlopeData` carried ten fields, six of them the axiom triple twice over. Rank and degree
are now two homs and the six are theorems. `MukaiChargeData` carried four and now carries
one.
-/

#print axioms CategoryTheory.Triangulated.SlopeData.rankHom
#print axioms CategoryTheory.Triangulated.SlopeData.degreeHom
#print axioms CategoryTheory.Triangulated.SlopeData.rank
#print axioms CategoryTheory.Triangulated.SlopeData.degree
#print axioms CategoryTheory.Triangulated.expCharge_zero
#print axioms CategoryTheory.Triangulated.expCharge_add
#print axioms CategoryTheory.Triangulated.MukaiChargeData
#print axioms CategoryTheory.Triangulated.MukaiChargeData.mk
#print axioms CategoryTheory.Triangulated.MukaiChargeData.mk.inj
#print axioms CategoryTheory.Triangulated.MukaiChargeData.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.MukaiChargeData.mukai
#print axioms CategoryTheory.Triangulated.MukaiChargeData.charge
#print axioms CategoryTheory.Triangulated.MukaiChargeData.charge_apply
#print axioms CategoryTheory.Triangulated.MukaiChargeData.charge_zero
#print axioms CategoryTheory.Triangulated.MukaiChargeData.charge_iso
#print axioms CategoryTheory.Triangulated.MukaiChargeData.charge_additive

/-! ## `extendMap`, bundled

The Mukai-lattice leg of the charge chain was additive and unbundled like the numerical leg.
-/

#print axioms Mukai.extendMapHom
