/-
Mass--Hom slice of the StabilityCondition audit. The predicate is abstract;
the scheme-perfect test class is audited on the geometry side.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.MassHom

#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBoundFor
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasGlobalMassHomBound
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.anti
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.top_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBoundFor.bound_congr
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBoundFor.congr
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBoundFor.exists_semistable_bound
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBoundFor.bound_shift_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBoundFor.bound_shift_neg_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBoundFor.shift_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBoundFor.shift_neg_one
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.autPair_act
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.autPair_act_iff
#print axioms CategoryTheory.Triangulated.HNFiltration.relabelStability
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.glMassBound
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.glMassBound_pos
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.stabilityMass_smul_le
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.stabilityMass_le_smul
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.gltilde_smul
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.gltilde_smul_iff

/-! ## Finite distance and connected components -/

#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.finiteDistanceClass
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.isClopen_finiteDistanceClass
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.connectedComponent_subset_finiteDistanceClass
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.of_stabilityDist_lt
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.of_finiteDistance
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.finiteDistance_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.of_mem_connectedComponent
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.massHomLocus
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.isOpen_massHomLocus
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.isClosed_massHomLocus
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.isClopen_massHomLocus

/-! ## Full support from finite Euler probes -/

#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.EulerProbeFamily
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.SemistableExtWindow
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.FullSupport.probeQuadratic
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.FullSupport.chargeQuadratic
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.FullSupport.hasQuadraticSupportProperty_of_finite_probes
#print axioms CategoryTheory.Triangulated.StabilityCondition.WithClassMap.HasMassHomBound.quadraticSupportData
