/-
WeakStability slice of the StabilityCondition audit, split out so concurrent
branches append to different files (#480). See the umbrella file for the contract and reading guide.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition
import DerivedAlgGeo.CategoryTheory.Triangulated.FourierMukai
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearYoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearCoyoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.GrothendieckGroup.EulerForm
import DerivedAlgGeo.LinearAlgebra
open CategoryTheory.Triangulated

/-! ## WeakStability lane -- the section-14 definitions

Definitions 14.1-14.3 of 1902.08184v4 on the abstract layer, plus the
ordinary-into-weak embeddings and the closure properties of the zero-charge
subcategory. The three `structure`s and the constructions among these report
axiom closures of DEFINITIONS; the embedding and closure results are the
theorems. Closes #107; no source binding is claimed (see the module
docstring and #111). -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.ofStrict
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.toWeak
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityFunction
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.upper
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityFunction.upper
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityFunction.toWeak
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.StabilityFunction.toWeak_Z
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.charge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.charge_triangle
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.charge_triangle'
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.charge_isZero
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.slope
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.slope_of_im_pos
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.slope_of_im_nonpos
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.IsSemistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.IsStable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.IsStable.isSemistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.zeroCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.zeroCharge_def
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.zeroCharge_isClosedUnderIsomorphisms
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.charge_eq_zero_pair
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.zeroCharge_left
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.zeroCharge_right
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.zeroCharge_extension

/-! ## WeakStability lane -- noetherian torsion subcategories

Definition 14.6 in Remark 14.7's chain form (the design decision is in the
module docstring), the free = B-perp identification riding on
free_of_orthogonal, and the zero-subcategory nonvacuity witness. Lemmas
14.8 and 14.11 are deliberately UNDECLARED with their gaps named in the
module -- absent beats sorry-backed. Closes #108. -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.IsHeartMono
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.SubobjectChain
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.SubobjectChain.Terminates
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.NoetherianTorsionSubcategory
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.rightOrthogonal
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.free_iff_rightOrthogonal
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.isIso_of_isZero
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.zeroTorsionPair
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.zeroNoetherianTorsion
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.noetherian_mono

/-! ## WeakStability lane -- the torsion pair at a phase cutoff

Display (14.1) in phase language, unconditional on the slicing axioms: the
pair (P((b,1]), P((0,b])) as a HeartTorsionPair on the slicing-induced
t-structure, with the HN cut as decomposition and the slicing's own
hom-vanishing as the orthogonality. slicingTilt_heart_iff composes with
tilt_heart_iff (#106) to identify the tilted heart. The normalized
slope--phase ray identity is formalized later in this lane, but the exact
source-facing cutoff equivalence is not packaged or reviewed; the coverage
map therefore remains `mapped`, not a claim. Closes #109. -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseTors
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseFree
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.leProp_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.gtProp_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.mem_heart_of_bounds
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.slicingTorsionPair
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.slicingTorsionPair_tors
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.slicingTorsionPair_free
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.slicingTilt_heart_iff

/-! ## WeakStability lane -- the tilting property

Definition 14.12 in phase language: A0 is the torsion class of a noetherian
torsion subcategory, and every heart object with phiPlus below the boundary
has a heart-triangle envelope with zero-charge quotient and shifted
Hom-vanishing. The later phase-language Lemma 14.17 infrastructure and
phase-language Proposition 14.16 infrastructure make no coverage promotion:
the map stays `mapped`, and the exact source proposition remains undeclared.
The raw Definition 14.12 envelope is now sufficient for the heart-level
assembly. -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.IsNoetherianTorsionSubcategory
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.zeroCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.HasFiniteMaxSlope
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.HasTiltingEnvelope
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.HasPhaseTiltingEnvelope
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.HasPhaseTiltingEnvelope.hasTiltingEnvelope
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.TiltingProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.TiltingProperty.hasTiltingEnvelope_of_phaseFree

/-! ## WeakStability lane -- heart equivalence and weak HN infrastructure

The two stacked weak-stability milestones following #110: isomorphism
transport for weak stability functions, the slicing-to-heart forward bridge,
and abelian weak Harder--Narasimhan filtrations with existence for the induced
heart function.  These declarations make no new source-coverage claim. -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.charge_eq_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.isSemistable_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.slope_eq_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.isSemistable_iff_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.isStable_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.isStable_iff_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart_Z
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart_charge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart_zeroCharge_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.charge_mem_upperHalfPlane_and_arg_le_phiPlus
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.pi_mul_phiMinus_le_charge_arg_of_im_pos
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart_isSemistable_of_mem_P_phi
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.mem_P_phiPlus_of_weakStabilityFunctionOnHeart_isSemistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart_isSemistable_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.SlicingBridge.phiPlus_le_of_heart_subobject
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.heartSlope
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.heartSlope_cokernel_ofLE_congr
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.heartSlope_cokernel_mapMono_eq
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.heartSemistable_cokernel_ofLE_congr
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.heartSemistable_cokernel_mapMono_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration.factor
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration.factor_not_isZero
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration.factor_obj_not_isZero
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.HeartSemistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.HasHNProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.append_hn_filtration_of_mono
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.exists_hn_with_last_slope_of_semistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.HNQuotientStep
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.HasHNQuotientInduction
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.hasHNProperty_of_quotientInduction
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.instAbelianFullSubcategoryHeart_derivedAlgGeo_2
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.charge_arg_eq_pi_mul_of_mem_P_phi_lt_one
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.charge_im_pos_of_mem_P_phi_lt_one
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slope_lt_of_mem_P_of_phase_lt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slope_eq_top_of_mem_P_one
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart_hasHN
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.instAbelianFullSubcategoryHeart_derivedAlgGeo
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.instAbelianFullSubcategoryHeart_derivedAlgGeo_1

/-! ## WeakStability lane -- phase-tilt semistable classification

The rotated weak stability function on the HRS tilt, both directions of the
phase-language counterpart of Lemma 14.17, and the positive-imaginary/stable
Hom-vanishing refinement.  These entries make no source-coverage promotion:
the slope--phase reparameterisation remains the mapped boundary. -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltRotation
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltRotation_apply
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltCharge_apply
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.WeakUpperClosed
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakUpperClosed_zero
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakUpperClosed_sum
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakUpperClosed_eq_zero_of_sum_eq_zero
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.rotatedRay_weakUpperClosed
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.cross
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.rotatedCharge_cross_ray_nonneg_of_bounds
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltHeart_interval
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltHeart_iff_phaseShiftHeart
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltWeakStabilityFunction
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltWeakStabilityFunction_Z
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltWeakStabilityFunction_charge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.zeroCharge_mem_P_one
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltWeakStabilityFunction_zeroCharge_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.hom_eq_zero_of_zeroCharge_to_phaseTiltSemistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_isSemistable_left_of_zeroCharge_right
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart_isSemistable_of_phaseTors_phaseTiltSemistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart_isSemistable_of_phaseFree_shiftSemistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltWeakStabilityFunction_isSemistable_of_ray
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.IsPhaseTiltTypeOne
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.IsPhaseTiltTypeTwo
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.isSemistable_of_isPhaseTiltTypeOne
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.isSemistable_of_isPhaseTiltTypeTwo
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltClassification_of_isSemistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.isSemistable_of_phaseTiltClassification
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltWeakStabilityFunction_isSemistable_iff_classification

/-! ## WeakStability lane -- Proposition 14.16 heart-level assembly

The maximal-zero-charge-subobject construction, raw-envelope noetherian
assembly, boundary-saturated weak HN assembly over the cohomological `H⁻¹`
and `H⁰` filtrations, and support-property transport. Proposition 14.16
itself remains undeclared, but its heart-level constructive obligations are
assembled directly from Definition 14.12's `TiltingProperty`. -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.HasZeroChargeDecompositions
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.zeroChargeTorsionPair
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.zeroChargeTorsionPair_tors
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.zeroChargeTorsionPair_free
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.heartZeroCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.heartZeroCharge_isSerreClass
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.rightOrthogonal_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.cokernelCompShortComplex
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.cokernelCompShortComplex_shortExact
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.kernelCokernelCompMiddleShortComplex
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.kernelCokernelCompMiddleShortComplex_shortExact
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.kernelCompShortComplex
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.kernelCompShortComplex_shortExact
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.isSemistable_middle_of_zeroCharge_quotient
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.isSemistable_quotient_of_zeroCharge_subobject
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.isHeartMono_of_mono
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.mono_of_isHeartMono
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.isNoetherianObject_of_zeroCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.hasZeroChargeDecomposition_of_chainCondition
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.hasZeroChargeDecompositions_of_chainCondition
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.hasZeroChargeDecomposition_of_reduction
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.mono_comp_of_zeroCharge_of_rightOrthogonal
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.mono_in_originalHeart_of_mono_in_phaseTilt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.zeroCharge_phaseTors
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltingEnvelope_gives_shiftedZeroChargeDecomposition
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltingEnvelope_middle_semistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_zeroChargeChain_terminates_of_tiltingEnvelope
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_semistableQuotient_of_saturatedExtension
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_zeroChargeChain_terminates_of_rightOrthogonal
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hasZeroChargeDecompositions_of_freeShiftDecompositions
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hasZeroChargeDecompositions_of_phaseEnvelopes
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hasZeroChargeDecompositions_of_tiltingEnvelopes
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_isNoetherianObject_of_zeroCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltNoetherianTorsionSubcategory
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hasZeroChargeDecompositions_of_chainCondition
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltNoetherianTorsionSubcategoryOfDecompositions
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltNoetherianTorsionSubcategoryOfTiltingProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltNoetherianTorsionSubcategoryOfPhaseEnvelopes
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltNoetherianTorsionSubcategoryOfTiltingEnvelopes
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltNoetherianTorsionSubcategoryOfChainCondition
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltCharge_im_pos_of_phaseTors
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_slope_lt_of_phase_separated
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_slope_shift_lt_shift_of_phase_separated
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_slope_unshifted_lt_shifted_of_phase_separated
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_semistableQuotient_of_extension
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hnLastQuotient
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_existsHNWithLastSource_of_freeShift_zeroCharge_extension
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hasHN_of_freeShift_zeroCharge_extension
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hZeroLastQuotient
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hasHNProperty_of_zeroChargeDecompositions
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.semistableClasses
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.HasSupportProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.isSemistable_of_zeroCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.class_eq_zero_of_zeroCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseTiltLinearCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.phaseTiltLinearCharge_apply
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.norm_phaseTiltLinearCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hasSupportProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.QuadraticSupportData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.QuadraticSupportData.hasSupportProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.QuadraticSupportData.class_eq_zero_of_zeroCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.UniformQuadraticSupportData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.UniformQuadraticSupportData.fiber
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.UniformQuadraticSupportData.reindex
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.QuadraticSupportData.constant
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.QuotientUniformQuadraticSupportData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.QuotientUniformQuadraticSupportData.fiber
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.QuotientUniformQuadraticSupportData.zero_class_eq_zero
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.semistableClasses
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.mem_semistableClasses_iff
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.class_mem_semistableClasses
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.HasSupportProperty
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.QuadraticSupportData
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.QuadraticSupportData.charge_compatible
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.QuadraticSupportData.quadratic
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.QuadraticSupportData.hasSupportProperty
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.UniformQuadraticSupportData
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.UniformQuadraticSupportData.charge_compatible
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.UniformQuadraticSupportData.quadratic
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.UniformQuadraticSupportData.fiber
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.UniformQuadraticSupportData.reindex
#print axioms CategoryTheory.Triangulated.PreStabilityCondition.WithClassMap.QuadraticSupportData.constant
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.PhaseTiltHeartObligations
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltHeartObligations
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltHeartObligationsOfPhaseEnvelopes
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltHeartObligationsOfTiltingProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_hasHNPropertyOfTiltingProperty

/-! ## WeakStability lane -- reverse heart--slicing foundations

The extended-slope phase normalization, integer-normalized ambient phase
family, analytic charge-ray identity, heart-HN to ambient-Postnikov
conversion, and phase-tilt prestability assembly. These declarations package
no source statement and make no §14 coverage promotion. -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.weakPhaseOfSlope
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.weakPhaseOfSlope_top
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.weakPhaseOfSlope_coe
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.weakPhaseOfSlope_coe_mem_Ioo
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.weakPhaseOfSlope_mem_Ioc
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.weakPhaseOfSlope_strictMono
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.weakPhaseOfSlope_lt_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.complex_eq_pos_mul_exp_weakPhaseOfSlope
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.charge_ray_of_mem_heart
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.negOnePow_mul_exp_pi_eq_exp_add_int
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientPhasePredicate_charge_ray
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.phase
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.phase_mem_Ioc
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.phase_lt_phase_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.phase_eq_of_iso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.heartPhasePredicate
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.heartPhasePredicate_closedUnderIso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.heartPhasePredicate_instClosedUnderIso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.shiftedHeartPhasePredicate
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientPhasePredicate
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.shiftedHeartPhasePredicate_zero_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientPhasePredicate_iff_of_mem_Ioc
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.shiftedHeartPhasePredicate_closedUnderIso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientPhasePredicate_closedUnderIso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientPhasePredicate_instClosedUnderIso
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.shiftedHeartPhasePredicate_shift_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientPhasePredicate_shift_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientPhasePredicate_shift_int
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration.factorInclusion
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration.factorInclusion_mono
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.instAbelianFullSubcategoryHeart_derivedAlgGeo_3
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration.factorTriangle
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration.factorTriangle_distinguished
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration.toAmbientHN
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.HNFiltration.relabelPhasePredicate
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakAbelianHNFiltration.toAmbientNormalizedHN
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientHNOfHeart
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientHN_exists_of_mem_heart
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.HNFiltration.shiftWeakAmbient
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.HNFiltration.shiftWeakAmbient_phase
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientHN_exists_of_mem_heart_with_phase_bounds
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientHN_exists_of_pure
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientHN_exists_of_width
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientHN_exists_of_bounded
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientHN_of_bounded
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.heartTorsionPair_tilt_isBounded
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ReverseSlicingObligations
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ReverseSlicingObligations.toSlicing
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ReverseSlicingObligations.toSlicing_P
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ReverseSlicingObligations.toWeakPreStabilityCondition
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ReverseSlicingObligations.toWeakPreStabilityCondition_slicing
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltLatticeCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltLatticeCharge_apply
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTilt_ambientPhasePredicate_charge_ray
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.PhaseTiltHeartObligations.ambientHN_exists_of_mem_tiltedHeart
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.PhaseTiltHeartObligations.ambientHN
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.PhaseTiltHeartObligations.toWeakPreStabilityCondition
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.PhaseTiltHeartObligations.toWeakPreStabilityCondition_Z
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.PhaseTiltHeartObligations.toWeakPreStabilityCondition_P
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltWeakPreStabilityConditionOfTiltingProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltWeakPreStabilityConditionOfTiltingProperty_Z
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.phaseTiltWeakPreStabilityConditionOfTiltingProperty_P

/-! ## WeakStability lane -- source-normalized §14 tilting -/

#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakStabilityFunctionOnHeart_phase_eq_of_mem_P_phi
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.ExtremalHNData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.extremalHNData
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.muPlus
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.muMinus
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakPhaseOfSlope_muPlus
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.weakPhaseOfSlope_muMinus
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeCutPhase
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeCutPhase_mem_Ioo
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.muMinus_gt_iff_phiMinus_gt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.muPlus_le_iff_phiPlus_le
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeTors
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeFree
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeTors_iff_phaseTors
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeFree_iff_phaseFree
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeTorsionPair
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeTorsionPair_tors
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeTorsionPair_free
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.slopeTilt_heart_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltScale
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltScale_pos
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTilt_multiplier
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltRotation
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltRotation_apply
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltRotation_eq_scale_phaseTiltRotation
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltLatticeCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltLatticeCharge_apply
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltLatticeCharge_eq_scale_phaseTiltLatticeCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltCharge_apply
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltCharge_eq_scale_phaseTiltCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_Z
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_charge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_charge_eq_scale_phaseTilt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_slope_eq_phaseTilt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_isSemistable_iff_phaseTilt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_isStable_iff_phaseTilt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_zeroCharge_iff
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_ambientPhasePredicate_eq_phaseTilt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakPreStabilityConditionOfTiltingProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakPreStabilityConditionOfTiltingProperty_Z
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakPreStabilityConditionOfTiltingProperty_P
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakPreStabilityConditionOfTiltingProperty_P_source
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.sourceTiltLinearCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.sourceTiltLinearCharge_apply
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.sourceTiltLinearCharge_eq_scale_phaseTiltLinearCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.norm_sourceTiltLinearCharge
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTilt_hasSupportProperty
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.SourceTiltConclusion
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltConclusion
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltConclusion_condition_Z
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_isSemistable_iff_phaseClassification
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTilt_typeOne_im_nonneg
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTilt_typeTwo_im_neg
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.sourceTiltWeakStabilityFunction_isSemistable_iff_classification
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakPreStabilityCondition.hom_eq_zero_of_zeroCharge_to_sourceTiltSemistable
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.slope_between_of_triangle
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.instAbelianFullSubcategoryHeart
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.slope_le_of_heart_epi
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.heart_subobject_slope_le
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.heart_hom_zero_of_semistable_phase_gt
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.ambientPhasePredicate_hom_zero
#print axioms CategoryTheory.Triangulated.WeakStabilityCondition.WeakStabilityFunction.reverseSlicingObligationsOfHN
