/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.Chambers.Basic
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.Foundation.Deformation.StabilityTopology

/-!
# Topology of charge-vanishing walls

For a lattice class in `Set.range v`, evaluation of the central charge is
continuous on `StabilityCondition.WithClassMap C v`.  Consequently, when `v`
is surjective, each `stabWall` is closed and a regular locus indexed by a
finite set of classes is open.

## Why the range hypothesis is necessary

The owner topology is generated by `Deformation.basisNhd`.  Its charge
coordinate is measured by `Deformation.stabilitySeminorm`, which evaluates a
perturbation only on classes `classOf C v E` and hence only on `Set.range v`.
Charges that agree on that range but differ outside it are therefore
topologically indistinguishable.  Evaluation at an arbitrary `δ : Λ` cannot
be continuous without a range hypothesis; surjectivity is used below only to
put every `δ` in the range.

For an object class, continuity follows directly from an HN filtration: the
seminorm bounds the charge change on every semistable factor, and the
Postnikov-tower identity sums those bounds.  A general element of `K₀ C` need
not be represented by a single object under the hypotheses of this file, so
the proof extends from object classes by
`GrothendieckPresentation.induction_on` rather than assuming such a
representative exists.

The estimates are pointwise in the center stability condition.  No uniform
continuity or Lipschitz bound is asserted.  Openness is proved only for finite
wall sets; the corresponding result for an infinite family would require a
local-finiteness input not present here.
-/

open CategoryTheory.Triangulated
open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open Set
open scoped Topology

namespace CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.StabWall

noncomputable section

universe w u u'

variable {C : Type u} [Category.{w} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
variable {Λ : Type u'} [AddCommGroup Λ] {v : K₀ C →+ Λ}

open Deformation

private theorem exists_basisNhd_radius_sin_mul_lt {a M : ℝ} (ha : 0 < a) :
    ∃ ε : ℝ, 0 < ε ∧ ε < 1 / 8 ∧ Real.sin (Real.pi * ε) * M < a := by
  have hcont : ContinuousAt (fun x : ℝ => Real.sin (Real.pi * x) * M) 0 := by
    fun_prop
  have hcontrol : {x : ℝ | Real.sin (Real.pi * x) * M < a} ∈ 𝓝 0 := by
    exact hcont.preimage_mem_nhds (isOpen_Iio.mem_nhds (by simpa using ha))
  have hsmall : Set.Iio (1 / 8 : ℝ) ∈ 𝓝 (0 : ℝ) :=
    isOpen_Iio.mem_nhds (by norm_num)
  obtain ⟨r, hr, hrsub⟩ :=
    Metric.mem_nhds_iff.mp (Filter.inter_mem hcontrol hsmall)
  have hball : r / 2 ∈ Metric.ball (0 : ℝ) r := by
    rw [Metric.mem_ball, Real.dist_eq, sub_zero, abs_of_nonneg (by positivity)]
    linarith
  exact ⟨r / 2, by positivity, (hrsub hball).2, (hrsub hball).1⟩

private theorem norm_chargeAt_classOf_sub_le_of_mem_basisNhd
    (σ τ : StabilityCondition.WithClassMap C v) (E : C)
    (F : HNFiltration C σ.slicing.P E) {ε : ℝ}
    (hε : 0 < ε) (hε8 : ε < 1 / 8) (hτ : τ ∈ basisNhd C σ ε) :
    ‖τ.Z (classOf C v E) - σ.Z (classOf C v E)‖ ≤
      Real.sin (Real.pi * ε) * ∑ i : Fin F.n, ‖σ.charge (F.factor i)‖ := by
  have hsin : 0 ≤ Real.sin (Real.pi * ε) := by
    exact (Real.sin_pos_of_pos_of_lt_pi (mul_pos Real.pi_pos hε)
      (by nlinarith [Real.pi_pos])).le
  have hfactor := semistableChargeBound_of_stabilitySeminorm_le
    C σ τ.Z hsin hτ.1.le
  calc
    ‖τ.Z (classOf C v E) - σ.Z (classOf C v E)‖ =
        ‖(τ.Z - σ.Z) (classOf C v E)‖ := by
          rw [AddMonoidHom.sub_apply]
    _ = ‖∑ i : Fin F.n, (τ.Z - σ.Z) (classOf C v (F.factor i))‖ := by
      rw [classOf_postnikovTower_eq_sum C v F.toPostnikovTower, map_sum]
    _ ≤ ∑ i : Fin F.n, ‖(τ.Z - σ.Z) (classOf C v (F.factor i))‖ :=
      norm_sum_le _ _
    _ ≤ ∑ i : Fin F.n,
        Real.sin (Real.pi * ε) * ‖σ.charge (F.factor i)‖ := by
      apply Finset.sum_le_sum
      intro i _
      by_cases hi : IsZero (F.factor i)
      · rw [classOf_isZero (C := C) (v := v) hi, map_zero, norm_zero]
        exact mul_nonneg hsin (norm_nonneg _)
      · exact hfactor (F.φ i) (F.factor i) (F.semistable i) hi
    _ = Real.sin (Real.pi * ε) * ∑ i : Fin F.n, ‖σ.charge (F.factor i)‖ := by
      rw [Finset.mul_sum]

private theorem continuous_chargeAt_classOf (E : C) :
    Continuous (fun σ : StabilityCondition.WithClassMap C v =>
      σ.Z (classOf C v E)) := by
  rw [continuous_iff_continuousAt]
  intro σ
  obtain ⟨F⟩ := σ.slicing.hn_exists E
  change Filter.Tendsto _ (𝓝 σ) (𝓝 _)
  rw [Metric.tendsto_nhds]
  intro a ha
  obtain ⟨ε, hε, hε8, hbound⟩ := exists_basisNhd_radius_sin_mul_lt
    (M := ∑ i : Fin F.n, ‖σ.charge (F.factor i)‖) ha
  filter_upwards [
    (basisNhd_isOpen_generator C σ hε hε8).mem_nhds
      (self_mem_basisNhd C σ hε (by linarith))] with τ hτ
  rw [dist_eq_norm]
  exact lt_of_le_of_lt
    (norm_chargeAt_classOf_sub_le_of_mem_basisNhd σ τ E F hε hε8 hτ) hbound

/-- Evaluation of the central charge at a class in the range of the class map
is continuous on the stability space. -/
theorem continuous_chargeAt_of_mem_range {δ : Λ} (hδ : δ ∈ Set.range v) :
    Continuous (fun σ : StabilityCondition.WithClassMap C v => σ.Z δ) := by
  obtain ⟨x, rfl⟩ := hδ
  induction x using (triangulatedPresentation C).induction_on with
  | of E => simpa [classOf, K₀.of] using continuous_chargeAt_classOf (v := v) E
  | zero => simpa using
      (continuous_const : Continuous
        (fun _ : StabilityCondition.WithClassMap C v => (0 : ℂ)))
  | neg x hx =>
      simp only [map_neg]
      change Continuous (-fun σ : StabilityCondition.WithClassMap C v => σ.Z (v x))
      exact hx.neg
  | add x y hx hy =>
      simp only [map_add]
      change Continuous ((fun σ : StabilityCondition.WithClassMap C v => σ.Z (v x)) +
        fun σ => σ.Z (v y))
      exact hx.add hy

/-- Surjectivity makes every lattice class visible to the owner stability
seminorm, so the range-level continuity theorem applies to every `δ : Λ`. -/
theorem continuous_chargeAt (hv : Function.Surjective v) (δ : Λ) :
    Continuous (fun σ : StabilityCondition.WithClassMap C v => σ.Z δ) :=
  continuous_chargeAt_of_mem_range (Set.mem_range.mpr (hv δ))

/-- For a surjective class map, the charge-vanishing wall of each lattice
class is closed. -/
theorem isClosed_stabWall (hv : Function.Surjective v) (δ : Λ) :
    IsClosed (stabWall (C := C) (v := v) δ) := by
  rw [show stabWall (C := C) (v := v) δ =
      (fun σ : StabilityCondition.WithClassMap C v => σ.Z δ) ⁻¹' {0} by
    ext σ
    simp [stabWall]]
  exact isClosed_singleton.preimage (continuous_chargeAt (C := C) hv δ)

/-- For a surjective class map, the regular locus associated to finitely many
lattice classes is open. -/
theorem isOpen_stabRegular (hv : Function.Surjective v) {Δ : Set Λ}
    (hΔ : Δ.Finite) : IsOpen (stabRegular (C := C) (v := v) Δ) := by
  rw [stabRegular_eq_compl_iUnion]
  exact (hΔ.isClosed_biUnion fun δ _ => isClosed_stabWall (C := C) hv δ).isOpen_compl

end

end CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.StabWall
