/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.Algebra.SaturatedQuotient
import Mathlib.Algebra.DirectSum.Basic

/-!
# The algebraic core of relative numerical Grothendieck groups

Definition 8.7 of Li--Liu--Liu--Macrì--Perry--Stellari--Zhao starts with the
direct sum of numerical groups of geometric fibres and quotients by the
saturation of the relations supplied by connected relative-perfect families.
This file isolates that common algebraic core.

The geometric layer still has to construct the fibre groups (including their
algebraic-closure overlattices) and the specialization classes `ηᵛ(F_t)`.
Keeping those inputs outside this module prevents the numerical hierarchy from
acquiring a second Grothendieck-group presentation.
-/

noncomputable section

open scoped DirectSum

namespace AlgebraicGeometry.Numerical.Relative

universe u v w

variable {I : Type u} (K : I → Type v) [∀ i, AddCommGroup (K i)]

/-- The direct sum of the numerical groups attached to the fibres. -/
abbrev FiberSum := ⨁ i, K i

/-- The canonical inclusion of one fibre group into the direct sum.  The
classical choice of decidable equality on the index type is confined here. -/
def fiberInclusion (i : I) : K i →+ FiberSum K := by
  classical
  exact DirectSum.of K i

/-- The homomorphism from the fibre sum induced by a family of homomorphisms. -/
def fiberwiseHom {B : Type*} [AddCommGroup B] (f : ∀ i, K i →+ B) :
    FiberSum K →+ B := by
  classical
  exact DirectSum.toAddMonoid f

@[simp]
theorem fiberwiseHom_fiberInclusion {B : Type*} [AddCommGroup B]
    (f : ∀ i, K i →+ B) (i : I) (x : K i) :
    fiberwiseHom K f (fiberInclusion K i x) = f i x := by
  classical
  exact DirectSum.toAddMonoid_of f i x

/-- The subgroup generated by the connected-family relations. -/
def relationSubgroup (relations : Set (FiberSum K)) :
    AddSubgroup (FiberSum K) :=
  AddSubgroup.closure relations

/-- The saturated quotient determined by a collection of connected-family
relations. -/
abbrev Group (relations : Set (FiberSum K)) :=
  (relationSubgroup K relations).SaturatedQuotient

/-- The class of an element of one fibre group in the relative quotient. -/
def of (relations : Set (FiberSum K)) (i : I) : K i →+ Group K relations :=
  (relationSubgroup K relations).saturatedQuotientMk.comp (fiberInclusion K i)

@[simp]
theorem of_apply (relations : Set (FiberSum K)) (i : I) (x : K i) :
    of K relations i x =
      (relationSubgroup K relations).saturatedQuotientMk (fiberInclusion K i x) :=
  rfl

/-- Every specified connected-family relation vanishes in the quotient. -/
@[simp]
theorem relation_eq_zero (relations : Set (FiberSum K))
    {r : FiberSum K} (hr : r ∈ relations) :
    (relationSubgroup K relations).saturatedQuotientMk r = 0 := by
  rw [(relationSubgroup K relations).saturatedQuotientMk_eq_zero_iff]
  exact (relationSubgroup K relations).le_saturation
    (AddSubgroup.subset_closure hr)

/-- Two fibre classes agree when their difference is one of the specified
connected-family relations. -/
theorem of_eq_of (relations : Set (FiberSum K)) {i j : I} {x : K i} {y : K j}
    (h : fiberInclusion K i x - fiberInclusion K j y ∈ relations) :
    of K relations i x = of K relations j y := by
  rw [← sub_eq_zero, of_apply, of_apply, ← map_sub]
  exact relation_eq_zero K relations h

/-- A family of maps to a torsion-free group descends when it kills every
connected-family relation. -/
def lift {B : Type*} [AddCommGroup B] [IsAddTorsionFree B]
    (relations : Set (FiberSum K)) (f : ∀ i, K i →+ B)
    (hrelations : ∀ r ∈ relations, fiberwiseHom K f r = 0) :
    Group K relations →+ B :=
  (relationSubgroup K relations).saturatedQuotientLift
    (fiberwiseHom K f) <| by
      rw [relationSubgroup, AddSubgroup.closure_le]
      intro r hr
      exact hrelations r hr

@[simp]
theorem lift_of {B : Type*} [AddCommGroup B] [IsAddTorsionFree B]
    (relations : Set (FiberSum K)) (f : ∀ i, K i →+ B)
    (hrelations : ∀ r ∈ relations, fiberwiseHom K f r = 0)
    (i : I) (x : K i) :
    lift K relations f hrelations (of K relations i x) = f i x := by
  simp [lift, of]

/-- A homomorphism of fibre sums which carries the generated relation subgroup
into another induces a homomorphism of relative quotients. -/
def map {J : Type*} (L : J → Type*) [∀ j, AddCommGroup (L j)]
    (sourceRelations : Set (FiberSum K))
    (targetRelations : Set (FiberSum L)) (f : FiberSum K →+ FiberSum L)
    (hf : relationSubgroup K sourceRelations ≤
      (relationSubgroup L targetRelations).comap f) :
    Group K sourceRelations →+ Group L targetRelations :=
  (relationSubgroup K sourceRelations).saturatedQuotientMap
    (relationSubgroup L targetRelations) f hf

@[simp]
theorem map_mk {J : Type*} (L : J → Type*) [∀ j, AddCommGroup (L j)]
    (sourceRelations : Set (FiberSum K))
    (targetRelations : Set (FiberSum L)) (f : FiberSum K →+ FiberSum L)
    (hf : relationSubgroup K sourceRelations ≤
      (relationSubgroup L targetRelations).comap f) (x : FiberSum K) :
    map K L sourceRelations targetRelations f hf
        ((relationSubgroup K sourceRelations).saturatedQuotientMk x) =
      (relationSubgroup L targetRelations).saturatedQuotientMk (f x) :=
  rfl

/-- It is enough to check preservation on the specified generating
relations. -/
def mapOfRelations {J : Type*} (L : J → Type*) [∀ j, AddCommGroup (L j)]
    (sourceRelations : Set (FiberSum K))
    (targetRelations : Set (FiberSum L)) (f : FiberSum K →+ FiberSum L)
    (hf : ∀ r ∈ sourceRelations, f r ∈ relationSubgroup L targetRelations) :
    Group K sourceRelations →+ Group L targetRelations :=
  map K L sourceRelations targetRelations f <| by
    rw [relationSubgroup, AddSubgroup.closure_le]
    exact hf

@[simp]
theorem map_id (relations : Set (FiberSum K)) :
    map K K relations relations (AddMonoidHom.id _) (by simp) =
      AddMonoidHom.id (Group K relations) :=
  AddSubgroup.saturatedQuotientMap_id _

/-- Induced relative-quotient maps preserve composition. -/
theorem map_comp {J M : Type*} (L : J → Type*) (N : M → Type*)
    [∀ j, AddCommGroup (L j)] [∀ m, AddCommGroup (N m)]
    (sourceRelations : Set (FiberSum K))
    (middleRelations : Set (FiberSum L))
    (targetRelations : Set (FiberSum N))
    (f : FiberSum K →+ FiberSum L) (g : FiberSum L →+ FiberSum N)
    (hf : relationSubgroup K sourceRelations ≤
      (relationSubgroup L middleRelations).comap f)
    (hg : relationSubgroup L middleRelations ≤
      (relationSubgroup N targetRelations).comap g) :
    (map L N middleRelations targetRelations g hg).comp
        (map K L sourceRelations middleRelations f hf) =
      map K N sourceRelations targetRelations (g.comp f) (by
        intro x hx
        exact hg (hf hx)) :=
  AddSubgroup.saturatedQuotientMap_comp _ _ _ f g hf hg

/-- Maps out of the relative quotient are determined by their values on every
fibre group. -/
@[ext]
theorem hom_ext {B : Type*} [AddCommGroup B]
    (relations : Set (FiberSum K)) {f g : Group K relations →+ B}
    (h : ∀ i, f.comp (of K relations i) = g.comp (of K relations i)) :
    f = g := by
  classical
  apply AddSubgroup.saturatedQuotientHom_ext
  apply DirectSum.addHom_ext'
  intro i
  simpa [of, fiberInclusion, AddMonoidHom.comp_assoc] using h i

/-! ## Relations generated by admissible families -/

/-- The statement-layer data from which connected-family relations are made.

`Family` is intended to contain only the admissible families for the geometric
application.  In Definition 8.7 these are connected schemes over the base
together with a relative-perfect complex.  Consequently, connectivity and
relative perfection do not appear as inert fields here: the future geometric
adapter proves them when it constructs an inhabitant of `Family`.

The value `classValue F t` is the class of the fibre at `t`, already transported to
the numerical group indexed by `index F t`.  Thus the same root also applies
to other comparison problems whose families and point types are unrelated to
schemes. -/
structure FamilyRelationSystem where
  /-- Admissible families whose point classes must agree. -/
  Family : Type w
  /-- The points at which an admissible family can be restricted. -/
  Point : Family → Type w
  /-- The base fibre containing a point of a family. -/
  index : ∀ F, Point F → I
  /-- The transported numerical class of the family at a point. -/
  classValue : ∀ F t, K (index F t)

namespace FamilyRelationSystem

variable (D : FamilyRelationSystem K)

/-- The difference of the two transported classes of one admissible family. -/
def relation (F : D.Family) (t₁ t₂ : D.Point F) : FiberSum K :=
  fiberInclusion K (D.index F t₁) (D.classValue F t₁) -
    fiberInclusion K (D.index F t₂) (D.classValue F t₂)

/-- All relations generated by pairs of points in one admissible family. -/
def relations : Set (FiberSum K) :=
  {r | ∃ (F : D.Family) (t₁ t₂ : D.Point F),
    r = relation K D F t₁ t₂}

@[simp]
theorem relation_mem (F : D.Family) (t₁ t₂ : D.Point F) :
    relation K D F t₁ t₂ ∈ relations K D :=
  ⟨F, t₁, t₂, rfl⟩

/-- The relative saturated quotient generated by the admissible families. -/
abbrev RelativeGroup := Group K (relations K D)

/-- The class of one point of an admissible family in the relative group. -/
def pointClass (F : D.Family) (t : D.Point F) : RelativeGroup K D :=
  of K (relations K D) (D.index F t) (D.classValue F t)

/-- The class of an admissible family is independent of the chosen point. -/
theorem pointClass_eq (F : D.Family) (t₁ t₂ : D.Point F) :
    pointClass K D F t₁ = pointClass K D F t₂ :=
  of_eq_of K (relations K D) (relation_mem K D F t₁ t₂)

/-- Fibrewise maps that are constant on every admissible family descend to
the family-generated relative group. -/
def lift {B : Type*} [AddCommGroup B] [IsAddTorsionFree B]
    (f : ∀ i, K i →+ B)
    (hfamily : ∀ (F : D.Family) (t₁ t₂ : D.Point F),
      f (D.index F t₁) (D.classValue F t₁) =
        f (D.index F t₂) (D.classValue F t₂)) :
    RelativeGroup K D →+ B :=
  Relative.lift K (relations K D) f <| by
    rintro r ⟨F, t₁, t₂, rfl⟩
    simpa [relation, sub_eq_zero] using hfamily F t₁ t₂

@[simp]
theorem lift_pointClass {B : Type*} [AddCommGroup B] [IsAddTorsionFree B]
    (f : ∀ i, K i →+ B)
    (hfamily : ∀ (F : D.Family) (t₁ t₂ : D.Point F),
      f (D.index F t₁) (D.classValue F t₁) =
        f (D.index F t₂) (D.classValue F t₂))
    (F : D.Family) (t : D.Point F) :
    FamilyRelationSystem.lift K D f hfamily (pointClass K D F t) =
      f (D.index F t) (D.classValue F t) := by
  apply Relative.lift_of

end FamilyRelationSystem

/-- For a one-point base, the relative quotient with no relations maps back to
the unique fibre group. -/
def singletonFold (A : Type*) [AddCommGroup A] [IsAddTorsionFree A] :
    Group (fun _ : PUnit ↦ A) ∅ →+ A :=
  lift (fun _ : PUnit ↦ A) ∅ (fun _ ↦ AddMonoidHom.id A) <| by
    intro r hr
    simp at hr

@[simp]
theorem singletonFold_of (A : Type*) [AddCommGroup A] [IsAddTorsionFree A]
    (x : A) :
    singletonFold A (of (fun _ : PUnit ↦ A) ∅ PUnit.unit x) = x := by
  apply lift_of

/-- The relative construction over one point, with no connected-family
relations, agrees with its unique torsion-free fibre group. -/
def singletonEquiv (A : Type*) [AddCommGroup A] [IsAddTorsionFree A] :
    Group (fun _ : PUnit ↦ A) ∅ ≃+ A where
  toFun := singletonFold A
  invFun := of (fun _ : PUnit ↦ A) ∅ PUnit.unit
  left_inv := by
    intro q
    have hhom :
        (of (fun _ : PUnit ↦ A) ∅ PUnit.unit).comp (singletonFold A) =
          AddMonoidHom.id _ := by
      apply hom_ext (fun _ : PUnit ↦ A) ∅
      intro i
      obtain rfl : i = PUnit.unit := Subsingleton.elim _ _
      ext x
      simp only [AddMonoidHom.comp_apply, singletonFold_of,
        AddMonoidHom.id_apply]
    exact DFunLike.congr_fun hhom q
  right_inv := by
    intro x
    exact singletonFold_of A x
  map_add' := map_add (singletonFold A)

@[simp]
theorem singletonEquiv_of (A : Type*) [AddCommGroup A] [IsAddTorsionFree A]
    (x : A) :
    singletonEquiv A (of (fun _ : PUnit ↦ A) ∅ PUnit.unit x) = x := by
  exact singletonFold_of A x

end AlgebraicGeometry.Numerical.Relative
