/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.FourierMukai.Adjunction
import DerivedAlgGeo.CategoryTheory.Triangulated.SemiorthogonalDecomposition.Mutation

/-!
# Fourier--Mukai extension across exceptional blocks

This file gives precise interfaces for the extension results used in
arXiv:1912.04332v2, Propositions 2.4--2.5 and Theorem 5.1, and
arXiv:2104.13610v2, Proposition 3.2 and Theorem 3.3.

There are three layers.

* `KernelEquivalence` is a Fourier--Mukai transform known to be an
  equivalence.  Its constructor from a kernel-presented right adjoint with
  invertible unit and counit is a theorem, not supplied data.
* `OneStepExtensionData` is the exact conclusion of the one-object extension
  proposition: a new kernel agrees on the old component, maps the new
  exceptional object, kills the remaining orthogonal, and is an equivalence
  on the enlarged triangulated span.
* `ExceptionalBlockExtensionData` is the finite iteration's conclusion: an
  ambient kernel equivalence extending the residual equivalence and matching
  every object of every exceptional block, with one common shift per block.

The kernel constructed in the papers is a cone of a morphism of kernels.
Functorial construction of that morphism and cone belongs to the dg
enhancement chain #855, #853, #854 and is not available at the current pin.
Accordingly the two extension structures are explicitly *result data*.  They
state the paper theorems without pretending to construct their geometric/dg
input.  Once their adjunction fields are supplied, however, the ambient
equivalence itself is derived through `Adjunction.toEquivalence`.
-/

open CategoryTheory

universe w v v' v'' v''' u u' u'' u''' t t'

namespace CategoryTheory.Triangulated.FourierMukai

open CategoryTheory.Limits CategoryTheory.ObjectProperty

section KernelEquivalence

variable {X : Type u} {Y : Type u'} {W : Type u''} {W' : Type u'''}
  [Category.{v} X] [Category.{v'} Y] [Category.{v''} W] [Category.{v'''} W']

/-- An equivalence between two categories presented by a Fourier--Mukai
kernel.  Unlike `KernelAutoequivalence`, the source and target may differ. -/
structure KernelEquivalence (corr : Correspondence X Y W) where
  /-- The kernel presenting the forward equivalence. -/
  kernel : W
  /-- The underlying equivalence. -/
  equiv : X ≌ Y
  /-- Identification of the equivalence functor with the kernel transform. -/
  iso : equiv.functor ≅ corr.transform kernel

namespace KernelEquivalence

/-- A kernel-presented right adjunction with invertible unit and counit gives
a kernel equivalence.  The equivalence is `Adjunction.toEquivalence`, and the
forward functor is the original transform definitionally. -/
@[reducible] noncomputable def ofRightAdjointKernel
    (corr : Correspondence X Y W) (corr' : Correspondence Y X W') (K : W)
    (R : RightAdjointKernelData corr corr' K)
    [∀ A, IsIso (R.adj.unit.app A)] [∀ B, IsIso (R.adj.counit.app B)] :
    KernelEquivalence corr where
  kernel := K
  equiv :=
    { functor := corr.transform K
      inverse := corr'.transform R.adjKernel
      unitIso := R.adj.toEquivalence.unitIso
      counitIso := R.adj.toEquivalence.counitIso
      functor_unitIso_comp := R.adj.toEquivalence.functor_unitIso_comp }
  iso := Iso.refl _

@[simp]
theorem ofRightAdjointKernel_kernel
    (corr : Correspondence X Y W) (corr' : Correspondence Y X W') (K : W)
    (R : RightAdjointKernelData corr corr' K)
    [∀ A, IsIso (R.adj.unit.app A)] [∀ B, IsIso (R.adj.counit.app B)] :
    (ofRightAdjointKernel corr corr' K R).kernel = K := rfl

end KernelEquivalence

end KernelEquivalence

section ExtensionStages

variable {X : Type u} [Category.{v} X] [Limits.HasZeroObject X]
  [HasShift X ℤ] [Preadditive X]
  [∀ n : ℤ, (shiftFunctor X n).Additive] [Pretriangulated X]

/-- The full triangulated property generated by an old component `P` and one
new object `E`. -/
abbrev adjoinObject (P : ObjectProperty X) (E : X) : ObjectProperty X :=
  (P ⊔ ObjectProperty.singleton E).triangEnvelope

end ExtensionStages

section Results

variable {k : Type w} [Field k]
variable {X : Type u} {Y : Type u'} {W : Type u''} {W' : Type u'''}
  [Category.{v} X] [Preadditive X] [Linear k X]
  [HasZeroObject X] [HasShift X ℤ]
  [∀ n : ℤ, (shiftFunctor X n).Additive] [Pretriangulated X]
  [Category.{v'} Y] [Preadditive Y] [Linear k Y]
  [HasZeroObject Y] [HasShift Y ℤ]
  [∀ n : ℤ, (shiftFunctor Y n).Additive] [Pretriangulated Y]
  [Category.{v''} W] [Category.{v'''} W']

/-- A residual equivalence presented by the restriction of an ambient
Fourier--Mukai transform.

This is the papers' phrase "an equivalence of Fourier--Mukai type" written
against the existing correspondence interface. -/
structure ResidualKernelEquivalence
    {I : Type t} {J : Type t'}
    (B_X : Triangulated.OrthogonalExceptionalBlocks k X I)
    (B_Y : Triangulated.OrthogonalExceptionalBlocks k Y J)
    (corr : Correspondence X Y W) where
  /-- The equivalence of residual categories. -/
  equiv : B_X.ResidualCategory ≌ B_Y.ResidualCategory
  /-- An ambient kernel inducing that equivalence on the residual category. -/
  kernel : W
  /-- The restriction of the transform is the given residual equivalence. -/
  restrictionIso :
    B_X.residual.ι ⋙ corr.transform kernel ≅
      equiv.functor ⋙ B_Y.residual.ι

/-- The conclusion of one application of the Fourier--Mukai extension
proposition across a single exceptional object.

The fields are intentionally conclusions rather than assumptions disguised as
a theorem: constructing `newKernel` requires the functorial cone of kernels
which the dg lane has not yet delivered. -/
structure OneStepExtensionData
    (P : ObjectProperty X) (Q : ObjectProperty Y) (E : X) (F : Y)
    (base : P.FullSubcategory ≌ Q.FullSubcategory)
    (corr : Correspondence X Y W) (oldKernel : W) where
  /-- The extended Fourier--Mukai kernel. -/
  newKernel : W
  /-- The kernel morphism from the extension to the preceding kernel, as in
  Paper I, Proposition 2.4. -/
  kernelMap : newKernel ⟶ oldKernel
  /-- The induced transform comparison is an isomorphism on the old
  component.  This is the categorical content of Proposition 2.4(1). -/
  agreesWithOld :
    P.ι ⋙ corr.transform newKernel ≅ P.ι ⋙ corr.transform oldKernel
  /-- The extended transform commutes with shifts. -/
  transformCommShift : (corr.transform newKernel).CommShift ℤ
  /-- The extended transform is exact. -/
  transformTriangulated : (corr.transform newKernel).IsTriangulated
  /-- The extended transform maps the enlarged source span into the enlarged
  target span. -/
  mapsAdjoin : ∀ A : (adjoinObject P E).FullSubcategory,
    adjoinObject Q F ((corr.transform newKernel).obj A.obj)
  /-- The induced equivalence of enlarged components. -/
  enlargedEquiv :
    (adjoinObject P E).FullSubcategory ≌
      (adjoinObject Q F).FullSubcategory
  /-- The enlarged equivalence is induced by the extended transform. -/
  enlargedIso :
    (adjoinObject P E).ι ⋙ corr.transform newKernel ≅
      enlargedEquiv.functor ⋙ (adjoinObject Q F).ι
  /-- On the old component the new transform agrees with the old
  equivalence. -/
  agreesOnBase :
    P.ι ⋙ corr.transform newKernel ≅ base.functor ⋙ Q.ι
  /-- The newly adjoined source object is sent to the newly adjoined target
  object. -/
  objectIso : (corr.transform newKernel).obj E ≅ F
  /-- The remaining left orthogonal is annihilated, allowing the next
  induction step. -/
  annihilates : ∀ A : X, (adjoinObject P E).leftOrthogonal A →
    IsZero ((corr.transform newKernel).obj A)

namespace OneStepExtensionData

variable {P : ObjectProperty X} {Q : ObjectProperty Y} {E : X} {F : Y}
  {base : P.FullSubcategory ≌ Q.FullSubcategory}
  {corr : Correspondence X Y W} {oldKernel : W}
  (A : OneStepExtensionData P Q E F base corr oldKernel)

/-- The actual restricted functor induced by the new kernel. -/
noncomputable def restrictedFunctor :
    Functor (adjoinObject P E).FullSubcategory
      (adjoinObject Q F).FullSubcategory :=
  (adjoinObject Q F).lift
    ((adjoinObject P E).ι ⋙ corr.transform A.newKernel) A.mapsAdjoin

/-- The supplied enlarged equivalence has the restricted transform as its
underlying functor, up to natural isomorphism. -/
noncomputable def restrictedFunctorIso :
    restrictedFunctor A ≅ A.enlargedEquiv.functor :=
  (adjoinObject Q F).fullyFaithfulι.whiskeringRight _ |>.preimageIso
    (((adjoinObject Q F).liftCompιIso
        ((adjoinObject P E).ι ⋙ corr.transform A.newKernel)
        A.mapsAdjoin) ≪≫ A.enlargedIso)

end OneStepExtensionData

/-- The finite blockwise extension conclusion of Paper I, Theorem 5.1 and
Paper II, Theorem 3.3.

`blockEquiv` and `length_eq` record equality of decomposition type.
`objectIso` uses the same shift for every member of a block, exactly as in
Paper II.  The ambient equivalence is not stored redundantly: a
kernel-presented right adjoint and pointwise invertibility of its unit and
counit are stored, and `toKernelEquivalence` derives it. -/
structure ExceptionalBlockExtensionData
    {I : Type t} {J : Type t'}
    (B_X : Triangulated.OrthogonalExceptionalBlocks k X I)
    (B_Y : Triangulated.OrthogonalExceptionalBlocks k Y J)
    (corr : Correspondence X Y W) (corr' : Correspondence Y X W')
    (R : ResidualKernelEquivalence B_X B_Y corr) where
  /-- The final extended kernel. -/
  kernel : W
  /-- A kernel-presented right adjoint of the final transform. -/
  rightAdjoint : RightAdjointKernelData corr corr' kernel
  /-- Full faithfulness half of the final equivalence. -/
  unitIsIso : ∀ A, IsIso (rightAdjoint.adj.unit.app A)
  /-- Essential-surjectivity half of the final equivalence. -/
  counitIsIso : ∀ B, IsIso (rightAdjoint.adj.counit.app B)
  /-- The final transform commutes with shifts. -/
  transformCommShift : (corr.transform kernel).CommShift ℤ
  /-- The final transform is exact. -/
  transformTriangulated : (corr.transform kernel).IsTriangulated
  /-- The final transform still restricts to the original residual
  equivalence. -/
  residualIso :
    B_X.residual.ι ⋙ corr.transform kernel ≅
      R.equiv.functor ⋙ B_Y.residual.ι
  /-- Reordering of the exceptional blocks. -/
  blockEquiv : I ≃ J
  /-- Corresponding blocks have equal length. -/
  length_eq : ∀ i, B_X.length i = B_Y.length (blockEquiv i)
  /-- The common shift attached to each source block. -/
  shift : I → ℤ
  /-- Every member of a source block maps to the corresponding member of the
  target block with the common block shift. -/
  objectIso : ∀ (i : I) (j : Fin (B_X.length i)),
    (corr.transform kernel).obj ((B_X.collection i).obj j) ≅
      ((B_Y.collection (blockEquiv i)).obj
        (Fin.cast (length_eq i) j))⟦shift i⟧

namespace ExceptionalBlockExtensionData

variable {I : Type t} {J : Type t'}
  {B_X : Triangulated.OrthogonalExceptionalBlocks k X I}
  {B_Y : Triangulated.OrthogonalExceptionalBlocks k Y J}
  {corr : Correspondence X Y W} {corr' : Correspondence Y X W'}
  {R : ResidualKernelEquivalence B_X B_Y corr}
  (A : ExceptionalBlockExtensionData B_X B_Y corr corr' R)

/-- The ambient Fourier--Mukai equivalence, derived from the final adjunction
and its invertible unit and counit. -/
noncomputable def toKernelEquivalence : KernelEquivalence corr := by
  letI (X : X) : IsIso (A.rightAdjoint.adj.unit.app X) := A.unitIsIso X
  letI (Y : Y) : IsIso (A.rightAdjoint.adj.counit.app Y) := A.counitIsIso Y
  exact KernelEquivalence.ofRightAdjointKernel corr corr' A.kernel A.rightAdjoint

@[simp]
theorem toKernelEquivalence_kernel : A.toKernelEquivalence.kernel = A.kernel := rfl

/-- The final kernel transform is an equivalence of the ambient categories. -/
theorem transform_isEquivalence : (corr.transform A.kernel).IsEquivalence := by
  letI (X : X) : IsIso (A.rightAdjoint.adj.unit.app X) := A.unitIsIso X
  letI (Y : Y) : IsIso (A.rightAdjoint.adj.counit.app Y) := A.counitIsIso Y
  exact (A.toKernelEquivalence.equiv.isEquivalence_functor)

/-- The induced ambient equivalence, exposed directly for downstream Torelli
consumers. -/
noncomputable def ambientEquivalence : X ≌ Y :=
  A.toKernelEquivalence.equiv

@[simp]
theorem ambientEquivalence_functor :
    A.ambientEquivalence.functor = corr.transform A.kernel := rfl

end ExceptionalBlockExtensionData

end Results

end CategoryTheory.Triangulated.FourierMukai
