/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.Divisors.AssociatedSheaf.RationalSections
import DerivedAlgGeo.CategoryTheory.Sites.Sheaves.CoversTop
import DerivedAlgGeo.CategoryTheory.Sites.Sheaves.Modules.Invertible

/-!
# The associated sheaf of a Cartier divisor

This file owns the construction of `O_X(D)`.  It defines local equations of a
Cartier divisor, the fractional subpresheaf of the rational presheaf generated
by their inverses, and the associated sheaf as its module sheafification.

Local equations trivialize the result, so the associated sheaf is invertible;
`equationTransitionIso` gives the canonical change of trivialization and
`equationTransitionIso_trans` records its cocycle law.  Pointwise multiplication
of rational functions gives the canonical additive comparison before
sheafification, and it is proved to be a local equivalence, which yields the
tensor comparison `associatedTensorAddIso`.

The construction is intrinsic: the fractional presheaf is generated by every
local equation.  The scaffolding lemmas that establish the local surjectivity
and injectivity conditions are private to this module; only the resulting
sheaves, isomorphisms, and their defining data are exported.
-/

set_option backward.isDefEq.respectTransparency false

open CategoryTheory Opposite TopologicalSpace MonoidalCategory

universe u

namespace AlgebraicGeometry.Scheme

variable (X : Scheme.{u}) [IsIntegral X]

namespace CartierDivisor

variable {X : Scheme.{u}} [IsIntegral X]

/-- A rational function is an equation for `D` throughout `U`. -/
def IsEquationOn (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) : Prop :=
  ∀ x, x ∈ U → D.1 x = localCartierClass X x f

lemma IsEquationOn.mono {D : CartierDivisor X} {U V : X.Opens}
    {f : Additive X.functionFieldˣ} (hf : IsEquationOn D U f) (h : V ≤ U) :
    IsEquationOn D V f :=
  fun x hx ↦ hf x (h hx)

/-- The rational section `1/f`. -/
private noncomputable def inverseSection (U : X.Opens) (f : Additive X.functionFieldˣ) :
    RationalSections X U :=
  fun _ ↦ ((f.toMul : X.functionField)⁻¹)

/-- Local inverse equations which generate the fractional module attached to `D`. -/
private def inverseEquationSections (D : CartierDivisor X) (U : X.Opens) :
    Set (RationalSections X U) :=
  { s | ∃ f, IsEquationOn D U f ∧ s = inverseSection U f }

/-- The fractional sections generated by inverse local equations for `D`. -/
private noncomputable def fractionalSections (D : CartierDivisor X) (U : X.Opens) :
    Submodule Γ(X, U) (RationalSections X U) :=
  Submodule.span Γ(X, U) (inverseEquationSections D U)

private lemma rationalSectionsRes_inverseSection {U V : X.Opens} (h : V ≤ U)
    (f : Additive X.functionFieldˣ) :
    rationalSectionsRes X h (inverseSection U f) = inverseSection V f := by
  rfl

private lemma rationalSectionsRes_mem_fractionalSections (D : CartierDivisor X)
    {U V : X.Opens} (h : V ≤ U) {s : RationalSections X U}
    (hs : s ∈ fractionalSections D U) :
    rationalSectionsRes X h s ∈ fractionalSections D V := by
  refine Submodule.span_induction (p := fun s _ ↦
    rationalSectionsRes X h s ∈ fractionalSections D V) ?_ ?_ ?_ ?_ hs
  · intro s hs
    obtain ⟨f, hf, rfl⟩ := hs
    rw [rationalSectionsRes_inverseSection]
    exact Submodule.subset_span ⟨f, hf.mono h, rfl⟩
  · exact map_zero (rationalSectionsRes X h) ▸ Submodule.zero_mem _
  · intro s t _ _ hs ht
    rw [map_add]
    exact Submodule.add_mem _ hs ht
  · intro r s _ hs
    rw [rationalSectionsRes_smul]
    exact Submodule.smul_mem _ _ hs

/-- The fractional module presheaf underlying `O_X(D)`. -/
private noncomputable def fractionalPresheafSubmodule (D : CartierDivisor X) :
    (rationalPresheaf X).Submodule where
  obj U := by
    change Submodule Γ(X, U.unop) (RationalSections X U.unop)
    exact fractionalSections D U.unop
  map {U V} f := by
    intro s hs
    change rationalSectionsRes X (leOfHom f.unop) s ∈ fractionalSections D V.unop
    exact rationalSectionsRes_mem_fractionalSections D (leOfHom f.unop) hs

/-- The fractional module presheaf attached to a Cartier divisor. -/
noncomputable def fractionalPresheaf (D : CartierDivisor X) : X.PresheafOfModules :=
  (fractionalPresheafSubmodule D).toPresheafOfModules

private noncomputable abbrev overPresheaf (P : X.PresheafOfModules) (U : X.Opens) :=
  (PresheafOfModules.pushforward
    (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).obj P

/-- Multiplication by the inverse of a local equation, as a map into the fractional presheaf. -/
private noncomputable def equationHom (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f) :
    PresheafOfModules.unit (X.ringCatSheaf.over U).obj ⟶
      overPresheaf (fractionalPresheaf D) U :=
  (PresheafOfModules.unitHomEquiv _).symm {
    val := fun V ↦ ⟨inverseSection V.unop.left f,
      Submodule.subset_span ⟨f, hf.mono (leOfHom V.unop.hom), rfl⟩⟩
    property := fun g ↦ by
      apply Subtype.ext
      exact rationalSectionsRes_inverseSection (leOfHom g.unop.left) f }

private lemma equationHom_app_one (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (V : (Over U)ᵒᵖ) :
    (equationHom D U f hf).app V
        (show (PresheafOfModules.unit
          (X.ringCatSheaf.over U).obj).obj V from
            (1 : (X.ringCatSheaf.over U).obj.obj V)) =
      (show fractionalSections D V.unop.left from
        ⟨inverseSection V.unop.left f,
          Submodule.subset_span
            ⟨f, hf.mono (leOfHom V.unop.hom), rfl⟩⟩) := by
  let s : (overPresheaf (fractionalPresheaf D) U).sections :=
    { val := fun W ↦ ⟨inverseSection W.unop.left f,
        Submodule.subset_span
          ⟨f, hf.mono (leOfHom W.unop.hom), rfl⟩⟩
      property := fun g ↦ by
        apply Subtype.ext
        exact rationalSectionsRes_inverseSection (leOfHom g.unop.left) f }
  have hs := (overPresheaf
    (fractionalPresheaf D) U).unitHomEquiv.apply_symm_apply s
  have hsV := congrArg
    (fun q : (overPresheaf (fractionalPresheaf D) U).sections ↦ q.val V) hs
  change (equationHom D U f hf).app V _ = _
  exact hsV

private lemma equationHom_app_injective (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f) (V : (Over U)ᵒᵖ) :
    Function.Injective ((equationHom D U f hf).app V) := by
  let e : RationalSections X V.unop.left := inverseSection V.unop.left f
  have he : e ∈ fractionalSections D V.unop.left :=
    Submodule.subset_span ⟨f, hf.mono (leOfHom V.unop.hom), rfl⟩
  change Function.Injective (fun a : Γ(X, V.unop.left) ↦
    (⟨a • e, Submodule.smul_mem _ a he⟩ : fractionalSections D V.unop.left))
  intro a b hab
  by_cases hV : Nonempty V.unop.left
  · letI : Nonempty V.unop.left := hV
    have hab' := congrArg
      (fun s : fractionalSections D V.unop.left ↦ (s.1 : RationalSections X V.unop.left) ⟨hV⟩)
      hab
    change X.germToFunctionField V.unop.left a * ((f.toMul : X.functionField)⁻¹) =
      X.germToFunctionField V.unop.left b * ((f.toMul : X.functionField)⁻¹) at hab'
    apply X.germToFunctionField_injective V.unop.left
    exact mul_right_cancel₀ (inv_ne_zero f.toMul.ne_zero) hab'
  · haveI : IsEmpty V.unop.left := not_nonempty_iff.mp hV
    have hbot : V.unop.left = ⊥ := by
      apply Opens.ext
      apply Set.not_nonempty_iff_eq_empty.mp
      rintro ⟨x, hx⟩
      exact hV ⟨⟨x, hx⟩⟩
    exact @Subsingleton.elim _
      (CommRingCat.subsingleton_of_isTerminal
        (X.sheaf.isTerminalOfEqEmpty hbot)) _ _

private lemma equationHom_isLocallyInjective (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f) :
    Presheaf.IsLocallyInjective ((_root_.Opens.grothendieckTopology X).over U)
      ((PresheafOfModules.toPresheaf _).map (equationHom D U f hf)) :=
  Presheaf.isLocallyInjective_of_injective _ _
    (fun V ↦ equationHom_app_injective D U f hf V)

private lemma exists_local_section_eq_equation_div (x : X)
    (f g : Additive X.functionFieldˣ)
    (hfg : localCartierClass X x f = localCartierClass X x g) :
    ∃ (A : X.Opens) (hxA : x ∈ A) (a : Γ(X, A)),
      letI : Nonempty A := ⟨⟨x, hxA⟩⟩
      X.germToFunctionField A a =
        (f.toMul : X.functionField) * (g.toMul : X.functionField)⁻¹ := by
  have hq : f - g ∈ localUnits X x :=
    (localCartierClass_eq_iff X x f g).mp hfg
  obtain ⟨u, hu⟩ := hq
  obtain ⟨A, hxA, a, ha⟩ := X.presheaf.exists_germ_eq (u : X.presheaf.stalk x)
  refine ⟨A, hxA, a, ?_⟩
  letI : Nonempty A := ⟨⟨x, hxA⟩⟩
  rw [← X.algebraMap_germ_eq_germToFunctionField hxA, ha]
  change ((localUnitHom X x u : X.functionFieldˣ) : X.functionField) = _
  rw [hu]
  simp [sub_eq_add_neg]

private lemma imageSieve_inverseSection_mem (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (V : Over U) (g : Additive X.functionFieldˣ)
    (hg : IsEquationOn D V.left g) :
    Presheaf.imageSieve
      ((PresheafOfModules.toPresheaf _).map (equationHom D U f hf))
      (show fractionalSections D V.left from
        ⟨inverseSection V.left g, Submodule.subset_span ⟨g, hg, rfl⟩⟩) ∈
      ((_root_.Opens.grothendieckTopology X).over U) V := by
  rw [GrothendieckTopology.mem_over_iff]
  intro x hxV
  obtain ⟨A, hxA, a, ha⟩ := exists_local_section_eq_equation_div x f g
    ((hf x (leOfHom V.hom hxV)).symm.trans (hg x hxV))
  let W : X.Opens := A ⊓ V.left
  have hxW : x ∈ W := ⟨hxA, hxV⟩
  let i : W ⟶ V.left := homOfLE inf_le_right
  let Y : Over U := Over.mk (i ≫ V.hom)
  let j : Y ⟶ V := Over.homMk i
  refine ⟨W, i, ?_, hxW⟩
  rw [Sieve.overEquiv_iff]
  change ∃ b : Γ(X, W), _
  let aW : Γ(X, W) := X.presheaf.map (homOfLE inf_le_left).op a
  refine ⟨aW, ?_⟩
  apply Subtype.ext
  funext hW
  letI : Nonempty A := ⟨⟨x, hxA⟩⟩
  letI : Nonempty W := hW.down
  change X.germToFunctionField W aW * (f.toMul : X.functionField)⁻¹ =
    (g.toMul : X.functionField)⁻¹
  rw [show X.germToFunctionField W aW =
      X.germToFunctionField A a by
    exact germToFunctionField_res X inf_le_left a hW]
  rw [ha]
  field_simp

set_option maxHeartbeats 800000 in
private lemma equationHom_isLocallySurjective (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f) :
    Presheaf.IsLocallySurjective ((_root_.Opens.grothendieckTopology X).over U)
      ((PresheafOfModules.toPresheaf _).map (equationHom D U f hf)) := by
  let K := (_root_.Opens.grothendieckTopology X).over U
  let φ := (PresheafOfModules.toPresheaf _).map (equationHom D U f hf)
  constructor
  intro V z
  change fractionalSections D V.left at z
  refine Submodule.span_induction (p := fun s hs ↦
    Presheaf.imageSieve φ (show fractionalSections D V.left from ⟨s, hs⟩) ∈ K V)
      ?_ ?_ ?_ ?_ z.property
  · intro s hs
    obtain ⟨g, hg, rfl⟩ := hs
    exact imageSieve_inverseSection_mem D U f hf V g hg
  · have hzero : Presheaf.imageSieve φ (φ.app (.op V) 0) ∈ K V := by
      rw [Presheaf.imageSieve_app]
      exact K.top_mem V
    have hz : (⟨0, Submodule.zero_mem _⟩ : fractionalSections D V.left) = 0 := rfl
    simpa only [hz, map_zero] using hzero
  · intro s t hs ht hsc htc
    apply K.superset_covering
      (S := Presheaf.imageSieve φ (show fractionalSections D V.left from ⟨s, hs⟩) ⊓
        Presheaf.imageSieve φ (show fractionalSections D V.left from ⟨t, ht⟩))
    · intro W j hj
      refine ⟨Presheaf.localPreimage φ (show fractionalSections D V.left from ⟨s, hs⟩) j hj.1 +
        Presheaf.localPreimage φ (show fractionalSections D V.left from ⟨t, ht⟩) j hj.2, ?_⟩
      rw [map_add, Presheaf.app_localPreimage, Presheaf.app_localPreimage]
      exact (map_add _ _ _).symm
    · exact K.intersection_covering hsc htc
  · intro r s hs hsc
    apply K.superset_covering
      (S := Presheaf.imageSieve φ (show fractionalSections D V.left from ⟨s, hs⟩))
    · intro W j hj
      let rW : Γ(X, W.left) := X.presheaf.map j.left.op r
      let t : Γ(X, W.left) := Presheaf.localPreimage φ
        (show fractionalSections D V.left from ⟨s, hs⟩) j hj
      refine ⟨rW * t, ?_⟩
      change (equationHom D U f hf).app (.op W) (rW • t) = _
      rw [map_smul]
      dsimp only [t]
      have ht := Presheaf.app_localPreimage φ
        (show fractionalSections D V.left from ⟨s, hs⟩) j hj
      change (equationHom D U f hf).app (.op W)
          (Presheaf.localPreimage φ
            (show fractionalSections D V.left from ⟨s, hs⟩) j hj) =
        (overPresheaf (fractionalPresheaf D) U).map j.op
          (show fractionalSections D V.left from ⟨s, hs⟩) at ht
      rw [ht]
      apply Subtype.ext
      exact (rationalSectionsRes_smul X (leOfHom j.left) r s).symm
    · exact hsc

private lemma equationHom_mem_W (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f) :
    ((_root_.Opens.grothendieckTopology X).over U).W
      ((PresheafOfModules.toPresheaf _).map (equationHom D U f hf)) := by
  letI := equationHom_isLocallyInjective D U f hf
  letI := equationHom_isLocallySurjective D U f hf
  exact ((_root_.Opens.grothendieckTopology X).over U).W_of_isLocallyBijective _

/-- The associated sheaf `O_X(D)`, obtained by sheafifying the fractional presheaf. -/
noncomputable def associatedSheaf (D : CartierDivisor X) : X.Modules :=
  (PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).obj
    (fractionalPresheaf D)

private lemma isIso_sheafification_map_equationHom (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f) :
    IsIso ((PresheafOfModules.sheafification
      (𝟙 (X.ringCatSheaf.over U).obj)).map (equationHom D U f hf)) := by
  apply Localization.inverts
    (PresheafOfModules.sheafification (𝟙 (X.ringCatSheaf.over U).obj))
    (((_root_.Opens.grothendieckTopology X).over U).W.inverseImage
      (PresheafOfModules.toPresheaf (X.ringCatSheaf.over U).obj))
  exact equationHom_mem_W D U f hf

/-- A local equation trivializes the associated sheaf on its domain. -/
noncomputable def equationIso (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f) :
    SheafOfModules.unit (X.ringCatSheaf.over U) ≅ (associatedSheaf D).over U := by
  let aU := PresheafOfModules.sheafification (𝟙 (X.ringCatSheaf.over U).obj)
  exact ((asIso (PresheafOfModules.sheafificationAdjunction
      (𝟙 (X.ringCatSheaf.over U).obj)).counit).app
        (SheafOfModules.unit (X.ringCatSheaf.over U))).symm ≪≫
    @asIso _ _ _ _ (aU.map (equationHom D U f hf))
      (isIso_sheafification_map_equationHom D U f hf) ≪≫
    @asIso _ _ _ _ (Modules.overSheafificationComparison (fractionalPresheaf D) U)
      (Modules.isIso_overSheafificationComparison _ _)

/-- The canonical change of trivialization between two equations for the same divisor on an
open. -/
noncomputable def equationTransitionIso (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn D U g) :
    SheafOfModules.unit (X.ringCatSheaf.over U) ≅
      SheafOfModules.unit (X.ringCatSheaf.over U) :=
  equationIso D U f hf ≪≫ (equationIso D U g hg).symm

/-- Changes of local equation satisfy the cocycle law. -/
lemma equationTransitionIso_trans (D : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn D U g)
    (h : Additive X.functionFieldˣ) (hh : IsEquationOn D U h) :
    equationTransitionIso D U f hf g hg ≪≫
      equationTransitionIso D U g hg h hh =
        equationTransitionIso D U f hf h hh := by
  ext
  simp [equationTransitionIso]

private noncomputable def localEquationOpen (D : CartierDivisor X) (x : X) : X.Opens :=
  (exists_localEquation D x).choose

private lemma mem_localEquationOpen (D : CartierDivisor X) (x : X) :
    x ∈ localEquationOpen D x :=
  (exists_localEquation D x).choose_spec.1

private noncomputable def localEquation (D : CartierDivisor X) (x : X) :
    Additive X.functionFieldˣ :=
  (exists_localEquation D x).choose_spec.2.choose

private lemma localEquation_isEquationOn (D : CartierDivisor X) (x : X) :
    IsEquationOn D (localEquationOpen D x) (localEquation D x) :=
  (exists_localEquation D x).choose_spec.2.choose_spec

private lemma localEquationOpen_coversTop (D : CartierDivisor X) :
    (_root_.Opens.grothendieckTopology X).CoversTop (localEquationOpen D) := by
  rw [_root_.Opens.coversTop_iff]
  apply top_unique
  intro x hx
  exact Opens.mem_iSup.mpr ⟨x, mem_localEquationOpen D x⟩

/-- The associated sheaf of a Cartier divisor is invertible. -/
lemma associatedSheaf_isInvertible (D : CartierDivisor X) :
    SheafOfModules.IsInvertible.{u, u, u}
      (show SheafOfModules X.ringCatSheaf from associatedSheaf D) := by
  apply SheafOfModules.IsInvertible.of_trivializations
    (localEquationOpen D) (localEquationOpen_coversTop D)
  intro x
  exact equationIso D (localEquationOpen D x) (localEquation D x)
    (localEquation_isEquationOn D x)

attribute [instance] associatedSheaf_isInvertible

private lemma IsEquationOn.add {D E : CartierDivisor X} {U : X.Opens}
    {f g : Additive X.functionFieldˣ} (hf : IsEquationOn D U f)
    (hg : IsEquationOn E U g) : IsEquationOn (D + E) U (f + g) := by
  intro x hx
  rw [add_apply, hf x hx, hg x hx, localCartierClass_add]

/-- Pointwise multiplication of rational sections. -/
private noncomputable def rationalMul (U : X.Opens)
    (s t : RationalSections X U) : RationalSections X U :=
  fun h ↦ s h * t h

private lemma rationalMul_mem_fractionalSections (D E : CartierDivisor X) (U : X.Opens)
    {s t : RationalSections X U} (hs : s ∈ fractionalSections D U)
    (ht : t ∈ fractionalSections E U) :
    rationalMul U s t ∈ fractionalSections (D + E) U := by
  induction hs using Submodule.span_induction with
  | mem s hs =>
      obtain ⟨f, hf, rfl⟩ := hs
      induction ht using Submodule.span_induction with
      | mem t ht =>
          obtain ⟨g, hg, rfl⟩ := ht
          apply Submodule.subset_span
          refine ⟨f + g, hf.add hg, ?_⟩
          funext h
          simp [rationalMul, inverseSection]
          exact mul_comm _ _
      | zero =>
          rw [show rationalMul U (inverseSection U f) 0 = 0 by
            funext h; simp [rationalMul]]
          exact Submodule.zero_mem _
      | add t₁ t₂ _ _ ht₁ ht₂ =>
          rw [show rationalMul U (inverseSection U f) (t₁ + t₂) =
            rationalMul U (inverseSection U f) t₁ +
              rationalMul U (inverseSection U f) t₂ by
                funext h; simp [rationalMul, mul_add]]
          exact Submodule.add_mem _ ht₁ ht₂
      | smul r t _ ht =>
          rw [show rationalMul U (inverseSection U f) (r • t) =
            r • rationalMul U (inverseSection U f) t by
              funext h
              letI : Nonempty U := h.down
              change ((f.toMul : X.functionField)⁻¹) *
                  (X.germToFunctionField U r * t h) =
                X.germToFunctionField U r *
                  (((f.toMul : X.functionField)⁻¹) * t h)
              ring]
          exact Submodule.smul_mem _ r ht
  | zero =>
      rw [show rationalMul U 0 t = 0 by funext h; simp [rationalMul]]
      exact Submodule.zero_mem _
  | add s₁ s₂ _ _ hs₁ hs₂ =>
      rw [show rationalMul U (s₁ + s₂) t =
        rationalMul U s₁ t + rationalMul U s₂ t by
          funext h; simp [rationalMul, add_mul]]
      exact Submodule.add_mem _ hs₁ hs₂
  | smul r s _ hs =>
      rw [show rationalMul U (r • s) t = r • rationalMul U s t by
        funext h
        letI : Nonempty U := h.down
        change (X.germToFunctionField U r * s h) * t h =
          X.germToFunctionField U r * (s h * t h)
        rw [mul_assoc]]
      exact Submodule.smul_mem _ r hs

private lemma rationalSectionsRes_rationalMul {U V : X.Opens} (h : V ≤ U)
    (s t : RationalSections X U) :
    rationalSectionsRes X h (rationalMul U s t) =
      rationalMul V (rationalSectionsRes X h s) (rationalSectionsRes X h t) := by
  rfl

noncomputable local instance : MonoidalCategory X.PresheafOfModules :=
  PresheafOfModules.monoidalCategory (R := X.presheaf)

noncomputable local instance (U : X.Opens) : MonoidalCategory
    (_root_.PresheafOfModules (X.ringCatSheaf.over U).obj) :=
  PresheafOfModules.monoidalCategory (R := (X.sheaf.over U).obj)

noncomputable local instance (U : X.Opens) : SymmetricCategory
    (_root_.PresheafOfModules (X.ringCatSheaf.over U).obj) :=
  PresheafOfModules.symmetricCategory (R := (X.sheaf.over U).obj)

/-- Multiplication of fractional sections. -/
noncomputable def multiplicationHom (D E : CartierDivisor X) :
    fractionalPresheaf D ⊗ fractionalPresheaf E ⟶ fractionalPresheaf (D + E) where
  app U := ModuleCat.MonoidalCategory.tensorLift
    (fun s t ↦ (⟨rationalMul U.unop s.1 t.1,
      rationalMul_mem_fractionalSections D E U.unop s.2 t.2⟩ :
        fractionalSections (D + E) U.unop))
    (fun s₁ s₂ t ↦ by
      apply Subtype.ext
      funext h
      change (s₁.1 h + s₂.1 h) * t.1 h =
        s₁.1 h * t.1 h + s₂.1 h * t.1 h
      rw [add_mul])
    (fun r s t ↦ by
      apply Subtype.ext
      funext h
      letI : Nonempty U.unop := h.down
      change (X.germToFunctionField U.unop r * s.1 h) * t.1 h =
        X.germToFunctionField U.unop r * (s.1 h * t.1 h)
      rw [mul_assoc])
    (fun s t₁ t₂ ↦ by
      apply Subtype.ext
      funext h
      change s.1 h * (t₁.1 h + t₂.1 h) =
        s.1 h * t₁.1 h + s.1 h * t₂.1 h
      rw [mul_add])
    (fun r s t ↦ by
      apply Subtype.ext
      funext h
      letI : Nonempty U.unop := h.down
      change s.1 h * (X.germToFunctionField U.unop r * t.1 h) =
        X.germToFunctionField U.unop r * (s.1 h * t.1 h)
      ring)
  naturality {U V} i := by
    apply ModuleCat.MonoidalCategory.tensor_ext
    intro s t
    apply Subtype.ext
    exact rationalSectionsRes_rationalMul (leOfHom i.unop) s.1 t.1

/-- On a common equation domain, the tensor product has the generator `1/f ⊗ 1/g`. -/
private noncomputable def tensorEquationHom (D E : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    PresheafOfModules.unit (X.ringCatSheaf.over U).obj ⟶
      overPresheaf (fractionalPresheaf D ⊗ fractionalPresheaf E) U :=
  (PresheafOfModules.unitHomEquiv _).symm {
    val := fun V ↦
      let sf : fractionalSections D V.unop.left :=
        ⟨inverseSection V.unop.left f,
          Submodule.subset_span ⟨f, hf.mono (leOfHom V.unop.hom), rfl⟩⟩
      let sg : fractionalSections E V.unop.left :=
        ⟨inverseSection V.unop.left g,
          Submodule.subset_span ⟨g, hg.mono (leOfHom V.unop.hom), rfl⟩⟩
      sf ⊗ₜ sg
    property := fun {V W} i ↦ by
      change (fractionalPresheaf D ⊗ fractionalPresheaf E).map i.unop.left.op _ = _
      rfl }

private lemma tensorEquationHom_eq_tensor (D E : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    tensorEquationHom D E U f hf g hg =
      (λ_ (PresheafOfModules.unit (X.ringCatSheaf.over U).obj)).inv ≫
        (equationHom D U f hf ⊗ₘ equationHom E U g hg) := by
  rw [tensorEquationHom]
  apply (overPresheaf
    (fractionalPresheaf D ⊗ fractionalPresheaf E) U).unitHomEquiv.injective
  rw [Equiv.apply_symm_apply]
  ext V
  letI : CommRing ((X.ringCatSheaf.over U).obj.obj V) :=
    inferInstanceAs (CommRing Γ(X, V.unop.left))
  change _ =
    ((equationHom D U f hf).app V ⊗ₘ (equationHom E U g hg).app V)
      (((λ_ (PresheafOfModules.unit
        (X.ringCatSheaf.over U).obj)).inv.app V)
          (show (PresheafOfModules.unit
            (X.ringCatSheaf.over U).obj).obj V from
              (1 : (X.ringCatSheaf.over U).obj.obj V)))
  erw [PresheafOfModules.leftUnitor_inv_app,
    ModuleCat.MonoidalCategory.leftUnitor_inv_apply,
    ModuleCat.MonoidalCategory.tensorHom_tmul]
  rw [equationHom_app_one D U f hf V,
    equationHom_app_one E U g hg V]
  change
    (show fractionalSections D V.unop.left from
        ⟨inverseSection V.unop.left f,
          Submodule.subset_span
            ⟨f, hf.mono (leOfHom V.unop.hom), rfl⟩⟩) ⊗ₜ[Γ(X, V.unop.left)]
      (show fractionalSections E V.unop.left from
        ⟨inverseSection V.unop.left g,
          Submodule.subset_span
            ⟨g, hg.mono (leOfHom V.unop.hom), rfl⟩⟩) = _
  rfl

private lemma unitHomEquiv_symm_comp' (U : X.Opens)
    {M N : _root_.PresheafOfModules (X.ringCatSheaf.over U).obj}
    (s : M.sections) (p : M ⟶ N) :
    M.unitHomEquiv.symm s ≫ p =
      N.unitHomEquiv.symm (PresheafOfModules.sectionsMap p s) := by
  apply N.unitHomEquiv.injective
  rw [N.unitHomEquiv.apply_symm_apply]
  ext V
  change p.app V ((M.unitHomEquiv.symm s).app V
    (1 : (X.ringCatSheaf.over U).obj.obj V)) = p.app V (s.val V)
  have hs := M.unitHomEquiv.apply_symm_apply s
  exact congrArg (fun q ↦ p.app V q)
    (congrArg (fun q : M.sections ↦ q.val V) hs)

private lemma multiplicationHom_comp_tensorEquationHom (D E : CartierDivisor X)
    (U : X.Opens) (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    tensorEquationHom D E U f hf g hg ≫
      (PresheafOfModules.pushforward
        (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).map
          (multiplicationHom D E) =
    equationHom (D + E) U (f + g) (hf.add hg) := by
  rw [tensorEquationHom, unitHomEquiv_symm_comp']
  rw [equationHom]
  change (overPresheaf (fractionalPresheaf (D + E)) U).unitHomEquiv.symm _ =
    (overPresheaf (fractionalPresheaf (D + E)) U).unitHomEquiv.symm _
  congr 1
  ext V
  apply Subtype.ext
  funext h
  dsimp [PresheafOfModules.sectionsMap, equationHom, multiplicationHom,
    rationalMul, inverseSection]
  change (f.toMul : X.functionField)⁻¹ * (g.toMul : X.functionField)⁻¹ =
    ((f + g).toMul : X.functionField)⁻¹
  simp
  exact mul_comm _ _

set_option maxHeartbeats 800000 in
private lemma tensorEquationHom_isLocallySurjective (D E : CartierDivisor X)
    (U : X.Opens) (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    Presheaf.IsLocallySurjective ((_root_.Opens.grothendieckTopology X).over U)
      ((PresheafOfModules.toPresheaf _).map (tensorEquationHom D E U f hf g hg)) := by
  let K := (_root_.Opens.grothendieckTopology X).over U
  let φD := (PresheafOfModules.toPresheaf _).map (equationHom D U f hf)
  let φE := (PresheafOfModules.toPresheaf _).map (equationHom E U g hg)
  let φT := (PresheafOfModules.toPresheaf _).map (tensorEquationHom D E U f hf g hg)
  letI : Presheaf.IsLocallySurjective K φD := equationHom_isLocallySurjective D U f hf
  letI : Presheaf.IsLocallySurjective K φE := equationHom_isLocallySurjective E U g hg
  constructor
  intro V z
  induction z using TensorProduct.induction_on with
  | zero =>
      have hzero : Presheaf.imageSieve φT (φT.app (.op V) 0) ∈ K V := by
        rw [Presheaf.imageSieve_app]
        exact K.top_mem V
      simpa only [map_zero] using hzero
  | add z₁ z₂ hz₁ hz₂ =>
      apply K.superset_covering
        (S := Presheaf.imageSieve φT z₁ ⊓ Presheaf.imageSieve φT z₂)
      · intro W j hj
        refine ⟨Presheaf.localPreimage φT z₁ j hj.1 +
          Presheaf.localPreimage φT z₂ j hj.2, ?_⟩
        rw [map_add, Presheaf.app_localPreimage, Presheaf.app_localPreimage]
        exact (map_add _ _ _).symm
      · exact K.intersection_covering hz₁ hz₂
  | tmul s t =>
      apply K.superset_covering
        (S := Presheaf.imageSieve φD s ⊓ Presheaf.imageSieve φE t)
      · intro W j hj
        let a : Γ(X, W.left) := Presheaf.localPreimage φD s j hj.1
        let b : Γ(X, W.left) := Presheaf.localPreimage φE t j hj.2
        refine ⟨a * b, ?_⟩
        have ha := Presheaf.app_localPreimage φD s j hj.1
        have hb := Presheaf.app_localPreimage φE t j hj.2
        change (equationHom D U f hf).app (.op W) a =
          (fractionalPresheaf D).map j.left.op s at ha
        change (equationHom E U g hg).app (.op W) b =
          (fractionalPresheaf E).map j.left.op t at hb
        change (tensorEquationHom D E U f hf g hg).app (.op W) (a * b) =
          (fractionalPresheaf D ⊗ fractionalPresheaf E).map j.left.op (s ⊗ₜ t)
        change (tensorEquationHom D E U f hf g hg).app (.op W) (a * b) =
          (fractionalPresheaf D).map j.left.op s ⊗ₜ
            (fractionalPresheaf E).map j.left.op t
        change (a * b) •
            ((show fractionalSections D W.left from
                ⟨inverseSection W.left f, Submodule.subset_span
                  ⟨f, hf.mono (leOfHom W.hom), rfl⟩⟩) ⊗ₜ[Γ(X, W.left)]
              (show fractionalSections E W.left from
                ⟨inverseSection W.left g, Submodule.subset_span
                  ⟨g, hg.mono (leOfHom W.hom), rfl⟩⟩)) = _
        rw [TensorProduct.smul_tmul']
        rw [mul_smul]
        rw [show a • b •
            (show fractionalSections D W.left from
              ⟨inverseSection W.left f, Submodule.subset_span
                ⟨f, hf.mono (leOfHom W.hom), rfl⟩⟩) =
            b • (a •
              (show fractionalSections D W.left from
                ⟨inverseSection W.left f, Submodule.subset_span
                  ⟨f, hf.mono (leOfHom W.hom), rfl⟩⟩)) by
          rw [← mul_smul, ← mul_smul, mul_comm]]
        rw [TensorProduct.smul_tmul]
        change (equationHom D U f hf).app (.op W) a ⊗ₜ
          (equationHom E U g hg).app (.op W) b = _
        rw [ha, hb]
        rfl
      · exact K.intersection_covering
          (Presheaf.imageSieve_mem K φD s) (Presheaf.imageSieve_mem K φE t)

private lemma tensorEquationHom_isLocallyInjective (D E : CartierDivisor X)
    (U : X.Opens) (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    Presheaf.IsLocallyInjective ((_root_.Opens.grothendieckTopology X).over U)
      ((PresheafOfModules.toPresheaf _).map (tensorEquationHom D E U f hf g hg)) := by
  apply Presheaf.isLocallyInjective_of_injective _ _
  intro V a b hab
  apply equationHom_app_injective (D + E) U (f + g) (hf.add hg) V
  change (tensorEquationHom D E U f hf g hg).app V a =
    (tensorEquationHom D E U f hf g hg).app V b at hab
  have hcomp := multiplicationHom_comp_tensorEquationHom D E U f hf g hg
  let m := (PresheafOfModules.pushforward
        (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).map
          (multiplicationHom D E)
  have h := congrArg (fun q ↦ m.app V q) hab
  change (tensorEquationHom D E U f hf g hg ≫ m).app V a =
    (tensorEquationHom D E U f hf g hg ≫ m).app V b at h
  rw [hcomp] at h
  exact h

private lemma tensorEquationHom_mem_W (D E : CartierDivisor X)
    (U : X.Opens) (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    ((_root_.Opens.grothendieckTopology X).over U).W
      ((PresheafOfModules.toPresheaf _).map (tensorEquationHom D E U f hf g hg)) := by
  letI := tensorEquationHom_isLocallyInjective D E U f hf g hg
  letI := tensorEquationHom_isLocallySurjective D E U f hf g hg
  exact ((_root_.Opens.grothendieckTopology X).over U).W_of_isLocallyBijective _

private lemma restrictedMultiplicationHom_mem_W (D E : CartierDivisor X)
    (U : X.Opens) (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    ((_root_.Opens.grothendieckTopology X).over U).W
      ((PresheafOfModules.toPresheaf _).map
        ((PresheafOfModules.pushforward
          (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).map
            (multiplicationHom D E))) := by
  let K := (_root_.Opens.grothendieckTopology X).over U
  let t := (PresheafOfModules.toPresheaf _).map (tensorEquationHom D E U f hf g hg)
  let m := (PresheafOfModules.toPresheaf _).map
    ((PresheafOfModules.pushforward
      (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).map (multiplicationHom D E))
  let e := (PresheafOfModules.toPresheaf _).map
    (equationHom (D + E) U (f + g) (hf.add hg))
  have hfac : t ≫ m = e := by
    exact congrArg (fun q ↦ (PresheafOfModules.toPresheaf _).map q)
      (multiplicationHom_comp_tensorEquationHom D E U f hf g hg)
  have ht := tensorEquationHom_mem_W D E U f hf g hg
  have he := equationHom_mem_W (D + E) U (f + g) (hf.add hg)
  letI : Presheaf.IsLocallyInjective K t := ht.isLocallyInjective
  letI : Presheaf.IsLocallySurjective K t := ht.isLocallySurjective
  letI : Presheaf.IsLocallyInjective K e := he.isLocallyInjective
  letI : Presheaf.IsLocallySurjective K e := he.isLocallySurjective
  letI : Presheaf.IsLocallySurjective K m :=
    Presheaf.isLocallySurjective_of_isLocallySurjective_fac K hfac
  letI : Presheaf.IsLocallyInjective K m :=
    Presheaf.isLocallyInjective_of_isLocallyInjective_of_isLocallySurjective_fac K e hfac
  exact K.W_of_isLocallyBijective m

private noncomputable def commonEquationOpen (D E : CartierDivisor X)
    (p : X × X) : X.Opens :=
  localEquationOpen D p.1 ⊓ localEquationOpen E p.2

private lemma commonEquationOpen_coversTop (D E : CartierDivisor X) :
    (_root_.Opens.grothendieckTopology X).CoversTop (commonEquationOpen D E) := by
  rw [_root_.Opens.coversTop_iff]
  change ⨆ p : X × X, localEquationOpen D p.1 ⊓ localEquationOpen E p.2 = ⊤
  rw [← iSup_inf_iSup]
  have hD : ⨆ x, localEquationOpen D x = ⊤ :=
    (_root_.Opens.coversTop_iff (X : Type u) (localEquationOpen D)).mp
      (localEquationOpen_coversTop D)
  have hE : ⨆ x, localEquationOpen E x = ⊤ :=
    (_root_.Opens.coversTop_iff (X : Type u) (localEquationOpen E)).mp
      (localEquationOpen_coversTop E)
  rw [hD, hE, inf_top_eq]

set_option maxHeartbeats 800000 in
private lemma multiplicationHom_mem_W (D E : CartierDivisor X) :
    (_root_.Opens.grothendieckTopology X).W
      ((PresheafOfModules.toPresheaf _).map (multiplicationHom D E)) := by
  let K := _root_.Opens.grothendieckTopology X
  let p := (PresheafOfModules.toPresheaf _).map (multiplicationHom D E)
  let Y := commonEquationOpen D E
  have hY : K.CoversTop Y := commonEquationOpen_coversTop D E
  have hlocal (q : X × X) : (K.over (Y q)).W
      (Functor.whiskerLeft (Over.forget (Y q)).op p) := by
    let f := localEquation D q.1
    let g := localEquation E q.2
    have hf : IsEquationOn D (Y q) f :=
      (localEquation_isEquationOn D q.1).mono inf_le_left
    have hg : IsEquationOn E (Y q) g :=
      (localEquation_isEquationOn E q.2).mono inf_le_right
    have hw := restrictedMultiplicationHom_mem_W D E (Y q) f hf g hg
    change (K.over (Y q)).W
      ((PresheafOfModules.toPresheaf _).map
        ((PresheafOfModules.pushforward
          (F := Over.forget (Y q)) (𝟙 (X.ringCatSheaf.over (Y q)).obj)).map
            (multiplicationHom D E)))
    exact hw
  exact Presheaf.W_of_coversTop p Y hY hlocal

private lemma isIso_sheafification_map_multiplicationHom (D E : CartierDivisor X) :
    IsIso ((PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).map
      (multiplicationHom D E)) := by
  apply Localization.inverts
    (PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj))
    ((_root_.Opens.grothendieckTopology X).W.inverseImage
      (PresheafOfModules.toPresheaf X.ringCatSheaf.obj))
  exact multiplicationHom_mem_W D E

/-- Sheafified multiplication identifies the tensor of the two fractional models with the
associated sheaf of the sum. -/
noncomputable def fractionalTensorAddIso (D E : CartierDivisor X) :
    (PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).obj
        (fractionalPresheaf D ⊗ fractionalPresheaf E) ≅
      associatedSheaf (D + E) :=
  @asIso _ _ _ _
    ((PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).map
      (multiplicationHom D E))
    (isIso_sheafification_map_multiplicationHom D E)

/-! ### Tensor additivity for the associated sheaves -/

/-- The canonical comparison from the tensor of the fractional models to the tensor of their
sheafifications. -/
private noncomputable def fractionalToAssociatedTensorHom
    (D E : CartierDivisor X) :
    fractionalPresheaf D ⊗ fractionalPresheaf E ⟶
      (Modules.toPresheafOfModules X).obj (associatedSheaf D) ⊗
        (Modules.toPresheafOfModules X).obj (associatedSheaf E) :=
  (PresheafOfModules.sheafificationAdjunction
      (𝟙 X.ringCatSheaf.obj)).unit.app (fractionalPresheaf D) ⊗ₘ
    (PresheafOfModules.sheafificationAdjunction
      (𝟙 X.ringCatSheaf.obj)).unit.app (fractionalPresheaf E)

/-- A local equation map followed by the sheafification unit. -/
private noncomputable def equationToAssociatedHom (D : CartierDivisor X)
    (U : X.Opens) (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f) :
    PresheafOfModules.unit (X.ringCatSheaf.over U).obj ⟶
      overPresheaf ((Modules.toPresheafOfModules X).obj (associatedSheaf D)) U :=
  equationHom D U f hf ≫
    (PresheafOfModules.pushforward
      (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).map
        ((PresheafOfModules.sheafificationAdjunction
          (𝟙 X.ringCatSheaf.obj)).unit.app (fractionalPresheaf D))

private lemma equationToAssociatedHom_mem_W (D : CartierDivisor X)
    (U : X.Opens) (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f) :
    ((_root_.Opens.grothendieckTopology X).over U).W
      ((PresheafOfModules.toPresheaf _).map
        (equationToAssociatedHom D U f hf)) := by
  let K := _root_.Opens.grothendieckTopology X
  let η := (PresheafOfModules.sheafificationAdjunction
    (𝟙 X.ringCatSheaf.obj)).unit.app (fractionalPresheaf D)
  let F := PresheafOfModules.pushforward
    (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)
  have hη : K.W ((PresheafOfModules.toPresheaf _).map η) := by
    dsimp only [η]
    rw [PresheafOfModules.toPresheaf_map_sheafificationAdjunction_unit_app]
    exact K.W_toSheafify (fractionalPresheaf D).presheaf
  have hFη : (K.over U).W
      ((PresheafOfModules.toPresheaf _).map (F.map η)) := by
    change (K.over U).W
      (Functor.whiskerLeft (Over.forget U).op
        ((PresheafOfModules.toPresheaf _).map η))
    letI : Presheaf.IsLocallyInjective K
        ((PresheafOfModules.toPresheaf _).map η) := hη.isLocallyInjective
    letI : Presheaf.IsLocallySurjective K
        ((PresheafOfModules.toPresheaf _).map η) := hη.isLocallySurjective
    letI : Presheaf.IsLocallyInjective (K.over U)
        (Functor.whiskerLeft (Over.forget U).op
          ((PresheafOfModules.toPresheaf _).map η)) :=
      Presheaf.isLocallyInjective_whisker (K.over U) K (Over.forget U) _
    letI : Presheaf.IsLocallySurjective (K.over U)
        (Functor.whiskerLeft (Over.forget U).op
          ((PresheafOfModules.toPresheaf _).map η)) :=
      Presheaf.isLocallySurjective_whisker (K.over U) K (Over.forget U) _
    exact (K.over U).W_of_isLocallyBijective _
  rw [equationToAssociatedHom, Functor.map_comp]
  exact (K.over U).W.comp_mem _ _ (equationHom_mem_W D U f hf) hFη

/-- The tensor of two local equation trivializations after sheafification. -/
private noncomputable def associatedTensorEquationHom (D E : CartierDivisor X)
    (U : X.Opens) (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    PresheafOfModules.unit (X.ringCatSheaf.over U).obj ⟶
      overPresheaf ((Modules.toPresheafOfModules X).obj (associatedSheaf D)) U ⊗
        overPresheaf ((Modules.toPresheafOfModules X).obj (associatedSheaf E)) U :=
  (λ_ (PresheafOfModules.unit (X.ringCatSheaf.over U).obj)).inv ≫
    (equationToAssociatedHom D U f hf ⊗ₘ equationToAssociatedHom E U g hg)

set_option maxHeartbeats 800000 in
private lemma associatedTensorEquationHom_mem_W (D E : CartierDivisor X)
    (U : X.Opens) (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    ((_root_.Opens.grothendieckTopology X).over U).W
      ((PresheafOfModules.toPresheaf _).map
        (associatedTensorEquationHom D E U f hf g hg)) := by
  let K := (_root_.Opens.grothendieckTopology X).over U
  let aD := equationToAssociatedHom D U f hf
  let aE := equationToAssociatedHom E U g hg
  have haD : K.W ((PresheafOfModules.toPresheaf _).map aD) :=
    equationToAssociatedHom_mem_W D U f hf
  have haE : K.W ((PresheafOfModules.toPresheaf _).map aE) :=
    equationToAssociatedHom_mem_W E U g hg
  letI : SheafOfModules.IsInvertible.{u, u, u}
      (SheafOfModules.unit (X.ringCatSheaf.over U)) :=
    SheafOfModules.instIsInvertibleUnit.{u, u, u}
  letI : SheafOfModules.IsInvertible.{u, u, u}
      ((associatedSheaf D).over U) :=
    SheafOfModules.IsInvertible.ofIso
      (M := SheafOfModules.unit (X.ringCatSheaf.over U))
      (N := (associatedSheaf D).over U) (equationIso D U f hf)
  letI : SheafOfModules.IsInvertible.{u, u, u}
      ((associatedSheaf E).over U) :=
    SheafOfModules.IsInvertible.ofIso
      (M := SheafOfModules.unit (X.ringCatSheaf.over U))
      (N := (associatedSheaf E).over U) (equationIso E U g hg)
  obtain ⟨qI, hqI, hrankI⟩ :=
    SheafOfModules.IsInvertible.exists_rankOneData
      (M := SheafOfModules.unit (X.ringCatSheaf.over U))
  obtain ⟨qE, hqE, hrankE⟩ :=
    SheafOfModules.IsInvertible.exists_rankOneData
      (M := (associatedSheaf E).over U)
  letI : qI.IsLocallyFreeData := hqI
  letI : qE.IsLocallyFreeData := hqE
  have hleft : K.W ((PresheafOfModules.toPresheaf _).map
      (PresheafOfModules.unit (X.ringCatSheaf.over U).obj ◁ aE)) :=
    SheafOfModules.W_whiskerLeft_of_rankOneData
      (S := X.sheaf.over U) qI hrankI aE haE
  have hmid : K.W ((PresheafOfModules.toPresheaf _).map
      (overPresheaf ((Modules.toPresheafOfModules X).obj
        (associatedSheaf E)) U ◁ aD)) :=
    SheafOfModules.W_whiskerLeft_of_rankOneData
      (S := X.sheaf.over U) qE hrankE aD haD
  have hright : K.W ((PresheafOfModules.toPresheaf _).map
      (aD ▷ overPresheaf ((Modules.toPresheafOfModules X).obj
        (associatedSheaf E)) U)) := by
    have hbraid : aD ▷ overPresheaf ((Modules.toPresheafOfModules X).obj
        (associatedSheaf E)) U =
        (β_ (PresheafOfModules.unit (X.ringCatSheaf.over U).obj)
          (overPresheaf ((Modules.toPresheafOfModules X).obj
            (associatedSheaf E)) U)).hom ≫
            (overPresheaf ((Modules.toPresheafOfModules X).obj
              (associatedSheaf E)) U ◁ aD) ≫
          (β_ (overPresheaf ((Modules.toPresheafOfModules X).obj
              (associatedSheaf D)) U)
            (overPresheaf ((Modules.toPresheafOfModules X).obj
              (associatedSheaf E)) U)).inv := by
      calc
        _ = (aD ▷ overPresheaf ((Modules.toPresheafOfModules X).obj
              (associatedSheaf E)) U) ≫
              (β_ (overPresheaf ((Modules.toPresheafOfModules X).obj
                  (associatedSheaf D)) U)
                (overPresheaf ((Modules.toPresheafOfModules X).obj
                  (associatedSheaf E)) U)).hom ≫
              (β_ (overPresheaf ((Modules.toPresheafOfModules X).obj
                  (associatedSheaf D)) U)
                (overPresheaf ((Modules.toPresheafOfModules X).obj
                  (associatedSheaf E)) U)).inv := by simp
        _ = _ := by
          have h := congrArg (fun k ↦ k ≫
              (β_ (overPresheaf ((Modules.toPresheafOfModules X).obj
                  (associatedSheaf D)) U)
                (overPresheaf ((Modules.toPresheafOfModules X).obj
                  (associatedSheaf E)) U)).inv)
            (BraidedCategory.braiding_naturality_left aD
              (overPresheaf ((Modules.toPresheafOfModules X).obj
                (associatedSheaf E)) U))
          simpa only [Category.assoc] using h
    rw [hbraid, Functor.map_comp, Functor.map_comp]
    have hb₁ : K.W ((PresheafOfModules.toPresheaf _).map
        (β_ (PresheafOfModules.unit (X.ringCatSheaf.over U).obj)
          (overPresheaf ((Modules.toPresheafOfModules X).obj
            (associatedSheaf E)) U)).hom) := K.W.of_isIso _
    have hb₂ : K.W ((PresheafOfModules.toPresheaf _).map
        (β_ (overPresheaf ((Modules.toPresheafOfModules X).obj
            (associatedSheaf D)) U)
          (overPresheaf ((Modules.toPresheafOfModules X).obj
            (associatedSheaf E)) U)).inv) := K.W.of_isIso _
    have htail := K.W.comp_mem _ _ hmid hb₂
    exact K.W.comp_mem _ _ hb₁ htail
  have htensor : K.W ((PresheafOfModules.toPresheaf _).map (aD ⊗ₘ aE)) := by
    have hfac : aD ⊗ₘ aE =
        (PresheafOfModules.unit (X.ringCatSheaf.over U).obj ◁ aE) ≫
          (aD ▷ overPresheaf ((Modules.toPresheafOfModules X).obj
            (associatedSheaf E)) U) := by
      simpa only [MonoidalCategory.id_tensorHom, MonoidalCategory.tensorHom_id,
        Category.id_comp, Category.comp_id] using
          (MonoidalCategory.tensorHom_comp_tensorHom
            (𝟙 (PresheafOfModules.unit (X.ringCatSheaf.over U).obj)) aE aD
              (𝟙 (overPresheaf ((Modules.toPresheafOfModules X).obj
                (associatedSheaf E)) U))).symm
    rw [hfac, Functor.map_comp]
    exact K.W.comp_mem _ _ hleft hright
  rw [associatedTensorEquationHom, Functor.map_comp]
  exact K.W.comp_mem _ _ (K.W.of_isIso _) htensor

private lemma tensorEquationHom_comp_fractionalToAssociatedTensorHom
    (D E : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    tensorEquationHom D E U f hf g hg ≫
      (PresheafOfModules.pushforward
        (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).map
          (fractionalToAssociatedTensorHom D E) =
    associatedTensorEquationHom D E U f hf g hg := by
  rw [tensorEquationHom_eq_tensor, associatedTensorEquationHom]
  simp only [equationToAssociatedHom, fractionalToAssociatedTensorHom]
  ext V
  rfl

private lemma restrictedFractionalToAssociatedTensorHom_mem_W
    (D E : CartierDivisor X) (U : X.Opens)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D U f)
    (g : Additive X.functionFieldˣ) (hg : IsEquationOn E U g) :
    ((_root_.Opens.grothendieckTopology X).over U).W
      ((PresheafOfModules.toPresheaf _).map
        ((PresheafOfModules.pushforward
          (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).map
            (fractionalToAssociatedTensorHom D E))) := by
  let K := (_root_.Opens.grothendieckTopology X).over U
  let t := (PresheafOfModules.toPresheaf _).map
    (tensorEquationHom D E U f hf g hg)
  let c := (PresheafOfModules.toPresheaf _).map
    ((PresheafOfModules.pushforward
      (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).map
        (fractionalToAssociatedTensorHom D E))
  have ht : K.W t := tensorEquationHom_mem_W D E U f hf g hg
  have htc : K.W (t ≫ c) := by
    rw [← Functor.map_comp,
      tensorEquationHom_comp_fractionalToAssociatedTensorHom]
    exact associatedTensorEquationHom_mem_W D E U f hf g hg
  exact K.W.of_precomp t c ht htc

set_option maxHeartbeats 800000 in
private lemma fractionalToAssociatedTensorHom_mem_W (D E : CartierDivisor X) :
    (_root_.Opens.grothendieckTopology X).W
      ((PresheafOfModules.toPresheaf _).map
        (fractionalToAssociatedTensorHom D E)) := by
  let K := _root_.Opens.grothendieckTopology X
  let p := (PresheafOfModules.toPresheaf _).map
    (fractionalToAssociatedTensorHom D E)
  let Y := commonEquationOpen D E
  have hY : K.CoversTop Y := commonEquationOpen_coversTop D E
  refine Presheaf.W_of_coversTop p Y hY (fun q => ?_)
  exact restrictedFractionalToAssociatedTensorHom_mem_W D E (Y q) (localEquation D q.1)
    ((localEquation_isEquationOn D q.1).mono inf_le_left) (localEquation E q.2)
    ((localEquation_isEquationOn E q.2).mono inf_le_right)

private lemma isIso_sheafification_map_fractionalToAssociatedTensorHom
    (D E : CartierDivisor X) :
    IsIso ((PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).map
      (fractionalToAssociatedTensorHom D E)) := by
  apply Localization.inverts
    (PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj))
    ((_root_.Opens.grothendieckTopology X).W.inverseImage
      (PresheafOfModules.toPresheaf X.ringCatSheaf.obj))
  exact fractionalToAssociatedTensorHom_mem_W D E

/-- The associated-sheaf construction converts addition of Cartier divisors into tensor
product. -/
noncomputable def associatedTensorAddIso (D E : CartierDivisor X) :
    Modules.tensorObj (associatedSheaf D) (associatedSheaf E) ≅
      associatedSheaf (D + E) :=
  (@asIso _ _ _ _
    ((PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).map
      (fractionalToAssociatedTensorHom D E))
    (isIso_sheafification_map_fractionalToAssociatedTensorHom D E)).symm ≪≫
      fractionalTensorAddIso D E

/-! ### Global equations, zero, and tensor inverses -/

/-- Multiplication by the inverse of an equation which is valid on all of `X`. -/
private noncomputable def globalEquationHom (D : CartierDivisor X)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D ⊤ f) :
    PresheafOfModules.unit X.ringCatSheaf.obj ⟶ fractionalPresheaf D :=
  (PresheafOfModules.unitHomEquiv _).symm {
    val := fun U ↦ ⟨inverseSection U.unop f,
      Submodule.subset_span ⟨f, hf.mono le_top, rfl⟩⟩
    property := fun g ↦ by
      apply Subtype.ext
      exact rationalSectionsRes_inverseSection (leOfHom g.unop) f }

private lemma restrictGlobalEquationHom (D : CartierDivisor X)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D ⊤ f) (U : X.Opens) :
    (PresheafOfModules.pushforward
      (F := Over.forget U) (𝟙 (X.ringCatSheaf.over U).obj)).map
        (globalEquationHom D f hf) =
      equationHom D U f (hf.mono le_top) := by
  ext V
  rfl

set_option maxHeartbeats 800000 in
private lemma globalEquationHom_mem_W (D : CartierDivisor X)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D ⊤ f) :
    (_root_.Opens.grothendieckTopology X).W
      ((PresheafOfModules.toPresheaf _).map
        (globalEquationHom D f hf)) := by
  let K := _root_.Opens.grothendieckTopology X
  let p := (PresheafOfModules.toPresheaf _).map (globalEquationHom D f hf)
  let Y : PUnit.{u + 1} → X.Opens := fun _ ↦ ⊤
  have hY : K.CoversTop Y := by
    rw [_root_.Opens.coversTop_iff]
    change ⨆ _ : PUnit.{u + 1}, (⊤ : X.Opens) = ⊤
    simp
  have hlocal : (K.over ⊤).W
      (Functor.whiskerLeft (Over.forget ⊤).op p) := by
    change (K.over ⊤).W
      ((PresheafOfModules.toPresheaf _).map
        ((PresheafOfModules.pushforward
          (F := Over.forget ⊤) (𝟙 (X.ringCatSheaf.over ⊤).obj)).map
            (globalEquationHom D f hf)))
    rw [restrictGlobalEquationHom]
    exact equationHom_mem_W D ⊤ f hf
  exact Presheaf.W_of_coversTop p Y hY (fun _ => hlocal)

private lemma isIso_sheafification_map_globalEquationHom
    (D : CartierDivisor X) (f : Additive X.functionFieldˣ)
    (hf : IsEquationOn D ⊤ f) :
    IsIso ((PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).map
      (globalEquationHom D f hf)) := by
  apply Localization.inverts
    (PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj))
    ((_root_.Opens.grothendieckTopology X).W.inverseImage
      (PresheafOfModules.toPresheaf X.ringCatSheaf.obj))
  exact globalEquationHom_mem_W D f hf

/-- A global equation trivializes its associated sheaf. -/
noncomputable def globalEquationIso (D : CartierDivisor X)
    (f : Additive X.functionFieldˣ) (hf : IsEquationOn D ⊤ f) :
    SheafOfModules.unit X.ringCatSheaf ≅ associatedSheaf D :=
  ((asIso (PresheafOfModules.sheafificationAdjunction
    (𝟙 X.ringCatSheaf.obj)).counit).app
      (SheafOfModules.unit X.ringCatSheaf)).symm ≪≫
    @asIso _ _ _ _
      ((PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).map
        (globalEquationHom D f hf))
      (isIso_sheafification_map_globalEquationHom D f hf)

end CartierDivisor

end AlgebraicGeometry.Scheme
