/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.Phase.Transfer.Adjoint
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.Phase.Transfer.HN
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.Phase.Transfer.IndExtensions
import DerivedAlgGeo.CategoryTheory.Triangulated.CompactlyGenerated.Polishchuk

/-!
# Corollary A.23: inducing a slicing through Theorem A.17

Corollary A.23 of arXiv:2607.28411v1 produces a slicing on the source of a
functor `Φ` from a slicing on its target.  Its proof applies Theorem A.17 at
every real phase `φ`, to the Ind-extension `τ̂'_φ` (Definition A.22) of the
dual t-structure `τ'_φ = (𝒫(≥ φ), 𝒫(< φ + 1))` of the target slicing, and
then reads the resulting family of bounded t-structures through the
recognition formulas (A.8).  The repository already owns both ends of that
argument: `Polishchuk.induce` is Theorem A.17, and
`Slicing.InducedTStructures.preimageData` is the finite phase-truncation
argument that turns (A.8) into slicing data.  This file is the joint between
them; the Definition A.22 input is `Slicing.IndExtensions`.

## Main results

* `Slicing.IndExtensions.monad_isRightTExact`: assumption (v') of Corollary
  A.23, stated on semistable objects, implies assumption (v) of Theorem A.17
  at every phase: the monad is right t-exact for `τ̂'_φ`.  This is the step
  the paper summarizes as "(v') precisely corresponds to (v)".
* `Slicing.IndExtensions.nonempty_inducedTStructures`: Theorem A.17 at every
  phase assembles into the phase-indexed recognition formulas (A.8).
* `Slicing.IndExtensions.preimageData`: **Corollary A.23, without the
  S-local half**: the preimage collection (A.7) is a slicing.
* `Slicing.IndExtensions.mapsSemistableGE_iff`: assumption (v') is the
  bounded predicate `Slicing.MapsSemistableGE` of the monad restricted to
  `Q`, which `Slicing.MapsSemistableGE.of_mapsSemistableLE` produces from
  condition (3.2) of Proposition 3.8.

## Implementation notes

The large categories are `C` and `D`; the bounded ones are the full
subcategories `Q ⊆ D` and its inverse image `F⁻¹ Q ⊆ C`, so that hypothesis
(iv) of Theorem A.17 holds by construction, as in `Polishchuk.induce`.  The
slicing lives on `Q`, and the detecting functor of the output is
`ObjectProperty.inverseImageLift F Q`, the restriction of `F`.

Assumption (v') is `Slicing.IndExtensions.MapsSemistableAisle`, stated as the
paper states it, on semistable objects and in the large category.  Extending
it to `𝒫(≥ φ)` uses that the aisles `τ̂'_φ^{≤ 0}` decrease in `φ` and are
closed under extensions, and then right t-exactness follows because the aisle
is the coproduct-and-extension closure of `𝒫(≥ φ)` (Lemma A.14(i)) and the
monad preserves coproducts and triangles.

The source-side existence input of Theorem A.17, a t-structure on `C`
compactly generated by the left-adjoint image of some generators of `τ̂'_φ`,
is taken as the hypothesis `hsrc`, in the shape `Polishchuk.induce` consumes;
`Polishchuk.induceOfApproximation` and `induceOfBrown` show how the owned
Theorem A.13 constructions discharge it.

Assumption (i) of Theorem A.17, S-linearity of `Φ`, and the S-locality of the
input and output slicings are outside the categorical layer, as in
`Polishchuk.lean`; what is proved here is Corollary A.23 at `S = Spec ℤ`.

`w` is the coproduct-size universe and is the first universe parameter of
every declaration here, which is what `.{w}` binds.  Both categories share one
hom universe `v`, as `Polishchuk.induce` requires.

Nothing here is geometric.  Realizing `Slicing.IndExtensions` for the
standard slicings of `Dᵇ(Coh)` inside `Dqc`, and the adjunction `f_! ⊣ f^*`
on `Dqc`, are the remaining inputs of Proposition 3.8.

## References

* arXiv:2607.28411v1, Definition A.22, Corollary A.23, and the proof of
  Proposition 3.8.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open CategoryTheory.Triangulated

universe w v u₁ u₂

namespace CategoryTheory.Triangulated

variable {C : Type u₁} [Category.{v} C]
  {D : Type u₂} [Category.{v} D] [HasZeroObject D] [HasShift D ℤ]
  [Preadditive D] [∀ n : ℤ, (shiftFunctor D n).Additive] [Pretriangulated D]
  [IsTriangulated D]
  {Q : ObjectProperty D} [Q.IsTriangulated]

namespace Slicing.IndExtensions

variable {s : Slicing Q.FullSubcategory} (ind : s.IndExtensions.{w})

/-- Assumption (v') of Corollary A.23 is the bounded predicate
`Slicing.MapsSemistableGE` of the monad restricted to `Q`, whenever the
monad preserves `Q`.  For `f^* f_!` this is the reading of Proposition 3.8:
`f_!` preserves `Dᵇ(Coh)` when the relative dualizing complex is perfect, and
then `f^* f_! 𝒫(φ) ⊆ 𝒫̂(≥ φ)` is `f^* f_! 𝒫(φ) ⊆ 𝒫(≥ φ)`. -/
theorem mapsSemistableGE_iff {L : D ⥤ C} {F : C ⥤ D}
    (hQL : ∀ E : D, Q E → Q (F.obj (L.obj E))) :
    s.MapsSemistableGE (ObjectProperty.liftToInverseImage F Q L hQL ⋙
        ObjectProperty.inverseImageLift F Q) ↔
      ind.MapsSemistableAisle (L ⋙ F) :=
  forall_congr' fun φ => forall_congr' fun _ => imp_congr_right fun _ =>
    (ind.isLE_zero_iff_geProp φ _).symm

section Monad

variable {L : D ⥤ C} {F : C ⥤ D}
  [(L ⋙ F).Additive] [(L ⋙ F).CommShift ℤ] [(L ⋙ F).IsTriangulated]

/-- Assumption (v') of Corollary A.23 extends from semistable objects of
phase `φ` to all of `𝒫(≥ φ)`: the monad carries the HN filtration to a
Postnikov tower whose factors lie in aisles `τ̂'_ψ^{≤ 0} ⊆ τ̂'_φ^{≤ 0}` for
`ψ ≥ φ`, and aisles are closed under extensions. -/
theorem monad_isLE_zero_of_geProp (hv : ind.MapsSemistableAisle (L ⋙ F))
    {φ : ℝ} {E : Q.FullSubcategory} (hE : s.geProp _ φ E) :
    (ind.tStructure φ).IsLE ((L ⋙ F).obj E.obj) 0 := by
  rcases hE with hz | ⟨Fil, hn, hge⟩
  · exact (ind.tStructure φ).isLE_of_isZero ((L ⋙ F).map_isZero (Q.ι.map_isZero hz)) 0
  · have hfac : ∀ i, (ind.tStructure φ).le 0
        ((PostnikovTower.mapF Fil.toPostnikovTower (Q.ι ⋙ L ⋙ F)).factor i) := by
      intro i
      exact ind.le_zero_anti (hge.trans (Fil.phase_mem_range _ hn i).1) _
        (hv (Fil.φ i) (Fil.factor i) (Fil.semistable i)).le
    refine ⟨ExtensionClosure.le_of_closed (fun hz => ((ind.tStructure φ).isLE_of_isZero hz 0).le)
      le_rfl (fun hT hX hY => ((ind.tStructure φ).isLE₂ _ hT 0 ⟨hX⟩ ⟨hY⟩).le) _
      (ExtensionClosure.ofPostnikovTower _ hfac)⟩

/-- **Assumption (v') implies assumption (v).**  If the monad `L ⋙ F`
preserves coproducts and sends `𝒫(φ)` into `τ̂'_φ^{≤ 0}` for every `φ`, then
it is right t-exact for `τ̂'_φ`: the aisle is the coproduct-and-extension
closure of `𝒫(≥ φ)` by Lemma A.14(i), the monad carries that closure into
the closure of its image, and the image lies in the aisle by
`Slicing.IndExtensions.monad_isLE_zero_of_geProp`. -/
theorem monad_isRightTExact (hLF : (L ⋙ F).PreservesSmallCoproducts.{w})
    (hv : ind.MapsSemistableAisle (L ⋙ F)) (φ : ℝ) :
    (L ⋙ F).IsRightTExact (ind.tStructure φ) (ind.tStructure φ) :=
  (L ⋙ F).isRightTExact_of_isLE_zero fun X hX => by
    have hX' : (TStructure.boundedAisle Q
        ((s.phaseShift _ φ).toDualTStructure _)).coprodClosure.{w} X := by
      rw [← (ind.indExtensionData φ).largeAisle]
      exact hX.le
    have hmap := (TStructure.boundedAisle Q
      ((s.phaseShift _ φ).toDualTStructure _)).coprodClosure_map_obj (L ⋙ F) hLF hX'
    have hgen : (TStructure.boundedAisle Q
        ((s.phaseShift _ φ).toDualTStructure _)).map (L ⋙ F) ≤ (ind.tStructure φ).le 0 := by
      rintro Z ⟨Y, ⟨X', hX', ⟨eι⟩⟩, ⟨eLF⟩⟩
      haveI : (ind.tStructure φ).IsLE ((L ⋙ F).obj (Q.ι.obj X')) 0 :=
        ind.monad_isLE_zero_of_geProp hv
          ((s.phaseShift_toDualTStructure_isLE_zero_iff _ φ X').1 ⟨hX'⟩)
      exact ((ind.tStructure φ).isLE_of_iso (((L ⋙ F).mapIso eι).trans eLF) 0).le
    rw [(ind.indExtensionData φ).largeAisle] at hgen
    refine ⟨?_⟩
    rw [(ind.indExtensionData φ).largeAisle]
    exact ObjectProperty.coprodClosure_le _ hgen _ hmap

end Monad

section Induce

variable [HasZeroObject C] [HasShift C ℤ] [Preadditive C]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] [Q.IsClosedUnderIsomorphisms]
  {L : D ⥤ C} {F : C ⥤ D} [L.CommShift ℤ] [L.IsTriangulated]
  [F.Additive] [F.CommShift ℤ] [F.IsTriangulated]

/-- **Theorem A.17 at every phase.**  Under the hypotheses of Theorem A.17
with `Φ = F`, hypothesis (iv) built in as `P = F⁻¹ Q`, and assumption (v')
of Corollary A.23 in place of (v), the induced bounded t-structures on
`F⁻¹ Q` satisfy the recognition formulas (A.8) for the slicing on `Q`.  The
source-side input `hsrc` is Theorem A.13 on `C` for the left-adjoint image of
one generating family of each `τ̂'_φ`, the shape `Polishchuk.induce`
consumes. -/
theorem nonempty_inducedTStructures (adj : L ⊣ F) (hF : F.PreservesSmallCoproducts.{w})
    (hsrc : ∀ φ : ℝ, ∃ (G : ObjectProperty D) (tC : TStructure C),
      (ind.tStructure φ).IsCompactlyGeneratedBy.{w} G ∧
        tC.IsCompactlyGeneratedBy.{w} (G.map L))
    (hzero : ∀ E : C, Q (F.obj E) → IsZero (F.obj E) → IsZero E)
    (hv : ind.MapsSemistableAisle (L ⋙ F)) :
    Nonempty (s.InducedTStructures (ObjectProperty.inverseImageLift F Q)) := by
  have hL : L.PreservesSmallCoproducts.{w} := fun ι ↦ by
    haveI : PreservesColimitsOfShape (Discrete ι) L :=
      adj.leftAdjoint_preservesColimits.preservesColimitsOfShape
    infer_instance
  have hLF : (L ⋙ F).PreservesSmallCoproducts.{w} := fun ι ↦ by
    haveI := hL ι
    haveI := hF ι
    infer_instance
  have hdata : ∀ φ : ℝ, Nonempty (Polishchuk.InducedTStructureData F (Q.inverseImage F) Q
      (ind.tStructure φ) (fun _ ↦ Iff.rfl)) := by
    intro φ
    obtain ⟨G, tC, hG, htC⟩ := hsrc φ
    exact ⟨Polishchuk.induce adj hF hG htC (ind.monad_isRightTExact hLF hv φ) hzero
      (ind.tStructure_isBounded φ)⟩
  refine ⟨{ tStructure := fun φ => (hdata φ).some.tStructure
            le_zero_iff := fun φ E => ?_
            ge_one_iff := fun φ E => ?_ }⟩
  · exact ((hdata φ).some.isLE_iff E 0).trans
      ((Q.tStructure_isLE_iff (ind.tStructure φ) _ 0).trans (ind.isLE_zero_iff_geProp φ _))
  · exact ((hdata φ).some.isGE_iff E 1).trans
      ((Q.tStructure_isGE_iff (ind.tStructure φ) _ 1).trans (ind.isGE_one_iff_ltProp φ _))

/-- **Corollary A.23 of arXiv:2607.28411v1, without the S-local half.**  The
preimage collection (A.7), `𝒫_X(φ) = {E | F E ∈ 𝒫(φ)}` on `F⁻¹ Q`, is a
slicing: the phase-indexed t-structures of
`Slicing.IndExtensions.nonempty_inducedTStructures` supply Hom-vanishing and,
through the finite phase-truncation argument
`Slicing.InducedTStructures.preimageData`, HN filtrations.  The slicing itself
is `s.preimage (ObjectProperty.inverseImageLift F Q)` at this witness. -/
theorem preimageData [IsTriangulated C] (adj : L ⊣ F) (hF : F.PreservesSmallCoproducts.{w})
    (hsrc : ∀ φ : ℝ, ∃ (G : ObjectProperty D) (tC : TStructure C),
      (ind.tStructure φ).IsCompactlyGeneratedBy.{w} G ∧
        tC.IsCompactlyGeneratedBy.{w} (G.map L))
    (hzero : ∀ E : C, Q (F.obj E) → IsZero (F.obj E) → IsZero E)
    (hv : ind.MapsSemistableAisle (L ⋙ F)) :
    s.PreimageData (ObjectProperty.inverseImageLift F Q) :=
  (ind.nonempty_inducedTStructures adj hF hsrc hzero hv).elim fun h => h.preimageData

end Induce

end Slicing.IndExtensions

end CategoryTheory.Triangulated
