/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Linear.Adjunction
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.MassHom.Generator
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.Phase.Transfer.Metric

/-!
# Transfer of mass--Hom bounds

Let `G : C ⥤ D` detect a preimage stability condition and let `L ⊣ G` be a
linear adjunction.  A mass--Hom bound for a test object `A : D` transfers to
`L.obj A`: the adjunction identifies `Hom(LA, F)` with `Hom(A, GF)`, while
`stabilityMass_preimage` identifies the two masses.

Consequently, a bound on a target test class `T` transfers to the essential
image `T.map L` and then, by thick closure, to every source test class contained
in `(T.map L).triangEnvelope`.  The generation comparison is deliberately an
explicit hypothesis: the abstract theorem neither supplies a geometric
generator nor assumes that `L` preserves one.

This is the categorical core of arXiv:2607.28411v1, Lemma 7.4.  Its finite and
faithfully-flat geometric realizations are separate consumers.
-/

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open CategoryTheory.Triangulated
open CategoryTheory.SerreFunctor

namespace CategoryTheory.Triangulated.StabilityCondition.WithClassMap

noncomputable section

universe w v₁ u₁ v₂ u₂ u'

variable {k : Type w} [Field k]
variable {C : Type u₁} [Category.{v₁} C] [Preadditive C] [Linear k C]
  [HasZeroObject C] [HasShift C ℤ]
  [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C] [IsTriangulated C] [HomFinite k C]
variable {D : Type u₂} [Category.{v₂} D] [Preadditive D] [Linear k D]
  [HasZeroObject D] [HasShift D ℤ]
  [∀ n : ℤ, (shiftFunctor D n).Additive]
  [Pretriangulated D] [IsTriangulated D] [HomFinite k D]
variable {Λ : Type u'} [AddCommGroup Λ] {v₀ : K₀ D →+ Λ}
variable {G : C ⥤ D} [G.Additive] [G.CommShift ℤ] [G.IsTriangulated]
variable {L : D ⥤ C} [L.Additive] [L.Linear k]
variable {σ : StabilityCondition.WithClassMap D v₀}
variable {T : ObjectProperty D} {T' : ObjectProperty C}

namespace HasMassHomBoundFor

/-- An objectwise mass--Hom bound transfers across a linear left adjoint.

No conservativity hypothesis is needed here.  The supplied `PreimageData`
already says that the preimage slicing is a genuine slicing, and the proof uses
only the adjunction on Hom spaces and the exact mass identity. -/
theorem preimage_obj {A : D} (hA : σ.HasMassHomBoundFor (k := k) A)
    (adj : L ⊣ G) (hpre : σ.slicing.PreimageData G) :
    (σ.preimage G hpre).HasMassHomBoundFor (k := k) (L.obj A) := by
  obtain ⟨K, hK, hbound⟩ := hA
  refine ⟨K, hK, fun F ↦ ?_⟩
  have hdim := (adj.homLinearEquiv (R := k) A F).finrank_eq
  have hdimR :
      (Module.finrank k (L.obj A ⟶ F) : ℝ) =
        (Module.finrank k (A ⟶ G.obj F) : ℝ) := by
    exact_mod_cast hdim
  rw [hdimR, stabilityMass_preimage]
  exact hbound (G.obj F)

end HasMassHomBoundFor

namespace HasMassHomBound

/-- A mass--Hom bound transfers to the essential image of the test class under
the linear left adjoint. -/
theorem preimage_map (h : σ.HasMassHomBound (k := k) T)
    (adj : L ⊣ G) (hpre : σ.slicing.PreimageData G) :
    (σ.preimage G hpre).HasMassHomBound (k := k) (T.map L) := by
  rintro A ⟨B, hB, ⟨e⟩⟩
  exact (HasMassHomBoundFor.preimage_obj (h B hB) adj hpre).congr e

section Generator

variable [∀ n : ℤ, (shiftFunctor C n).Linear k]

/-- Transfer a mass--Hom bound to a source test class generated by the
left-adjoint images of the bounded target tests.

The containment `T' ≤ (T.map L).triangEnvelope` is the exact generation input.
Geometric applications may instantiate `T` and `T'` by perfect complexes, but
that comparison is not asserted by this categorical theorem. -/
theorem preimage (h : σ.HasMassHomBound (k := k) T)
    (adj : L ⊣ G) (hpre : σ.slicing.PreimageData G)
    (hgen : T' ≤ (T.map L).triangEnvelope) :
    (σ.preimage G hpre).HasMassHomBound (k := k) T' :=
  ((h.preimage_map adj hpre).triangEnvelope (T.map L)).anti hgen

end Generator

end HasMassHomBound

end

end CategoryTheory.Triangulated.StabilityCondition.WithClassMap
