/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Foundation.Deformation.DeformedPredicate
import DerivedAlgGeo.CategoryTheory.Triangulated.ExtensionClosure

/-!
# Extension-closed cuts of the owner deformed predicate

The provisional `Q(>t)`, `Q(≤t)`, and `Q(<t)` subcategories are the extension
closures generated by owner deformed slices on the corresponding side of a
phase cutoff.  Their order laws are independent of hom-vanishing and HN
existence, so they can be owned before the final slicing is assembled.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open scoped ENNReal

universe u v u'

namespace CategoryTheory.Triangulated

open Deformation

variable (C : Type u) [Category.{v} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
variable {Λ : Type u'} [AddCommGroup Λ] {κ : K₀ C →+ Λ}

namespace StabilityCondition.WithClassMap

/-- Generators of the provisional owner cut `Q(>t)`. -/
def deformedGtGen (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    (ε t : ℝ) : ObjectProperty C :=
  fun E => ∃ ψ, t < ψ ∧ σ.deformedPred C W hr0 hr1 hW ε ψ E

/-- Generators of the provisional owner cut `Q(≤t)`. -/
def deformedLeGen (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    (ε t : ℝ) : ObjectProperty C :=
  fun E => ∃ ψ, ψ ≤ t ∧ σ.deformedPred C W hr0 hr1 hW ε ψ E

/-- Generators of the provisional owner cut `Q(<t)`. -/
def deformedLtGen (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    (ε t : ℝ) : ObjectProperty C :=
  fun E => ∃ ψ, ψ < t ∧ σ.deformedPred C W hr0 hr1 hW ε ψ E

/-- The provisional owner cut `Q(>t)`. -/
def deformedGtPred (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    (ε t : ℝ) : ObjectProperty C :=
  ExtensionClosure (σ.deformedGtGen C W hr0 hr1 hW ε t)

/-- The provisional owner cut `Q(≤t)`. -/
def deformedLePred (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    (ε t : ℝ) : ObjectProperty C :=
  ExtensionClosure (σ.deformedLeGen C W hr0 hr1 hW ε t)

/-- The provisional owner cut `Q(<t)`. -/
def deformedLtPred (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    (ε t : ℝ) : ObjectProperty C :=
  ExtensionClosure (σ.deformedLtGen C W hr0 hr1 hW ε t)

/-- Provisional `Q(≤t)` is monotone in the cutoff. -/
theorem deformedLePred_mono
    (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    {ε t₁ t₂ : ℝ} (ht : t₁ ≤ t₂) :
    σ.deformedLePred C W hr0 hr1 hW ε t₁ ≤
      σ.deformedLePred C W hr0 hr1 hW ε t₂ :=
  ExtensionClosure.mono
    (fun _ ⟨ψ, hψ, hP⟩ => ⟨ψ, hψ.trans ht, hP⟩)

/-- Provisional `Q(<t)` is monotone in the cutoff. -/
theorem deformedLtPred_mono
    (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    {ε t₁ t₂ : ℝ} (ht : t₁ ≤ t₂) :
    σ.deformedLtPred C W hr0 hr1 hW ε t₁ ≤
      σ.deformedLtPred C W hr0 hr1 hW ε t₂ :=
  ExtensionClosure.mono
    (fun _ ⟨ψ, hψ, hP⟩ => ⟨ψ, hψ.trans_le ht, hP⟩)

/-- Every provisional `Q(<t)` object belongs to `Q(≤t)`. -/
theorem deformedLePred_of_deformedLtPred
    (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    {ε t : ℝ} :
    σ.deformedLtPred C W hr0 hr1 hW ε t ≤
      σ.deformedLePred C W hr0 hr1 hW ε t :=
  ExtensionClosure.mono
    (fun _ ⟨ψ, hψ, hP⟩ => ⟨ψ, hψ.le, hP⟩)

/-- Provisional `Q(>t)` is antitone in the cutoff. -/
theorem deformedGtPred_anti
    (σ : StabilityCondition.WithClassMap C κ)
    (W : Λ →+ ℂ) {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hW : stabilitySeminorm C σ (W - σ.Z) ≤ ENNReal.ofReal r)
    {ε t₁ t₂ : ℝ} (ht : t₁ ≤ t₂) :
    σ.deformedGtPred C W hr0 hr1 hW ε t₂ ≤
      σ.deformedGtPred C W hr0 hr1 hW ε t₁ :=
  ExtensionClosure.mono
    (fun _ ⟨ψ, hψ, hP⟩ => ⟨ψ, ht.trans_lt hψ, hP⟩)

end StabilityCondition.WithClassMap

end CategoryTheory.Triangulated
