/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Foundation.Deformation.SlicingDistance
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Foundation.Deformation.StabilitySeminorm

/-!
# The owner topology on stability conditions

This module defines the standard small neighborhoods combining stability-
seminorm control of the charge with intrinsic slicing-distance control, then
generates the repository-owned stability-space topology from them.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open scoped ENNReal Topology

universe u v u'

namespace CategoryTheory.Triangulated.Deformation

variable (C : Type u) [Category.{v} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
variable {Λ : Type u'} [AddCommGroup Λ] {κ : K₀ C →+ Λ}

/-- The basic `ε`-neighborhood of an owner stability condition. -/
def basisNhd (σ : StabilityCondition.WithClassMap C κ) (ε : ℝ) :
    Set (StabilityCondition.WithClassMap C κ) :=
  {τ | stabilitySeminorm C σ (τ.Z - σ.Z) <
      ENNReal.ofReal (Real.sin (Real.pi * ε)) ∧
    slicingDist C σ.slicing τ.slicing < ENNReal.ofReal ε}

/-- Membership in a basic owner neighborhood separates into charge and phase
control. -/
theorem mem_basisNhd_iff (σ τ : StabilityCondition.WithClassMap C κ) (ε : ℝ) :
    τ ∈ basisNhd C σ ε ↔
      stabilitySeminorm C σ (τ.Z - σ.Z) <
          ENNReal.ofReal (Real.sin (Real.pi * ε)) ∧
        slicingDist C σ.slicing τ.slicing < ENNReal.ofReal ε :=
  Iff.rfl

/-- Every owner stability condition belongs to each positive basic
neighborhood of radius below one. -/
theorem self_mem_basisNhd (σ : StabilityCondition.WithClassMap C κ) {ε : ℝ}
    (hε : 0 < ε) (hε_one : ε < 1) : σ ∈ basisNhd C σ ε := by
  rw [mem_basisNhd_iff]
  constructor
  · rw [sub_self, stabilitySeminorm_zero]
    exact ENNReal.ofReal_pos.mpr (Real.sin_pos_of_pos_of_lt_pi
      (mul_pos Real.pi_pos hε) (by nlinarith [Real.pi_pos]))
  · rw [slicingDist_self]
    exact ENNReal.ofReal_pos.mpr hε

/-- The owner topology on stability conditions, generated by basic
neighborhoods of radii in `(0, 1/8)`. -/
instance StabilityCondition.WithClassMap.topologicalSpace :
    TopologicalSpace (StabilityCondition.WithClassMap C κ) :=
  TopologicalSpace.generateFrom
    {U | ∃ (σ : StabilityCondition.WithClassMap C κ) (ε : ℝ),
      0 < ε ∧ ε < 1 / 8 ∧ U = basisNhd C σ ε}

/-- The generating family used by the owner stability topology. -/
theorem basisNhd_isOpen_generator (σ : StabilityCondition.WithClassMap C κ) {ε : ℝ}
    (hε : 0 < ε) (hε_eighth : ε < 1 / 8) : IsOpen (basisNhd C σ ε) := by
  apply TopologicalSpace.GenerateOpen.basic
  exact ⟨σ, ε, hε, hε_eighth, rfl⟩

end CategoryTheory.Triangulated.Deformation
