/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Symmetry.GLTilde.Basic

/-!
# The integer fibre of the lifted matrix projection

The algebraic fibre calculation underlying the universal-cover construction.

**Proved here:** `ker (toMatHom) ≃* Multiplicative ℤ`, generated by the deck
transformations `φ ↦ φ + 2n`. Every element of `G̃L⁺(2, ℝ)` lying over the
identity matrix is one of these, and distinct `n` give distinct elements.

**Proved in the companion files:**

* **Surjectivity of `toMatHom`.** Not proved *here* — landed separately in
  `WeakStabilityCondition/StabilityCondition/Symmetry/GLTilde/Covering/Surjectivity.lean`, which writes the lift down in closed form rather than
  invoking covering-space machinery.
* **Simple connectedness.** Landed separately in `WeakStabilityCondition/StabilityCondition/Symmetry/GLTilde/Covering/SourceTopology.lean`, using
  global contractible coordinates rather than a computation of `π₁(S¹)`.
* **Covering-map property.** Landed in `WeakStabilityCondition/StabilityCondition/Symmetry/GLTilde/Covering/Map.lean`, by conjugating the
  projection in global coordinates to the standard exponential cover
  `ℝ → S¹` times an identity map.

## Why the kernel is exactly `2ℤ` and not `ℤ`

Bridgeland's phase convention puts the circle at `ℝ / 2ℤ`: `rayVec φ` is the
ray at angle `π φ`, so `φ ↦ φ + 1` is the *antipodal* map (`rayVec_add_one`),
and only `φ ↦ φ + 2` returns a ray to itself. A normalized shift over the
identity matrix must therefore move phases by an even integer.

The group is still `ℤ` — `n ↦ (φ ↦ φ + 2n)` — but the factor of two is
Bridgeland's convention showing through, not an accident, and it is why
`deckShift` is defined with `2 * n` rather than `n`.
-/

namespace CategoryTheory.Triangulated.StabilityCondition.GroupAction

open Matrix Real

/-! ## When two phases give the same ray -/

/-- `rayVec` identifies exactly the phases differing by an even integer.

This is the statement that the phase line covers the circle of rays with deck
group `2ℤ`, in elementary form and with no covering-space machinery. -/
theorem rayVec_eq_iff (φ ψ : ℝ) : rayVec φ = rayVec ψ ↔ ∃ n : ℤ, φ = ψ + 2 * n := by
  constructor
  · intro h
    have hc : Real.cos (π * φ) = Real.cos (π * ψ) := congrFun h 0
    have hs : Real.sin (π * φ) = Real.sin (π * ψ) := congrFun h 1
    -- `cos (a - b) = 1` collapses the pair of equations into one, and
    -- `Real.cos_eq_one_iff` is then exactly the periodicity statement.
    have hcos1 : Real.cos (π * φ - π * ψ) = 1 := by
      rw [Real.cos_sub, hc, hs]
      nlinarith [Real.sin_sq_add_cos_sq (π * ψ)]
    obtain ⟨n, hn⟩ := (Real.cos_eq_one_iff _).mp hcos1
    exact ⟨n, by
      have hπ : (π : ℝ) ≠ 0 := Real.pi_ne_zero
      field_simp at hn ⊢
      nlinarith [hn]⟩
  · rintro ⟨n, rfl⟩
    ext i
    have hre : π * (ψ + 2 * n) = π * ψ + n * (2 * π) := by ring
    fin_cases i <;>
      simp only [rayVec, hre, Real.cos_add_int_mul_two_pi, Real.sin_add_int_mul_two_pi]

/-- On the unit circle `OnRay` is equality: both vectors have norm one, so the
positive scalar is forced to be `1`. -/
theorem rayVec_eq_of_onRay {φ ψ : ℝ} (h : OnRay (rayVec φ) (rayVec ψ)) :
    rayVec φ = rayVec ψ := by
  obtain ⟨r, hr, hveq⟩ := h
  have hc : Real.cos (π * φ) = r * Real.cos (π * ψ) := by
    have := congrFun hveq 0; simpa [rayVec] using this
  have hs : Real.sin (π * φ) = r * Real.sin (π * ψ) := by
    have := congrFun hveq 1; simpa [rayVec] using this
  have hpφ := Real.sin_sq_add_cos_sq (π * φ)
  have hpψ := Real.sin_sq_add_cos_sq (π * ψ)
  -- Squaring and adding kills the trigonometry: `1 = r² · 1`.
  have hsq : r ^ 2 = 1 := by
    have h1 : Real.sin (π * φ) ^ 2 = r ^ 2 * Real.sin (π * ψ) ^ 2 := by rw [hs]; ring
    have h2 : Real.cos (π * φ) ^ 2 = r ^ 2 * Real.cos (π * ψ) ^ 2 := by rw [hc]; ring
    nlinarith [hpφ, hpψ, h1, h2]
  have hr1 : r = 1 := by
    have hfac : (r - 1) * (r + 1) = 0 := by nlinarith [hsq]
    rcases mul_eq_zero.mp hfac with h | h <;> linarith
  rw [hveq, hr1, one_smul]

/-! ## The deck transformations -/

/-- The deck transformation `φ ↦ φ + 2n`, as a normalized shift.

`2 * n`, not `n`: only an even shift of phase returns every ray to itself. See
the module docstring. -/
def deckShift (n : ℤ) : NormalizedShift where
  toOrderIso := OrderIso.addRight (2 * n : ℝ)
  map_add_one φ := by simp [OrderIso.addRight]; ring

@[simp] theorem deckShift_apply (n : ℤ) (φ : ℝ) :
    (deckShift n).toOrderIso φ = φ + 2 * n := rfl

/-- A deck transformation is compatible with the identity matrix: it moves
every ray back onto itself. -/
theorem compat_one_deckShift (n : ℤ) : Compatible 1 (deckShift n) := by
  intro φ
  simp only [toMat_one, Matrix.one_mulVec, deckShift_apply]
  rw [(rayVec_eq_iff (φ + 2 * n) φ).mpr ⟨n, rfl⟩]
  exact OnRay.refl _

/-- The deck transformation as an element of `G̃L⁺(2, ℝ)`. -/
noncomputable def deck (n : ℤ) : GLTilde :=
  ⟨1, deckShift n, compat_one_deckShift n⟩

@[simp] theorem deck_mat (n : ℤ) : (deck n).mat = 1 := rfl
@[simp] theorem deck_shift (n : ℤ) : (deck n).shift = deckShift n := rfl

/-! ## Everything over the identity is a deck transformation

The one analytic step. A normalized shift lying over `1` moves each phase by
*some* even integer; the content is that it is the **same** integer for every
phase, which is connectedness of `ℝ` and nothing else. -/

/-- A continuous integer-valued function on `ℝ` is constant.

Proved by the intermediate value theorem rather than by a local-constancy
argument: if two values differed, `g` would have to pass through the
half-integer between them. -/
private theorem const_of_intValued {g : ℝ → ℝ} (hg : Continuous g)
    (hint : ∀ φ, ∃ n : ℤ, g φ = n) (a b : ℝ) : g a = g b := by
  -- A value of `g` is never a half-integer.
  have hhalf : ∀ (m : ℤ) (ψ : ℝ), g ψ ≠ (m : ℝ) + 1 / 2 := by
    intro m ψ h
    obtain ⟨k, hk⟩ := hint ψ
    rw [hk] at h
    have hcast : ((2 * k : ℤ) : ℝ) = ((2 * m + 1 : ℤ) : ℝ) := by push_cast; linarith
    have : (2 * k : ℤ) = 2 * m + 1 := by exact_mod_cast hcast
    omega
  -- On any interval, the endpoints agree.
  have step : ∀ u w : ℝ, u ≤ w → g u = g w := by
    intro u w huw
    by_contra hne
    obtain ⟨m, hm⟩ := hint u
    obtain ⟨k, hk⟩ := hint w
    have hmk : (m : ℝ) ≠ (k : ℝ) := by rw [← hm, ← hk]; exact hne
    have hcontOn : ContinuousOn g (Set.Icc u w) := hg.continuousOn
    rcases lt_or_gt_of_ne hmk with hlt | hlt
    · -- `g u < g w`: the half-integer above `g u` is caught by the IVT.
      have hle : (m : ℝ) + 1 / 2 ≤ (k : ℝ) := by
        have : m < k := by exact_mod_cast hlt
        have : (m : ℝ) + 1 ≤ (k : ℝ) := by exact_mod_cast this
        linarith
      have hmem : (m : ℝ) + 1 / 2 ∈ Set.Icc (g u) (g w) := by
        rw [hm, hk]; constructor <;> linarith
      obtain ⟨ψ, _, hψ⟩ := intermediate_value_Icc huw hcontOn hmem
      exact hhalf m ψ hψ
    · -- `g w < g u`: same, with the decreasing form of the IVT.
      have hle : (k : ℝ) + 1 / 2 ≤ (m : ℝ) := by
        have : k < m := by exact_mod_cast hlt
        have : (k : ℝ) + 1 ≤ (m : ℝ) := by exact_mod_cast this
        linarith
      have hmem : (k : ℝ) + 1 / 2 ∈ Set.Icc (g w) (g u) := by
        rw [hm, hk]; constructor <;> linarith
      obtain ⟨ψ, _, hψ⟩ := intermediate_value_Icc' huw hcontOn hmem
      exact hhalf k ψ hψ
  rcases le_total a b with h | h
  · exact step a b h
  · exact (step b a h).symm

/-- **Everything lying over the identity matrix is a deck transformation.** -/
theorem exists_deckShift_of_mat_eq_one (x : GLTilde) (hx : x.mat = 1) :
    ∃ n : ℤ, x.shift = deckShift n := by
  set f := x.shift.toOrderIso with hf
  -- Each phase moves by *some* even integer.
  have hstep : ∀ φ : ℝ, ∃ n : ℤ, f φ = φ + 2 * n := by
    intro φ
    have hcompat := x.compat φ
    rw [hx, toMat_one, Matrix.one_mulVec] at hcompat
    have := rayVec_eq_of_onRay hcompat
    obtain ⟨n, hn⟩ := (rayVec_eq_iff φ (f φ)).mp this
    exact ⟨-n, by push_cast; linarith⟩
  -- The same integer for every phase, because `ℝ` is connected.
  have hcont : Continuous fun φ : ℝ => (f φ - φ) / 2 :=
    ((f.continuous).sub continuous_id).div_const 2
  have hint : ∀ φ : ℝ, ∃ n : ℤ, (f φ - φ) / 2 = (n : ℝ) := by
    intro φ; obtain ⟨n, hn⟩ := hstep φ; exact ⟨n, by rw [hn]; ring⟩
  obtain ⟨n, hn⟩ := hint 0
  refine ⟨n, ?_⟩
  ext φ
  have := const_of_intValued hcont hint φ 0
  rw [hn] at this
  have : f φ - φ = 2 * n := by linarith [this]
  simp only [deckShift_apply, ← hf]
  linarith

/-! ## The fibre, as a group -/

/-- The deck transformations, as a homomorphism from `ℤ`. -/
noncomputable def deckHom : Multiplicative ℤ →* GLTilde where
  toFun n := deck (Multiplicative.toAdd n)
  map_one' := by
    refine GLTilde.ext' rfl ?_
    ext φ
    simp [deck, GLTilde.one_shift]
  map_mul' m n := by
    refine GLTilde.ext' (by simp [deck]) ?_
    ext φ
    simp [deck, GLTilde.mul_shift]
    ring

theorem deckHom_injective : Function.Injective deckHom := by
  intro m n h
  have h0 := congrArg (fun x : GLTilde => x.shift.toOrderIso 0) h
  simp only [deckHom, MonoidHom.coe_mk, OneHom.coe_mk, deck_shift, deckShift_apply,
    zero_add] at h0
  have hz : ((Multiplicative.toAdd m : ℤ) : ℝ) = ((Multiplicative.toAdd n : ℤ) : ℝ) := by
    linarith
  exact Multiplicative.toAdd.injective (by exact_mod_cast hz)

/-- **The fibre of the projection is exactly `ℤ`.**

`deckHom` is injective with range the kernel of `toMatHom`, so the subgroup of
`G̃L⁺(2, ℝ)` lying over the identity matrix is infinite cyclic. -/
theorem range_deckHom_eq_ker : deckHom.range = GLTilde.toMatHom.ker := by
  ext x
  simp only [MonoidHom.mem_range, MonoidHom.mem_ker]
  constructor
  · rintro ⟨n, rfl⟩
    rfl
  · intro hx
    have hmat : x.mat = 1 := hx
    obtain ⟨n, hn⟩ := exists_deckShift_of_mat_eq_one x hmat
    exact ⟨Multiplicative.ofAdd n, GLTilde.ext' hmat.symm hn.symm⟩

/-- **The kernel of the projection, as an explicit `ℤ`.**

The fibre over the identity is infinite cyclic, generated by `deck 1`. -/
noncomputable def kerEquiv : Multiplicative ℤ ≃* GLTilde.toMatHom.ker :=
  (MonoidHom.ofInjective deckHom_injective).trans
    (MulEquiv.subgroupCongr range_deckHom_eq_ker)

end CategoryTheory.Triangulated.StabilityCondition.GroupAction
