/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.BaseChangeSequence

/-!
# The source quasicoherent sequence of a compact source sequence

Theorem 3.17 of arXiv:1902.08184 starts from a strong semiorthogonal component
`𝒟 ⊆ Dᵇ(X)` and works throughout with its quasicoherent companion
`𝒟qc ⊆ Dqc(X)`. Every theorem in the base-change layer so far takes that
companion as an input `A : SemiorthogonalSequence (SourceDqc X) ι`, and carries
three standing hypotheses about it: triangulated components, repleteness, and
closure under coproducts in the scheme universe.

This file removes all three for the sequence the paper actually uses. Given a
semiorthogonal sequence of *compact* source components -- the perfect side --
closing each component under coproducts and extensions produces the source
sequence, and the three hypotheses become theorems. `BaseChangeCategory.lean`
named this construction as one of the remaining layers of Theorem 3.17.

The geometry is in the other direction, and is not proved here. Recovering the
compact part of the closure as the original component is compact generation:
`Dqc.PerfectObjectsAreCompactInDqc` is the repository's name for the comparison
that would identify these compact objects with perfect complexes, and it is
deliberately uninhabited. Only the inclusion that is formal is recorded -- a
compact component sits inside the perfect part of its own closure.
-/

noncomputable section

attribute [local instance] HasDerivedCategory.standard

namespace AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange

open CategoryTheory CategoryTheory.Triangulated AlgebraicGeometry

universe u w

variable {S : Scheme.{u}} {X : SchemeBaseChange S}
  {ι : Type w} [Preorder ι]
  (A : SemiorthogonalSequence (SourceDqc X) ι)
  (hcompact : ∀ i, A.component i ≤ ObjectProperty.compactObjects.{u})

/-- The source quasicoherent sequence `𝒟qc`, generated by a semiorthogonal
sequence of compact source components.

Semiorthogonality of the closure is not assumed: it follows from
semiorthogonality of the compact components, because compactness carries
Hom-vanishing across the coproducts being adjoined. -/
def sourceQuasicoherentSequence : SemiorthogonalSequence (SourceDqc X) ι :=
  A.coprodClosure hcompact

@[simp]
theorem sourceQuasicoherentSequence_component (i : ι) :
    (sourceQuasicoherentSequence A hcompact).component i =
      (A.component i).coprodClosure.{u} :=
  rfl

/-- Triangulated components, the first of the three standing hypotheses. -/
theorem sourceQuasicoherentSequence_hasTriangulatedComponents
    (hA : A.HasTriangulatedComponents) :
    (sourceQuasicoherentSequence A hcompact).HasTriangulatedComponents :=
  A.coprodClosure_hasTriangulatedComponents hcompact hA

/-- Repleteness, the second standing hypothesis, with no input at all. -/
theorem sourceQuasicoherentSequence_isClosedUnderIsomorphisms (i : ι) :
    ((sourceQuasicoherentSequence A hcompact).component i).IsClosedUnderIsomorphisms :=
  A.coprodClosure_isClosedUnderIsomorphisms hcompact i

/-- Closure under coproducts in the scheme universe, the third standing
hypothesis, with no input at all. -/
theorem sourceQuasicoherentSequence_isClosedUnderColimitsOfShape
    (i : ι) (κ : Type u) :
    ((sourceQuasicoherentSequence A hcompact).component i).IsClosedUnderColimitsOfShape
      (Discrete κ) :=
  A.coprodClosure_isClosedUnderColimitsOfShape hcompact i κ

/-- A compact source component lies in the perfect part of its own closure.

The reverse inclusion -- that the closure adjoins no new compact objects -- is
compact generation, and is a geometric input rather than a consequence. -/
theorem le_sourcePerfectPart_sourceQuasicoherentSequence (i : ι) :
    A.component i ≤
      sourcePerfectPart X ((sourceQuasicoherentSequence A hcompact).component i) :=
  le_inf (A.le_coprodClosure_component hcompact i) (hcompact i)

end AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange
