/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Dqc
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.Scheme
import DerivedAlgGeo.CategoryTheory.Triangulated.CompactlyGenerated

/-!
# Base-change components of scheme-derived categories

This file starts the construction of the categories `D_T` and `(Dqc)_T` from
Section 3 of arXiv:1902.08184v4 without imposing a Noetherian hypothesis on
`T` or on the fibre product `X_T`.

If `X` and `T` are schemes over `S`, their product in `Over S` is the ordinary
fibre product `X_T`.  A source component is represented by an object property
`P` in `Dqc(X)`.  Its perfect part is the intersection with the canonical
compact-object property.  Given the geometric external-product functor on
those compact factors, the paper's construction is then expressed by the
existing object-property closure operators:

1. take the triangulated envelope of the external products in `Dqc(X_T)`;
2. take its coproduct-and-extension closure to obtain `(Dqc)_T`;
3. restrict `(Dqc)_T` to the intrinsic bounded-coherent cohomology locus to
   obtain `D_T`.

The use of compact objects is deliberate.  Under the quasi-compact affine-
diagonal hypotheses of Proposition 3.15 they are the perfect complexes, while
the repository's current `SchemePerfectDerivedCategory` is built from
`D(Coh -)` and therefore requires local Noetherianity.  Using it for `T` would
silently strengthen Theorem 3.17.  The eventual compact-equals-perfect theorem
will identify this construction with the paper's notation rather than change
its carrier.

No new category hierarchy is introduced: every category below is an
abbreviation for `ObjectProperty.FullSubcategory`.  The external-product
functor is still an explicit input.  Constructing it from derived pullback and
tensor, proving that its triangulated envelope remains compact, constructing
the source `Dqc` component from a strong semiorthogonal component of
`Dᵇ(X)`, and proving pullback/pushforward functoriality are the next layers of
Theorem 3.17.

## Main definitions

* `SchemeBaseChange.CompactDqcFiber`: compact objects of `Dqc` on a base
  change;
* `SchemeBaseChange.sourcePerfectPart`: the compact part of a source
  component;
* `SchemeBaseChange.perfectBaseChangeGenerators` and
  `perfectBaseChangeEnvelope`: the external-product construction;
* `SchemeBaseChange.quasicoherentBaseChangeComponent` and
  `QuasicoherentBaseChangeCategory`: `(Dqc)_T`;
* `SchemeBaseChange.boundedBaseChangeComponent` and
  `BoundedBaseChangeCategory`: `D_T`.

## Reference

* arXiv:1902.08184v4, Proposition 3.15, Theorem 3.17, and Lemma 3.18.
-/

attribute [local instance] HasDerivedCategory.standard

namespace AlgebraicGeometry.DerivedCategory.Families

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open CategoryTheory.Triangulated AlgebraicGeometry

noncomputable section

universe u

namespace SchemeBaseChange

variable {S : Scheme.{u}}

/-- The compact objects of `Dqc(T)`.  Under the quasi-compact affine-diagonal
hypotheses in Section 3 these are the perfect complexes.  This formulation is
available without assuming that `T` is locally Noetherian. -/
abbrev CompactDqcFiber (T : SchemeBaseChange S) :=
  (ObjectProperty.compactObjects.{u}
    (C := Dqc.SchemeQuasicoherentDerivedCategory T.left)).FullSubcategory

/-- The perfect part of a source quasi-coherent component: its intersection
with the compact objects of `Dqc(X)`. -/
def sourcePerfectPart (X : SchemeBaseChange S)
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left)) :
    ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left) :=
  P ⊓ ObjectProperty.compactObjects.{u}

/-- The full compact part of a source quasi-coherent component. -/
abbrev SourcePerfectPartCategory (X : SchemeBaseChange S)
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left)) :=
  (sourcePerfectPart X P).FullSubcategory

variable (X T : SchemeBaseChange S)

/-- The objects `φ'^* F ⊗ g'^* G` which generate the perfect base-change
component in Proposition 3.15.  The curried functor is the geometric external
product on the compact part of the source component and the compact objects
of `Dqc(T)`. -/
def perfectBaseChangeGenerators
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)) :
    ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left) :=
  fun E ↦ ∃ (F : SourcePerfectPartCategory X P),
    ∃ (G : CompactDqcFiber T), Nonempty ((externalProduct.obj F).obj G ≅ E)

/-- The triangulated envelope generated by the perfect external products in
`Dqc(X_T)`.  The later compactness theorem identifies this envelope with the
paper's subcategory of `Perf(X_T)`. -/
def perfectBaseChangeEnvelope
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)) :
    ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left) :=
  (perfectBaseChangeGenerators X T P externalProduct).triangEnvelope

/-- The full subcategory cut out by `perfectBaseChangeEnvelope`. -/
abbrev PerfectBaseChangeEnvelopeCategory
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)) :=
  (perfectBaseChangeEnvelope X T P externalProduct).FullSubcategory

/-- The quasi-coherent base-change component `(Dqc)_T`: the
coproduct-and-extension closure of the perfect base-change envelope. -/
def quasicoherentBaseChangeComponent
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)) :
    ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left) :=
  (perfectBaseChangeEnvelope X T P externalProduct).coprodClosure.{u}

/-- The full quasi-coherent base-change category `(Dqc)_T`. -/
abbrev QuasicoherentBaseChangeCategory
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)) :=
  (quasicoherentBaseChangeComponent X T P externalProduct).FullSubcategory

/-- The intrinsic bounded-coherent locus on `X_T`, included in `Dqc(X_T)`.
Unlike `Dᵇ(Coh X_T)`, this category is defined without assuming `X_T`
locally Noetherian. -/
abbrev boundedCoherentFiberToDqc :
    Dqc.SchemeBoundedCoherentDqcCategory (X ⨯ T).left ⥤
      Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left :=
  Dqc.SchemeBoundedCoherentDqcCategory.ι (X ⨯ T).left

/-- The bounded base-change component `D_T`, defined as the inverse image of
`(Dqc)_T` in the intrinsic bounded-coherent locus of `Dqc(X_T)`. -/
def boundedBaseChangeComponent
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)) :
    ObjectProperty (Dqc.SchemeBoundedCoherentDqcCategory (X ⨯ T).left) :=
  (quasicoherentBaseChangeComponent X T P externalProduct).inverseImage
    (boundedCoherentFiberToDqc X T)

/-- The full bounded base-change category `D_T`. -/
abbrev BoundedBaseChangeCategory
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)) :=
  (boundedBaseChangeComponent X T P externalProduct).FullSubcategory

/-- The perfect part is contained in the source quasi-coherent component. -/
theorem sourcePerfectPart_le
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left)) :
    sourcePerfectPart X P ≤ P :=
  inf_le_left

/-- The perfect part consists of compact objects. -/
theorem sourcePerfectPart_le_compact
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left)) :
    sourcePerfectPart X P ≤ ObjectProperty.compactObjects.{u} :=
  inf_le_right

/-- Every external-product generator belongs to the perfect base-change
envelope. -/
theorem perfectBaseChangeGenerators_le_envelope
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)) :
    perfectBaseChangeGenerators X T P externalProduct ≤
      perfectBaseChangeEnvelope X T P externalProduct :=
  ObjectProperty.le_triangEnvelope _

/-- Universal property of the perfect envelope: any thick triangulated
property containing the external-product generators contains the envelope. -/
theorem perfectBaseChangeEnvelope_le
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left))
    {Q : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)}
    [Q.IsStableUnderRetracts] [Q.IsTriangulated]
    (h : perfectBaseChangeGenerators X T P externalProduct ≤ Q) :
    perfectBaseChangeEnvelope X T P externalProduct ≤ Q :=
  (ObjectProperty.triangEnvelope_le_iff
    (P := perfectBaseChangeGenerators X T P externalProduct) (Q := Q)).2 h

/-- Universal property of the quasi-coherent construction: any property
closed under isomorphisms, `Type u`-indexed coproducts, and extensions which
contains the perfect envelope contains `(Dqc)_T`. -/
theorem quasicoherentBaseChangeComponent_le
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left))
    {Q : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)}
    [Q.IsClosedUnderIsomorphisms]
    [∀ (ι : Type u), Q.IsClosedUnderColimitsOfShape (Discrete ι)]
    [Q.IsTriangulatedClosed₂]
    (h : perfectBaseChangeEnvelope X T P externalProduct ≤ Q) :
    quasicoherentBaseChangeComponent X T P externalProduct ≤ Q :=
  (perfectBaseChangeEnvelope X T P externalProduct).coprodClosure_le h

/-- The perfect base-change envelope lies in its quasi-coherent companion. -/
theorem perfectBaseChangeEnvelope_le_quasicoherent
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left)) :
    perfectBaseChangeEnvelope X T P externalProduct ≤
      quasicoherentBaseChangeComponent X T P externalProduct :=
  (perfectBaseChangeEnvelope X T P externalProduct).le_coprodClosure

/-- Membership in `D_T` is definitionally membership of the intrinsic
bounded-coherent object's image in `(Dqc)_T`. -/
theorem mem_boundedBaseChangeComponent_iff
    (P : ObjectProperty (Dqc.SchemeQuasicoherentDerivedCategory X.left))
    (externalProduct : SourcePerfectPartCategory X P ⥤
      (CompactDqcFiber T ⥤
        Dqc.SchemeQuasicoherentDerivedCategory (X ⨯ T).left))
    (E : Dqc.SchemeBoundedCoherentDqcCategory (X ⨯ T).left) :
    boundedBaseChangeComponent X T P externalProduct E ↔
      quasicoherentBaseChangeComponent X T P externalProduct
        ((boundedCoherentFiberToDqc X T).obj E) :=
  Iff.rfl

end SchemeBaseChange

end


end AlgebraicGeometry.DerivedCategory.Families
