/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.BaseChangeSLinearity
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.KFlatBaseChangeFunctors
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.OpensBaseChange
import DerivedAlgGeo.CategoryTheory.Triangulated.TStructure.Local

/-!
# `S`-local t-structures on a base-change category

Section 4 of arXiv:1902.08184 calls a t-structure on `𝒟` **`S`-local** when
every quasi-compact open `U ⊆ S` carries a t-structure on `𝒟_U` making
restriction t-exact. `TStructure/Local.lean` supplies the one-functor half of
that sentence -- `RestrictsAlong` -- and observes that the restricted
t-structure is determined by its aisle. This file takes the quantifier.

Three things make the quantifier cheap to state.

* `𝒟` is already a base-change category. It is `𝒟_S` at `identityBaseChange S`,
  the terminal object of `Over S`, so no separate source category is needed and
  restriction is an ordinary base-change pullback.
* An open is already an object of `Over S`, by `opensBaseChange`.
* Base change is already functorial in the index, by
  `KFlatBaseChangeData.quasicoherentPullback`.

What is *not* cheap, and is therefore an explicit input, is the base-change data
over each open. The repository's base change consumes bundled K-flat
resolutions, not just a morphism, so a family of them is what `S`-locality has
to quantify over; `OpenRestrictionFamily` is that family, and it carries the
restriction functors with it rather than deriving them.

Nothing here is inhabited. `IsSLocal` says a supplied family restricts the
t-structure everywhere; it does not construct the family, the restricted
t-structures, or any inhabitant of the definition. Remark A.20 -- every bounded
t-structure on `Dᵇ(X)` is `S`-local over an affine base -- is the first
inhabitant #1061 asks for and is not proved here.
-/

noncomputable section

attribute [local instance] HasDerivedCategory.standard

namespace AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange

open CategoryTheory CategoryTheory.Triangulated AlgebraicGeometry
open AlgebraicGeometry.DerivedCategory.Families

universe u

variable {S : Scheme.{u}}

/-- The restriction data `S`-locality quantifies over.

For each quasi-compact open of the base: a base change of `X` to it, and a
restriction functor from the base-change category over `S` itself. The functor
is carried rather than derived, because deriving it needs a derived pullback and
the component-preservation statement that `quasicoherentPullback` consumes, and
both are geometry. -/
structure OpenRestrictionFamily (X : SchemeBaseChange S)
    (P : ObjectProperty (SourceDqc X)) [P.ContainsZero]
    (DS : KFlatBaseChangeData X (identityBaseChange S)) where
  /-- The base change of `X` to each quasi-compact open of the base. -/
  data (U : S.Opens) (hU : CompactSpace U.toScheme) :
    KFlatBaseChangeData X (opensBaseChange U)
  /-- Restriction from the base to that open. -/
  restriction (U : S.Opens) (hU : CompactSpace U.toScheme) :
    DS.QuasicoherentCategory P ⥤ (data U hU).QuasicoherentCategory P

namespace OpenRestrictionFamily

variable {X : SchemeBaseChange S} {P : ObjectProperty (SourceDqc X)}
  [P.ContainsZero] {DS : KFlatBaseChangeData X (identityBaseChange S)}

/-- **`S`-locality** (§4 of arXiv:1902.08184): the t-structure restricts along
the restriction to every quasi-compact open of the base.

This is `TStructure.RestrictsAlong` quantified over the family. The t-structures
on the `𝒟_U` are existential here rather than chosen, which is the paper's
statement; Remark 4.6(1) is what makes that harmless, since
`TStructure.ext_le` pins each of them once its aisle is. -/
def IsSLocal (R : OpenRestrictionFamily X P DS)
    (t : TStructure (DS.QuasicoherentCategory P)) : Prop :=
  ∀ (U : S.Opens) (hU : CompactSpace U.toScheme),
    t.RestrictsAlong (R.restriction U hU)

/-- The chosen form: a restriction of the t-structure at every quasi-compact
open, rather than the bare existence of one. -/
structure SLocalData (R : OpenRestrictionFamily X P DS)
    (t : TStructure (DS.QuasicoherentCategory P)) where
  /-- The restricted t-structure over each quasi-compact open. -/
  restriction (U : S.Opens) (hU : CompactSpace U.toScheme) :
    t.Restriction (R.restriction U hU)

namespace SLocalData

variable {R : OpenRestrictionFamily X P DS}
  {t : TStructure (DS.QuasicoherentCategory P)}

/-- Chosen restrictions witness `S`-locality. -/
theorem isSLocal (L : SLocalData R t) : R.IsSLocal t :=
  fun U hU ↦ (L.restriction U hU).restrictsAlong

/-- Two choices of `S`-local data agree at an open as soon as their aisles do.

This is Remark 4.6(1) with its geometric half left visible: what pins the aisle
of the restricted t-structure is that `𝒟_U` is generated by the image of `𝒟`,
which is a generation theorem about base change and is not proved here. -/
theorem tStructure_eq_of_le_eq (L₁ L₂ : SLocalData R t)
    (U : S.Opens) (hU : CompactSpace U.toScheme)
    (hle : (L₁.restriction U hU).tStructure.le =
      (L₂.restriction U hU).tStructure.le) :
    (L₁.restriction U hU).tStructure = (L₂.restriction U hU).tStructure :=
  TStructure.ext_le hle

end SLocalData

end OpenRestrictionFamily

end AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange
