/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.Topology.Sheaves.Cech.BasisComparison
import Mathlib.CategoryTheory.Sites.SheafCohomology.MayerVietoris
import Mathlib.Topology.Sheaves.MayerVietoris

/-!
# Cohomological boundedness from a finite acyclic open cover

A nonempty list of opens is `IntersectionAcyclic` when the coefficient sheaf
has vanishing positive local cohomology on every nonempty intersection of
members of the list. Repeated Mayer--Vietoris then bounds the cohomology of
their union by the length of the list.
-/

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace

namespace CategoryTheory.Sheaf

variable {X : TopCat.{u}}

set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 4000000
set_option maxRecDepth 10000

/-- The union of a finite list of opens. -/
def opensUnion : List (Opens X) → Opens X :=
  List.foldr (· ⊔ ·) ⊥

@[simp] lemma opensUnion_nil : opensUnion ([] : List (Opens X)) = ⊥ := rfl

@[simp] lemma opensUnion_cons (U : Opens X) (L : List (Opens X)) :
    opensUnion (U :: L) = U ⊔ opensUnion L := rfl

@[simp] lemma inf_opensUnion (U : Opens X) (L : List (Opens X)) :
    U ⊓ opensUnion L = opensUnion (L.map (U ⊓ ·)) := by
  induction L with
  | nil => simp
  | cons V L ih => simp only [opensUnion_cons, List.map_cons, inf_sup_left, ih]

private noncomputable abbrev localHPrime
    (hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X))
    (F : TopCat.Sheaf AddCommGrpCat.{u} X) (n : ℕ) (U : Opens X) : Type (u + 1) :=
  @Sheaf.H' (Opens X) _ (Opens.grothendieckTopology X) _ hExt F n U

/-- Positive local cohomology vanishes on every nonempty intersection generated by a list.

For `U :: L`, besides acyclicity on `U` and on intersections generated by `L`, the third field
records acyclicity on intersections which also contain `U`. -/
inductive IntersectionAcyclic
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    (hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X)) :
    List (Opens X) → Prop
  | nil : IntersectionAcyclic F hExt []
  | cons (U : Opens X) (L : List (Opens X))
      (head : ∀ (n : ℕ), 0 < n → Subsingleton (localHPrime hExt F n U))
      (tail : IntersectionAcyclic F hExt L)
      (intersections : IntersectionAcyclic F hExt (L.map (U ⊓ ·))) :
      IntersectionAcyclic F hExt (U :: L)

set_option maxHeartbeats 1600000 in
/-- A union of `m` opens with acyclic nonempty intersections has no cohomology in degrees
`n ≥ m`.  This is the finite-cover Mayer--Vietoris bound. -/
theorem HPrime_subsingleton_opensUnion_of_intersectionAcyclic
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    [hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X)]
    {L : List (Opens X)} (hL : IntersectionAcyclic F hExt L)
    (hne : L ≠ []) (n : ℕ) (hn : L.length ≤ n) :
    Subsingleton (localHPrime hExt F n (opensUnion L)) := by
  induction hL generalizing n with
  | nil => exact (hne rfl).elim
  | cons U L hU hL hUL ihL ihUL =>
      have hnCons : L.length + 1 ≤ n := by
        simpa only [List.length_cons] using hn
      by_cases hnil : L = []
      · subst L
        simpa using hU n (by omega)
      · let S := Opens.mayerVietorisSquare U (opensUnion L)
        have hnpos : 0 < n := by
          have : 2 ≤ (U :: L).length := by
            cases L with
            | nil => contradiction
            | cons => simp
          omega
        have hnTail : L.length ≤ n := by omega
        have hnInter : (L.map (U ⊓ ·)).length ≤ n - 1 := by
          simp only [List.length_map]
          omega
        letI : Subsingleton (localHPrime hExt F n U) := hU n hnpos
        letI : Subsingleton (localHPrime hExt F n (opensUnion L)) := ihL hnil n hnTail
        letI : Subsingleton (localHPrime hExt F (n - 1) (U ⊓ opensUnion L)) := by
          rw [inf_opensUnion]
          exact ihUL (by
            cases L with
            | nil => contradiction
            | cons => simp) (n - 1) hnInter
        let seq :=
          @GrothendieckTopology.MayerVietorisSquare.sequence
            (Opens X) _ (Opens.grothendieckTopology X) _ _ hExt
            S F (n - 1) n (by omega)
        have hseq : seq.Exact :=
          @GrothendieckTopology.MayerVietorisSquare.sequence_exact
            (Opens X) _ (Opens.grothendieckTopology X) _ _ hExt
            S F (n - 1) n (by omega)
        have hall (x : localHPrime hExt F n (opensUnion (U :: L))) : x = 0 := by
          change localHPrime hExt F n S.X₄ at x
          let A : AddCommGrpCat.{u + 1} :=
            @Sheaf.H' (Opens X) _ (Opens.grothendieckTopology X) _ hExt F n S.X₂
          let B : AddCommGrpCat.{u + 1} :=
            @Sheaf.H' (Opens X) _ (Opens.grothendieckTopology X) _ hExt F n S.X₃
          have hx : (@GrothendieckTopology.MayerVietorisSquare.toBiprod
              (Opens X) _ (Opens.grothendieckTopology X) _ _ hExt S F n) x = 0 := by
            rw [@GrothendieckTopology.MayerVietorisSquare.toBiprod_apply
              (Opens X) _ (Opens.grothendieckTopology X) _ _ hExt S F n x]
            change (AddCommGrpCat.biprodIsoProd A B).inv _ = 0
            apply (AddCommGrpCat.biprodIsoProd A B).addCommGroupIsoToAddEquiv.injective
            simp only [map_zero]
            ext
            · change (_ : localHPrime hExt F n U) = _
              exact Subsingleton.elim _ _
            · change (_ : localHPrime hExt F n (opensUnion L)) = _
              exact Subsingleton.elim _ _
          obtain ⟨y, hy⟩ := (ShortComplex.ab_exact_iff
            (seq.sc hseq.toIsComplex 2)).mp
              (hseq.exact 2) x hx
          have hy₀ : y = 0 := by
            change localHPrime hExt F (n - 1) (U ⊓ opensUnion L) at y
            exact Subsingleton.elim y 0
          rw [hy₀, map_zero] at hy
          exact hy.symm
        exact ⟨fun x y ↦ (hall x).trans (hall y).symm⟩

end CategoryTheory.Sheaf
