/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.Algebra.Module.LocalizedModule.Submodule
import Mathlib.RingTheory.Localization.BaseChange

/-!
# Finite module descent through localization

A finite module over a localized ring is obtained by extending scalars from
the finite base-ring submodule generated by a chosen finite set of localized
generators. Over a Noetherian base that submodule is finitely presented.

These are module-level object lifts. They do not descend a complex, a map of
complexes, or a bounded-coherent semiorthogonal component.
-/

open Submodule
open scoped TensorProduct

noncomputable section

/-- A finite module over a localization has a finite base-ring submodule
whose scalar extension is the original module. -/
theorem Module.exists_finite_submodule_of_isLocalization
    {R A N : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (S : Submonoid R) [IsLocalization S A]
    [AddCommGroup N] [Module R N] [Module A N] [IsScalarTower R A N]
    [Module.Finite A N] :
    ∃ L : Submodule R N, Module.Finite R L ∧
      Nonempty (A ⊗[R] L ≃ₗ[A] N) := by
  letI : IsLocalizedModule S (LinearMap.id : N →ₗ[R] N) :=
    isLocalizedModule_id (S := S) N A
  obtain ⟨s, hs⟩ := (Module.Finite.fg_top (R := A) (M := N))
  let L : Submodule R N := Submodule.span R (s : Set N)
  have hfinite : Module.Finite R L :=
    Module.Finite.of_fg (Submodule.fg_span s.finite_toSet)
  have hloc : L.localized' A S (LinearMap.id : N →ₗ[R] N) = ⊤ := by
    rw [Submodule.localized'_eq_span]
    apply top_unique
    calc
      ⊤ = Submodule.span A (s : Set N) := hs.symm
      _ ≤ Submodule.span A ((LinearMap.id : N →ₗ[R] N) '' L) :=
        Submodule.span_mono (by
          intro x hx
          exact ⟨x, Submodule.subset_span hx, rfl⟩)
  let f : L →ₗ[R] N := L.subtype
  haveI hf : IsLocalizedModule S f := by
    constructor
    · exact IsLocalizedModule.map_units (LinearMap.id : N →ₗ[R] N)
    · intro n
      have hn : n ∈ L.localized' A S (LinearMap.id : N →ₗ[R] N) := by
        rw [hloc]
        trivial
      obtain ⟨m, hm, t, hmt⟩ := hn
      refine ⟨(⟨m, hm⟩, t), ?_⟩
      change t • n = m
      rw [← hmt, IsLocalizedModule.mk'_cancel']
      rfl
    · intro x y hxy
      refine ⟨1, ?_⟩
      have : x = y := Subtype.ext hxy
      simp [this]
  exact ⟨L, hfinite, ⟨(IsLocalizedModule.isBaseChange S A f).equiv⟩⟩

/-- Over a Noetherian base ring the descended finite submodule is finitely presented. -/
theorem Module.exists_finitely_presented_submodule_of_isLocalization
    {R A N : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (S : Submonoid R) [IsLocalization S A] [IsNoetherianRing R]
    [AddCommGroup N] [Module R N] [Module A N] [IsScalarTower R A N]
    [Module.Finite A N] :
    ∃ L : Submodule R N, Module.FinitePresentation R L ∧
      Nonempty (A ⊗[R] L ≃ₗ[A] N) := by
  obtain ⟨L, hL, e⟩ :=
    Module.exists_finite_submodule_of_isLocalization (R := R) (A := A) (N := N) S
  letI : Module.Finite R L := hL
  exact ⟨L, Module.finitePresentation_of_finite R L, e⟩
