/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.Algebra.Module.LocalizedModule.Submodule
import Mathlib.RingTheory.Localization.BaseChange

/-!
# Finite module descent through localization

A finite module over a localized ring is obtained by extending scalars from
the finite base-ring submodule generated by a chosen finite set of localized
generators. Over a Noetherian base that submodule is finitely presented.

These are module-level object lifts and closure steps for one or two arrows.
They do not descend a complex, a map of complexes, or a bounded-coherent
semiorthogonal component.
-/

open Submodule
open scoped TensorProduct

noncomputable section

/-- A finite module over a localization has a finite base-ring submodule
whose scalar extension is the original module. -/
theorem Module.exists_finite_submodule_of_isLocalization
    {R A N : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (S : Submonoid R) [IsLocalization S A]
    [AddCommGroup N] [Module R N] [Module A N] [IsScalarTower R A N]
    [Module.Finite A N] :
    ∃ L : Submodule R N, Module.Finite R L ∧
      IsLocalizedModule S L.subtype ∧
      Nonempty (A ⊗[R] L ≃ₗ[A] N) := by
  letI : IsLocalizedModule S (LinearMap.id : N →ₗ[R] N) :=
    isLocalizedModule_id (S := S) N A
  obtain ⟨s, hs⟩ := (Module.Finite.fg_top (R := A) (M := N))
  let L : Submodule R N := Submodule.span R (s : Set N)
  have hfinite : Module.Finite R L :=
    Module.Finite.of_fg (Submodule.fg_span s.finite_toSet)
  have hloc : L.localized' A S (LinearMap.id : N →ₗ[R] N) = ⊤ := by
    rw [Submodule.localized'_eq_span]
    apply top_unique
    calc
      ⊤ = Submodule.span A (s : Set N) := hs.symm
      _ ≤ Submodule.span A ((LinearMap.id : N →ₗ[R] N) '' L) :=
        Submodule.span_mono (by
          intro x hx
          exact ⟨x, Submodule.subset_span hx, rfl⟩)
  let f : L →ₗ[R] N := L.subtype
  haveI hf : IsLocalizedModule S f := by
    constructor
    · exact IsLocalizedModule.map_units (LinearMap.id : N →ₗ[R] N)
    · intro n
      have hn : n ∈ L.localized' A S (LinearMap.id : N →ₗ[R] N) := by
        rw [hloc]
        trivial
      obtain ⟨m, hm, t, hmt⟩ := hn
      refine ⟨(⟨m, hm⟩, t), ?_⟩
      change t • n = m
      rw [← hmt, IsLocalizedModule.mk'_cancel']
      rfl
    · intro x y hxy
      refine ⟨1, ?_⟩
      have : x = y := Subtype.ext hxy
      simp [this]
  exact ⟨L, hfinite, hf, ⟨(IsLocalizedModule.isBaseChange S A f).equiv⟩⟩

/-- Over a Noetherian base ring the descended finite submodule is finitely presented. -/
theorem Module.exists_finitely_presented_submodule_of_isLocalization
    {R A N : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (S : Submonoid R) [IsLocalization S A] [IsNoetherianRing R]
    [AddCommGroup N] [Module R N] [Module A N] [IsScalarTower R A N]
    [Module.Finite A N] :
    ∃ L : Submodule R N, Module.FinitePresentation R L ∧
      IsLocalizedModule S L.subtype ∧
      Nonempty (A ⊗[R] L ≃ₗ[A] N) := by
  obtain ⟨L, hL, hloc, e⟩ :=
    Module.exists_finite_submodule_of_isLocalization (R := R) (A := A) (N := N) S
  letI : Module.Finite R L := hL
  exact ⟨L, Module.finitePresentation_of_finite R L, hloc, e⟩

/-- The finite descent witness can be chosen to contain any prescribed finite
base-ring submodule. This permits adjoining images of a differential before
descending the next term of a bounded complex. -/
theorem Module.exists_finite_submodule_of_isLocalization_containing
    {R A N : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (S : Submonoid R) [IsLocalization S A]
    [AddCommGroup N] [Module R N] [Module A N] [IsScalarTower R A N]
    [Module.Finite A N] (F : Submodule R N) [Module.Finite R F] :
    ∃ L : Submodule R N, F ≤ L ∧ Module.Finite R L ∧
      IsLocalizedModule S L.subtype := by
  obtain ⟨L₀, hL₀, hloc₀, _⟩ :=
    Module.exists_finite_submodule_of_isLocalization (R := R) (A := A) (N := N) S
  let L : Submodule R N := F ⊔ L₀
  letI : Module.Finite R L₀ := hL₀
  have hfinite : Module.Finite R L := inferInstance
  have hloc : IsLocalizedModule S L.subtype := by
    constructor
    · exact hloc₀.map_units
    · intro n
      obtain ⟨⟨x, s⟩, hx⟩ := hloc₀.surj n
      exact ⟨(⟨x.1, (le_sup_right : L₀ ≤ L) x.2⟩, s), hx⟩
    · intro x y hxy
      refine ⟨1, ?_⟩
      have : x = y := Subtype.ext hxy
      simp [this]
  exact ⟨L, le_sup_left, hfinite, hloc⟩

/-- Over a Noetherian base, the prescribed-set descent witness is finitely
presented as well as finite. -/
theorem Module.exists_finitely_presented_submodule_of_isLocalization_containing
    {R A N : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (S : Submonoid R) [IsLocalization S A] [IsNoetherianRing R]
    [AddCommGroup N] [Module R N] [Module A N] [IsScalarTower R A N]
    [Module.Finite A N] (F : Submodule R N) [Module.Finite R F] :
    ∃ L : Submodule R N, F ≤ L ∧ Module.FinitePresentation R L ∧
      IsLocalizedModule S L.subtype := by
  obtain ⟨L, hFL, hL, hloc⟩ :=
    Module.exists_finite_submodule_of_isLocalization_containing
      (R := R) (A := A) (N := N) S F
  letI : Module.Finite R L := hL
  exact ⟨L, hFL, Module.finitePresentation_of_finite R L, hloc⟩

/-- A map between finite modules over a localization has finite base-ring
submodules on both sides that localize back to the given modules and are
closed under that map. This is the one-arrow step toward descending a
bounded complex; no complex or component descent is asserted here. -/
theorem Module.exists_finite_submodules_of_isLocalization_map
    {R A M N : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (S : Submonoid R) [IsLocalization S A]
    [AddCommGroup M] [Module R M] [Module A M] [IsScalarTower R A M]
    [AddCommGroup N] [Module R N] [Module A N] [IsScalarTower R A N]
    [Module.Finite A M] [Module.Finite A N] (f : M →ₗ[A] N) :
    ∃ (L : Submodule R M) (K : Submodule R N),
      Module.Finite R L ∧ Module.Finite R K ∧
      IsLocalizedModule S L.subtype ∧ IsLocalizedModule S K.subtype ∧
      L.map (f.restrictScalars R) ≤ K := by
  obtain ⟨L, hL, hloc, _⟩ :=
    Module.exists_finite_submodule_of_isLocalization (R := R) (A := A) (N := M) S
  letI : Module.Finite R L := hL
  let F : Submodule R N := L.map (f.restrictScalars R)
  letI : Module.Finite R F := inferInstance
  obtain ⟨K, hFK, hK, hKloc⟩ :=
    Module.exists_finite_submodule_of_isLocalization_containing
      (R := R) (A := A) (N := N) S F
  exact ⟨L, K, hL, hK, hloc, hKloc, hFK⟩

/-- Three finite modules over a localization admit finite base-ring submodules
that localize back to them and are simultaneously closed under two consecutive
arrows. The theorem supplies submodules and closure only. A zero-composite
hypothesis on the original arrows must be supplied and checked on the restricted
arrows before these data form a complex. -/
theorem Module.exists_finite_submodules_of_isLocalization_two_maps
    {R A M₀ M₁ M₂ : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (S : Submonoid R) [IsLocalization S A]
    [AddCommGroup M₀] [Module R M₀] [Module A M₀] [IsScalarTower R A M₀]
    [AddCommGroup M₁] [Module R M₁] [Module A M₁] [IsScalarTower R A M₁]
    [AddCommGroup M₂] [Module R M₂] [Module A M₂] [IsScalarTower R A M₂]
    [Module.Finite A M₀] [Module.Finite A M₁] [Module.Finite A M₂]
    (f₀ : M₀ →ₗ[A] M₁) (f₁ : M₁ →ₗ[A] M₂) :
    ∃ (L₀ : Submodule R M₀) (L₁ : Submodule R M₁) (L₂ : Submodule R M₂),
      Module.Finite R L₀ ∧ Module.Finite R L₁ ∧ Module.Finite R L₂ ∧
      IsLocalizedModule S L₀.subtype ∧ IsLocalizedModule S L₁.subtype ∧
      IsLocalizedModule S L₂.subtype ∧
      L₀.map (f₀.restrictScalars R) ≤ L₁ ∧
      L₁.map (f₁.restrictScalars R) ≤ L₂ := by
  obtain ⟨L₀, hL₀, hloc₀, _⟩ :=
    Module.exists_finite_submodule_of_isLocalization (R := R) (A := A) (N := M₀) S
  letI : Module.Finite R L₀ := hL₀
  let F₁ : Submodule R M₁ := L₀.map (f₀.restrictScalars R)
  letI : Module.Finite R F₁ := inferInstance
  obtain ⟨L₁, hF₁, hL₁, hloc₁⟩ :=
    Module.exists_finite_submodule_of_isLocalization_containing
      (R := R) (A := A) (N := M₁) S F₁
  letI : Module.Finite R L₁ := hL₁
  let F₂ : Submodule R M₂ := L₁.map (f₁.restrictScalars R)
  letI : Module.Finite R F₂ := inferInstance
  obtain ⟨L₂, hF₂, hL₂, hloc₂⟩ :=
    Module.exists_finite_submodule_of_isLocalization_containing
      (R := R) (A := A) (N := M₂) S F₂
  exact ⟨L₀, L₁, L₂, hL₀, hL₁, hL₂, hloc₀, hloc₁, hloc₂, hF₁, hF₂⟩
