/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Metric.Distance.Separation
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.StabilityCondition.Foundation.Deformation.ConnectedComponent
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Bounds
import Mathlib.Topology.EMetricSpace.Defs
import MathFormalContract

/-!
# Topology induced by the full stability distance

This file is the topology-comparison part of Bridgeland's Proposition 8.1.
There is already a topology on `StabilityCondition.WithClassMap C v`: the
Section 6 topology generated by `basisNhd`.  Consequently it would be unsafe
to install a raw `EMetricSpace` whose inherited topology might be a second,
merely propositionally equal instance.

The constructor below instead uses
`PseudoEMetricSpace.ofEDistOfTopology`.  Its input is precisely the remaining
interface at this layer: full-distance balls form a neighbourhood basis for
the *existing* Section 6 topology.  The completed mass-subadditivity module
later inhabits that interface as `stabilityDistanceTopologyCompatible`.
Mathlib then constructs the compatible
uniformity while retaining that topology definitionally.  No metric instance
is installed by either module.

The first part of the file records elimination lemmas for a strict full-
distance bound.  They feed the **easy** direction only —
`exists_stabilityDist_ball_subset_basisNhd`.  The hard direction,
`exists_basisNhd_subset_stabilityDist_ball`, goes through
`phiPlus_sub_lt_of_slicingDist`
(`WeakStabilityCondition/StabilityCondition/Foundation/Deformation/SlicingDistance.lean`) and
`abs_log_mass_ratio_le_of_mem_basisNhd`, and touches none of them.
-/

open CategoryTheory.Triangulated
open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open CategoryTheory.Triangulated CategoryTheory.Triangulated.Deformation
open scoped ENNReal Topology

namespace CategoryTheory.Triangulated

noncomputable section

universe w u u'

variable {C : Type u} [Category.{w} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
  [IsTriangulated C]
variable {Λ : Type u'} [AddCommGroup Λ] {v : K₀ C →+ Λ}

omit [IsTriangulated C] in
/-- A strict full-distance bound controls the positive intrinsic phase of
every nonzero object. -/
theorem abs_phiPlus_sub_lt_of_stabilityDist
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} (hE : ¬IsZero E)
    {ε : ℝ} (hε : 0 < ε)
    (hd : stabilityDist σ τ < ENNReal.ofReal ε) :
    |σ.slicing.phiPlus C E hE - τ.slicing.phiPlus C E hE| < ε := by
  have hcoord : phiPlusDist σ τ E hE < ENNReal.ofReal ε :=
    lt_of_le_of_lt (phiPlusDist_le_stabilityDist σ τ E hE) hd
  exact (ENNReal.ofReal_lt_ofReal_iff hε).mp (by
    simpa [phiPlusDist] using hcoord)

omit [IsTriangulated C] in
/-- A strict full-distance bound controls the negative intrinsic phase of
every nonzero object. -/
theorem abs_phiMinus_sub_lt_of_stabilityDist
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} (hE : ¬IsZero E)
    {ε : ℝ} (hε : 0 < ε)
    (hd : stabilityDist σ τ < ENNReal.ofReal ε) :
    |σ.slicing.phiMinus C E hE - τ.slicing.phiMinus C E hE| < ε := by
  have hcoord : phiMinusDist σ τ E hE < ENNReal.ofReal ε :=
    lt_of_le_of_lt (phiMinusDist_le_stabilityDist σ τ E hE) hd
  exact (ENNReal.ofReal_lt_ofReal_iff hε).mp (by
    simpa [phiMinusDist] using hcoord)

/-- A strict full-distance bound controls the literal logarithmic mass ratio
of every nonzero object. -/
theorem abs_log_mass_ratio_lt_of_stabilityDist
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} (hE : ¬IsZero E)
    {ε : ℝ} (hε : 0 < ε)
    (hd : stabilityDist σ τ < ENNReal.ofReal ε) :
    |Real.log ((stabilityMass τ E).toReal /
      (stabilityMass σ E).toReal)| < ε := by
  have hcoord : massDist σ τ E < ENNReal.ofReal ε :=
    lt_of_le_of_lt (massDist_le_stabilityDist σ τ E hE) hd
  rw [massDist_eq_abs_log_ratio σ τ E hE] at hcoord
  exact (ENNReal.ofReal_lt_ofReal_iff hε).mp hcoord

/-- Exponential form of the mass-coordinate bound. -/
theorem exp_neg_lt_mass_ratio_and_lt_exp_of_stabilityDist
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} (hE : ¬IsZero E)
    {ε : ℝ} (hε : 0 < ε)
    (hd : stabilityDist σ τ < ENNReal.ofReal ε) :
    Real.exp (-ε) < (stabilityMass τ E).toReal /
        (stabilityMass σ E).toReal ∧
      (stabilityMass τ E).toReal /
        (stabilityMass σ E).toReal < Real.exp ε := by
  have hlog := abs_log_mass_ratio_lt_of_stabilityDist σ τ hE hε hd
  rw [abs_lt] at hlog
  have hratio : 0 < (stabilityMass τ E).toReal /
      (stabilityMass σ E).toReal :=
    div_pos (stabilityMass_toReal_pos τ hE) (stabilityMass_toReal_pos σ hE)
  constructor
  · calc
      Real.exp (-ε)
          < Real.exp (Real.log ((stabilityMass τ E).toReal /
              (stabilityMass σ E).toReal)) := Real.exp_lt_exp.mpr hlog.1
      _ = (stabilityMass τ E).toReal /
          (stabilityMass σ E).toReal := Real.exp_log hratio
  · calc
      (stabilityMass τ E).toReal /
          (stabilityMass σ E).toReal
          = Real.exp (Real.log ((stabilityMass τ E).toReal /
              (stabilityMass σ E).toReal)) := (Real.exp_log hratio).symm
      _ < Real.exp ε := Real.exp_lt_exp.mpr hlog.2

/-- A full-distance bound gives the convenient one-sided mass comparison. -/
theorem stabilityMass_toReal_lt_exp_mul_of_stabilityDist
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} (hE : ¬IsZero E)
    {ε : ℝ} (hε : 0 < ε)
    (hd : stabilityDist σ τ < ENNReal.ofReal ε) :
    (stabilityMass τ E).toReal <
      Real.exp ε * (stabilityMass σ E).toReal := by
  exact (div_lt_iff₀ (stabilityMass_toReal_pos σ hE)).mp
    (exp_neg_lt_mass_ratio_and_lt_exp_of_stabilityDist σ τ hE hε hd).2

/-- The preceding mass comparison in the reverse orientation. -/
theorem stabilityMass_toReal_lt_exp_mul_of_stabilityDist'
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} (hE : ¬IsZero E)
    {ε : ℝ} (hε : 0 < ε)
    (hd : stabilityDist σ τ < ENNReal.ofReal ε) :
    (stabilityMass σ E).toReal <
      Real.exp ε * (stabilityMass τ E).toReal := by
  apply stabilityMass_toReal_lt_exp_mul_of_stabilityDist τ σ hE hε
  rwa [stabilityDist_comm]

/-- Points on the phase unit circle are Lipschitz in their real phase, with
constant `π`.  The exponent convention is the one used by a stability
condition's compatibility axiom. -/
theorem norm_phaseExp_sub_phaseExp_le (φ ψ : ℝ) :
    ‖Complex.exp (↑(Real.pi * ψ) * Complex.I) -
        Complex.exp (↑(Real.pi * φ) * Complex.I)‖ ≤
      Real.pi * |ψ - φ| := by
  have hfactor :
      Complex.exp (↑(Real.pi * ψ) * Complex.I) -
          Complex.exp (↑(Real.pi * φ) * Complex.I) =
        Complex.exp (↑(Real.pi * φ) * Complex.I) *
          (Complex.exp (Complex.I * (Real.pi * (ψ - φ))) - 1) := by
    rw [mul_sub, mul_one, ← Complex.exp_add]
    congr 2
    push_cast
    ring
  rw [hfactor, norm_mul, Complex.norm_exp_ofReal_mul_I, one_mul]
  calc
    ‖Complex.exp (Complex.I * (Real.pi * (ψ - φ))) - 1‖
        ≤ ‖Real.pi * (ψ - φ)‖ := by
          convert Real.norm_exp_I_mul_ofReal_sub_one_le
            (x := Real.pi * (ψ - φ)) using 1
          all_goals norm_cast
    _ = Real.pi * |ψ - φ| := by
      rw [Real.norm_eq_abs, abs_mul, abs_of_pos Real.pi_pos]

/-- Finite sums of rays whose phases lie in an `ε`-window are within
`π ε` times their total length of the central ray. -/
theorem norm_sum_phaseExp_sub_centralRay_le
    {ι : Type*} [Fintype ι] (r ψ : ι → ℝ) (φ ε : ℝ)
    (hr : ∀ i, 0 ≤ r i) (hψ : ∀ i, |ψ i - φ| ≤ ε) :
    ‖(∑ i, (r i : ℂ) * Complex.exp (↑(Real.pi * ψ i) * Complex.I)) -
        ((∑ i, r i : ℝ) : ℂ) *
          Complex.exp (↑(Real.pi * φ) * Complex.I)‖ ≤
      Real.pi * ε * ∑ i, r i := by
  have hcentral :
      ((∑ i, r i : ℝ) : ℂ) *
          Complex.exp (↑(Real.pi * φ) * Complex.I) =
        ∑ i, (r i : ℂ) *
          Complex.exp (↑(Real.pi * φ) * Complex.I) := by
    calc
      ((∑ i, r i : ℝ) : ℂ) *
          Complex.exp (↑(Real.pi * φ) * Complex.I) =
          (∑ i, (r i : ℂ)) *
            Complex.exp (↑(Real.pi * φ) * Complex.I) := by
              rw [← Complex.ofReal_sum Finset.univ r]
      _ = ∑ i, (r i : ℂ) *
          Complex.exp (↑(Real.pi * φ) * Complex.I) := by
            simpa using
              (Finset.sum_mul Finset.univ (fun i ↦ (r i : ℂ))
                (Complex.exp (↑(Real.pi * φ) * Complex.I)))
  rw [hcentral, ← Finset.sum_sub_distrib]
  calc
    ‖∑ i, ((r i : ℂ) * Complex.exp (↑(Real.pi * ψ i) * Complex.I) -
        (r i : ℂ) * Complex.exp (↑(Real.pi * φ) * Complex.I))‖
        ≤ ∑ i, ‖(r i : ℂ) *
            Complex.exp (↑(Real.pi * ψ i) * Complex.I) -
          (r i : ℂ) * Complex.exp (↑(Real.pi * φ) * Complex.I)‖ :=
      norm_sum_le _ _
    _ ≤ ∑ i, Real.pi * ε * r i := by
      apply Finset.sum_le_sum
      intro i _
      rw [← mul_sub, norm_mul, Complex.norm_real, Real.norm_eq_abs,
        abs_of_nonneg (hr i)]
      calc
        r i * ‖Complex.exp (↑(Real.pi * ψ i) * Complex.I) -
            Complex.exp (↑(Real.pi * φ) * Complex.I)‖
            ≤ r i * (Real.pi * |ψ i - φ|) :=
          mul_le_mul_of_nonneg_left (norm_phaseExp_sub_phaseExp_le φ (ψ i)) (hr i)
        _ ≤ r i * (Real.pi * ε) := by
          exact mul_le_mul_of_nonneg_left
            (mul_le_mul_of_nonneg_left (hψ i) Real.pi_pos.le) (hr i)
        _ = Real.pi * ε * r i := by ring
    _ = Real.pi * ε * ∑ i, r i := by rw [Finset.mul_sum]

/-- The charge of a semistable object is its real HN mass times the unit ray
at its phase. -/
theorem charge_eq_stabilityMass_mul_phaseExp
    (σ : StabilityCondition.WithClassMap C v) {E : C} {φ : ℝ}
    (hP : σ.slicing.P φ E) (hE : ¬IsZero E) :
    σ.charge E = ((stabilityMass σ E).toReal : ℂ) *
      Complex.exp (↑(Real.pi * φ) * Complex.I) := by
  obtain ⟨m, hm, hZ⟩ := σ.compat φ E hP hE
  have hnorm : ‖σ.charge E‖ = m := by
    rw [hZ, norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_pos hm,
      Complex.norm_exp_ofReal_mul_I, mul_one]
  have hmass : (stabilityMass σ E).toReal = m :=
    (stabilityMass_toReal_eq_norm_charge σ hP).trans hnorm
  rw [hmass]
  exact hZ

/-- If `E` is `σ`-semistable of phase `φ` and the full distance from `σ` to
`τ` is less than `ε`, then the `τ`-charge of `E` is close to the ray at `φ`.
The coefficient on that ray is the full `τ`-HN mass of `E`.

This is the finite-HN-sector estimate needed for the easy direction of
Proposition 8.1. -/
theorem norm_charge_sub_mass_phaseExp_le_of_stabilityDist
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} {φ ε : ℝ}
    (hP : σ.slicing.P φ E) (hE : ¬IsZero E) (hε : 0 < ε)
    (hd : stabilityDist σ τ < ENNReal.ofReal ε) :
    ‖τ.charge E - ((stabilityMass τ E).toReal : ℂ) *
        Complex.exp (↑(Real.pi * φ) * Complex.I)‖ ≤
      Real.pi * ε * (stabilityMass τ E).toReal := by
  obtain ⟨F, hn, hfirst, hlast⟩ :=
    τ.slicing.exists_hn_intrinsic_width C hE
  have hfirst' : F.φ ⟨0, hn⟩ = τ.slicing.phiPlus C E hE := by
    simpa [CategoryTheory.Triangulated.HNFiltration.phiPlus] using hfirst
  have hlast' : F.φ ⟨F.n - 1, by lia⟩ =
      τ.slicing.phiMinus C E hE := by
    simpa [CategoryTheory.Triangulated.HNFiltration.phiMinus] using hlast
  have hσphase := σ.slicing.phiPlus_eq_phiMinus_of_semistable C hP hE
  have hplus := abs_phiPlus_sub_lt_of_stabilityDist σ τ hE hε hd
  have hminus := abs_phiMinus_sub_lt_of_stabilityDist σ τ hE hε hd
  rw [hσphase.1] at hplus
  rw [hσphase.2] at hminus
  have hphase : ∀ i : Fin F.n, |F.φ i - φ| ≤ ε := by
    intro i
    apply le_of_lt
    rw [abs_lt]
    constructor
    · have hi : F.φ ⟨F.n - 1, by lia⟩ ≤ F.φ i :=
        F.hφ.antitone (Fin.mk_le_mk.mpr (by lia))
      rw [hlast'] at hi
      rw [abs_lt] at hminus
      linarith
    · have hi : F.φ i ≤ F.φ ⟨0, hn⟩ :=
        F.hφ.antitone (Fin.mk_le_mk.mpr (Nat.zero_le i.val))
      rw [hfirst'] at hi
      rw [abs_lt] at hplus
      linarith
  have hZi : ∀ i : Fin F.n,
      τ.charge (F.factor i) =
        (‖τ.charge (F.factor i)‖ : ℂ) *
          Complex.exp (↑(Real.pi * F.φ i) * Complex.I) := by
    intro i
    by_cases hi : IsZero (F.factor i)
    · simp [τ.charge_isZero hi]
    · obtain ⟨m, hm, hmZ⟩ := τ.compat (F.φ i) (F.factor i) (F.semistable i) hi
      rw [hmZ]
      congr 1
      rw [norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_pos hm,
        Complex.norm_exp_ofReal_mul_I, mul_one]
  have hcharge := τ.charge_postnikovTower_eq_sum F.toPostnikovTower
  have hmass := stabilityMass_toReal_eq_sum τ F
  calc
    ‖τ.charge E - ((stabilityMass τ E).toReal : ℂ) *
        Complex.exp (↑(Real.pi * φ) * Complex.I)‖ =
      ‖(∑ i, (‖τ.charge (F.factor i)‖ : ℂ) *
          Complex.exp (↑(Real.pi * F.φ i) * Complex.I)) -
        ((∑ i, ‖τ.charge (F.factor i)‖ : ℝ) : ℂ) *
          Complex.exp (↑(Real.pi * φ) * Complex.I)‖ := by
            rw [hcharge, hmass]
            congr 2
            apply Finset.sum_congr rfl
            intro i _
            exact hZi i
    _ ≤ Real.pi * ε * ∑ i, ‖τ.charge (F.factor i)‖ :=
      norm_sum_phaseExp_sub_centralRay_le
        (fun i ↦ ‖τ.charge (F.factor i)‖) F.φ φ ε
        (fun _ ↦ norm_nonneg _) hphase
    _ = Real.pi * ε * (stabilityMass τ E).toReal := by rw [hmass]

/-- Projecting a finite collection of rays onto the bisector of a sector
bounds their total length by the norm of their sum. -/
private theorem norm_sum_phaseExp_ge_cos_mul_sum
    {ι : Type*} {s : Finset ι} {m θ : ι → ℝ}
    (hm : ∀ i ∈ s, 0 ≤ m i) {α w : ℝ} (hw0 : 0 ≤ w)
    (hwπ : w < Real.pi)
    (hθ : ∀ i ∈ s, θ i ∈ Set.Icc α (α + w)) :
    Real.cos (w / 2) * ∑ i ∈ s, m i ≤
      ‖∑ i ∈ s, (m i : ℂ) *
        Complex.exp ((θ i : ℂ) * Complex.I)‖ := by
  let β := α + w / 2
  have hpoint : ∀ i ∈ s, Real.cos (w / 2) * m i ≤
      (((m i : ℂ) * Complex.exp ((θ i : ℂ) * Complex.I)) *
        Complex.exp (-((β : ℂ) * Complex.I))).re := by
    intro i hi
    rw [mul_assoc, ← Complex.exp_add]
    have hexp : (θ i : ℂ) * Complex.I + -((β : ℂ) * Complex.I) =
        ((θ i - β : ℝ) : ℂ) * Complex.I := by
      push_cast
      ring
    rw [hexp, Complex.re_ofReal_mul, Complex.exp_ofReal_mul_I_re]
    have hdist : |θ i - β| ≤ w / 2 := by
      rw [abs_le]
      constructor <;> [have hlo := (hθ i hi).1; have hhi := (hθ i hi).2] <;>
        dsimp [β] <;> linarith
    calc
      Real.cos (w / 2) * m i ≤ Real.cos (θ i - β) * m i := by
        apply mul_le_mul_of_nonneg_right _ (hm i hi)
        rw [← Real.cos_abs (θ i - β)]
        exact Real.cos_le_cos_of_nonneg_of_le_pi (abs_nonneg _)
          (by linarith) hdist
      _ = m i * Real.cos (θ i - β) := mul_comm _ _
  calc
    Real.cos (w / 2) * ∑ i ∈ s, m i =
        ∑ i ∈ s, Real.cos (w / 2) * m i := Finset.mul_sum _ _ _
    _ ≤ ∑ i ∈ s,
        ((((m i : ℂ) * Complex.exp ((θ i : ℂ) * Complex.I)) *
          Complex.exp (-((β : ℂ) * Complex.I))).re) :=
      Finset.sum_le_sum hpoint
    _ = ((∑ i ∈ s, (m i : ℂ) *
          Complex.exp ((θ i : ℂ) * Complex.I)) *
        Complex.exp (-((β : ℂ) * Complex.I))).re := by
      rw [Finset.sum_mul, Complex.re_sum]
    _ ≤ ‖(∑ i ∈ s, (m i : ℂ) *
          Complex.exp ((θ i : ℂ) * Complex.I)) *
        Complex.exp (-((β : ℂ) * Complex.I))‖ := Complex.re_le_norm _
    _ = ‖∑ i ∈ s, (m i : ℂ) *
        Complex.exp ((θ i : ℂ) * Complex.I)‖ := by
      rw [norm_mul]
      have hrewrite : -((β : ℂ) * Complex.I) =
          ((-β : ℝ) : ℂ) * Complex.I := by
        push_cast
        ring
      rw [hrewrite, Complex.norm_exp_ofReal_mul_I, mul_one]

/-- A narrow HN sector bounds mass by the norm of the total charge.  This is
the mass-specialized lower-sector estimate, used by the **hard** direction of
the topology comparison (`exists_basisNhd_subset_stabilityDist_ball`) only. -/
theorem cos_mul_stabilityMass_le_norm_charge_of_width
    (σ : StabilityCondition.WithClassMap C v) {E : C} (hE : ¬IsZero E)
    {η : ℝ} (hη : 0 ≤ η) (hη1 : η < 1)
    (hwidth : σ.slicing.phiPlus C E hE -
      σ.slicing.phiMinus C E hE ≤ η) :
    Real.cos (Real.pi * η / 2) * (stabilityMass σ E).toReal ≤
      ‖σ.charge E‖ := by
  obtain ⟨F, hn, hfirst, hlast⟩ :=
    σ.slicing.exists_hn_intrinsic_width C hE
  have hfirst' : F.φ ⟨0, hn⟩ = σ.slicing.phiPlus C E hE := by
    simpa [CategoryTheory.Triangulated.HNFiltration.phiPlus] using hfirst
  have hlast' : F.φ ⟨F.n - 1, by lia⟩ =
      σ.slicing.phiMinus C E hE := by
    simpa [CategoryTheory.Triangulated.HNFiltration.phiMinus] using hlast
  have hZi : ∀ i : Fin F.n,
      σ.charge (F.factor i) =
        (‖σ.charge (F.factor i)‖ : ℂ) *
          Complex.exp (↑(Real.pi * F.φ i) * Complex.I) := by
    intro i
    by_cases hi : IsZero (F.factor i)
    · simp [σ.charge_isZero hi]
    · obtain ⟨m, hm, hmZ⟩ := σ.compat (F.φ i) (F.factor i) (F.semistable i) hi
      rw [hmZ]
      congr 1
      rw [norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_pos hm,
        Complex.norm_exp_ofReal_mul_I, mul_one]
  let α := Real.pi * F.φ ⟨F.n - 1, by lia⟩
  let w := Real.pi * η
  have hw0 : 0 ≤ w := mul_nonneg Real.pi_pos.le hη
  have hwπ : w < Real.pi := by
    dsimp [w]
    nlinarith [Real.pi_pos]
  have hθ : ∀ i : Fin F.n,
      Real.pi * F.φ i ∈ Set.Icc α (α + w) := by
    intro i
    constructor
    · exact mul_le_mul_of_nonneg_left
        (F.hφ.antitone (Fin.mk_le_mk.mpr (by lia))) Real.pi_pos.le
    · have hi : F.φ i ≤ F.φ ⟨0, hn⟩ :=
        F.hφ.antitone (Fin.mk_le_mk.mpr (Nat.zero_le i.val))
      have hextreme : F.φ ⟨0, hn⟩ - F.φ ⟨F.n - 1, by lia⟩ ≤ η := by
        rw [hfirst', hlast']
        exact hwidth
      dsimp [α, w]
      nlinarith [Real.pi_pos]
  have hsector :
      Real.cos (w / 2) * ∑ i : Fin F.n, ‖σ.charge (F.factor i)‖ ≤
        ‖σ.charge E‖ := by
    calc
      Real.cos (w / 2) * ∑ i : Fin F.n, ‖σ.charge (F.factor i)‖ ≤
          ‖∑ i : Fin F.n, (‖σ.charge (F.factor i)‖ : ℂ) *
            Complex.exp (↑(Real.pi * F.φ i) * Complex.I)‖ :=
        norm_sum_phaseExp_ge_cos_mul_sum (fun i _ ↦ norm_nonneg _) hw0 hwπ
          (fun i _ ↦ hθ i)
      _ = ‖∑ i : Fin F.n, σ.charge (F.factor i)‖ := by
        congr 1
        exact Finset.sum_congr rfl (fun i _ ↦ (hZi i).symm)
      _ = ‖σ.charge E‖ := by
        rw [← σ.charge_postnikovTower_eq_sum F.toPostnikovTower]
  rw [stabilityMass_toReal_eq_sum σ F]
  simpa [w] using hsector

/-- A pointwise bound on a charge homomorphism over semistable factors extends
to every object whose HN phases lie in a sector of width less than one. -/
theorem chargeHom_norm_le_of_intrinsic_width
    (σ : StabilityCondition.WithClassMap C v) (U : Λ →+ ℂ)
    {E : C} (hE : ¬IsZero E) {η M : ℝ} (hη : 0 ≤ η)
    (hη1 : η < 1)
    (hwidth : σ.slicing.phiPlus C E hE -
      σ.slicing.phiMinus C E hE ≤ η)
    (hM0 : 0 ≤ M)
    (hM : ∀ (A : C) (φ : ℝ), σ.slicing.P φ A → ¬IsZero A →
      ‖U (classOf C v A)‖ ≤ M * ‖σ.charge A‖) :
    ‖U (classOf C v E)‖ ≤
      M / Real.cos (Real.pi * η / 2) * ‖σ.charge E‖ := by
  obtain ⟨F⟩ := σ.slicing.hn_exists E
  have hclass : U (classOf C v E) =
      ∑ i : Fin F.n, U (classOf C v (F.factor i)) := by
    rw [classOf_postnikovTower_eq_sum C v F.toPostnikovTower, map_sum]
  have hfactor : ∀ i : Fin F.n,
      ‖U (classOf C v (F.factor i))‖ ≤
        M * ‖σ.charge (F.factor i)‖ := by
    intro i
    by_cases hi : IsZero (F.factor i)
    · simp [classOf_isZero C v hi, σ.charge_isZero hi]
    · exact hM _ _ (F.semistable i) hi
  have hcos : 0 < Real.cos (Real.pi * η / 2) := by
    apply Real.cos_pos_of_mem_Ioo
    constructor <;> nlinarith [Real.pi_pos]
  have hmass : (stabilityMass σ E).toReal ≤
      ‖σ.charge E‖ / Real.cos (Real.pi * η / 2) := by
    apply (le_div_iff₀ hcos).2
    simpa [mul_comm] using
      cos_mul_stabilityMass_le_norm_charge_of_width σ hE hη hη1 hwidth
  calc
    ‖U (classOf C v E)‖ =
        ‖∑ i : Fin F.n, U (classOf C v (F.factor i))‖ := by rw [hclass]
    _ ≤ ∑ i : Fin F.n, ‖U (classOf C v (F.factor i))‖ := norm_sum_le _ _
    _ ≤ ∑ i : Fin F.n, M * ‖σ.charge (F.factor i)‖ :=
      Finset.sum_le_sum (fun i _ ↦ hfactor i)
    _ = M * (stabilityMass σ E).toReal := by
      rw [stabilityMass_toReal_eq_sum σ F, Finset.mul_sum]
    _ ≤ M * (‖σ.charge E‖ / Real.cos (Real.pi * η / 2)) :=
      mul_le_mul_of_nonneg_left hmass hM0
    _ = M / Real.cos (Real.pi * η / 2) * ‖σ.charge E‖ := by ring

/-- A Section 6 basis bound controls the mass of a `σ`-semistable object in
the nearby stability condition. -/
theorem stabilityMass_toReal_le_of_mem_basisNhd_of_semistable
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} {φ ε : ℝ}
    (hP : σ.slicing.P φ E) (hE : ¬IsZero E)
    (hε : 0 < ε) (hε2 : ε < 1 / 2) (hτ : τ ∈ basisNhd C σ ε) :
    (stabilityMass τ E).toReal ≤
      ((1 + Real.sin (Real.pi * ε)) / Real.cos (Real.pi * ε)) *
        (stabilityMass σ E).toReal := by
  have hslice : slicingDist C τ.slicing σ.slicing < ENNReal.ofReal ε := by
    rw [slicingDist_symm]
    exact hτ.2
  have hbounds := intervalProp_of_semistable_slicingDist C τ.slicing σ.slicing
    hE hP hε hslice
  have hwidth : τ.slicing.phiPlus C E hE -
      τ.slicing.phiMinus C E hE ≤ 2 * ε := by
    have hp := τ.slicing.phiPlus_lt_of_intervalProp C hE hbounds
    have hm := τ.slicing.phiMinus_gt_of_intervalProp C hE hbounds
    linarith
  have hsector := cos_mul_stabilityMass_le_norm_charge_of_width τ hE
    (η := 2 * ε) (by linarith) (by linarith) hwidth
  have hcos : 0 < Real.cos (Real.pi * ε) := by
    apply Real.cos_pos_of_mem_Ioo
    constructor <;> nlinarith [Real.pi_pos]
  have hsector' : Real.cos (Real.pi * ε) *
      (stabilityMass τ E).toReal ≤ ‖τ.charge E‖ := by
    convert hsector using 1
    all_goals ring_nf
  have hsemi := semistableChargeBound_toReal C σ τ.Z
    (ne_top_of_lt (lt_trans hτ.1 ENNReal.ofReal_lt_top)) φ E hP hE
  have hsin : 0 < Real.sin (Real.pi * ε) :=
    Real.sin_pos_of_pos_of_lt_pi (mul_pos Real.pi_pos hε)
      (by nlinarith [Real.pi_pos])
  have hseminorm : (stabilitySeminorm C σ (τ.Z - σ.Z)).toReal <
      Real.sin (Real.pi * ε) :=
    ENNReal.toReal_lt_of_lt_ofReal hτ.1
  have hchargeDiff : ‖τ.charge E - σ.charge E‖ <
      Real.sin (Real.pi * ε) * ‖σ.charge E‖ := by
    refine lt_of_le_of_lt ?_ (mul_lt_mul_of_pos_right hseminorm ?_)
    · simpa only [AddMonoidHom.sub_apply] using hsemi
    · exact norm_pos_iff.mpr (σ.charge_ne_zero_of_semistable φ E hP hE)
  have hcharge : ‖τ.charge E‖ <
      (1 + Real.sin (Real.pi * ε)) * ‖σ.charge E‖ := by
    calc
      ‖τ.charge E‖ ≤ ‖τ.charge E - σ.charge E‖ + ‖σ.charge E‖ := by
        have := norm_add_le (τ.charge E - σ.charge E) (σ.charge E)
        simpa using this
      _ < Real.sin (Real.pi * ε) * ‖σ.charge E‖ + ‖σ.charge E‖ :=
        by simpa [add_comm] using add_lt_add_right hchargeDiff ‖σ.charge E‖
      _ = (1 + Real.sin (Real.pi * ε)) * ‖σ.charge E‖ := by ring
  rw [stabilityMass_toReal_eq_norm_charge σ hP]
  calc
    (stabilityMass τ E).toReal ≤
        ‖τ.charge E‖ / Real.cos (Real.pi * ε) :=
      (le_div_iff₀ hcos).2 (by simpa [mul_comm] using hsector')
    _ ≤ ((1 + Real.sin (Real.pi * ε)) * ‖σ.charge E‖) /
        Real.cos (Real.pi * ε) :=
      (div_le_div_iff_of_pos_right hcos).2 hcharge.le
    _ = (1 + Real.sin (Real.pi * ε)) / Real.cos (Real.pi * ε) *
        ‖σ.charge E‖ := by ring

/-- The same basis bound controls the old mass of a `τ`-semistable object in
terms of its new mass.  The factor is written so that it tends to one as the
basis radius tends to zero. -/
theorem stabilityMass_toReal_le_of_mem_basisNhd_of_semistable'
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} {φ ε : ℝ}
    (hP : τ.slicing.P φ E) (hE : ¬IsZero E)
    (hε : 0 < ε) (hε4 : ε < 1 / 4) (hτ : τ ∈ basisNhd C σ ε) :
    (stabilityMass σ E).toReal ≤
      (1 / (Real.cos (Real.pi * ε) - Real.sin (Real.pi * ε))) *
          (stabilityMass τ E).toReal := by
  have hwidth : σ.slicing.phiPlus C E hE -
      σ.slicing.phiMinus C E hE ≤ 2 * ε := by
    have hbounds := intervalProp_of_semistable_slicingDist C σ.slicing τ.slicing
      hE hP hε hτ.2
    have hp := σ.slicing.phiPlus_lt_of_intervalProp C hE hbounds
    have hm := σ.slicing.phiMinus_gt_of_intervalProp C hE hbounds
    linarith
  have hsector := cos_mul_stabilityMass_le_norm_charge_of_width σ hE
    (η := 2 * ε) (by linarith) (by linarith) hwidth
  have hcos : 0 < Real.cos (Real.pi * ε) := by
    apply Real.cos_pos_of_mem_Ioo
    constructor <;> nlinarith [Real.pi_pos]
  have hsector' : Real.cos (Real.pi * ε) *
      (stabilityMass σ E).toReal ≤ ‖σ.charge E‖ := by
    convert hsector using 1
    all_goals ring_nf
  have hsin0 : 0 < Real.sin (Real.pi * ε) :=
    Real.sin_pos_of_pos_of_lt_pi (mul_pos Real.pi_pos hε)
      (by nlinarith [Real.pi_pos])
  have hsincos : Real.sin (Real.pi * ε) < Real.cos (Real.pi * ε) := by
    rw [← Real.cos_pi_div_two_sub]
    apply Real.cos_lt_cos_of_nonneg_of_le_pi_div_two
    · nlinarith [Real.pi_pos]
    · nlinarith [Real.pi_pos]
    · nlinarith [Real.pi_pos]
  have hsemiFin : stabilitySeminorm C σ (τ.Z - σ.Z) ≠ ⊤ :=
    ne_top_of_lt (lt_trans hτ.1 ENNReal.ofReal_lt_top)
  have hseminorm : (stabilitySeminorm C σ (τ.Z - σ.Z)).toReal <
      Real.sin (Real.pi * ε) := ENNReal.toReal_lt_of_lt_ofReal hτ.1
  have hσsem : ∀ {A : C} {ψ : ℝ}, σ.slicing.P ψ A → ¬IsZero A →
      ‖τ.charge A - σ.charge A‖ <
        Real.sin (Real.pi * ε) * ‖σ.charge A‖ := by
    intro A ψ hPA hA
    have hbound := semistableChargeBound_toReal C σ τ.Z
      hsemiFin ψ A hPA hA
    refine lt_of_le_of_lt ?_ (mul_lt_mul_of_pos_right hseminorm ?_)
    · simpa only [AddMonoidHom.sub_apply] using hbound
    · exact norm_pos_iff.mpr (σ.charge_ne_zero_of_semistable ψ A hPA hA)
  have hdiff : ‖τ.charge E - σ.charge E‖ ≤
      (Real.sin (Real.pi * ε) / Real.cos (Real.pi * ε)) *
        ‖σ.charge E‖ := by
    have hbound := chargeHom_norm_le_of_intrinsic_width σ (τ.Z - σ.Z) hE
      (η := 2 * ε) (by linarith) (by linarith) hwidth hsin0.le
      (fun A ψ hPA hA ↦ (hσsem hPA hA).le)
    have harg : Real.pi * (2 * ε) / 2 = Real.pi * ε := by ring
    rw [harg] at hbound
    simpa only [AddMonoidHom.sub_apply] using hbound
  have hcharge : (1 - Real.sin (Real.pi * ε) / Real.cos (Real.pi * ε)) *
      ‖σ.charge E‖ ≤ ‖τ.charge E‖ := by
    calc
      (1 - Real.sin (Real.pi * ε) / Real.cos (Real.pi * ε)) *
          ‖σ.charge E‖ = ‖σ.charge E‖ -
            (Real.sin (Real.pi * ε) / Real.cos (Real.pi * ε)) *
              ‖σ.charge E‖ := by ring
      _ ≤ ‖σ.charge E‖ - ‖τ.charge E - σ.charge E‖ := by linarith
      _ ≤ ‖τ.charge E‖ := by
        have htri := norm_sub_le (τ.charge E) (τ.charge E - σ.charge E)
        have heq : τ.charge E - (τ.charge E - σ.charge E) = σ.charge E := by ring
        rw [heq] at htri
        linarith
  have hcoeff : 0 ≤ 1 -
      Real.sin (Real.pi * ε) / Real.cos (Real.pi * ε) := by
    rw [sub_nonneg, div_le_one hcos]
    exact hsincos.le
  have hsimple : (Real.cos (Real.pi * ε) - Real.sin (Real.pi * ε)) *
      (stabilityMass σ E).toReal ≤ ‖τ.charge E‖ := by
    calc
      (Real.cos (Real.pi * ε) - Real.sin (Real.pi * ε)) *
          (stabilityMass σ E).toReal =
        (1 - Real.sin (Real.pi * ε) / Real.cos (Real.pi * ε)) *
          (Real.cos (Real.pi * ε) * (stabilityMass σ E).toReal) := by
            field_simp [hcos.ne']
      _ ≤ (1 - Real.sin (Real.pi * ε) / Real.cos (Real.pi * ε)) *
          ‖σ.charge E‖ := mul_le_mul_of_nonneg_left hsector' hcoeff
      _ ≤ ‖τ.charge E‖ := hcharge
  rw [stabilityMass_toReal_eq_norm_charge τ hP]
  have hden : 0 < Real.cos (Real.pi * ε) - Real.sin (Real.pi * ε) :=
    sub_pos.mpr hsincos
  calc
    (stabilityMass σ E).toReal ≤ ‖τ.charge E‖ /
        (Real.cos (Real.pi * ε) - Real.sin (Real.pi * ε)) :=
      (le_div_iff₀ hden).2 (by simpa [mul_comm] using hsimple)
    _ = 1 / (Real.cos (Real.pi * ε) - Real.sin (Real.pi * ε)) *
        ‖τ.charge E‖ := by ring

/-- The remaining categorical mass lemma needed by the global topology
comparison: HN mass is subadditive across every distinguished triangle.

This is stated as a proposition so that all analytic and topological parts of
Proposition 8.1 can be checked independently of its filtration-assembly
proof.  No instance or theorem below assumes it globally without taking an
explicit proof argument. -/
def StabilityMassTriangleInequality : Prop :=
  ∀ (σ : StabilityCondition.WithClassMap C v) (T : Triangle C),
    T ∈ distTriang C →
      (stabilityMass σ T.obj₂).toReal ≤
        (stabilityMass σ T.obj₁).toReal +
          (stabilityMass σ T.obj₃).toReal

omit [IsTriangulated C] in
/-- Real mass is invariant under object isomorphism. -/
theorem stabilityMass_toReal_congr
    (σ : StabilityCondition.WithClassMap C v) {E E' : C} (e : E ≅ E') :
    (stabilityMass σ E).toReal = (stabilityMass σ E').toReal :=
  congrArg ENNReal.toReal (stabilityMass_congr σ e)

/-- Triangle subadditivity iterated along the first `k` stages of a Postnikov
tower. -/
theorem stabilityMass_chain_le_partial_sum
    (htriangle : StabilityMassTriangleInequality (C := C) (v := v))
    (σ : StabilityCondition.WithClassMap C v) {E : C}
    (P : PostnikovTower C E) (k : ℕ) (hk : k ≤ P.n) :
    (stabilityMass σ (P.chain.obj' k (by lia))).toReal ≤
      ∑ i : Fin k,
        (stabilityMass σ (P.factor ⟨i.val, by lia⟩)).toReal := by
  induction k with
  | zero =>
      simp only [Finset.univ_eq_empty, Finset.sum_empty]
      change (stabilityMass σ P.chain.left).toReal ≤ 0
      rw [(stabilityMass_eq_zero_iff σ P.chain.left).2 P.base_isZero]
      simp
  | succ k ih =>
      let i : Fin P.n := ⟨k, by lia⟩
      have hstep := htriangle σ (P.triangle i) (P.triangle_dist i)
      have h₁ := stabilityMass_toReal_congr σ
        (Classical.choice (P.triangle_obj₁ i))
      have h₂ := stabilityMass_toReal_congr σ
        (Classical.choice (P.triangle_obj₂ i))
      have hstep' :
          (stabilityMass σ (P.chain.obj' (k + 1) (by lia))).toReal ≤
            (stabilityMass σ (P.chain.obj' k (by lia))).toReal +
              (stabilityMass σ (P.factor i)).toReal := by
        rw [h₂, h₁] at hstep
        exact hstep
      calc
        (stabilityMass σ (P.chain.obj' (k + 1) (by lia))).toReal ≤
            (stabilityMass σ (P.chain.obj' k (by lia))).toReal +
              (stabilityMass σ (P.factor i)).toReal := hstep'
        _ ≤ (∑ j : Fin k,
              (stabilityMass σ (P.factor ⟨j.val, by lia⟩)).toReal) +
            (stabilityMass σ (P.factor i)).toReal :=
          add_le_add (ih (by lia)) le_rfl
        _ = ∑ j : Fin (k + 1),
            (stabilityMass σ (P.factor ⟨j.val, by lia⟩)).toReal := by
          rw [Fin.sum_univ_castSucc]
          rfl

/-- Triangle subadditivity bounds the mass of the top of any Postnikov tower
by the sum of the masses of its factors. -/
theorem stabilityMass_le_sum_postnikov_factors
    (htriangle : StabilityMassTriangleInequality (C := C) (v := v))
    (σ : StabilityCondition.WithClassMap C v) {E : C}
    (P : PostnikovTower C E) :
    (stabilityMass σ E).toReal ≤
      ∑ i : Fin P.n, (stabilityMass σ (P.factor i)).toReal := by
  have hchain := stabilityMass_chain_le_partial_sum htriangle σ P P.n le_rfl
  have htop := stabilityMass_toReal_congr σ (Classical.choice P.top_iso)
  calc
    (stabilityMass σ E).toReal =
        (stabilityMass σ P.chain.right).toReal := htop.symm
    _ ≤ ∑ i : Fin P.n, (stabilityMass σ (P.factor i)).toReal := hchain

/-- With triangle subadditivity, the local semistable estimate extends to all
objects. -/
theorem stabilityMass_toReal_le_of_mem_basisNhd
    (htriangle : StabilityMassTriangleInequality (C := C) (v := v))
    (σ τ : StabilityCondition.WithClassMap C v) {ε : ℝ}
    (hε : 0 < ε) (hε8 : ε < 1 / 8) (hτ : τ ∈ basisNhd C σ ε)
    (E : C) :
    (stabilityMass τ E).toReal ≤
      ((1 + Real.sin (Real.pi * ε)) / Real.cos (Real.pi * ε)) *
        (stabilityMass σ E).toReal := by
  obtain ⟨F⟩ := σ.slicing.hn_exists E
  let K := (1 + Real.sin (Real.pi * ε)) / Real.cos (Real.pi * ε)
  have hpoint : ∀ i : Fin F.n,
      (stabilityMass τ (F.factor i)).toReal ≤
        K * (stabilityMass σ (F.factor i)).toReal := by
    intro i
    by_cases hi : IsZero (F.factor i)
    · rw [(stabilityMass_eq_zero_iff τ _).2 hi,
        (stabilityMass_eq_zero_iff σ _).2 hi]
      simp
    · exact stabilityMass_toReal_le_of_mem_basisNhd_of_semistable σ τ
        (F.semistable i) hi hε (by linarith) hτ
  have hsumσ :
      (∑ i : Fin F.n, (stabilityMass σ (F.factor i)).toReal) =
        (stabilityMass σ E).toReal := by
    rw [stabilityMass_toReal_eq_sum σ F]
    apply Finset.sum_congr rfl
    intro i _
    exact stabilityMass_toReal_eq_norm_charge σ (F.semistable i)
  calc
    (stabilityMass τ E).toReal ≤
        ∑ i : Fin F.n, (stabilityMass τ (F.factor i)).toReal :=
      stabilityMass_le_sum_postnikov_factors htriangle τ F.toPostnikovTower
    _ ≤ ∑ i : Fin F.n, K * (stabilityMass σ (F.factor i)).toReal :=
      Finset.sum_le_sum (fun i _ ↦ hpoint i)
    _ = K * ∑ i : Fin F.n, (stabilityMass σ (F.factor i)).toReal := by
      rw [Finset.mul_sum]
    _ = K * (stabilityMass σ E).toReal := by rw [hsumσ]

/-- The global mass comparison in the reverse orientation. -/
theorem stabilityMass_toReal_le_of_mem_basisNhd'
    (htriangle : StabilityMassTriangleInequality (C := C) (v := v))
    (σ τ : StabilityCondition.WithClassMap C v) {ε : ℝ}
    (hε : 0 < ε) (hε8 : ε < 1 / 8) (hτ : τ ∈ basisNhd C σ ε)
    (E : C) :
    (stabilityMass σ E).toReal ≤
      (1 / (Real.cos (Real.pi * ε) - Real.sin (Real.pi * ε))) *
        (stabilityMass τ E).toReal := by
  obtain ⟨F⟩ := τ.slicing.hn_exists E
  let K := 1 / (Real.cos (Real.pi * ε) - Real.sin (Real.pi * ε))
  have hpoint : ∀ i : Fin F.n,
      (stabilityMass σ (F.factor i)).toReal ≤
        K * (stabilityMass τ (F.factor i)).toReal := by
    intro i
    by_cases hi : IsZero (F.factor i)
    · rw [(stabilityMass_eq_zero_iff σ _).2 hi,
        (stabilityMass_eq_zero_iff τ _).2 hi]
      simp
    · exact stabilityMass_toReal_le_of_mem_basisNhd_of_semistable' σ τ
        (F.semistable i) hi hε (by linarith) hτ
  have hsumτ :
      (∑ i : Fin F.n, (stabilityMass τ (F.factor i)).toReal) =
        (stabilityMass τ E).toReal := by
    rw [stabilityMass_toReal_eq_sum τ F]
    apply Finset.sum_congr rfl
    intro i _
    exact stabilityMass_toReal_eq_norm_charge τ (F.semistable i)
  calc
    (stabilityMass σ E).toReal ≤
        ∑ i : Fin F.n, (stabilityMass σ (F.factor i)).toReal :=
      stabilityMass_le_sum_postnikov_factors htriangle σ F.toPostnikovTower
    _ ≤ ∑ i : Fin F.n, K * (stabilityMass τ (F.factor i)).toReal :=
      Finset.sum_le_sum (fun i _ ↦ hpoint i)
    _ = K * ∑ i : Fin F.n, (stabilityMass τ (F.factor i)).toReal := by
      rw [Finset.mul_sum]
    _ = K * (stabilityMass τ E).toReal := by rw [hsumτ]

/-- The forward uniform mass factor supplied by a Section 6 basis
neighborhood. -/
def basisForwardMassFactor (ε : ℝ) : ℝ :=
  (1 + Real.sin (Real.pi * ε)) / Real.cos (Real.pi * ε)

/-- The reverse uniform mass factor supplied by a Section 6 basis
neighborhood. -/
def basisReverseMassFactor (ε : ℝ) : ℝ :=
  1 / (Real.cos (Real.pi * ε) - Real.sin (Real.pi * ε))

/-- A symmetric logarithmic mass-error coefficient for a Section 6 basis
neighborhood. -/
def basisMassControl (ε : ℝ) : ℝ :=
  max (Real.log (basisForwardMassFactor ε))
    (Real.log (basisReverseMassFactor ε))

@[simp]
theorem basisForwardMassFactor_zero : basisForwardMassFactor 0 = 1 := by
  simp [basisForwardMassFactor]

@[simp]
theorem basisReverseMassFactor_zero : basisReverseMassFactor 0 = 1 := by
  simp [basisReverseMassFactor]

@[simp]
theorem basisMassControl_zero : basisMassControl 0 = 0 := by
  simp [basisMassControl]

/-- The two global mass comparisons give a symmetric logarithmic ratio
bound. -/
theorem abs_log_mass_ratio_le_of_mem_basisNhd
    (htriangle : StabilityMassTriangleInequality (C := C) (v := v))
    (σ τ : StabilityCondition.WithClassMap C v) {ε : ℝ}
    (hε : 0 < ε) (hε8 : ε < 1 / 8) (hτ : τ ∈ basisNhd C σ ε)
    {E : C} (hE : ¬IsZero E) :
    |Real.log ((stabilityMass τ E).toReal /
      (stabilityMass σ E).toReal)| ≤ basisMassControl ε := by
  let mσ := (stabilityMass σ E).toReal
  let mτ := (stabilityMass τ E).toReal
  let KF := basisForwardMassFactor ε
  let KR := basisReverseMassFactor ε
  have hmσ : 0 < mσ := stabilityMass_toReal_pos σ hE
  have hmτ : 0 < mτ := stabilityMass_toReal_pos τ hE
  have hcos : 0 < Real.cos (Real.pi * ε) := by
    apply Real.cos_pos_of_mem_Ioo
    constructor <;> nlinarith [Real.pi_pos]
  have hsincos : Real.sin (Real.pi * ε) < Real.cos (Real.pi * ε) := by
    rw [← Real.cos_pi_div_two_sub]
    apply Real.cos_lt_cos_of_nonneg_of_le_pi_div_two
    · nlinarith [Real.pi_pos]
    · nlinarith [Real.pi_pos]
    · nlinarith [Real.pi_pos]
  have hKF : 0 < KF := by
    dsimp [KF, basisForwardMassFactor]
    exact div_pos (by
      have hsin : 0 < Real.sin (Real.pi * ε) :=
        Real.sin_pos_of_pos_of_lt_pi (mul_pos Real.pi_pos hε)
          (by nlinarith [Real.pi_pos])
      linarith) hcos
  have hKR : 0 < KR := by
    dsimp [KR, basisReverseMassFactor]
    exact one_div_pos.mpr (sub_pos.mpr hsincos)
  have hf : mτ ≤ KF * mσ := by
    exact stabilityMass_toReal_le_of_mem_basisNhd htriangle σ τ hε hε8 hτ E
  have hr : mσ ≤ KR * mτ := by
    exact stabilityMass_toReal_le_of_mem_basisNhd' htriangle σ τ hε hε8 hτ E
  change |Real.log (mτ / mσ)| ≤ max (Real.log KF) (Real.log KR)
  rcases le_total mσ mτ with hστ | hτσ
  · have hratioOne : 1 ≤ mτ / mσ := (le_div_iff₀ hmσ).2 (by simpa using hστ)
    have hratioKF : mτ / mσ ≤ KF := (div_le_iff₀ hmσ).2 hf
    rw [abs_of_nonneg (Real.log_nonneg hratioOne)]
    exact (Real.log_le_log (div_pos hmτ hmσ) hratioKF).trans
      (le_max_left _ _)
  · have hratioOne : mτ / mσ ≤ 1 := (div_le_one hmσ).2 hτσ
    have hratioKR : mσ / mτ ≤ KR := (div_le_iff₀ hmτ).2 hr
    rw [abs_of_nonpos (Real.log_nonpos (div_pos hmτ hmσ).le hratioOne)]
    have hident : -Real.log (mτ / mσ) = Real.log (mσ / mτ) := by
      rw [Real.log_div hmτ.ne' hmσ.ne', Real.log_div hmσ.ne' hmτ.ne']
      ring
    rw [hident]
    exact (Real.log_le_log (div_pos hmσ hmτ) hratioKR).trans
      (le_max_right _ _)

/-- The symmetric mass-error coefficient tends to zero at the origin, so it
can be made smaller than any positive target while retaining the Section 6
radius restrictions. -/
theorem exists_basisMassControl_lt {a : ℝ} (ha : 0 < a) :
    ∃ ε : ℝ, 0 < ε ∧ ε < 1 / 8 ∧ ε < a ∧ basisMassControl ε < a := by
  have hcont : ContinuousAt basisMassControl 0 := by
    unfold basisMassControl basisForwardMassFactor basisReverseMassFactor
    have hx : ContinuousAt (fun x : ℝ ↦ Real.pi * x) 0 :=
      continuousAt_const.mul continuousAt_id
    have hsin : ContinuousAt (fun x : ℝ ↦ Real.sin (Real.pi * x)) 0 :=
      by simpa [Function.comp_def] using Real.continuous_sin.continuousAt.comp hx
    have hcos : ContinuousAt (fun x : ℝ ↦ Real.cos (Real.pi * x)) 0 :=
      by simpa [Function.comp_def] using Real.continuous_cos.continuousAt.comp hx
    have hfwd : ContinuousAt
        (fun x : ℝ ↦ (1 + Real.sin (Real.pi * x)) /
          Real.cos (Real.pi * x)) 0 :=
      (continuousAt_const.add hsin).div hcos (by simp)
    have hrev : ContinuousAt
        (fun x : ℝ ↦ 1 /
          (Real.cos (Real.pi * x) - Real.sin (Real.pi * x))) 0 :=
      continuousAt_const.div (hcos.sub hsin) (by simp)
    exact (hfwd.log (by simp)).max (hrev.log (by simp))
  have hcontrol : {x : ℝ | basisMassControl x < a} ∈ 𝓝 0 := by
    exact hcont.preimage_mem_nhds (isOpen_Iio.mem_nhds (by simpa using ha))
  have hsmall8 : Set.Iio (1 / 8 : ℝ) ∈ 𝓝 (0 : ℝ) :=
    isOpen_Iio.mem_nhds (by norm_num)
  have hsmalla : Set.Iio a ∈ 𝓝 (0 : ℝ) := isOpen_Iio.mem_nhds ha
  obtain ⟨r, hr, hrsub⟩ := Metric.mem_nhds_iff.mp
    (Filter.inter_mem hcontrol (Filter.inter_mem hsmall8 hsmalla))
  have hball : r / 2 ∈ Metric.ball (0 : ℝ) r := by
    rw [Metric.mem_ball, Real.dist_eq, sub_zero, abs_of_nonneg (by positivity)]
    linarith
  exact ⟨r / 2, by positivity, (hrsub hball).2.1, (hrsub hball).2.2,
    (hrsub hball).1⟩

/-- Assuming triangle subadditivity of mass, every sufficiently small Section
6 basis neighborhood lies in any prescribed positive real full-distance
ball.  This is the hard cofinality direction of Proposition 8.1. -/
theorem exists_basisNhd_subset_stabilityDist_ball
    (htriangle : StabilityMassTriangleInequality (C := C) (v := v))
    (σ : StabilityCondition.WithClassMap C v) {a : ℝ} (ha : 0 < a) :
    ∃ ε : ℝ, 0 < ε ∧ ε < 1 / 8 ∧
      basisNhd C σ ε ⊆ {τ | stabilityDist σ τ < ENNReal.ofReal a} := by
  obtain ⟨ε, hε, hε8, hεa, hmass⟩ := exists_basisMassControl_lt ha
  let b := max ε (basisMassControl ε)
  have hb : b < a := max_lt hεa hmass
  refine ⟨ε, hε, hε8, ?_⟩
  intro τ hτ
  refine lt_of_le_of_lt ?_ ((ENNReal.ofReal_lt_ofReal_iff ha).2 hb)
  unfold stabilityDist
  refine iSup₂_le fun E hE ↦ ?_
  have hp := abs_phiPlus_sub_lt_of_slicingDist C σ.slicing τ.slicing hE hε hτ.2
  have hm := abs_phiMinus_sub_lt_of_slicingDist C σ.slicing τ.slicing hE hε hτ.2
  have hmassE := abs_log_mass_ratio_le_of_mem_basisNhd
    htriangle σ τ hε hε8 hτ hE
  unfold stabilityDistTerm
  apply max_le
  · unfold phiPlusDist
    exact ENNReal.ofReal_le_ofReal ((le_of_lt hp).trans (le_max_left _ _))
  · apply max_le
    · unfold phiMinusDist
      exact ENNReal.ofReal_le_ofReal ((le_of_lt hm).trans (le_max_left _ _))
    · rw [massDist_eq_abs_log_ratio σ τ E hE]
      exact ENNReal.ofReal_le_ofReal (hmassE.trans (le_max_right _ _))

/-- A convenient uniform charge-error coefficient.  It tends to zero with
`ε`; the first term is angular error and the second is radial mass error. -/
def stabilityChargeControl (ε : ℝ) : ℝ :=
  Real.pi * ε * Real.exp ε + Real.exp ε - 1

@[simp]
theorem stabilityChargeControl_zero : stabilityChargeControl 0 = 0 := by
  simp [stabilityChargeControl]

/-- On a `σ`-semistable object, a strict full-distance bound controls the
relative difference of the central charges. -/
theorem norm_charge_sub_charge_lt_of_stabilityDist
    (σ τ : StabilityCondition.WithClassMap C v) {E : C} {φ ε : ℝ}
    (hP : σ.slicing.P φ E) (hE : ¬IsZero E) (hε : 0 < ε)
    (hd : stabilityDist σ τ < ENNReal.ofReal ε) :
    ‖τ.charge E - σ.charge E‖ <
      stabilityChargeControl ε * ‖σ.charge E‖ := by
  let mσ := (stabilityMass σ E).toReal
  let mτ := (stabilityMass τ E).toReal
  let uφ := Complex.exp (↑(Real.pi * φ) * Complex.I)
  have hmσ : 0 < mσ := stabilityMass_toReal_pos σ hE
  have hmτ : 0 < mτ := stabilityMass_toReal_pos τ hE
  have hτ : mτ < Real.exp ε * mσ :=
    stabilityMass_toReal_lt_exp_mul_of_stabilityDist σ τ hE hε hd
  have hσ : mσ < Real.exp ε * mτ :=
    stabilityMass_toReal_lt_exp_mul_of_stabilityDist' σ τ hE hε hd
  have hexp : 0 ≤ Real.exp ε - 1 := sub_nonneg.mpr (Real.one_le_exp hε.le)
  have hmass : |mτ - mσ| < (Real.exp ε - 1) * mσ := by
    rcases le_total mσ mτ with hle | hle
    · rw [abs_of_nonneg (sub_nonneg.mpr hle)]
      calc
        mτ - mσ < Real.exp ε * mσ - mσ := sub_lt_sub_right hτ mσ
        _ = (Real.exp ε - 1) * mσ := by ring
    · rw [abs_of_nonpos (sub_nonpos.mpr hle), neg_sub]
      calc
        mσ - mτ < Real.exp ε * mτ - mτ := sub_lt_sub_right hσ mτ
        _ = (Real.exp ε - 1) * mτ := by ring
        _ ≤ (Real.exp ε - 1) * mσ :=
          mul_le_mul_of_nonneg_left hle hexp
  have hray : ‖τ.charge E - (mτ : ℂ) * uφ‖ <
      Real.pi * ε * (Real.exp ε * mσ) := by
    refine lt_of_le_of_lt
      (norm_charge_sub_mass_phaseExp_le_of_stabilityDist σ τ hP hE hε hd) ?_
    exact mul_lt_mul_of_pos_left hτ (mul_pos Real.pi_pos hε)
  have hσray : σ.charge E = (mσ : ℂ) * uφ :=
    charge_eq_stabilityMass_mul_phaseExp σ hP hE
  have huφ : ‖uφ‖ = 1 := by
    exact Complex.norm_exp_ofReal_mul_I (Real.pi * φ)
  have hnormDiff : ‖(mτ : ℂ) * uφ - (mσ : ℂ) * uφ‖ = |mτ - mσ| := by
    rw [← sub_mul, norm_mul, huφ, mul_one]
    rw [show (mτ : ℂ) - (mσ : ℂ) = ((mτ - mσ : ℝ) : ℂ) by norm_cast]
    rw [Complex.norm_real, Real.norm_eq_abs]
  calc
    ‖τ.charge E - σ.charge E‖ =
        ‖τ.charge E - (mσ : ℂ) * uφ‖ := by rw [hσray]
    _ =
        ‖(τ.charge E - (mτ : ℂ) * uφ) +
          ((mτ : ℂ) * uφ - (mσ : ℂ) * uφ)‖ := by
            congr 1
            ring
    _ ≤ ‖τ.charge E - (mτ : ℂ) * uφ‖ +
        ‖(mτ : ℂ) * uφ - (mσ : ℂ) * uφ‖ := norm_add_le _ _
    _ = ‖τ.charge E - (mτ : ℂ) * uφ‖ + |mτ - mσ| := by
      rw [hnormDiff]
    _ < Real.pi * ε * (Real.exp ε * mσ) +
        (Real.exp ε - 1) * mσ := add_lt_add hray hmass
    _ = stabilityChargeControl ε * mσ := by
      unfold stabilityChargeControl
      ring
    _ = stabilityChargeControl ε * ‖σ.charge E‖ := by
      rw [← stabilityMass_toReal_eq_norm_charge σ hP]

/-- A full-distance ball gives a uniform bound in the Section 6 charge
seminorm. -/
theorem stabilitySeminorm_le_of_stabilityDist_lt
    (σ τ : StabilityCondition.WithClassMap C v) {ε : ℝ} (hε : 0 < ε)
    (hd : stabilityDist σ τ < ENNReal.ofReal ε) :
    stabilitySeminorm C σ (τ.Z - σ.Z) ≤
      ENNReal.ofReal (stabilityChargeControl ε) := by
  unfold stabilitySeminorm
  refine iSup_le fun E ↦ iSup_le fun φ ↦ iSup_le fun hP ↦ iSup_le fun hE ↦ ?_
  apply ENNReal.ofReal_le_ofReal
  have hZpos : 0 < ‖σ.charge E‖ :=
    norm_pos_iff.mpr (σ.charge_ne_zero_of_semistable φ E hP hE)
  apply (div_le_iff₀ hZpos).2
  change ‖τ.charge E - σ.charge E‖ ≤
    stabilityChargeControl ε * ‖σ.charge E‖
  exact (norm_charge_sub_charge_lt_of_stabilityDist σ τ hP hE hε hd).le

/-- The charge-error coefficient can be made smaller than any prescribed
positive number while also keeping the distance radius below a prescribed
positive radius. -/
theorem exists_stabilityChargeControl_lt {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    ∃ ε : ℝ, 0 < ε ∧ ε < b ∧ stabilityChargeControl ε < a := by
  have hcont : ContinuousAt stabilityChargeControl 0 := by
    unfold stabilityChargeControl
    fun_prop
  have hcontrol : {x : ℝ | stabilityChargeControl x < a} ∈ 𝓝 0 := by
    exact hcont.preimage_mem_nhds (isOpen_Iio.mem_nhds (by simpa using ha))
  have hsmall : Set.Iio b ∈ 𝓝 (0 : ℝ) := isOpen_Iio.mem_nhds hb
  obtain ⟨r, hr, hrsub⟩ :=
    Metric.mem_nhds_iff.mp (Filter.inter_mem hcontrol hsmall)
  have hball : r / 2 ∈ Metric.ball (0 : ℝ) r := by
    rw [Metric.mem_ball, Real.dist_eq, sub_zero, abs_of_nonneg (by positivity)]
    linarith
  exact ⟨r / 2, by positivity, (hrsub hball).2, (hrsub hball).1⟩

/-- Every centered Section 6 basis neighborhood contains a centered full-
distance ball.  This is one of the two cofinality directions in Proposition
8.1, and the one that is **unconditional** — it does not take
`StabilityMassTriangleInequality`.

`hε8 : ε < 1 / 8` is stronger than this proof needs: it is consumed once, to
derive `hε1 : ε < 1` for `Real.sin_pos_of_pos_of_lt_pi`.  It is kept because
`ε < 1/8` is the radius convention of the whole `basisNhd` family
(`WeakStabilityCondition/StabilityCondition/Foundation/Deformation/StabilityTopology.lean`) and
matches `basisNhdFamily`'s generating predicate; weakening it here alone would
desynchronise this lemma from its siblings for no gain. -/
theorem exists_stabilityDist_ball_subset_basisNhd
    (σ : StabilityCondition.WithClassMap C v) {ε : ℝ}
    (hε : 0 < ε) (hε8 : ε < 1 / 8) :
    ∃ δ : ℝ, 0 < δ ∧
      {τ | stabilityDist σ τ < ENNReal.ofReal δ} ⊆ basisNhd C σ ε := by
  have hε1 : ε < 1 := by linarith
  have hsin : 0 < Real.sin (Real.pi * ε) :=
    Real.sin_pos_of_pos_of_lt_pi (mul_pos Real.pi_pos hε)
      (by nlinarith [Real.pi_pos])
  obtain ⟨δ, hδ, hδε, hcontrol⟩ :=
    exists_stabilityChargeControl_lt hsin hε
  refine ⟨δ, hδ, ?_⟩
  intro τ hτ
  constructor
  · exact lt_of_le_of_lt (stabilitySeminorm_le_of_stabilityDist_lt σ τ hδ hτ)
      ((ENNReal.ofReal_lt_ofReal_iff hsin).2 hcontrol)
  · exact lt_of_le_of_lt (slicingDist_le_stabilityDist σ τ)
      (lt_trans hτ ((ENNReal.ofReal_lt_ofReal_iff hε).2 hδε))

omit [IsTriangulated C] in
/-- The centered Section 6 neighborhoods are a neighborhood basis for the
already installed topology. -/
theorem nhds_hasBasis_basisNhd
    (σ : StabilityCondition.WithClassMap C v) :
    (𝓝 σ).HasBasis (fun ε : ℝ ↦ 0 < ε ∧ ε < 1 / 8)
      (fun ε ↦ basisNhd C σ ε) := by
  refine ⟨fun s ↦ ?_⟩
  constructor
  · intro hs
    obtain ⟨ε, hε, hε8, hsub⟩ :=
      exists_basisNhd_subset_of_mem_nhds C σ hs
    exact ⟨ε, ⟨hε, hε8⟩, hsub⟩
  · rintro ⟨ε, ⟨hε, hε8⟩, hsub⟩
    have hopen : IsOpen (basisNhd C σ ε) :=
      TopologicalSpace.isOpen_generateFrom_of_mem ⟨σ, ε, hε, hε8, rfl⟩
    exact Filter.mem_of_superset
      (hopen.mem_nhds (self_mem_basisNhd C σ hε (by linarith))) hsub

/-- The exact compatibility statement needed to turn `stabilityDist` into
Mathlib's extended metric without changing the already installed Section 6
topology. -/
def StabilityDistanceTopologyCompatible : Prop :=
  ∀ σ : StabilityCondition.WithClassMap C v,
    (𝓝 σ).HasBasis (fun r : ℝ≥0∞ ↦ 0 < r)
      (fun r ↦ {τ | stabilityDist σ τ < r})

/-- Once mass subadditivity across distinguished triangles is supplied, the
full-distance balls form a basis for the existing Section 6 topology.  This
packages both cofinality directions and is the exact hypothesis consumed by
`PseudoEMetricSpace.ofEDistOfTopology`. -/
@[cites "stmt:a520a8d4f877:bridgeland2007.prop-8.1" (relation := no_claim)
        (note := "Conditional topology-comparison substrate. All analytic estimates and both neighborhood cofinality directions are formalized here; Mass/Subadditivity/Triangle.lean supplies the proved mass premise and exposes the unconditional corollary. The citation remains no_claim pending exact-head source-faithfulness review and owner acceptance.")]
theorem stabilityDistanceTopologyCompatible_of_mass_triangle
    (htriangle : StabilityMassTriangleInequality (C := C) (v := v)) :
    StabilityDistanceTopologyCompatible (C := C) (v := v) := by
  intro σ
  apply (nhds_hasBasis_basisNhd σ).to_hasBasis
  · intro ε hε
    obtain ⟨δ, hδ, hsub⟩ :=
      exists_stabilityDist_ball_subset_basisNhd σ hε.1 hε.2
    exact ⟨ENNReal.ofReal δ, ENNReal.ofReal_pos.mpr hδ, hsub⟩
  · intro r hr
    by_cases hrtop : r = ⊤
    · subst r
      obtain ⟨ε, hε, hε8, hsub⟩ :=
        exists_basisNhd_subset_stabilityDist_ball htriangle σ (by norm_num : (0 : ℝ) < 1)
      refine ⟨ε, ⟨hε, hε8⟩, hsub.trans ?_⟩
      intro τ hτ
      exact lt_trans hτ ENNReal.ofReal_lt_top
    · have hrreal : 0 < r.toReal := ENNReal.toReal_pos hr.ne' hrtop
      obtain ⟨ε, hε, hε8, hsub⟩ :=
        exists_basisNhd_subset_stabilityDist_ball htriangle σ hrreal
      refine ⟨ε, ⟨hε, hε8⟩, ?_⟩
      simpa [ENNReal.ofReal_toReal hrtop] using hsub

/-- The compatible pseudo-extended-metric structure, constructed from the
existing topology.  This is deliberately a named definition, not an instance:
the instance is installed only after `StabilityDistanceTopologyCompatible` is
proved. -/
@[reducible] noncomputable def stabilityPseudoEMetricSpace
    (hcompat : StabilityDistanceTopologyCompatible (C := C) (v := v)) :
    PseudoEMetricSpace (StabilityCondition.WithClassMap C v) :=
  PseudoEMetricSpace.ofEDistOfTopology stabilityDist stabilityDist_self
    stabilityDist_comm stabilityDist_triangle hcompat

omit [IsTriangulated C] in
/-- Regression check for the instance-diamond issue: the topology inherited
from the compatible pseudo-extended metric is definitionally the Section 6
topology that was already present on stability conditions. -/
theorem stabilityPseudoEMetricSpace_toTopologicalSpace
    (hcompat : StabilityDistanceTopologyCompatible (C := C) (v := v)) :
    (stabilityPseudoEMetricSpace hcompat).toUniformSpace.toTopologicalSpace =
      (inferInstance : TopologicalSpace (StabilityCondition.WithClassMap C v)) :=
  rfl

omit [IsTriangulated C] in
/-- The extended distance field of the compatible structure is literally
`stabilityDist`; no coercion or replacement distance is introduced. -/
theorem stabilityPseudoEMetricSpace_edist
    (hcompat : StabilityDistanceTopologyCompatible (C := C) (v := v))
    (σ τ : StabilityCondition.WithClassMap C v) :
    @edist _ (stabilityPseudoEMetricSpace hcompat).toEDist σ τ =
      stabilityDist σ τ :=
  rfl

/-- With a surjective class map, separation upgrades the compatible
pseudo-extended metric to an extended metric.  As above this remains a named
definition until the topology comparison is closed. -/
@[reducible] noncomputable def stabilityEMetricSpace
    (hv : Function.Surjective v)
    (hcompat : StabilityDistanceTopologyCompatible (C := C) (v := v)) :
    EMetricSpace (StabilityCondition.WithClassMap C v) :=
  { stabilityPseudoEMetricSpace hcompat with
    eq_of_edist_eq_zero := fun h ↦ stabilityDist_eq_zero hv h }

/-- The separated extended-metric upgrade retains the same definitionally
compatible topology. -/
theorem stabilityEMetricSpace_toTopologicalSpace
    (hv : Function.Surjective v)
    (hcompat : StabilityDistanceTopologyCompatible (C := C) (v := v)) :
    (stabilityEMetricSpace hv hcompat).toPseudoEMetricSpace.toUniformSpace.toTopologicalSpace =
      (inferInstance : TopologicalSpace (StabilityCondition.WithClassMap C v)) :=
  rfl

/-- Mass-premise-parameterized end-to-end pseudo-extended-metric package.  Its topology is
definitionally the pre-existing Section 6 topology because it is routed
through `stabilityPseudoEMetricSpace`, not through a fresh metric topology. -/
@[reducible] noncomputable def stabilityPseudoEMetricSpaceOfMassTriangle
    (htriangle : StabilityMassTriangleInequality (C := C) (v := v)) :
    PseudoEMetricSpace (StabilityCondition.WithClassMap C v) :=
  stabilityPseudoEMetricSpace
    (stabilityDistanceTopologyCompatible_of_mass_triangle htriangle)

/-- Mass-premise-parameterized end-to-end extended-metric package for a
surjective class map.  The completed mass-subadditivity module supplies the
premise; no global instance is installed. -/
@[reducible] noncomputable def stabilityEMetricSpaceOfMassTriangle
    (hv : Function.Surjective v)
    (htriangle : StabilityMassTriangleInequality (C := C) (v := v)) :
    EMetricSpace (StabilityCondition.WithClassMap C v) :=
  stabilityEMetricSpace hv
    (stabilityDistanceTopologyCompatible_of_mass_triangle htriangle)

end

end CategoryTheory.Triangulated
