/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import Mathlib.Algebra.Exact.Basic
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.RingTheory.Finiteness.Finsupp
import Mathlib.RingTheory.Noetherian.Basic

/-!
# Rank--nullity at an exact middle term

`LinearMap.finrank_range_add_finrank_ker` splits the dimension of the source of a linear map
into rank and nullity. At the middle term of an exact pair `A → B → C` the kernel of the
second map is the range of the first, so the dimension of `B` is the sum of the two ranks
around it. Both alternating-sum arguments, the bounded one in `Algebra/Exact/Sequence.lean`
and the `ℤ`-indexed one in `Algebra/Homology/EulerCharacteristic.lean`, consume this.

`k` is a division ring, not a field: that is what `LinearMap.finrank_range_add_finrank_ker`
asks for, and commutativity is used nowhere.
-/

namespace Function.Exact

variable {k : Type*} [DivisionRing k] {A B C : Type*} [AddCommGroup A] [AddCommGroup B]
  [AddCommGroup C] [Module k A] [Module k B] [Module k C] [Module.Finite k B]

/-- Rank--nullity at an exact middle term: an exact `A → B → C` splits `dim B` into the two
ranks around it. -/
theorem finrank_eq_finrank_range_add_finrank_range {f : A →ₗ[k] B} {g : B →ₗ[k] C}
    (h : Function.Exact f g) :
    Module.finrank k B =
      Module.finrank k (LinearMap.range f) + Module.finrank k (LinearMap.range g) := by
  have hr := g.finrank_range_add_finrank_ker
  rw [h.linearMap_ker_eq] at hr
  omega

end Function.Exact

namespace Function.Exact

variable {k : Type*} [DivisionRing k] {A B C : Type*} [AddCommGroup A] [AddCommGroup B]
  [AddCommGroup C] [Module k A] [Module k B] [Module k C]

/-- **The middle term of an exact pair between finite modules is finite.**

`B` is generated by a generating set of the kernel of `g`, which is the range of `f` and so
finite, together with lifts of a generating set of the range of `g`, a submodule of the finite
`C`. This is the step a dévissage takes at every degree: `Hⁱ(G) → Hⁱ(F) → Hⁱ⁺¹(K)` with the
outer terms finite-dimensional. -/
theorem module_finite_of_finite {f : A →ₗ[k] B} {g : B →ₗ[k] C} (h : Function.Exact f g)
    [Module.Finite k A] [Module.Finite k C] : Module.Finite k B := by
  haveI : IsNoetherian k C := isNoetherian_of_isNoetherianRing_of_finite k C
  refine Module.finite_def.mpr (Submodule.fg_of_fg_map_of_fg_inf_ker g ?_ ?_)
  · exact IsNoetherian.noetherian _
  · rw [top_inf_eq, h.linearMap_ker_eq]
    exact Module.Finite.iff_fg.mp (Module.Finite.range f)

end Function.Exact
