/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import Mathlib.CategoryTheory.Triangulated.Functor
import Mathlib.CategoryTheory.Triangulated.Generators
import Mathlib.CategoryTheory.Triangulated.Adjunction

/-!
# Functor transport for triangulated generators

## Main results

* `CategoryTheory.ObjectProperty.triangEnvelopeIter_map_obj_of_le` transports a stage when
  generators satisfy an arbitrary target property.
* `CategoryTheory.ObjectProperty.triangEnvelopeIter_map_obj` and
  `CategoryTheory.ObjectProperty.triangEnvelopeIter_map_le` specialize transport to
  `CategoryTheory.ObjectProperty.map`.
* `CategoryTheory.Triangulated.singleton_triangEnvelopeIter_map_obj` transports the tower
  generated by a single object.
* `CategoryTheory.Triangulated.singleton_triangEnvelopeIter_top_of_retract_coverage` preserves a
  fixed strong-generation stage under retract coverage.
* `CategoryTheory.Triangulated.isStrongTriangulatedGenerator_map_of_retract_coverage` transports
  a strong generator when every target object is a retract of a functor image.
* `CategoryTheory.Triangulated.exists_isStrongTriangulatedGenerator_iff_of_equiv` records
  invariance of strong generation under a triangulated equivalence.

## Implementation notes

A stage induction transports shifts, binary products, retracts, and distinguished triangles
separately, in the order used by Mathlib's envelope tower. The arbitrary target property lets
callers specialize directly to a singleton without first identifying its essential-image
property. The pointwise theorem asserts only forward transport: the reverse inclusion can fail
because a target envelope can contain objects outside the functor's essential image.

The source and target need only be pretriangulated with the structures required by
`CategoryTheory.ObjectProperty.triangEnvelopeIter`. The functor hypotheses are exactly
`[F.CommShift ℤ] [F.IsTriangulated]`; Mathlib derives additivity and preservation of binary
products. No octahedral `IsTriangulated` structure on either ambient category is required.

## References

* Mathlib's `CategoryTheory.ObjectProperty.triangEnvelopeIter` is defined in
  `Mathlib.CategoryTheory.Triangulated.Generators`.
* Rouquier, *Dimensions of triangulated categories*.

## Tags

triangulated category, exact functor, generation, strong generator
-/

universe v u v' u'

namespace CategoryTheory.ObjectProperty

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated

variable {C : Type u} {D : Type u'} [Category.{v} C] [Category.{v'} D]
  [HasZeroObject C] [HasZeroObject D] [HasShift C ℤ] [HasShift D ℤ]
  [Preadditive C] [Preadditive D]
  [∀ n : ℤ, (shiftFunctor C n).Additive]
  [∀ n : ℤ, (shiftFunctor D n).Additive]
  [Pretriangulated C] [Pretriangulated D]

omit [HasZeroObject C] [HasZeroObject D] [Preadditive C] [Preadditive D]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [∀ n : ℤ, (shiftFunctor D n).Additive]
  [Pretriangulated C] [Pretriangulated D] in
private lemma shiftClosure_map_obj (F : C ⥤ D) [F.CommShift ℤ]
    (P : ObjectProperty C) (Q : ObjectProperty D)
    (h : ∀ X, P X → Q (F.obj X)) (X : C)
    (hX : P.shiftClosure ℤ X) : Q.shiftClosure ℤ (F.obj X) := by
  rcases hX with ⟨Y, n, e, hY⟩
  exact ⟨F.obj Y, n, (F.mapIso e).trans ((F.commShiftIso n).app Y), h Y hY⟩

omit [HasZeroObject C] [HasZeroObject D] [HasShift C ℤ] [HasShift D ℤ]
  [Preadditive C] [Preadditive D]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [∀ n : ℤ, (shiftFunctor D n).Additive]
  [Pretriangulated C] [Pretriangulated D] in
private lemma binaryProductsClosure_map_obj (F : C ⥤ D)
    [PreservesLimitsOfShape (Discrete WalkingPair) F]
    (P : ObjectProperty C) (Q : ObjectProperty D)
    (h : ∀ X, P X → Q (F.obj X)) (X : C)
    (hX : P.binaryProductsClosure X) : Q.binaryProductsClosure (F.obj X) := by
  have hbase : P ≤ Q.binaryProductsClosure.inverseImage F := by
    intro Y hY
    exact Q.le_limitsClosure _ _ (h Y hY)
  exact limitsClosure_le hbase X hX

omit [HasZeroObject C] [HasZeroObject D] [HasShift C ℤ] [HasShift D ℤ]
  [Preadditive C] [Preadditive D]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [∀ n : ℤ, (shiftFunctor D n).Additive]
  [Pretriangulated C] [Pretriangulated D] in
private lemma retractClosure_map_obj (F : C ⥤ D)
    (P : ObjectProperty C) (Q : ObjectProperty D)
    (h : ∀ X, P X → Q (F.obj X)) (X : C)
    (hX : P.retractClosure X) : Q.retractClosure (F.obj X) := by
  rcases hX with ⟨Y, hY, ⟨r⟩⟩
  exact ⟨F.obj Y, h Y hY, ⟨r.map F⟩⟩

private lemma extensionProduct_map_obj (F : C ⥤ D) [F.CommShift ℤ] [F.IsTriangulated]
    (P R : ObjectProperty C) (Q S : ObjectProperty D)
    (hP : ∀ X, P X → Q (F.obj X)) (hR : ∀ X, R X → S (F.obj X)) (X : C)
    (hX : extensionProduct P R X) : extensionProduct Q S (F.obj X) := by
  rcases hX with ⟨Y, Z, f, g, t, ht, hY, hZ⟩
  exact ⟨F.obj Y, F.obj Z, F.map f, F.map g,
    F.map t ≫ (F.commShiftIso (1 : ℤ)).hom.app Y,
    F.map_distinguished _ ht, hP Y hY, hR Z hZ⟩

/-- Induct on the envelope stage, transporting shifts, binary products, retracts, and distinguished
triangles separately. The arbitrary target property lets callers specialize directly to a
singleton without first identifying its essential-image property. -/
theorem triangEnvelopeIter_map_obj_of_le (F : C ⥤ D) [F.CommShift ℤ] [F.IsTriangulated]
    (P : ObjectProperty C) (Q : ObjectProperty D) (h : ∀ X, P X → Q (F.obj X))
    (X : C) (n : ℕ) (hX : P.triangEnvelopeIter n X) :
    Q.triangEnvelopeIter n (F.obj X) := by
  have hshift : ∀ X, P.shiftClosure ℤ X → Q.shiftClosure ℤ (F.obj X) :=
    fun X hX => shiftClosure_map_obj F P Q h X hX
  have hproducts : ∀ X, (P.shiftClosure ℤ).binaryProductsClosure X →
      (Q.shiftClosure ℤ).binaryProductsClosure (F.obj X) :=
    fun X hX => binaryProductsClosure_map_obj F _ _ hshift X hX
  have hbase : ∀ X, ((P.shiftClosure ℤ).binaryProductsClosure).retractClosure X →
      ((Q.shiftClosure ℤ).binaryProductsClosure).retractClosure (F.obj X) :=
    fun X hX => retractClosure_map_obj F _ _ hproducts X hX
  induction n generalizing X with
  | zero =>
    simpa only [triangEnvelopeIter_zero] using
      hbase X (by simpa only [triangEnvelopeIter_zero] using hX)
  | succ n ih =>
    have hX' :
        ((P.shiftClosure ℤ).binaryProductsClosure.retractClosure.extensionProduct
          (P.triangEnvelopeIter n)).retractClosure X := by
      simpa only [triangEnvelopeIter_succ] using hX
    have hY := retractClosure_map_obj F _ _
      (extensionProduct_map_obj F _ _ _ _ hbase (fun X hX => ih X hX)) X hX'
    simpa only [triangEnvelopeIter_succ] using hY

/-- An exact functor carries every object in stage `n` of the source envelope into stage `n`
generated by the essential-image property in the target. This is a forward pointwise statement;
it does not assert that every object in the target stage lifts to the source. -/
theorem triangEnvelopeIter_map_obj (F : C ⥤ D) [F.CommShift ℤ] [F.IsTriangulated]
    (P : ObjectProperty C) (n : ℕ) {X : C} (hX : P.triangEnvelopeIter n X) :
    (P.map F).triangEnvelopeIter n (F.obj X) :=
  triangEnvelopeIter_map_obj_of_le F P (P.map F) (fun _ hP => P.prop_map_obj F hP) X n hX

/-- The object-property form of
`CategoryTheory.ObjectProperty.triangEnvelopeIter_map_obj`, for
`CategoryTheory.ObjectProperty.map` applied to `F`. The direction is forward; the reverse
inclusion fails for a general functor. -/
theorem triangEnvelopeIter_map_le (F : C ⥤ D) [F.CommShift ℤ] [F.IsTriangulated]
    (P : ObjectProperty C) (n : ℕ) :
    (P.triangEnvelopeIter n).map F ≤ (P.map F).triangEnvelopeIter n := by
  rintro Y ⟨X, hX, ⟨e⟩⟩
  exact ((P.map F).triangEnvelopeIter n).prop_of_iso e (triangEnvelopeIter_map_obj F P n hX)

end CategoryTheory.ObjectProperty

namespace CategoryTheory.Triangulated

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated

variable {C : Type u} {D : Type u'} [Category.{v} C] [Category.{v'} D]
  [HasZeroObject C] [HasZeroObject D] [HasShift C ℤ] [HasShift D ℤ]
  [Preadditive C] [Preadditive D]
  [∀ n : ℤ, (shiftFunctor C n).Additive]
  [∀ n : ℤ, (shiftFunctor D n).Additive]
  [Pretriangulated C] [Pretriangulated D]

/-- Stage membership generated by a single object transports to the stage generated by its image. -/
theorem singleton_triangEnvelopeIter_map_obj (F : C ⥤ D)
    [F.CommShift ℤ] [F.IsTriangulated] (G : C) (n : ℕ) {X : C}
    (hX : (ObjectProperty.singleton G).triangEnvelopeIter n X) :
    (ObjectProperty.singleton (F.obj G)).triangEnvelopeIter n (F.obj X) := by
  apply ObjectProperty.triangEnvelopeIter_map_obj_of_le F _ _ _ X n hX
  intro X hX
  obtain rfl := (ObjectProperty.singleton_iff G X).1 hX
  exact (ObjectProperty.singleton_iff _ _).2 rfl

/-- A fixed envelope stage generated by one object remains the whole target when every target
object is a retract of an image. The stage index is preserved. -/
theorem singleton_triangEnvelopeIter_top_of_retract_coverage (F : C ⥤ D)
    [F.CommShift ℤ] [F.IsTriangulated]
    (hCover : ∀ Y : D, ∃ X : C, Nonempty (Retract Y (F.obj X))) (G : C) (n : ℕ)
    (hn : (ObjectProperty.singleton G).triangEnvelopeIter n = ⊤) :
    (ObjectProperty.singleton (F.obj G)).triangEnvelopeIter n = ⊤ := by
  apply top_le_iff.mp
  intro Y _
  obtain ⟨X, ⟨r⟩⟩ := hCover Y
  exact ((ObjectProperty.singleton (F.obj G)).triangEnvelopeIter n).prop_of_retract r
    (singleton_triangEnvelopeIter_map_obj F G n (by rw [hn]; trivial))

/-- A triangulated functor carries a strong generator to a strong generator whenever every target
object is a retract of an object in its image. Essential surjectivity supplies this retract
coverage, but the explicit premise also applies to functors whose image is only retract-dense. -/
theorem isStrongTriangulatedGenerator_map_of_retract_coverage (F : C ⥤ D)
    [F.CommShift ℤ] [F.IsTriangulated]
    (hCover : ∀ Y : D, ∃ X : C, Nonempty (Retract Y (F.obj X))) (G : C)
    (hG : (ObjectProperty.singleton G).IsStrongTriangulatedGenerator) :
    (ObjectProperty.singleton (F.obj G)).IsStrongTriangulatedGenerator := by
  obtain ⟨n, hn⟩ := hG
  exact ⟨n, singleton_triangEnvelopeIter_top_of_retract_coverage F hCover G n hn⟩

/-- Strong generation is invariant under a triangulated equivalence. The inverse's compatible
shift structure and exactness follow from the equivalence adjunction in Mathlib. -/
theorem exists_isStrongTriangulatedGenerator_iff_of_equiv (E : C ≌ D)
    [E.functor.CommShift ℤ] [E.functor.IsTriangulated] :
    (∃ G : C, (ObjectProperty.singleton G).IsStrongTriangulatedGenerator) ↔
      ∃ H : D, (ObjectProperty.singleton H).IsStrongTriangulatedGenerator := by
  constructor
  · rintro ⟨G, hG⟩
    exact ⟨E.functor.obj G, isStrongTriangulatedGenerator_map_of_retract_coverage E.functor
      (fun Y => by
        let X := E.functor.objPreimage Y
        exact ⟨X, ⟨(E.functor.objObjPreimageIso Y).symm.retract⟩⟩) G hG⟩
  · rintro ⟨H, hH⟩
    letI := E.commShiftInverse ℤ
    letI := E.commShift_of_functor ℤ
    letI := E.toAdjunction.isTriangulated_rightAdjoint
    exact ⟨E.inverse.obj H, isStrongTriangulatedGenerator_map_of_retract_coverage E.inverse
      (fun X => by
        let Y := E.inverse.objPreimage X
        exact ⟨Y, ⟨(E.inverse.objObjPreimageIso X).symm.retract⟩⟩) H hH⟩

end CategoryTheory.Triangulated
