/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.Support.Predicate.Quotient
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.Support.Predicate.ZeroChargeLattice
import Mathlib.Algebra.Module.Torsion.Field
import Mathlib.LinearAlgebra.TensorProduct.Tower

/-!
# Comparing the integral and real zero-charge quotients

Definition 21.9 of arXiv:1902.08184v4 forms a free abelian quotient by the
saturated subgroup generated by zero-charge classes.  Definition 21.15(4)
puts the uniform quadratic form on a real quotient.  This file supplies the
previously missing comparison map between those two constructions.

The comparison is canonical once the integral classes are realized in the
real vector space and the chosen generators land in the killed subspace.  It
is *not* automatically an equivalence: the equivalence constructor below
requires a proof that the scalar-extended comparison is bijective.
-/

namespace CategoryTheory.Triangulated.StabilityCondition.Support

namespace ZeroChargeLattice

noncomputable section

open scoped TensorProduct

variable {Λ V : Type*} [AddCommGroup Λ]
  [AddCommGroup V] [Module ℝ V]

private local instance realModuleIsAddTorsionFree
    (M : Type*) [AddCommGroup M] [Module ℝ M] : IsAddTorsionFree M :=
  IsAddTorsionFree.of_isTorsionFree ℝ M

/-- The map from the saturated integral quotient to the real quotient.

The hypothesis says exactly that every chosen zero-charge generator is killed
by the real quotient.  Saturation then makes the map descend because a real
vector space is torsion-free as an additive group. -/
def quotientToRealQuotient (S : Set Λ) (ι : Λ →+ V)
    (V₀ : Submodule ℝ V) (hS : ∀ x ∈ S, ι x ∈ V₀) :
    Quotient S →+ (V ⧸ V₀) :=
  quotientCharge S (V₀.mkQ.toAddMonoidHom.comp ι) fun x hx => by
    change V₀.mkQ (ι x) = 0
    rw [← LinearMap.mem_ker, Submodule.ker_mkQ]
    exact hS x hx

/-- The integral comparison sends the class of `x` to its realized class in
the real quotient. -/
@[simp]
theorem quotientToRealQuotient_quotientClass (S : Set Λ) (ι : Λ →+ V)
    (V₀ : Submodule ℝ V) (hS : ∀ x ∈ S, ι x ∈ V₀) (x : Λ) :
    quotientToRealQuotient S ι V₀ hS (quotientClass S x) = V₀.mkQ (ι x) :=
  rfl

/-- Scalar extension of the saturated integral quotient to `ℝ`.

The scalar factor is placed first so Mathlib's canonical left-module
structure makes this tensor product an `ℝ`-module without any auxiliary
choice. -/
abbrev RealScalarExtension (S : Set Λ) := ℝ ⊗[ℤ] Quotient S

/-- The canonical real-linear comparison from the scalar-extended integral
quotient to the real quotient. -/
def scalarExtensionComparison (S : Set Λ) (ι : Λ →+ V)
    (V₀ : Submodule ℝ V) (hS : ∀ x ∈ S, ι x ∈ V₀) :
    RealScalarExtension S →ₗ[ℝ] (V ⧸ V₀) :=
  TensorProduct.AlgebraTensorModule.lift
    { toFun := fun r => r • (quotientToRealQuotient S ι V₀ hS).toIntLinearMap
      map_add' := by
        intro r s
        ext x
        simp [add_smul]
      map_smul' := by
        intro r s
        ext x
        simp [mul_smul] }

/-- Formula for the scalar-extension comparison on pure tensors. -/
@[simp]
theorem scalarExtensionComparison_tmul (S : Set Λ) (ι : Λ →+ V)
    (V₀ : Submodule ℝ V) (hS : ∀ x ∈ S, ι x ∈ V₀)
    (r : ℝ) (x : Quotient S) :
    scalarExtensionComparison S ι V₀ hS (r ⊗ₜ[ℤ] x) =
      r • quotientToRealQuotient S ι V₀ hS x :=
  rfl

/-- On a scalar-extended original class, the comparison is the expected
real multiple of its image in the quotient. -/
@[simp]
theorem scalarExtensionComparison_quotientClass (S : Set Λ) (ι : Λ →+ V)
    (V₀ : Submodule ℝ V) (hS : ∀ x ∈ S, ι x ∈ V₀)
    (r : ℝ) (x : Λ) :
    scalarExtensionComparison S ι V₀ hS
        (r ⊗ₜ[ℤ] quotientClass S x) = r • V₀.mkQ (ι x) := by
  rw [scalarExtensionComparison_tmul, quotientToRealQuotient_quotientClass]

/-- A real-linear equivalence exists with the canonical comparison as its
underlying map exactly when that comparison is bijective.  This records the
missing comparison hypothesis explicitly instead of treating it as automatic. -/
theorem exists_scalarExtensionEquiv_iff (S : Set Λ) (ι : Λ →+ V)
    (V₀ : Submodule ℝ V) (hS : ∀ x ∈ S, ι x ∈ V₀) :
    (∃ e : RealScalarExtension S ≃ₗ[ℝ] (V ⧸ V₀),
        e.toLinearMap = scalarExtensionComparison S ι V₀ hS) ↔
      Function.Bijective (scalarExtensionComparison S ι V₀ hS) := by
  constructor
  · rintro ⟨e, he⟩
    rw [← he]
    exact e.bijective
  · intro h
    exact ⟨LinearEquiv.ofBijective (scalarExtensionComparison S ι V₀ hS) h, rfl⟩

/-- Upgrade the canonical comparison to a linear equivalence when its
bijectivity has been proved in the geometric or numerical model at hand. -/
def scalarExtensionEquiv (S : Set Λ) (ι : Λ →+ V)
    (V₀ : Submodule ℝ V) (hS : ∀ x ∈ S, ι x ∈ V₀)
    (hbij : Function.Bijective (scalarExtensionComparison S ι V₀ hS)) :
    RealScalarExtension S ≃ₗ[ℝ] (V ⧸ V₀) :=
  LinearEquiv.ofBijective (scalarExtensionComparison S ι V₀ hS) hbij

@[simp]
theorem scalarExtensionEquiv_apply (S : Set Λ) (ι : Λ →+ V)
    (V₀ : Submodule ℝ V) (hS : ∀ x ∈ S, ι x ∈ V₀)
    (hbij : Function.Bijective (scalarExtensionComparison S ι V₀ hS))
    (x : RealScalarExtension S) :
    scalarExtensionEquiv S ι V₀ hS hbij x =
      scalarExtensionComparison S ι V₀ hS x :=
  rfl

end

end ZeroChargeLattice

end CategoryTheory.Triangulated.StabilityCondition.Support
