/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.WeakStabilityCondition.Support.Predicate.Uniform
import Mathlib.Analysis.Normed.Group.Quotient

/-!
# Uniform support after killing zero-charge classes

Definition 21.9 of arXiv:1902.08184v4 first quotients the class lattice by
the saturated subgroup generated by zero-charge heart classes.  Definition
21.15 then places its quadratic form on the resulting real quotient.  This
file models the real-linear part of that construction.

The quotient is genuine: the form has domain `V ⧸ V₀`, the charge is the
canonical lift through `Submodule.mkQ`, and the selected semistable classes
are mapped into that quotient.  In particular, no condition is imposed on a
pullback form along `V₀.mkQ`; such a pullback necessarily vanishes on `V₀`
and therefore cannot be negative definite on the original kernel.
-/

namespace CategoryTheory.Triangulated.WeakStabilityCondition.Support

noncomputable section

variable {I V W : Type*}
  [NormedAddCommGroup V] [NormedSpace ℝ V] [FiniteDimensional ℝ V]
  [NormedAddCommGroup W] [NormedSpace ℝ W]

private local instance quotientSubmoduleClosed (V₀ : Submodule ℝ V) :
    IsClosed (V₀ : Set V) :=
  V₀.closed_of_finiteDimensional

/-- The charge induced on a quotient by a subspace contained in its kernel. -/
def quotientCharge (V₀ : Submodule ℝ V) (Z : V →ₗ[ℝ] W)
    (hV₀ : V₀ ≤ LinearMap.ker Z) : (V ⧸ V₀) →ₗ[ℝ] W :=
  V₀.liftQ Z hV₀

omit [FiniteDimensional ℝ V] in
theorem quotientCharge_mkQ
    (V₀ : Submodule ℝ V) (Z : V →ₗ[ℝ] W)
    (hV₀ : V₀ ≤ LinearMap.ker Z) (x : V) :
    quotientCharge V₀ Z hV₀ (V₀.mkQ x) = Z x :=
  rfl

/-- The image in the quotient of each selected locus. -/
def quotientFamilyLocus (V₀ : Submodule ℝ V) (S : I → Set V) :
    I → Set (V ⧸ V₀) :=
  fun i => V₀.mkQ '' S i

/-- Uniform genuine quadratic support on the quotient `V ⧸ V₀`.

The proof `hV₀` is part of the input so the charge is definitionally the
canonical quotient charge. -/
def HasUniformQuadraticSupportPropertyModulo
    (V₀ : Submodule ℝ V) (Z : V →ₗ[ℝ] W)
    (hV₀ : V₀ ≤ LinearMap.ker Z) (S : I → Set V) : Prop :=
  HasUniformQuadraticSupportProperty (quotientCharge V₀ Z hV₀)
    (quotientFamilyLocus V₀ S)

/-- Unfolded source-facing form of quotient support: one quadratic form on
the quotient, nonnegative on every mapped selected class, and negative
definite on the kernel of the descended charge. -/
theorem hasUniformQuadraticSupportPropertyModulo_iff
    (V₀ : Submodule ℝ V) (Z : V →ₗ[ℝ] W)
    (hV₀ : V₀ ≤ LinearMap.ker Z) (S : I → Set V) :
    HasUniformQuadraticSupportPropertyModulo V₀ Z hV₀ S ↔
      ∃ Q : QuadraticForm ℝ (V ⧸ V₀),
        (∀ i x, x ∈ S i → 0 ≤ Q (V₀.mkQ x)) ∧
        ∀ y : V ⧸ V₀, quotientCharge V₀ Z hV₀ y = 0 →
          y ≠ 0 → Q y < 0 := by
  constructor
  · rintro ⟨Q, hnonneg, hneg⟩
    refine ⟨Q, ?_, hneg⟩
    intro i x hx
    exact hnonneg i (V₀.mkQ x) ⟨x, hx, rfl⟩
  · rintro ⟨Q, hnonneg, hneg⟩
    refine ⟨Q, ?_, hneg⟩
    intro i y hy
    obtain ⟨x, hx, rfl⟩ := hy
    exact hnonneg i x hx

/-- Quotient support supplies genuine quadratic support on each individual
fiber locus. -/
theorem HasUniformQuadraticSupportPropertyModulo.fiber
    {V₀ : Submodule ℝ V} {Z : V →ₗ[ℝ] W}
    {hV₀ : V₀ ≤ LinearMap.ker Z} {S : I → Set V}
    (h : HasUniformQuadraticSupportPropertyModulo V₀ Z hV₀ S) (i : I) :
    HasQuadraticSupportProperty (quotientCharge V₀ Z hV₀)
      (V₀.mkQ '' S i) :=
  HasUniformQuadraticSupportProperty.fiber h i

/-- Hence every quotient fiber locus satisfies the norm formulation of the
support property as well. -/
theorem HasUniformQuadraticSupportPropertyModulo.hasSupportProperty
    {V₀ : Submodule ℝ V} {Z : V →ₗ[ℝ] W}
    {hV₀ : V₀ ≤ LinearMap.ker Z} {S : I → Set V}
    (h : HasUniformQuadraticSupportPropertyModulo V₀ Z hV₀ S) (i : I) :
    HasSupportProperty (quotientCharge V₀ Z hV₀) (V₀.mkQ '' S i) :=
  (HasUniformQuadraticSupportProperty.fiber h i).hasSupportProperty

omit [FiniteDimensional ℝ V] in
/-- Every class in the killed subspace maps to zero in the quotient. -/
theorem mkQ_eq_zero_of_mem
    (V₀ : Submodule ℝ V) {x : V} (hx : x ∈ V₀) : V₀.mkQ x = 0 := by
  apply LinearMap.mem_ker.mp
  rw [Submodule.ker_mkQ]
  exact hx

/-- A constant selected locus gives a constant quotient-supported family. -/
theorem HasQuadraticSupportProperty.constant_modulo
    (V₀ : Submodule ℝ V) (Z : V →ₗ[ℝ] W)
    (hV₀ : V₀ ≤ LinearMap.ker Z) {S : Set V}
    (h : HasQuadraticSupportProperty (quotientCharge V₀ Z hV₀)
      (V₀.mkQ '' S)) (I : Type*) :
    HasUniformQuadraticSupportPropertyModulo V₀ Z hV₀ (fun _ : I => S) :=
  h.constant I

end

end CategoryTheory.Triangulated.WeakStabilityCondition.Support
