/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Tactic

/-!
# Grothendieck presentations

This file owns the algebraic quotient used by the repository's triangulated
Grothendieck group. A presentation consists of generators and three-term
relations `middle = left + right`; its group is the free abelian group on the
generators modulo those relations.
-/

noncomputable section

universe u v u' v' u'' v''

namespace CategoryTheory

/-- A presentation by three-term additive relations. -/
structure GrothendieckPresentation (Generator : Type u) (Relation : Type v) where
  /-- The left term of a relation. -/
  left : Relation → Generator
  /-- The middle term of a relation. -/
  middle : Relation → Generator
  /-- The right term of a relation. -/
  right : Relation → Generator

namespace GrothendieckPresentation

variable {Generator : Type u} {Relation : Type v}
  (P : GrothendieckPresentation Generator Relation)

/-- The subgroup generated by the relation elements
`[middle] - [left] - [right]`. -/
def relationSubgroup : AddSubgroup (FreeAbelianGroup Generator) :=
  AddSubgroup.closure
    {x | ∃ r : Relation,
      x = FreeAbelianGroup.of (P.middle r) - FreeAbelianGroup.of (P.left r) -
        FreeAbelianGroup.of (P.right r)}

/-- The abelian group presented by `P`. -/
abbrev Group : Type _ := FreeAbelianGroup Generator ⧸ P.relationSubgroup

instance : AddCommGroup P.Group :=
  inferInstanceAs (AddCommGroup (FreeAbelianGroup Generator ⧸ P.relationSubgroup))

/-- The class of a generator in the presented group. -/
def of (X : Generator) : P.Group :=
  QuotientAddGroup.mk (FreeAbelianGroup.of X)

/-- The defining three-term relation in the presented group. -/
theorem of_relation (r : Relation) :
    P.of (P.middle r) = P.of (P.left r) + P.of (P.right r) := by
  simp only [of, Group]
  apply _root_.Quotient.sound
  change QuotientAddGroup.leftRel _ _ _
  rw [QuotientAddGroup.leftRel_apply]
  have h : FreeAbelianGroup.of (P.middle r) - FreeAbelianGroup.of (P.left r) -
      FreeAbelianGroup.of (P.right r) ∈ P.relationSubgroup :=
    AddSubgroup.subset_closure ⟨r, rfl⟩
  convert P.relationSubgroup.neg_mem h using 1
  abel

/-- A function respects a Grothendieck presentation when it sends every
three-term relation to an additive equality. -/
class IsAdditive {A : Type*} [AddCommGroup A] (f : Generator → A) : Prop where
  additive : ∀ r : Relation, f (P.middle r) = f (P.left r) + f (P.right r)

/-- The universal additive map out of a Grothendieck presentation. -/
def lift {A : Type*} [AddCommGroup A] (f : Generator → A) [P.IsAdditive f] : P.Group →+ A :=
  QuotientAddGroup.lift P.relationSubgroup (FreeAbelianGroup.lift f)
    ((AddSubgroup.closure_le _).mpr fun x ⟨r, hx⟩ ↦ by
      simp only [SetLike.mem_coe, AddMonoidHom.mem_ker, hx, map_sub,
        FreeAbelianGroup.lift_apply_of]
      rw [IsAdditive.additive (P := P) (f := f) r]
      abel)

@[simp]
theorem lift_of {A : Type*} [AddCommGroup A] (f : Generator → A) [P.IsAdditive f]
    (X : Generator) : P.lift f (P.of X) = f X :=
  FreeAbelianGroup.lift_apply_of f X

/-- Additive maps out of the presented group are determined by generator
classes. -/
@[ext 1100]
theorem hom_ext {A : Type*} [AddCommGroup A] {f g : P.Group →+ A}
    (h : ∀ X : Generator, f (P.of X) = g (P.of X)) : f = g :=
  AddMonoidHom.ext fun x => by
    induction x using QuotientAddGroup.induction_on with
    | H x =>
      induction x using FreeAbelianGroup.induction_on with
      | zero => simp
      | of X => exact h X
      | neg x ih => simp [ih]
      | add x y ihx ihy => simp [ihx, ihy]

/-- Induction on a presented Grothendieck group through generators and the
abelian-group operations. -/
@[elab_as_elim]
theorem induction_on {motive : P.Group → Prop} (x : P.Group)
    (of : ∀ X : Generator, motive (P.of X))
    (zero : motive 0)
    (neg : ∀ a, motive a → motive (-a))
    (add : ∀ a b, motive a → motive b → motive (a + b)) : motive x := by
  induction x using QuotientAddGroup.induction_on with
  | H x =>
    induction x using FreeAbelianGroup.induction_on with
    | zero => simpa using zero
    | of X => exact of X
    | neg x ih => simpa using neg _ ih
    | add x y ihx ihy => simpa using add _ _ ihx ihy

instance isAdditive_of : P.IsAdditive P.of where
  additive := P.of_relation

/-- A generator map respecting relations induces a homomorphism of presented
Grothendieck groups. -/
def map {Generator' : Type u'} {Relation' : Type v'}
    {Q : GrothendieckPresentation Generator' Relation'} (f : Generator → Generator')
    (hf : P.IsAdditive (Q.of ∘ f)) : P.Group →+ Q.Group :=
  P.lift (Q.of ∘ f)

@[simp]
theorem map_of {Generator' : Type u'} {Relation' : Type v'}
    {Q : GrothendieckPresentation Generator' Relation'} (f : Generator → Generator')
    (hf : P.IsAdditive (Q.of ∘ f)) (X : Generator) :
    P.map f hf (P.of X) = Q.of (f X) :=
  P.lift_of (Q.of ∘ f) X

/-- A compatible relation map proves that the generator map is additive. -/
theorem IsAdditive.of_relationMap {Generator' : Type u'} {Relation' : Type v'}
    {Q : GrothendieckPresentation Generator' Relation'}
    (fGenerator : Generator → Generator') (fRelation : Relation → Relation')
    (hleft : ∀ r, fGenerator (P.left r) = Q.left (fRelation r))
    (hmiddle : ∀ r, fGenerator (P.middle r) = Q.middle (fRelation r))
    (hright : ∀ r, fGenerator (P.right r) = Q.right (fRelation r)) :
    P.IsAdditive (Q.of ∘ fGenerator) where
  additive r := by
    simp only [Function.comp_apply]
    rw [hmiddle, hleft, hright]
    exact Q.of_relation (fRelation r)

theorem map_id : P.map id ⟨P.of_relation⟩ = AddMonoidHom.id P.Group := by
  apply P.hom_ext
  intro X
  simp

variable {Generator : Type u} {Relation : Type v}
  {P : GrothendieckPresentation Generator Relation} in
/-- Composition law for maps of Grothendieck presentations. -/
theorem map_comp {Generator' : Type u'} {Relation' : Type v'}
    {Q : GrothendieckPresentation Generator' Relation'}
    {Generator'' : Type u''} {Relation'' : Type v''}
    {R : GrothendieckPresentation Generator'' Relation''}
    (f : Generator → Generator') (g : Generator' → Generator'')
    (hf : P.IsAdditive (Q.of ∘ f))
    (hg : Q.IsAdditive (R.of ∘ g))
    (hgf : P.IsAdditive (R.of ∘ g ∘ f)) :
    P.map (g ∘ f) hgf = (Q.map g hg).comp (P.map f hf) := by
  apply P.hom_ext
  intro X
  simp

end GrothendieckPresentation

end CategoryTheory
