/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.Numerical.RiemannRoch.General
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Core.GradedBasis
import Mathlib.RingTheory.AdjoinRoot

/-!
# The intersection ring of a Picard-rank-one variety, in every dimension

`DerivedAlgGeo/AlgebraicGeometry/Numerical/Examples/Surface/RankOne.lean` builds the
numerical intersection ring of a surface with `Pic X = ℤ·H` by hand at `n = 2`. Nothing in
that construction is two-dimensional: for a smooth projective `X` of dimension `n` whose
numerical intersection ring is generated by one ample class `H`, the ring is `ℚ[t]/(t^{n+1})`
with `t = H`, graded by codimension, and the degree map is pinned by where it sends `Hⁿ`.

This file does that construction once, for arbitrary `n`, and hands back a constructor for
`NumericalVarietyData`. A model then costs exactly four numbers-worth of input: the degree
`∫_X Hⁿ`, the Chern-character coefficients of a class, the Todd coefficients of `X`, and the
Euler characteristic — plus one rational identity relating them.

## Main definitions

* `RankOneRing n` — the ring `ℚ[t]/(t^{n+1})`.
* `rankOneH n` — the ample generator `H`, the image of `t`.
* `rankOneDegree n d` — `∫_X`, normalised by `∫_X Hⁿ = d`.
* `rankOneNumericalRing n d` — the `NumericalRingData n` structure.
* `rankOneNumericalVariety` — the `NumericalVarietyData n` constructor.

## Main results

* `rankOneDegree_pow` — `∫_X Hᵏ` is `d` when `k = n` and `0` otherwise, *including* for
  `k > n`, where the power itself vanishes.
* `rankOneDegree_sum_mul_sum` — the Riemann–Roch integral
  `∫_X (Σᵢ cᵢHⁱ)(Σⱼ tⱼHʲ) = d · Σᵢ cᵢ·t_{n−i}`.

## Implementation notes

Chern and Todd components are defined without a case split on `i ≤ n`: the component in
codimension `i` is `algebraMap (coefficient i) * Hⁱ` for *every* `i`, and above the dimension
`Hⁱ = 0` makes it vanish on its own. That removes an `if` from every downstream membership
proof, at the cost of the caller's coefficient function being ignored above the dimension.

The existing surface construction is not rebuilt on top of this file. `SurfaceRing` is the
`n = 2` case of `RankOneRing`, but migrating `Examples/Surface/K3.lean` and
`Examples/Surface/ProjectivePlane.lean` onto the general ring would rewrite two working
models and their audit entries for no new mathematics; it is deliberate follow-up work, not
part of this file.

`d` is a rational rather than a natural because a model may want a normalisation that is not
the self-intersection of an integral class. The individual models take integer degrees.

## References

* Hartshorne, *Algebraic Geometry*, appendix A
* Fulton, *Intersection Theory*, ch. 15 and 19
-/

universe v

open Polynomial
open DerivedAlgGeo.LinearAlgebra

namespace AlgebraicGeometry.Numerical

namespace Examples

/-! ### The ring `ℚ[t]/(t^{n+1})` -/

/-- The defining relation: nothing survives above codimension `n` on an `n`-fold. -/
noncomputable def rankOneRel (n : ℕ) : ℚ[X] := X ^ (n + 1)

theorem rankOneRel_ne_zero (n : ℕ) : rankOneRel n ≠ 0 :=
  pow_ne_zero _ Polynomial.X_ne_zero

/-- The numerical intersection ring `A^•(X)_ℚ = ℚ[t]/(t^{n+1})` of a Picard-rank-one variety
of dimension `n`. -/
abbrev RankOneRing (n : ℕ) : Type := AdjoinRoot (rankOneRel n)

/-- The power basis `1, H, …, Hⁿ`. -/
noncomputable def rankOnePB (n : ℕ) : PowerBasis ℚ (RankOneRing n) :=
  AdjoinRoot.powerBasis (rankOneRel_ne_zero n)

theorem rankOnePB_dim (n : ℕ) : (rankOnePB n).dim = n + 1 := by
  rw [rankOnePB, AdjoinRoot.powerBasis_dim, rankOneRel, Polynomial.natDegree_X_pow]

/-- The ample generator of the Picard group. -/
noncomputable def rankOneH (n : ℕ) : RankOneRing n := AdjoinRoot.root (rankOneRel n)

theorem rankOnePB_gen (n : ℕ) : (rankOnePB n).gen = rankOneH n :=
  AdjoinRoot.powerBasis_gen _

theorem rankOnePB_basis_apply (n : ℕ) (i : Fin (rankOnePB n).dim) :
    (rankOnePB n).basis i = rankOneH n ^ (i : ℕ) := by
  rw [(rankOnePB n).basis_eq_pow, rankOnePB_gen]

/-- `H^{n+1} = 0`: the relation, in the ring. -/
theorem rankOneH_pow_succ_eq_zero (n : ℕ) : rankOneH n ^ (n + 1) = 0 := by
  change AdjoinRoot.root (rankOneRel n) ^ (n + 1) = 0
  rw [← AdjoinRoot.eval₂_root (rankOneRel n)]
  simp [rankOneRel]
  rfl

/-- Every power above the dimension vanishes, not only the first one. This is what lets the
Chern and Todd components be defined uniformly in `i` — see the module docstring. -/
theorem rankOneH_pow_eq_zero (n : ℕ) {k : ℕ} (hk : n < k) : rankOneH n ^ k = 0 := by
  obtain ⟨m, rfl⟩ : ∃ m, k = n + 1 + m := ⟨k - (n + 1), by omega⟩
  rw [pow_add, rankOneH_pow_succ_eq_zero, zero_mul]

/-! ### The grading by codimension -/

/-- The codimension of `Hⁱ` is `i`. -/
def rankOneW (n : ℕ) : Fin (rankOnePB n).dim → ℕ := fun i => (i : ℕ)

-- `(rankOnePB n).dim` cannot be rewritten inside a hypothesis mentioning
-- `i : Fin (rankOnePB n).dim` — the motive does not typecheck. Feed the equation to `omega`
-- as a fact about naturals instead.
theorem rankOneW_le (n : ℕ) (i : Fin (rankOnePB n).dim) : rankOneW n i ≤ n := by
  have h := i.isLt
  have hd := rankOnePB_dim n
  show (i : ℕ) ≤ n
  omega

theorem lt_rankOnePB_dim (n : ℕ) {k : ℕ} (hk : k ≤ n) : k < (rankOnePB n).dim := by
  rw [rankOnePB_dim]
  omega

/-- The basis index of `Hᵏ`, for `k` at most the dimension. -/
def rankOneIdx (n : ℕ) {k : ℕ} (hk : k ≤ n) : Fin (rankOnePB n).dim :=
  ⟨k, lt_rankOnePB_dim n hk⟩

/-- The basis vector at index `k` is `Hᵏ`, stated with `k` rather than a `Fin` coercion so
that `rw` can use it against a goal mentioning the exponent directly. -/
theorem rankOnePB_basis_eq_pow (n : ℕ) {k : ℕ} (hk : k ≤ n) :
    (rankOnePB n).basis (rankOneIdx n hk) = rankOneH n ^ k := by
  rw [rankOnePB_basis_apply]
  rfl

/-- `Hᵏ` sits in codimension `k`. Above the dimension both sides of the claim are zero, which
is why no hypothesis `k ≤ n` is needed. -/
theorem rankOneH_pow_mem_piece (n k : ℕ) :
    rankOneH n ^ k ∈ gradedPiece (⇑(rankOnePB n).basis) (rankOneW n) k := by
  by_cases hk : k ≤ n
  · have hmem := mem_gradedPiece (b := ⇑(rankOnePB n).basis) (w := rankOneW n) (rankOneIdx n hk)
    rwa [rankOnePB_basis_eq_pow] at hmem
  · rw [rankOneH_pow_eq_zero n (by omega)]
    exact Submodule.zero_mem _

theorem rankOne_one_mem (n : ℕ) :
    (1 : RankOneRing n) ∈ gradedPiece (⇑(rankOnePB n).basis) (rankOneW n) 0 := by
  have h := rankOneH_pow_mem_piece n 0
  rwa [pow_zero] at h

theorem rankOne_mul_mem (n : ℕ) (p q : Fin (rankOnePB n).dim) :
    (rankOnePB n).basis p * (rankOnePB n).basis q
      ∈ gradedPiece (⇑(rankOnePB n).basis) (rankOneW n) (rankOneW n p + rankOneW n q) := by
  rw [rankOnePB_basis_apply, rankOnePB_basis_apply, ← pow_add]
  exact rankOneH_pow_mem_piece n _

theorem rankOne_algebraMap_mul_mem (n : ℕ) {i : ℕ} {x : RankOneRing n} (q : ℚ)
    (hx : x ∈ gradedPiece (⇑(rankOnePB n).basis) (rankOneW n) i) :
    algebraMap ℚ (RankOneRing n) q * x
      ∈ gradedPiece (⇑(rankOnePB n).basis) (rankOneW n) i := by
  rw [← Algebra.smul_def]
  exact Submodule.smul_mem _ _ hx

/-! ### The degree map, pinned by `∫_X Hⁿ = d` -/

/-- `∫_X`, normalised so that `∫_X Hⁿ = d`. -/
noncomputable def rankOneDegree (n : ℕ) (d : ℚ) : RankOneRing n →ₗ[ℚ] ℚ :=
  d • (rankOnePB n).basis.coord (rankOneIdx n (le_refl n))

-- `simp` is the wrong tool here: `PowerBasis.coe_basis` fires first and turns `basis i` into
-- `gen ^ i`, after which `Basis.repr_self` no longer matches. Rewrite by hand.
theorem rankOneDegree_basis_of_ne (n : ℕ) (d : ℚ) (i : Fin (rankOnePB n).dim)
    (hi : rankOneW n i ≠ n) : rankOneDegree n d ((rankOnePB n).basis i) = 0 := by
  have hne : i ≠ rankOneIdx n (le_refl n) := fun h => hi (by rw [h]; rfl)
  show (d • (rankOnePB n).basis.coord (rankOneIdx n (le_refl n))) ((rankOnePB n).basis i) = 0
  rw [LinearMap.smul_apply, Module.Basis.coord_apply, Module.Basis.repr_self]
  simp [hne]

theorem rankOneDegree_basis_top (n : ℕ) (d : ℚ) :
    rankOneDegree n d ((rankOnePB n).basis (rankOneIdx n (le_refl n))) = d := by
  show (d • (rankOnePB n).basis.coord (rankOneIdx n (le_refl n)))
    ((rankOnePB n).basis (rankOneIdx n (le_refl n))) = d
  rw [LinearMap.smul_apply, Module.Basis.coord_apply, Module.Basis.repr_self]
  simp

/-- `∫_X Hᵏ = d` if `k = n`, and `0` otherwise. The `k > n` case is not a separate
convention: the power is genuinely zero there. -/
theorem rankOneDegree_pow (n : ℕ) (d : ℚ) (k : ℕ) :
    rankOneDegree n d (rankOneH n ^ k) = if k = n then d else 0 := by
  by_cases hle : k ≤ n
  · rw [← rankOnePB_basis_eq_pow n hle]
    by_cases hk : k = n
    · -- the two indices are the same `Fin`, but only after `k = n` is used on the values
      have hidx : rankOneIdx n hle = rankOneIdx n (le_refl n) := by
        simp only [rankOneIdx, Fin.mk.injEq]
        exact hk
      rw [if_pos hk, hidx]
      exact rankOneDegree_basis_top n d
    · rw [if_neg hk]
      exact rankOneDegree_basis_of_ne n d _ hk
  · rw [rankOneH_pow_eq_zero n (by omega), map_zero, if_neg (by omega)]

theorem rankOneDegree_algebraMap_mul_pow (n : ℕ) (d q : ℚ) (k : ℕ) :
    rankOneDegree n d (algebraMap ℚ (RankOneRing n) q * rankOneH n ^ k)
      = q * if k = n then d else 0 := by
  rw [← Algebra.smul_def, map_smul, smul_eq_mul, rankOneDegree_pow]

/-- **The Riemann–Roch integral in a Picard-rank-one ring.**

`∫_X (Σᵢ cᵢHⁱ)·(Σⱼ tⱼHʲ) = d · Σᵢ cᵢ·t_{n−i}`.

This is the one computation every model in this family needs, and it is the reason the
family is worth having: expanding the product leaves `(n+1)² ` terms of which `n+1` survive,
and which ones survive does not depend on the model. -/
theorem rankOneDegree_sum_mul_sum (n : ℕ) (d : ℚ) (c t : ℕ → ℚ) :
    rankOneDegree n d
        ((∑ i ∈ Finset.range (n + 1), algebraMap ℚ (RankOneRing n) (c i) * rankOneH n ^ i)
          * ∑ j ∈ Finset.range (n + 1), algebraMap ℚ (RankOneRing n) (t j) * rankOneH n ^ j)
      = d * ∑ i ∈ Finset.range (n + 1), c i * t (n - i) := by
  have hterm : ∀ i j : ℕ,
      rankOneDegree n d ((algebraMap ℚ (RankOneRing n) (c i) * rankOneH n ^ i)
          * (algebraMap ℚ (RankOneRing n) (t j) * rankOneH n ^ j))
        = c i * t j * if i + j = n then d else 0 := by
    intro i j
    rw [show (algebraMap ℚ (RankOneRing n) (c i) * rankOneH n ^ i)
          * (algebraMap ℚ (RankOneRing n) (t j) * rankOneH n ^ j)
        = algebraMap ℚ (RankOneRing n) (c i * t j) * rankOneH n ^ (i + j) by
      rw [map_mul, pow_add]; ring]
    rw [rankOneDegree_algebraMap_mul_pow]
  rw [Finset.sum_mul_sum, map_sum, Finset.mul_sum]
  refine Finset.sum_congr rfl fun i hi => ?_
  have hin : i ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
  rw [map_sum, Finset.sum_congr rfl fun j _ => hterm i j]
  rw [Finset.sum_eq_single (n - i)]
  · rw [if_pos (show i + (n - i) = n by omega)]
    ring
  · intro b _ hb
    rw [if_neg (show i + b ≠ n by omega), mul_zero]
  · intro hmem
    exact absurd (Finset.mem_range.mpr (show n - i < n + 1 by omega)) hmem

/-- The numerical intersection ring of a Picard-rank-one `n`-fold with `∫_X Hⁿ = d`. -/
@[reducible]
noncomputable def rankOneNumericalRing (n : ℕ) (d : ℚ) : NumericalRingData n (RankOneRing n) :=
  NumericalRingData.ofGradedBasis n (rankOnePB n).basis (rankOneW n) (rankOneW_le n)
    (rankOne_one_mem n) (rankOne_mul_mem n) (rankOneDegree n d)
    (rankOneDegree_basis_of_ne n d)

/-! ### Chern character, Todd class, and the variety constructor -/

variable {N : Type v}

/-- The codimension-`i` Chern component of a class whose character is `Σᵢ chCoeff E i · Hⁱ`.
Above the dimension `Hⁱ = 0`, so the coefficient there is ignored rather than forbidden. -/
noncomputable def rankOneCh (n : ℕ) (chCoeff : N → ℕ → ℚ) (E : N) (i : ℕ) : RankOneRing n :=
  algebraMap ℚ (RankOneRing n) (chCoeff E i) * rankOneH n ^ i

theorem rankOneCh_mem (n : ℕ) (chCoeff : N → ℕ → ℚ) (E : N) (i : ℕ) :
    rankOneCh n chCoeff E i ∈ gradedPiece (⇑(rankOnePB n).basis) (rankOneW n) i :=
  rankOne_algebraMap_mul_mem n _ (rankOneH_pow_mem_piece n i)

theorem rankOneCh_sum (n : ℕ) (chCoeff : N → ℕ → ℚ) (E : N) :
    (∑ i ∈ Finset.range (n + 1), rankOneCh n chCoeff E i)
      = ∑ i ∈ Finset.range (n + 1),
          algebraMap ℚ (RankOneRing n) (chCoeff E i) * rankOneH n ^ i :=
  rfl

/-- The codimension-`j` Todd component of `X`, from the coefficients of
`td(X) = Σⱼ toddCoeff j · Hʲ`. -/
noncomputable def rankOneTodd (n : ℕ) (toddCoeff : ℕ → ℚ) (j : ℕ) : RankOneRing n :=
  algebraMap ℚ (RankOneRing n) (toddCoeff j) * rankOneH n ^ j

theorem rankOneTodd_mem (n : ℕ) (toddCoeff : ℕ → ℚ) (j : ℕ) :
    rankOneTodd n toddCoeff j ∈ gradedPiece (⇑(rankOnePB n).basis) (rankOneW n) j :=
  rankOne_algebraMap_mul_mem n _ (rankOneH_pow_mem_piece n j)

theorem rankOneTodd_sum (n : ℕ) (toddCoeff : ℕ → ℚ) :
    (∑ j ∈ Finset.range (n + 1), rankOneTodd n toddCoeff j)
      = ∑ j ∈ Finset.range (n + 1),
          algebraMap ℚ (RankOneRing n) (toddCoeff j) * rankOneH n ^ j :=
  rfl

/-- **Build a numerical `n`-fold of Picard rank one.**

The caller supplies the degree `d = ∫_X Hⁿ`, the rank and Euler-characteristic homomorphisms,
the Chern-character and Todd coefficient sequences, and one rational identity `hchi` that is
Riemann–Roch already expanded — `χ(E) = d · Σᵢ chᵢ(E)·td_{n−i}(X)`.

`hchi` is where the model earns its keep, and it is deliberately the only nontrivial
obligation: everything geometric about the ring, the grading and the integral has been
discharged above, so a new model is a table of coefficients plus one `push_cast; ring`. -/
@[reducible]
noncomputable def rankOneNumericalVariety (n : ℕ) (d : ℚ) [AddCommGroup N]
    (rankHom : N →+ ℤ) (chiHom : N →+ ℤ) (chCoeff : N → ℕ → ℚ) (toddCoeff : ℕ → ℚ)
    (hchZero : ∀ E : N, chCoeff E 0 = (rankHom E : ℚ))
    (hchAdd : ∀ (E F : N) (i : ℕ), chCoeff (E + F) i = chCoeff E i + chCoeff F i)
    (htoddZero : toddCoeff 0 = 1) :
    NumericalVarietyData n (RankOneRing n) N where
  ring := rankOneNumericalRing n d
  rank := rankHom
  chComp := rankOneCh n chCoeff
  chComp_mem := rankOneCh_mem n chCoeff
  chComp_zero E := by
    show algebraMap ℚ (RankOneRing n) (chCoeff E 0) * rankOneH n ^ 0 = _
    rw [pow_zero, mul_one, hchZero]
  chComp_add E F i := by
    show algebraMap ℚ (RankOneRing n) (chCoeff (E + F) i) * rankOneH n ^ i = _
    rw [hchAdd, map_add, add_mul]
    rfl
  toddComp := rankOneTodd n toddCoeff
  toddComp_mem := rankOneTodd_mem n toddCoeff
  toddComp_zero := by
    show algebraMap ℚ (RankOneRing n) (toddCoeff 0) * rankOneH n ^ 0 = 1
    rw [pow_zero, mul_one, htoddZero, map_one]
  chi := chiHom

/-- The expanded coefficient identity supplies HRR for the corresponding
rank-one numerical presentation. -/
theorem rankOneNumericalVariety_satisfiesHRR
    (n : ℕ) (d : ℚ) [AddCommGroup N]
    (rankHom : N →+ ℤ) (chiHom : N →+ ℤ) (chCoeff : N → ℕ → ℚ)
    (toddCoeff : ℕ → ℚ)
    (hchZero : ∀ E : N, chCoeff E 0 = (rankHom E : ℚ))
    (hchAdd : ∀ (E F : N) (i : ℕ), chCoeff (E + F) i = chCoeff E i + chCoeff F i)
    (htoddZero : toddCoeff 0 = 1)
    (hchi : ∀ E : N, (chiHom E : ℚ)
      = d * ∑ i ∈ Finset.range (n + 1), chCoeff E i * toddCoeff (n - i)) :
    (rankOneNumericalVariety n d rankHom chiHom chCoeff toddCoeff
      hchZero hchAdd htoddZero).SatisfiesHRR where
  eq E := by
    show (chiHom E : ℚ) = rankOneDegree n d _
    rw [hchi E, rankOneCh_sum, rankOneTodd_sum, rankOneDegree_sum_mul_sum]

end Examples

end AlgebraicGeometry.Numerical
