import DerivedAlgGeo.AlgebraicGeometry.Numerical.Examples.Surface.BlowUpPlane
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Examples.Surface.BlowUpPlaneSlice
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Examples.Surface.BlowUpPlaneWalls
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Examples.Surface.K3MukaiComparison
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Examples.Surface.ProjectivePlaneCharge
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Examples.Surface.RankOneRealization
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Examples.Surface.RankOneWalls
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Examples.Surface.SmoothQuadric
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Examples.Surface.SmoothQuadricCharge

/-! # Surface realizations, charges and walls -/
