/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.Scheme
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.ResidueFiber
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.SchemeDerived
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.FiniteType
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.BoundedGeometry
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.CoherentPushforward
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.CoherentPushforwardCoherence
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.ExactPullback
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.ExactPullbackCoherence
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.LeftDerivedPullback
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.PullbackAcyclicResolution
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.FlatPullback
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.FlatPullbackResolution
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.OpenImmersionPullback
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.DerivedPullbackCoherence
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.DerivedPullbackLaws
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Families.DerivedPullbackShift

/-!
# Scheme-derived categories in families

Scheme base changes, residue fibers, derived realizations, and geometric
pullback and direct-image constructions that are independent of stability
conditions. Public
declarations owned by this subtree use
`AlgebraicGeometry.DerivedCategory.Families`.
-/
