/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.Algebra.Category.ModuleCat.Sheaf.AB
import Mathlib.Algebra.Category.Grp.AB
import Mathlib.Algebra.Category.ModuleCat.Presheaf.Generator
import Mathlib.CategoryTheory.Abelian.GrothendieckCategory.Basic

/-!
# A separator for sheaves of modules, and the Grothendieck abelian instance

Mathlib proves that `Sheaf J A` is Grothendieck abelian for a Grothendieck abelian target `A`
(`CategoryTheory/Abelian/GrothendieckAxioms/Sheaf.lean`) and that the free presheaves of
modules on representables separate presheaves of modules
(`PresheafOfModules.freeYoneda.isSeparating`), but records no separator for
`SheafOfModules R` and hence no `IsGrothendieckAbelian` instance for it. This file adds both
over a small site. The separating family is the sheafification of the free presheaves of
modules on representables; the argument is the one for `Sheaf.freeYoneda`, run through the
sheafification adjunction for modules, whose right adjoint is the forgetful functor (the
restriction of scalars along `𝟙` is the identity on the nose).

AB5 for sheaves of modules is `SheafOfModules.ab5OfSize` in `Sheaf/AB.lean`, so with a
separator the Grothendieck abelian instance is a one-liner, and Mathlib then supplies enough
injectives and `HasExt`. The instance for `X.Modules` on a scheme is in
`AlgebraicGeometry/Modules/AB.lean`.

## Main results

* `SheafOfModules.freeYonedaSheaf`, `SheafOfModules.freeYonedaSheaf_isSeparating`.
* `SheafOfModules.hasSeparator`.
* `SheafOfModules.isGrothendieckAbelian`.
-/

universe u

open CategoryTheory Category Limits

namespace SheafOfModules

variable {C : Type u} [SmallCategory C] {J : GrothendieckTopology C}
  (R : Sheaf J RingCat.{u}) [HasSheafify J AddCommGrpCat.{u}]
  [J.WEqualsLocallyBijective AddCommGrpCat.{u}]

/-- The sheaf of modules freely generated by one section over `X`: the sheafification of the
free presheaf of modules on the representable presheaf of `X`. -/
noncomputable def freeYonedaSheaf (X : C) : SheafOfModules.{u} R :=
  (PresheafOfModules.sheafification (𝟙 R.obj)).obj
    ((PresheafOfModules.free R.obj).obj (yoneda.obj X))

set_option backward.isDefEq.respectTransparency false in
/-- The free sheaves of modules on representables separate sheaves of modules. -/
lemma freeYonedaSheaf_isSeparating :
    ObjectProperty.IsSeparating (.ofObj (freeYonedaSheaf R)) := by
  intro M N f g hfg
  apply (forget R).map_injective
  apply PresheafOfModules.freeYoneda.isSeparating R.obj
  rintro _ ⟨X⟩ h
  have := hfg _ (ObjectProperty.ofObj_apply _ X)
    (((PresheafOfModules.sheafificationAdjunction (𝟙 R.obj)).homEquiv _ _).symm h)
  have := congrArg ((PresheafOfModules.sheafificationAdjunction (𝟙 R.obj)).homEquiv _ _) this
  simp only [Adjunction.homEquiv_naturality_right, Equiv.apply_symm_apply] at this
  exact this

/-- Sheaves of modules on a small site have a separator: the coproduct of the free sheaves on
representables. -/
instance hasSeparator : HasSeparator (SheafOfModules.{u} R) where
  hasSeparator := ⟨_, (freeYonedaSheaf_isSeparating R).isSeparator_coproduct⟩

/-- **Sheaves of modules on a small site form a Grothendieck abelian category.** -/
instance isGrothendieckAbelian : IsGrothendieckAbelian.{u} (SheafOfModules.{u} R) where

end SheafOfModules
