/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.Proj.Modules.FracSection

/-!
# The twisting sheaf is generated by `gᴺ` on the chart `D₊(g)`

`exists_smul_sectionOfMem_eq` says that near every point of `D₊(g)`, every section of `O(N)` is a
structure-sheaf multiple of the single section `gᴺ / 1`. This is the chart-local half of Serre's
global generation: `#586` needs the twisted generators to generate `F(N)` on each chart, and the
`O(N)` factor of that is exactly this statement.

## Why this is not a triviality about invertible sheaves

`O(N)` is invertible (`twistingSheaf_isInvertible`) and trivial on a degree-one chart
(`twistingSheafOverUnitIso`), so it is tempting to read the statement off those. That does not
work, and the reason is `#585`'s: those isomorphisms are **property witnesses, not computations**.
They say a trivialization exists; they do not say that *this* section, `gᴺ / 1`, is one. A
generator has to be exhibited, and the argument has to be made on fractions.

## The argument

`isLocallyFraction` hands over, near the point, a single fraction: `w = r / s` on some `V'`, with
`s ∈ 𝒜 i` invertible there and `r` in the shifted piece — which, because the shift `N` is a
natural number, is just `𝒜 (i + N)` (`mem_intShift_ofNat_iff`).

Shrink to `V' ⊓ D₊(g)` and take the scalar

  `r / (s · gᴺ)`,

a degree-zero fraction because `s · gᴺ ∈ 𝒜 (i + N)` matches `r`'s degree, and a legitimate section
because both `s` and `g` are invertible on that open. Multiplying `gᴺ / 1` by it gives
`r · gᴺ / (s · gᴺ · 1)`, which is `r / s` after cancelling `gᴺ` — one `LocalizedModule.mk_eq` with
witness `1`, the same last step as `frac_smul_sectionOfMem`.

## Shrinking is not optional

The neighbourhood is cut down twice, and both cuts are forced. `isLocallyFraction` only offers a
fraction on *some* neighbourhood, and the denominator `s · gᴺ` is invertible only where `g` is —
which is why the conclusion carries `W` and a proof `W ≤ V` rather than asserting anything on `V`
itself. On the chart this costs nothing: the caller is choosing an open around a point it was
already handed.

## Scope

The `O(N)` factor alone. Nothing here mentions `F`, `twistBy`, or surjectivity; the passage from
this to `F(N)` is the tensor step and is not in this file.
-/

noncomputable section

open CategoryTheory Opposite SetLike TopCat TopologicalSpace

namespace AlgebraicGeometry.Proj

universe u

variable {A σA : Type u} [CommRing A] [SetLike σA A] [AddSubgroupClass σA A]
variable (𝒜 : ℕ → σA) [GradedRing 𝒜]

local notation3 "X" => ProjectiveSpectrum.top 𝒜

/-- **`gᴺ / 1` generates `O(N)` near every point of `D₊(g)`.**

For `g` of degree one and `w` a section of `O(N)` over `V`, every point of `V ⊓ D₊(g)` has a
neighbourhood on which `w` is a structure-sheaf multiple of `sectionOfMem 𝒜 𝒜 _ N gᴺ`.

The conclusion compares the two sections pointwise rather than through a restriction map: the
module action on `associatedSheafInType` is pointwise, so this is the form both the proof and the
callers want, and it avoids naming the restriction of `w` at all. -/
theorem exists_smul_sectionOfMem_eq
    {g : A} (hg : g ∈ 𝒜 1) (N : ℕ) {V : Opens X}
    (w : (associatedSheafInType 𝒜 (intShift 𝒜 (N : ℤ))).1.obj (op V))
    (x : ProjectiveSpectrum 𝒜) (hxV : x ∈ V) (hxg : x ∈ ProjectiveSpectrum.basicOpen 𝒜 g) :
    ∃ (W : Opens X) (hWV : W ≤ V), x ∈ W ∧
      ∃ r : (ProjectiveSpectrum.Proj.structureSheaf 𝒜).1.obj (op W),
        ∀ y : W, (r • sectionOfMem 𝒜 𝒜 W N (pow_mem_deg 𝒜 hg N)).1 y
          = w.1 ⟨y.1, hWV y.2⟩ := by
  obtain ⟨V', hxV', incl, i, r, s, hs, hw⟩ := w.2 ⟨x, hxV⟩
  refine ⟨V' ⊓ ProjectiveSpectrum.basicOpen 𝒜 g,
    fun y hy => (leOfHom incl) hy.1, ⟨hxV', hxg⟩, ?_⟩
  -- the numerator's degree: a natural-number shift is an honest graded piece
  have hrdeg : (r : A) ∈ 𝒜 (i + N) :=
    (mem_intShift_ofNat_iff 𝒜 N i (r : A)).mp r.2
  have hden : (s : A) * g ^ N ∈ 𝒜 (i + N) :=
    SetLike.mul_mem_graded s.2 (pow_mem_deg 𝒜 hg N)
  have hVs : V' ≤ ProjectiveSpectrum.basicOpen 𝒜 (s : A) := fun z hz => hs ⟨z, hz⟩
  have hWden : V' ⊓ ProjectiveSpectrum.basicOpen 𝒜 g
      ≤ ProjectiveSpectrum.basicOpen 𝒜 ((s : A) * g ^ N) := by
    rw [ProjectiveSpectrum.basicOpen_mul]
    exact le_inf (inf_le_left.trans hVs)
      (inf_le_right.trans (basicOpen_le_basicOpen_pow 𝒜 g N))
  refine ⟨fracSection 𝒜 hrdeg hden hWden, ?_⟩
  intro y
  refine Eq.trans ?_ (hw ⟨y.1, y.2.1⟩).symm
  show frac 𝒜 hrdeg hden (hWden y.2) •
      (sectionOfMem 𝒜 𝒜 (V' ⊓ ProjectiveSpectrum.basicOpen 𝒜 g) N (pow_mem_deg 𝒜 hg N)).1 y = _
  rw [sectionOfMem_apply, frac, DegreeZeroLocalization.mk_smul_mk]
  apply DegreeZeroLocalization.ext
  simp only [DegreeZeroLocalization.coe_mk, NumDenSameDeg.embedding, smul_eq_mul, mul_one]
  rw [LocalizedModule.mk_eq]
  exact ⟨1, by simp [Submonoid.smul_def]; ring⟩

end AlgebraicGeometry.Proj
