/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.Metric.Mass.Subadditivity.Triangle.Consequences

/-!
# Hausdorff separation for the stability space

For a surjective class map `v : K₀ C →+ Λ`, the space `StabilityCondition.WithClassMap C v` is
`T0` and `T2` **for the topology it already carries** -- the Section 6 topology generated by
`basisNhd` and installed as `StabilityCondition.WithClassMap.topologicalSpace`.

## The whole content is one `rfl`

`Metric/Distance/Topology.lean` builds the extended-metric package
`stabilityEMetricSpaceOfMassTriangle hv htriangle` and proves that the topology it induces **is**
the installed one, definitionally (`stabilityEMetricSpace_toTopologicalSpace`). The
mass-triangle premise is discharged unconditionally by `stabilityMassTriangleInequality`, with no
hypothesis beyond the ambient `[IsTriangulated C]`. So every proof below opens with

```
letI := stabilityEMetricSpaceOfMassTriangle hv stabilityMassTriangleInequality
```

and then reads Mathlib's separation instances for the metric topology off as statements about
the installed topology, because the two are the same term. `EMetricSpace` forgets to
`PseudoEMetricSpace`, to `UniformSpace`, to the already-installed `TopologicalSpace`; that last
step is `rfl`, and `stabilityEMetricSpaceOfMassTriangle_toTopologicalSpace` pins it once more so
that a later refactor cannot silently retarget these statements at a fresh metric topology.

## What is deliberately not here

* **No global instance.** No `TopologicalSpace`, `UniformSpace`, `EMetricSpace` or `MetricSpace`
  instance is installed on `WithClassMap C v`, and no new member joins the `stabilityEMetricSpace`
  definition family: `stabilityEMetricSpaceOfMassTriangle` already exists, and an
  `OfSurjective` alias would be a third `@[reducible]` definition equal to it.
* **No separation without surjectivity.** `stabilityDist` only sees charges on `Set.range v`, so
  two stability conditions differing on a class outside the range are at distance zero; this is
  why `stabilityDist_eq_zero` takes `hv`, and why every statement here does.
* **No local compactness, no completeness.** Nothing here needs either; the autoequivalence
  lane carries local compactness as a hypothesis.
-/

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated

namespace CategoryTheory.Triangulated

universe w u u'

variable {C : Type u} [Category.{w} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
  [IsTriangulated C]
variable {Λ : Type u'} [AddCommGroup Λ] {v : K₀ C →+ Λ}

/-- **Regression pin.** The topology of the unconditional extended-metric package is the
installed Section 6 topology, definitionally. Every separation statement below is about the
right-hand side. -/
theorem stabilityEMetricSpaceOfMassTriangle_toTopologicalSpace (hv : Function.Surjective v) :
    (stabilityEMetricSpaceOfMassTriangle hv
        stabilityMassTriangleInequality).toPseudoEMetricSpace.toUniformSpace.toTopologicalSpace =
      (inferInstance : TopologicalSpace (StabilityCondition.WithClassMap C v)) :=
  rfl

/-- **The stability space is `T0`** for its installed topology, when the class map is
surjective: `EMetricSpace.instT0Space` for the metric topology, which is the installed one. -/
theorem t0Space_withClassMap (hv : Function.Surjective v) :
    T0Space (StabilityCondition.WithClassMap C v) := by
  letI := stabilityEMetricSpaceOfMassTriangle hv stabilityMassTriangleInequality
  exact (inferInstance :
    @T0Space (StabilityCondition.WithClassMap C v)
      this.toPseudoEMetricSpace.toUniformSpace.toTopologicalSpace)

/-- **The stability space is Hausdorff** for its installed topology, when the class map is
surjective: `T0` together with the `R1Space` every pseudo-extended-metric topology has. -/
theorem t2Space_withClassMap (hv : Function.Surjective v) :
    T2Space (StabilityCondition.WithClassMap C v) := by
  letI := stabilityEMetricSpaceOfMassTriangle hv stabilityMassTriangleInequality
  exact (inferInstance :
    @T2Space (StabilityCondition.WithClassMap C v)
      this.toPseudoEMetricSpace.toUniformSpace.toTopologicalSpace)

/-- Points of the stability space are closed. -/
theorem isClosed_singleton_withClassMap (hv : Function.Surjective v)
    (σ : StabilityCondition.WithClassMap C v) : IsClosed ({σ} : Set _) :=
  haveI := t2Space_withClassMap hv
  isClosed_singleton

/-- The diagonal of the stability space is closed. -/
theorem isClosed_diagonal_withClassMap (hv : Function.Surjective v) :
    IsClosed (Set.diagonal (StabilityCondition.WithClassMap C v)) :=
  haveI := t2Space_withClassMap hv
  isClosed_diagonal

end CategoryTheory.Triangulated
