/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.Surface.Enriques.Exceptional
import DerivedAlgGeo.CategoryTheory.Triangulated.SemiorthogonalDecomposition.Collection

/-!
# The Enriques exceptional sequence and residual category

The refined derived Torelli papers arXiv:1912.04332v2 and
arXiv:2104.13610v2 study the right orthogonal to exceptional line-bundle
collections on Enriques surfaces. This file builds the repository's formal
counterpart from an isotropic 10-collection, its exceptionality data, and
supplied pairwise semiorthogonality witnesses.

The output is deliberately neutral. `residualComponent` is the right
orthogonal to the union of the ten generated components, and
`ResidualCategory` is its full subcategory. No fullness, admissibility,
mutation, Torelli theorem, or equivalence with the papers' Kuznetsov
component is asserted.

The pairwise vanishing remains supplied geometric data: proving it from the
intersection equations needs the effectiveness and line-bundle cohomology
arguments that are not available at the current pin.

## Main definitions

* `IsotropicCollection.SemiorthogonalityData` -- the pairwise shifted Hom
  vanishing in the classical exceptional-collection direction.
* `IsotropicCollection.exceptionalCollection` -- the ten line bundles as an
  `ExceptionalCollection`.
* `IsotropicCollection.collectionSequence` -- the associated finite
  semiorthogonal sequence.
* `IsotropicCollection.residualComponent` and `ResidualCategory` -- its
  right orthogonal and the corresponding full subcategory.

## Main results

* `bundle_mem_collectionSequence_component` -- each bundle lies in its
  designated (order-reversed) component.
* `residualComponent_isTriangulated` -- the residual is triangulated.
* `bundle_hom_residualCategory_eq_zero` -- maps from any selected bundle to
  a residual object vanish.
* `bundle_not_mem_residualComponent` -- no selected exceptional bundle lies
  in the residual.
-/

universe u

open CategoryTheory CategoryTheory.Limits CategoryTheory.Triangulated
open AlgebraicGeometry.DerivedCategory

attribute [local instance] HasDerivedCategory.standard

namespace AlgebraicGeometry.EnriquesSurface.IsotropicCollection

open Scheme.Modules

variable {k : Type u} [Field k]
variable {Y : Scheme.{u}} [Y.Over (Spec (CommRingCat.of k))]
  [IsSmoothProperVariety k Y]
variable {C : SmoothProperVariety.CanonicalSheafData k Y 2}
  [SmoothProperVariety.IsEnriquesSurface k Y C]
variable {D : Cohomology.FiniteCohomology k Y} {S : D.LinearConnectingSystem}
variable (T : IsotropicCollection (Y := Y) (C := C) D S)

/-- Pairwise shifted Hom-vanishing for the ten line bundles, in the classical
exceptional-collection direction: maps from a later bundle to a shift of an
earlier bundle vanish. This is the geometric input still missing from the
intersection-theoretic collection API. -/
structure SemiorthogonalityData : Prop where
  /-- The pairwise vanishing witnesses for the selected line bundles. -/
  hom_shift_eq_zero : ∀ ⦃i j : Fin 10⦄, i < j → ∀ (n : ℤ)
    (f : (T.bundles j).boundedDerivedObject ⟶
      (T.bundles i).boundedDerivedObject⟦n⟧), f = 0

/-- The ten selected line bundles as an exceptional collection. Individual
exceptionality is proved by `ExceptionalityData.bundle_isExceptional`; only
the pairwise geometric vanishing is read from `SemiorthogonalityData`. -/
noncomputable def exceptionalCollection (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) :
    ExceptionalCollection k (DerivedCat Y) (Fin 10) where
  obj i := (T.bundles i).boundedDerivedObject
  exceptional i := ExceptionalityData.bundle_isExceptional T exceptional i
  hom_shift_eq_zero := by
    intro i j hij n f
    exact SemiorthogonalityData.hom_shift_eq_zero semiorthogonal hij n f

@[simp]
theorem exceptionalCollection_obj (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) (i : Fin 10) :
    (T.exceptionalCollection exceptional semiorthogonal).obj i =
      (T.bundles i).boundedDerivedObject :=
  rfl

/-- The finite semiorthogonal sequence generated by the ten selected bundles.
Its root convention is opposite to the classical collection convention, so
component `i` is generated by bundle `i.rev`. -/
noncomputable def collectionSequence (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) :
    SemiorthogonalSequence (DerivedCat Y) (Fin 10) :=
  (T.exceptionalCollection exceptional semiorthogonal).toSemiorthogonalSequenceFin

@[simp]
theorem collectionSequence_component (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) (i : Fin 10) :
    (T.collectionSequence exceptional semiorthogonal).component i =
      (T.exceptionalCollection exceptional semiorthogonal).component i.rev :=
  rfl

/-- Bundle `i` lies in component `i.rev` of the root-oriented finite
semiorthogonal sequence. -/
theorem bundle_mem_collectionSequence_component
    (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) (i : Fin 10) :
    (T.collectionSequence exceptional semiorthogonal).component i.rev
      (T.bundles i).boundedDerivedObject := by
  simpa [collectionSequence] using
    (T.exceptionalCollection exceptional semiorthogonal).obj_mem_component i

/-- The residual object property: the right orthogonal to the union of the
ten generated components. -/
noncomputable def residualComponent (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) :
    ObjectProperty (DerivedCat Y) :=
  (T.collectionSequence exceptional semiorthogonal).residual

/-- The full subcategory on the residual object property. This name makes no
admissibility or fullness claim. -/
abbrev ResidualCategory (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) :=
  (T.residualComponent exceptional semiorthogonal).FullSubcategory

/-- The residual object property is triangulated, because each generated
component is triangulated and a right orthogonal to a shift-stable property
is triangulated. -/
theorem residualComponent_isTriangulated
    (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) :
    (T.residualComponent exceptional semiorthogonal).IsTriangulated := by
  apply SemiorthogonalSequence.HasTriangulatedComponents.residual_isTriangulated
  exact ExceptionalCollection.hasTriangulatedComponentsFin
    (T.exceptionalCollection exceptional semiorthogonal)

/-- The underlying object of every object of `ResidualCategory` satisfies the
residual membership predicate. -/
theorem residualCategory_obj_mem (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData)
    (R : T.ResidualCategory exceptional semiorthogonal) :
    T.residualComponent exceptional semiorthogonal R.obj :=
  R.property

/-- Every map from a selected bundle to an object satisfying the residual
predicate vanishes. -/
theorem bundle_hom_residual_eq_zero (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) (i : Fin 10)
    {R : DerivedCat Y}
    (hR : T.residualComponent exceptional semiorthogonal R)
    (f : (T.bundles i).boundedDerivedObject ⟶ R) : f = 0 :=
  SemiorthogonalSequence.component_hom_residual_eq_zero
    (T.collectionSequence exceptional semiorthogonal) i.rev
    (T.bundle_mem_collectionSequence_component exceptional semiorthogonal i)
    hR f

/-- Full-subcategory consumer form of `bundle_hom_residual_eq_zero`. -/
theorem bundle_hom_residualCategory_eq_zero
    (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) (i : Fin 10)
    (R : T.ResidualCategory exceptional semiorthogonal)
    (f : (T.bundles i).boundedDerivedObject ⟶ R.obj) : f = 0 :=
  T.bundle_hom_residual_eq_zero exceptional semiorthogonal i R.property f

/-- No selected line bundle lies in the residual: its identity would vanish,
contradicting exceptionality. -/
theorem bundle_not_mem_residualComponent
    (exceptional : T.ExceptionalityData)
    (semiorthogonal : T.SemiorthogonalityData) (i : Fin 10) :
    ¬ T.residualComponent exceptional semiorthogonal
      (T.bundles i).boundedDerivedObject := by
  intro hResidual
  apply (ExceptionalityData.bundle_isExceptional T exceptional i).not_isZero
  rw [IsZero.iff_id_eq_zero]
  exact T.bundle_hom_residual_eq_zero exceptional semiorthogonal i hResidual
    (𝟙 (T.bundles i).boundedDerivedObject)

end AlgebraicGeometry.EnriquesSurface.IsotropicCollection
