/-
Definition B.1 and the Lemma B.4 filtration-property consumer from arXiv:2607.28411v1.
The audit records only the neutral scheme-morphism root; no stability-condition module is an
input.
-/
import DerivedAlgGeo.AlgebraicGeometry.Morphisms

#print axioms AlgebraicGeometry.AlmostDisconnected.structureSheaf
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.support
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.inclusion
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.inclusion_isClosedImmersion
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.baseIso
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.baseIso_hom
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.mk.inj
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.mk.sizeOf_spec
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.instIsClosedImmersionInclusion
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.identity
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.comp
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.comp_support
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.comp_inclusion
#print axioms AlgebraicGeometry.AlmostDisconnected.SupportData.comp_baseIso
#print axioms AlgebraicGeometry.AlmostDisconnected.GradedPieceData
#print axioms AlgebraicGeometry.AlmostDisconnected.GradedPieceData.toSupportData
#print axioms AlgebraicGeometry.AlmostDisconnected.GradedPieceData.lineBundle
#print axioms AlgebraicGeometry.AlmostDisconnected.GradedPieceData.gradedIso
#print axioms AlgebraicGeometry.AlmostDisconnected.GradedPieceData.mk.inj
#print axioms AlgebraicGeometry.AlmostDisconnected.GradedPieceData.mk.sizeOf_spec
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.filtration
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.piece
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.support
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.inclusion
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.inclusion_isClosedImmersion
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.baseIso
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.baseIso_hom
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.lineBundle
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.gradedIso
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.mk.inj
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.mk.sizeOf_spec
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.instIsClosedImmersionInclusion
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.CompositionIndex
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.compositionIndexEquiv
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.compositionSupportData
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.compositionSupportData_support
#print axioms AlgebraicGeometry.AlmostDisconnected.Witness.compositionSupportData_inclusion
#print axioms AlgebraicGeometry.AlmostDisconnected.identityWitness
#print axioms AlgebraicGeometry.IsAlmostDisconnected
#print axioms AlgebraicGeometry.IsAlmostDisconnected.id
#print axioms AlgebraicGeometry.IsAlmostDisconnected.instContainsIdentitiesScheme

#print axioms AlgebraicGeometry.FiltrationProperty.Witness
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.isSeparated
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.kernel
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.secondProjectionIso
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.secondProjectionIso_hom
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.mk.inj
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.mk.sizeOf_spec
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.automorphism
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.automorphism_hom_over
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.automorphism_inv_over
#print axioms AlgebraicGeometry.FiltrationProperty.Witness.overAutomorphism
#print axioms AlgebraicGeometry.HasFiltrationProperty
