/-
Exceptional-block and residual-projection slice of the AlgebraicGeometry
audit.  Admissibility, the numerical curve chains, the derived divisor
triangles, Ext profiles, and completeness remain explicit data.  The chosen
projection, objectwise mutation triangle, same-projection result, and
Ext-to-classification consequences are constructions or theorems concerning
the actual ten derived line bundles and their actual residual projections.
-/
import DerivedAlgGeo.AlgebraicGeometry.Surface.Enriques.PaperTorelli

#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.blocks
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.bundleIndex
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.bundleIso
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.residual_eq
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.mk.inj
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.mk.sizeOf_spec
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.totalLength_eq_ten
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.decompositionType_sum_eq_ten
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.card_le_ten
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.firstBundleIndex
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.firstObjectIso
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.singleton_or_longer
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperResidualProjectionData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.projectedObject
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.projectedObjectHomEquiv
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.projectedObjectHomEquiv_id

#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.singleton
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.spherical
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.pairwise_orthogonal
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.complete
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.toSphericalClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.toSphericalClassificationData_candidate
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.spherical_iff
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.projectedObject_not_isZero
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.projectedObject_not_shift

#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.spherical_of_singleton
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.pseudoprojective_of_longer
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.pairwise_orthogonal
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.spherical_complete
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.pseudoprojective_complete
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.toMixedClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.toMixedClassificationData_blockLength
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.toMixedClassificationData_candidate
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.spherical_iff
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.pseudoprojective_iff
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.projectedObject_dichotomy
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.projectedObject_not_isZero
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.longer_projectedObject_not_spherical
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.singleton_projectedObject_not_shift
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.longer_projectedObject_not_shift

-- The downstream paper-extension layer turns residual admissibility into a
-- chosen projection, records the numerical (-2)-chain geometry and its
-- divisor triangles, proves same projection throughout every block, and
-- assembles the Ext computations into the two classification packages.
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperResidualAdmissibilityData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperResidualAdmissibilityData.rightAdmissible
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperResidualAdmissibilityData.projectionData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.mutationTriangle
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.MinusTwoCurveChain
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.MinusTwoCurveChain.curve
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.MinusTwoCurveChain.selfIntersection
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.MinusTwoCurveChain.adjacentIntersection
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.MinusTwoCurveChain.nonAdjacentIntersection
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.MinusTwoCurveChain.mk.inj
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.MinusTwoCurveChain.mk.sizeOf_spec
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.MinusTwoCurveChain.prefixDivisor
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.MinusTwoCurveChain.prefixDivisor_zero
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperCurveChainData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperCurveChainData.chain
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperCurveChainData.memberClass
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperCurveChainData.projectionTriangles
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperCurveChainData.mk.inj
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperCurveChainData.mk.sizeOf_spec
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperCurveChainData.projectionIso
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionExtData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionExtData.selfExt
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionExtData.pairwise
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionExtData.toProjectionClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionExtData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionExtData.sphericalExt
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionExtData.pseudoprojectiveExt
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionExtData.serreShift
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionExtData.pairwise
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionExtData.spherical_of_singleton
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionExtData.pseudoprojective_of_longer
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionExtData.toProjectionClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperResidualKernelEquivalence
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperExceptionalBlockExtensionData

-- Classification matching, exact block length, common shifts, and the
-- generation-certified ambient Fourier--Mukai extension.
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperResidualSerreEquivalence
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.matchingEquiv
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.matchingEquiv_spec
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.matchingEquiv
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.matchingEquiv_length_eq_one_iff
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.matchingEquiv_length_two_le_iff
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.matchingEquiv_spec
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperAdjacentExtData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBidirectionalPrefixData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBidirectionalPrefixData.length_eq
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.MatchingPrefixData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.matchingEquiv_length_eq
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperMemberwiseBlockShiftData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.MatchingMemberwiseShiftData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperMemberwiseBlockShiftData.commonShift
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperMemberwiseBlockShiftData.shift_eq_common
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperMemberwiseBlockShiftData.commonObjectIso
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperGeneratedExtensionSequenceData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperGeneratedExtensionSequenceData.toKernelEquivalence
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperGeneratedExtensionSequenceData.ambientEquivalence
