/-
Exceptional-block and residual-projection slice of the AlgebraicGeometry
audit.  Block geometry, projection existence, Ext profiles, and completeness
remain supplied data.  The checked consequences concern the actual ten
derived line bundles and their actual residual projections.
-/
import DerivedAlgGeo.AlgebraicGeometry.Surface.Enriques.PaperBlocks

#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.blocks
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.bundleIndex
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.bundleIso
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.residual_eq
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.mk.inj
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.mk.sizeOf_spec
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.totalLength_eq_ten
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.decompositionType_sum_eq_ten
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.card_le_ten
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.firstBundleIndex
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.firstObjectIso
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.singleton_or_longer
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperResidualProjectionData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.projectedObject
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.projectedObjectHomEquiv
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperBlockData.projectedObjectHomEquiv_id

#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.singleton
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.spherical
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.pairwise_orthogonal
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.complete
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.toSphericalClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.toSphericalClassificationData_candidate
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.spherical_iff
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.projectedObject_not_isZero
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIProjectionClassificationData.projectedObject_not_shift

#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.spherical_of_singleton
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.pseudoprojective_of_longer
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.pairwise_orthogonal
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.spherical_complete
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.pseudoprojective_complete
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.toMixedClassificationData
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.toMixedClassificationData_blockLength
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.toMixedClassificationData_candidate
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.spherical_iff
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.pseudoprojective_iff
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.projectedObject_dichotomy
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.projectedObject_not_isZero
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.longer_projectedObject_not_spherical
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.singleton_projectedObject_not_shift
#print axioms AlgebraicGeometry.EnriquesSurface.IsotropicCollection.PaperIIProjectionClassificationData.longer_projectedObject_not_shift
