import DerivedAlgGeo.AlgebraicGeometry.Modules.FlatGenerators

#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaModuleSheaf
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaModuleSheafStalkIsoRegularOfMem
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaModuleSheaf_stalk_isZero_of_not_mem
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaModuleSheaf_stalk_flat_of_mem
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaModuleSheaf_stalk_flat_of_not_mem
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaModuleSheaf_stalk_flat
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaModuleSheaf_isFlatOver_id
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproduct
#print axioms AlgebraicGeometry.Scheme.Modules.fromFreeYonedaSheafCoproduct
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductMap
#print axioms AlgebraicGeometry.Scheme.Modules.fromFreeYonedaSheafCoproduct_epi
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproduct_summand_stalk_flat
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproduct_stalk_flat
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductLeftResolution
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductReducedLeftResolution
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductReducedLeftResolution_preservesZeroMorphisms
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductReducedLeftResolution_chainComplexMap_zero
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductResolutionBicomplex
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductResolutionBicomplex_exactAt_succ
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductDegreewiseEpiCover
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductDegreewiseEpiCoverMap
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductDegreewiseEpiCoverMap_epi
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductReducedLeftResolution_augmentedExact
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductReducedLeftResolution_homologyZeroIso
#print axioms AlgebraicGeometry.Scheme.Modules.fromFreeYonedaSheafCoproduct_natural
