import DerivedAlgGeo.AlgebraicGeometry.Modules.FlatResolutionTotalization

#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductResolutionBicomplexUpInt
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductTotalComplexFunctor
#print axioms AlgebraicGeometry.Scheme.Modules.isColimitFreeYonedaSheafCoproductTotalTruncLETowerCocone
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductResolutionBicomplexAugmentation
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductResolutionBicomplexAugmentation_row_quasiIso
#print axioms AlgebraicGeometry.Scheme.Modules.normalizedBicomplexAugmentation
#print axioms AlgebraicGeometry.Scheme.Modules.normalizedBicomplexAugmentation_row_quasiIso
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductTotalAugmentationToSingleZero
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductTotalTargetIso
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductTotalAugmentation
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductTotalAugmentation_eq_toSingleZero_comp_targetIso
#print axioms AlgebraicGeometry.Scheme.Modules.quasiIso_freeYonedaSheafCoproductTotalAugmentation_of_isStrictlyLE
#print axioms AlgebraicGeometry.Scheme.Modules.quasiIso_freeYonedaSheafCoproductTotalAugmentation_truncLE
#print axioms AlgebraicGeometry.Scheme.Modules.quasiIso_freeYonedaSheafCoproductTotalAugmentation
#print axioms AlgebraicGeometry.Scheme.Modules.freeYonedaSheafCoproductTotalComplexFunctor_obj_X_isFlatOverId
