/-
Moduli slice of the AlgebraicGeometry audit, split out so concurrent
branches append to different files (#480). See the umbrella file for the contract.
-/
import DerivedAlgGeo.Algebra
import DerivedAlgGeo.AlgebraicGeometry
import DerivedAlgGeo.AlgebraicGeometry.IntersectionTheory.ChernCharacter.Basic
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Specializations.Surface
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Specializations.Threefold
import DerivedAlgGeo.AlgebraicGeometry.Numerical.Specializations.Fourfold
open AlgebraicGeometry AlgebraicGeometry.Numerical

/-! ## Relative-perfect affine-family moduli -/

#print axioms AlgebraicGeometry.affineFamilyUniversallyGluableRelativePerfect
#print axioms AlgebraicGeometry.affineFamilyUniversallyGluableRelativePerfect_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.AffineFamilyUniversallyGluableRelativePerfectCategory
#print axioms AlgebraicGeometry.affineFamilyUniversallyGluableRelativePerfectCoreProperty
#print axioms AlgebraicGeometry.affineFamilyUniversallyGluableRelativePerfectCoreProperty_isClosed
#print axioms AlgebraicGeometry.AffineFamilyUniversallyGluableRelativePerfectModuliFiber
#print axioms AlgebraicGeometry.affineFamilyUniversallyGluableRelativePerfectModuliFiber_isGroupoid
#print axioms AlgebraicGeometry.affineFamilyUniversallyGluableRelativePerfectCoreInclusion
#print axioms AlgebraicGeometry.affineFamilyUniversallyGluableRelativePerfectModuliForget
#print axioms AlgebraicGeometry.affineFamilyUniversallyStableRelativePerfectCoreProperty
#print axioms AlgebraicGeometry.affineFamilyUniversallyStableRelativePerfectCoreProperty_isClosedUnderMapObj
#print axioms AlgebraicGeometry.affineFamilyUniversallyStableRelativePerfectPseudofunctor
#print axioms AlgebraicGeometry.affineFamilyUniversallyStableRelativePerfectInclusion
#print axioms AlgebraicGeometry.affineFamilyUniversallyStableRelativePerfect_le_fullLocus
#print axioms AlgebraicGeometry.affineFamilyUniversallyStableRelativePerfect_eq_fullLocus

/-! ## Relative-perfect and universally-gluable scheme objects (#521) -/

#print axioms AlgebraicGeometry.Scheme.Modules.IsFlatOver
#print axioms AlgebraicGeometry.schemePseudoCoherent
#print axioms AlgebraicGeometry.schemePseudoCoherent_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.relativeOpenBaseChange
#print axioms AlgebraicGeometry.relativeOpenTo
#print axioms AlgebraicGeometry.relativeOpenTo_left
#print axioms AlgebraicGeometry.relativeOpenTo_isOpenImmersion
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.flatOverBase
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.lower
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.lower_le_upper
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.mem_openSubset
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.mk.inj
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.mk.sizeOf_spec
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.model
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.openSubset
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.represents
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.strictlyGE
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.strictlyLE
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.upper
#print axioms AlgebraicGeometry.schemeLocallyFiniteTorAmplitudeOver
#print axioms AlgebraicGeometry.schemeLocallyFiniteTorAmplitudeOver_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.schemeRelativePerfect
#print axioms AlgebraicGeometry.schemeRelativePerfect_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.SchemeRelativePerfectCategory
#print axioms AlgebraicGeometry.GeometricFiberModel
#print axioms AlgebraicGeometry.GeometricFiberModel.fiberComplex
#print axioms AlgebraicGeometry.GeometricFiberModel.fiberObject
#print axioms AlgebraicGeometry.GeometricFiberModel.flatOverBase
#print axioms AlgebraicGeometry.GeometricFiberModel.mk.inj
#print axioms AlgebraicGeometry.GeometricFiberModel.mk.sizeOf_spec
#print axioms AlgebraicGeometry.GeometricFiberModel.represents
#print axioms AlgebraicGeometry.GeometricFiberModel.totalModel
#print axioms AlgebraicGeometry.UniversallyGluableData
#print axioms AlgebraicGeometry.UniversallyGluableData.fiberModel
#print axioms AlgebraicGeometry.UniversallyGluableData.mk.inj
#print axioms AlgebraicGeometry.UniversallyGluableData.mk.sizeOf_spec
#print axioms AlgebraicGeometry.UniversallyGluableData.negativeExtVanishes
#print axioms AlgebraicGeometry.schemeUniversallyGluableRelativePerfect
#print axioms AlgebraicGeometry.UniversallyGluableData.ofIso
#print axioms AlgebraicGeometry.schemeUniversallyGluableRelativePerfect_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.SchemeUniversallyGluableCategory
#print axioms AlgebraicGeometry.zeroModuleComplex
#print axioms AlgebraicGeometry.zeroModuleComplex_isZero
#print axioms AlgebraicGeometry.zeroSchemeDerivedObject
#print axioms AlgebraicGeometry.zeroSchemeDerivedObject_isZero
#print axioms AlgebraicGeometry.zeroCoherentComplex
#print axioms AlgebraicGeometry.zeroCoherentDerivedObject
#print axioms AlgebraicGeometry.zeroCoherentDerivedObject_isZero
#print axioms AlgebraicGeometry.zeroBoundedCoherentDerivedObject
#print axioms AlgebraicGeometry.zeroBoundedCoherentDerivedObject_isZero
#print axioms AlgebraicGeometry.SchemeQuasicoherentDerivedCategory.zero
#print axioms AlgebraicGeometry.schemeQuasicoherentDerivedCategory_zero_obj_isZero
#print axioms AlgebraicGeometry.schemePseudoCoherent_zero
#print axioms AlgebraicGeometry.zeroLocalFiniteTorAmplitudeChart
#print axioms AlgebraicGeometry.schemeLocallyFiniteTorAmplitudeOver_zero
#print axioms AlgebraicGeometry.schemeRelativePerfect_zero
#print axioms AlgebraicGeometry.zeroGeometricFiberModel
#print axioms AlgebraicGeometry.universallyGluableDataZero
#print axioms AlgebraicGeometry.schemeUniversallyGluableRelativePerfect_zero

/-! ## Pullback of universally-gluable relative-perfect complexes -/

#print axioms AlgebraicGeometry.RelativePerfectPullback
#print axioms AlgebraicGeometry.RelativePerfectPullback.comparison
#print axioms AlgebraicGeometry.RelativePerfectPullback.comp
#print axioms AlgebraicGeometry.RelativePerfectPullback.compExact
#print axioms AlgebraicGeometry.RelativePerfectPullback.congr
#print axioms AlgebraicGeometry.RelativePerfectPullback.coreComparison
#print axioms AlgebraicGeometry.RelativePerfectPullback.coreFunctor
#print axioms AlgebraicGeometry.RelativePerfectPullback.ambient
#print axioms AlgebraicGeometry.RelativePerfectPullback.functor
#print axioms AlgebraicGeometry.RelativePerfectPullback.identity
#print axioms AlgebraicGeometry.RelativePerfectPullback.mk.inj
#print axioms AlgebraicGeometry.RelativePerfectPullback.mk.sizeOf_spec

/-! ## Groupoid-valued relative-perfect moduli problem (#518) -/

#print axioms AlgebraicGeometry.RelativePerfectGeometricFiber
#print axioms AlgebraicGeometry.RelativePerfectIsomorphismClasses
#print axioms AlgebraicGeometry.RelativePerfectModuliFiber
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.ambientComparison
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.base
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.exactAmbientComparison
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.fiberEquivalence
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.mk.inj
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.mk.sizeOf_spec
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.presheaf
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.pullback
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.presheaf_obj_isGroupoid
#print axioms AlgebraicGeometry.RelativePerfectModuliProblem.transitionComparison
#print axioms AlgebraicGeometry.constantRelativePerfectPresheaf
#print axioms AlgebraicGeometry.identityBaseChangeDiagram
#print axioms AlgebraicGeometry.identityRelativePerfectModuliProblem
#print axioms AlgebraicGeometry.relativePerfectForget
#print axioms AlgebraicGeometry.relativePerfectGeometricZeroObject
#print axioms AlgebraicGeometry.relativePerfectIsomorphismClass
#print axioms AlgebraicGeometry.relativePerfectModuliFiber_nonempty
#print axioms AlgebraicGeometry.relativePerfectModuliForget
#print axioms AlgebraicGeometry.relativePerfectZeroObject

/-! ## Relative-perfect moduli on the big Zariski site -/

#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf.ambientComparison
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf.exactAmbientComparison
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf.fiberEquivalence
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf.fiber_isGroupoid
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf.mk.inj
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf.mk.sizeOf_spec
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf.presheaf
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf.pullback
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiPresheaf.transitionComparison
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiStack
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiStack.cechDescentEquivalence
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiStack.essSurjToCechDescent
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiStack.fullyFaithfulToCechDescent
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiStack.isStack
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiStack.mk.inj
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiStack.mk.sizeOf_spec
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiStack.toRelativePerfectBigZariskiPresheaf
#print axioms AlgebraicGeometry.RelativePerfectBigZariskiStack.toStackInGroupoids

/-! ## Stacks in groupoids and scheme descent (#523) -/

#print axioms AlgebraicGeometry.StackMorphism
#print axioms AlgebraicGeometry.StackMorphism.FiberCategory
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentation
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentation.fiberEquivalence
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentation.mk.inj
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentation.mk.sizeOf_spec
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentation.representing
#print axioms AlgebraicGeometry.StackMorphism.IsRepresentable
#print axioms AlgebraicGeometry.StackMorphism.IsRepresentable.representation
#print axioms AlgebraicGeometry.StackMorphism.app
#print axioms AlgebraicGeometry.StackMorphism.comp
#print axioms AlgebraicGeometry.StackMorphism.id
#print axioms AlgebraicGeometry.StackMorphism.Modification
#print axioms AlgebraicGeometry.StackMorphism.pullbackIso
#print axioms AlgebraicGeometry.discretePseudofunctor
#print axioms AlgebraicGeometry.discretePseudofunctor_isStack
#print axioms AlgebraicGeometry.discretePseudofunctor_obj_isDiscrete
#print axioms AlgebraicGeometry.discretePseudofunctor_obj_isGroupoid
#print axioms AlgebraicGeometry.representableZariskiCechDescentEquivalence
#print axioms AlgebraicGeometry.representableZariskiObject
#print axioms AlgebraicGeometry.representableZariskiObject_injective
#print axioms AlgebraicGeometry.representableZariskiStack
#print axioms AlgebraicGeometry.stackInGroupoidsOfSheaf

/-! ## Finite-type boundedness witnesses (#519) -/

#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.covers
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.finiteType
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.geometricFiber
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.mk.inj
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.mk.sizeOf_spec
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.monotone
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.parameter
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.universalFamily
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.universalFamily_mem
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.MonotoneTo
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.MonotoneTo.family
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.MonotoneTo.geometric
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.family
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.family_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.family_iso
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.geometric
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.geometric_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.geometric_iso
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.mk.inj
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.mk.sizeOf_spec
#print axioms AlgebraicGeometry.castRelativePerfectModuliObject
#print axioms AlgebraicGeometry.identityRelativePerfectBaseChange
#print axioms AlgebraicGeometry.relativePerfectGeometricBoundednessProblem
#print axioms AlgebraicGeometry.relativePerfectZeroObject_mem_zeroFamily
#print axioms AlgebraicGeometry.universalBoundedness_zeroRelativePerfect
#print axioms AlgebraicGeometry.universalRelativePerfectBoundedness_of_witnesses
#print axioms AlgebraicGeometry.zeroFiniteTypeBoundednessWitness
#print axioms AlgebraicGeometry.zeroRelativePerfectBoundednessProblem
#print axioms AlgebraicGeometry.zeroRelativePerfectBoundedness_afterBaseChange
#print axioms AlgebraicGeometry.zeroRelativePerfectGeometricFiber
#print axioms AlgebraicGeometry.zeroRelativePerfectModuliSubproblem
#print axioms AlgebraicGeometry.zeroRelativePerfectModuliSubproblem_isBounded

/-! ## Quotient presentations and parameter spaces (#520) -/

#print axioms AlgebraicGeometry.FiniteTypeQuotientParameterSpace
#print axioms AlgebraicGeometry.FiniteTypeQuotientParameterSpace.finiteType
#print axioms AlgebraicGeometry.FiniteTypeQuotientParameterSpace.mk.inj
#print axioms AlgebraicGeometry.FiniteTypeQuotientParameterSpace.mk.sizeOf_spec
#print axioms AlgebraicGeometry.FiniteTypeQuotientParameterSpace.toRepresentableQuotientProblem
#print axioms AlgebraicGeometry.ModuleQuotient
#print axioms AlgebraicGeometry.ModuleQuotient.Hom
#print axioms AlgebraicGeometry.ModuleQuotient.Hom.comm
#print axioms AlgebraicGeometry.ModuleQuotient.Hom.ext
#print axioms AlgebraicGeometry.ModuleQuotient.Hom.ext_iff
#print axioms AlgebraicGeometry.ModuleQuotient.Hom.mk.congr_simp
#print axioms AlgebraicGeometry.ModuleQuotient.Hom.mk.inj
#print axioms AlgebraicGeometry.ModuleQuotient.Hom.mk.sizeOf_spec
#print axioms AlgebraicGeometry.ModuleQuotient.Hom.right
#print axioms AlgebraicGeometry.ModuleQuotient.category
#print axioms AlgebraicGeometry.ModuleQuotient.comp_right
#print axioms AlgebraicGeometry.ModuleQuotient.hom
#print axioms AlgebraicGeometry.ModuleQuotient.hom_isEpi
#print axioms AlgebraicGeometry.ModuleQuotient.id_right
#print axioms AlgebraicGeometry.ModuleQuotient.identity
#print axioms AlgebraicGeometry.ModuleQuotient.isEpi
#print axioms AlgebraicGeometry.ModuleQuotient.mk.inj
#print axioms AlgebraicGeometry.ModuleQuotient.mk.sizeOf_spec
#print axioms AlgebraicGeometry.ModuleQuotient.pullback
#print axioms AlgebraicGeometry.ModuleQuotient.pullbackFunctor
#print axioms AlgebraicGeometry.ModuleQuotient.pullbackIdentityIso
#print axioms AlgebraicGeometry.ModuleQuotient.pullbackZeroIso
#print axioms AlgebraicGeometry.ModuleQuotient.target
#print axioms AlgebraicGeometry.ModuleQuotient.targetFunctor
#print axioms AlgebraicGeometry.ModuleQuotient.zero
#print axioms AlgebraicGeometry.RepresentableQuotientProblem
#print axioms AlgebraicGeometry.RepresentableQuotientProblem.mk.inj
#print axioms AlgebraicGeometry.RepresentableQuotientProblem.mk.sizeOf_spec
#print axioms AlgebraicGeometry.RepresentableQuotientProblem.parameter
#print axioms AlgebraicGeometry.RepresentableQuotientProblem.problem
#print axioms AlgebraicGeometry.RepresentableQuotientProblem.representation
#print axioms AlgebraicGeometry.RepresentableQuotientProblem.universal
#print axioms AlgebraicGeometry.zeroFiniteTypeQuotientParameterSpace
#print axioms AlgebraicGeometry.zeroQuotientFiniteTypeBoundednessWitness
#print axioms AlgebraicGeometry.zeroQuotientProblem
#print axioms AlgebraicGeometry.zeroQuotientRealization
#print axioms AlgebraicGeometry.zeroQuotientRelativePerfectModuliProblem
#print axioms AlgebraicGeometry.zeroQuotientRepresentation
#print axioms AlgebraicGeometry.zeroQuotientToRelativePerfect
#print axioms AlgebraicGeometry.zeroQuotient_isGeometricallyBounded
#print axioms AlgebraicGeometry.zeroQuotient_universal_eq

/-! ## Big-Zariski stack presentations (#522, partial) -/

#print axioms AlgebraicGeometry.ZariskiStackPresentation
#print axioms AlgebraicGeometry.ZariskiStackPresentation.atlas
#print axioms AlgebraicGeometry.ZariskiStackPresentation.atlasScheme
#print axioms AlgebraicGeometry.ZariskiStackPresentation.atlasSmoothSurjective
#print axioms AlgebraicGeometry.ZariskiStackPresentation.schemeDiagonal
#print axioms AlgebraicGeometry.ZariskiStackPresentation.mk.inj
#print axioms AlgebraicGeometry.ZariskiStackPresentation.mk.sizeOf_spec
#print axioms AlgebraicGeometry.ZariskiStackPresentation.toStackInGroupoids
#print axioms AlgebraicGeometry.ZariskiStackPresentationOver
#print axioms AlgebraicGeometry.ZariskiStackPresentationOver.locallyOfFinitePresentation
#print axioms AlgebraicGeometry.ZariskiStackPresentationOver.mk.inj
#print axioms AlgebraicGeometry.ZariskiStackPresentationOver.mk.sizeOf_spec
#print axioms AlgebraicGeometry.ZariskiStackPresentationOver.structureMorphism
#print axioms AlgebraicGeometry.ZariskiStackPresentationOver.toZariskiStackPresentation
#print axioms AlgebraicGeometry.RepresentableZariskiStackMap.fiberFunctor
#print axioms AlgebraicGeometry.RepresentableZariskiStackMap.fiberFunctor_essSurj
#print axioms AlgebraicGeometry.RepresentableZariskiStackMap.fiberFunctor_faithful
#print axioms AlgebraicGeometry.RepresentableZariskiStackMap.fiberFunctor_full
#print axioms AlgebraicGeometry.RepresentableZariskiStackMap.fiberProduct
#print axioms AlgebraicGeometry.RepresentableZariskiStackMap.fiberRepresentation
#print axioms AlgebraicGeometry.StackInGroupoids.DiagonalFiberRepresentation
#print axioms AlgebraicGeometry.StackInGroupoids.DiagonalFiberRepresentation.isomorphismEquiv
#print axioms AlgebraicGeometry.StackInGroupoids.DiagonalFiberRepresentation.mk.inj
#print axioms AlgebraicGeometry.StackInGroupoids.DiagonalFiberRepresentation.mk.sizeOf_spec
#print axioms AlgebraicGeometry.StackInGroupoids.DiagonalFiberRepresentation.representing
#print axioms AlgebraicGeometry.StackInGroupoids.HasRepresentableDiagonal
#print axioms AlgebraicGeometry.StackInGroupoids.HasRepresentableDiagonal.representation
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentationWithProperty
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentationWithProperty.mk.inj
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentationWithProperty.mk.sizeOf_spec
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentationWithProperty.property
#print axioms AlgebraicGeometry.StackMorphism.FiberRepresentationWithProperty.toFiberRepresentation
#print axioms AlgebraicGeometry.StackMorphism.HasRepresentableProperty
#print axioms AlgebraicGeometry.StackMorphism.HasRepresentableProperty.representation
#print axioms AlgebraicGeometry.StackMorphism.IsLocallyOfFinitePresentation
#print axioms AlgebraicGeometry.StackMorphism.IsSmoothSurjective
#print axioms AlgebraicGeometry.StackMorphism.hasRepresentableProperty_mono
#print axioms AlgebraicGeometry.StackMorphism.isRepresentable_of_hasRepresentableProperty
#print axioms AlgebraicGeometry.affineLineZariskiStackPresentationOver
#print axioms AlgebraicGeometry.representableZariskiStackPresentation
#print axioms AlgebraicGeometry.representableZariskiStackPresentationOver
#print axioms AlgebraicGeometry.representableZariskiDiagonalFiberRepresentation
#print axioms AlgebraicGeometry.representableZariskiStackMap
#print axioms AlgebraicGeometry.representableZariskiStackMap_hasRepresentableProperty
#print axioms AlgebraicGeometry.representableZariskiStackMap_id_isLocallyOfFinitePresentation
#print axioms AlgebraicGeometry.representableZariskiStackMap_id_isSmoothSurjective
#print axioms AlgebraicGeometry.representableZariskiStackMap_isRepresentable
#print axioms AlgebraicGeometry.representableZariskiStackMap_obj
#print axioms AlgebraicGeometry.representableZariskiStackMap_tripleComp_obj
#print axioms AlgebraicGeometry.representableZariskiStack_hasRepresentableDiagonal

/-! ## Relative-perfect big-Zariski presentations (#522, partial) -/

#print axioms AlgebraicGeometry.BoundedRelativePerfectZariskiPresentation
#print axioms AlgebraicGeometry.BoundedRelativePerfectZariskiPresentation.boundedness
#print axioms AlgebraicGeometry.BoundedRelativePerfectZariskiPresentation.mk.inj
#print axioms AlgebraicGeometry.BoundedRelativePerfectZariskiPresentation.mk.sizeOf_spec
#print axioms AlgebraicGeometry.BoundedRelativePerfectZariskiPresentation.toRelativePerfectZariskiPresentation
#print axioms AlgebraicGeometry.BoundedRelativePerfectZariskiPresentation.universalFamilyIso
#print axioms AlgebraicGeometry.BoundedRelativePerfectZariskiPresentation.universalStackObject
#print axioms AlgebraicGeometry.FiniteTypeBoundednessWitness.universalObject
#print axioms AlgebraicGeometry.RelativePerfectZariskiPresentation
#print axioms AlgebraicGeometry.RelativePerfectZariskiPresentation.presentation
#print axioms AlgebraicGeometry.RelativePerfectZariskiPresentation.fiberEquivalence
#print axioms AlgebraicGeometry.RelativePerfectZariskiPresentation.locallyOfFinitePresentation
#print axioms AlgebraicGeometry.RelativePerfectZariskiPresentation.mk.inj
#print axioms AlgebraicGeometry.RelativePerfectZariskiPresentation.mk.sizeOf_spec
#print axioms AlgebraicGeometry.RelativePerfectZariskiPresentation.stack
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.Fiber
#print axioms AlgebraicGeometry.RelativePerfectModuliSubproblem.fiber_isGroupoid
#print axioms AlgebraicGeometry.RelativePerfectOpenZariskiPresentation
#print axioms AlgebraicGeometry.RelativePerfectOpenZariskiPresentation.ambient
#print axioms AlgebraicGeometry.RelativePerfectOpenZariskiPresentation.family_le
#print axioms AlgebraicGeometry.RelativePerfectOpenZariskiPresentation.inclusion
#print axioms AlgebraicGeometry.RelativePerfectOpenZariskiPresentation.isOpenImmersion
#print axioms AlgebraicGeometry.RelativePerfectOpenZariskiPresentation.mk.inj
#print axioms AlgebraicGeometry.RelativePerfectOpenZariskiPresentation.mk.sizeOf_spec
#print axioms AlgebraicGeometry.RelativePerfectOpenZariskiPresentation.openPresentation
#print axioms AlgebraicGeometry.RelativePerfectOpenZariskiPresentation.overBase
#print axioms AlgebraicGeometry.StackMorphism.IsOpenImmersion
#print axioms AlgebraicGeometry.integerZeroBoundedRelativePerfectZariskiPresentation
#print axioms AlgebraicGeometry.representableZariskiStackMap_isOpenImmersion
#print axioms AlgebraicGeometry.zeroBoundedRelativePerfectZariskiPresentation
#print axioms AlgebraicGeometry.zeroRelativePerfectZariskiPresentation
