import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory.Tensor.BoundedAboveKFlat

/-! Diagram-colimit preservation and bounded-above K-flatness for scheme tensor. -/

#print axioms AlgebraicGeometry.Scheme.Modules.preservesColimitsOfShape_totalTensor_obj_site
#print axioms AlgebraicGeometry.Scheme.Modules.preservesColimitsOfShape_totalTensor_flip_obj_site
#print axioms AlgebraicGeometry.Scheme.Modules.preservesColimitsOfShape_totalTensor_obj_small
#print axioms AlgebraicGeometry.Scheme.Modules.preservesColimitsOfShape_totalTensor_flip_obj_small
#print axioms AlgebraicGeometry.Scheme.Modules.preservesColimitsOfShape_totalTensor_obj_nat
#print axioms AlgebraicGeometry.Scheme.Modules.preservesColimitsOfShape_totalTensor_flip_obj_nat
#print axioms AlgebraicGeometry.Scheme.Modules.isKFlat_totalTensor_of_boundedAbove_flatTerms
