/-
Scheme-derived slice of the AlgebraicGeometry audit. The `Dqc` declarations
use their geometry-owned `AlgebraicGeometry.DerivedCategory.Dqc` namespace.
-/
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory
import DerivedAlgGeo.CategoryTheory.Triangulated.FourierMukai
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearYoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearCoyoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.GrothendieckGroup.EulerForm
import DerivedAlgGeo.LinearAlgebra
open CategoryTheory.Triangulated

#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactTriangle
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactTriangle_distinguished
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactTriangle_onBounded
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactBoundedTriangle
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactBoundedTriangleInclusionIso
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactBoundedTriangle_distinguished
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactTriangleMap
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactTriangleMap_id
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactTriangleMap_comp
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactBoundedTriangleMap
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactBoundedTriangleMap_id
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactBoundedTriangleMap_comp
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactBoundedTriangleMap_ambient
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohTwistTriangle
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohTwistTriangle_distinguished
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohTwistBoundedTriangle
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohTwistBoundedTriangleInclusionIso
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohTwistBoundedTriangle_distinguished
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.lineBundleTwistSequence
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.lineBundleTwistSequence_shortExact
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.lineBundleTwistCokernelIso
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.lineBundleTwistTarget_isCoherent
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohLineBundleTwistSequence
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohLineBundleTwistSequence_shortExact
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohLineBundleTwistTriangle
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohLineBundleTwistTriangle_distinguished
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohLineBundleTwistBoundedTriangle
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohLineBundleTwistBoundedTriangle_distinguished
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohLineBundleTwistBoundedTriangleObj₁Iso
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.cohLineBundleTwistBoundedTriangleObj₂Iso
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactBoundedTriangleMap_comp_assoc
#print axioms AlgebraicGeometry.DerivedCategory.cohShortExactTriangleMap_comp_assoc
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.lineBundleTwistMiddle_isCoherent
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.lineBundleTwistSequence_X₁
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.lineBundleTwistSequence_X₂
#print axioms AlgebraicGeometry.Scheme.EffectiveCartierDivisor.lineBundleTwistSource_isCoherent

/-! ## Cartier divisors as line bundles and derived objects -/

#print axioms AlgebraicGeometry.Scheme.CartierDivisor.lineBundleData
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.lineBundleData_toPic
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.associatedSheaf_isCoherent
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.coh
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.cohIso
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.derivedObject
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.derivedObject_perfect
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.derivedObject_bounded
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.derivedObjectIso
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.boundedDerivedObject
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.boundedDerivedObjectIso
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.boundedDerivedObjectOfCoherence
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.boundedDerivedObjectOfCoherence_obj
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.boundedDerivedObject_obj
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.coh_obj
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.derivedObject_eq_single
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.lineBundleData_inverse
#print axioms AlgebraicGeometry.Scheme.CartierDivisor.lineBundleData_line

/-! ## Affine quasi-coherent derived realization (#528) -/

#print axioms AlgebraicGeometry.DerivedCategory.Dqc.AffineQuasicoherentDerivedCategory
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.AffineQuasicoherentSheaves
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineGammaDerivedFunctor
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineGammaDerivedHomologyIso
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentDerivedCategory_isTriangulated
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentSheavesAbelian
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentSheavesEquiv
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentSheavesEquiv_functor_additive
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentSheavesEquiv_inverse_additive
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentSheavesHasFiniteProducts
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineTildeDerivedFunctor
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineTildeDerivedHomologyIso

/-! ## Coproducts in the affine quasi-coherent realization (#528)

The abelian coproducts are the ambient ones, created by the inclusion into
`(Spec R).Modules`; their exactness is transported across the tilde equivalence and
is affine-only. Nothing here claims unbounded essential surjectivity, compact
generation, or `S`-linearity. -/

#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentSheavesHasExactCoproducts
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentSheavesInclusion_preservesCoproductsOfShape
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentDerivedCategory_hasCoproductsOfShape
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentQ_preservesCoproductsOfShape
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentHomologyFunctor_preservesCoproductsOfShape
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineTildeDerivedFunctor_preservesCoproductsOfShape
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineGammaDerivedFunctor_preservesCoproductsOfShape
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentDerivedInclusion_preservesCoproductsOfShape
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.affineQuasicoherentDerivedToDqc_preservesCoproductsOfShape

/-! ## The supported non-flat affine pullback witness and one derived effect

(SF8.5 item 9, #1404; explicit representative calculation for #554)

`ZMod 2` over `ℤ` is the standard closed immersion that is not flat: flatness
would make `ZMod 2` torsion-free as a `ℤ`-module, and `2 • 1 = 0` with both
factors nonzero. The point of recording it is the pullback below -- the affine
bounded-above-projective core pseudofunctor builds `zmodTwoAffinePullback`
with no flatness hypothesis available to it, so the witness is what stops
"supported" being read as "flat, implicitly".

It is an EXAMPLE and the records below claim nothing more. It does not identify
the supported affine K-projective-derived lane with the relative-perfect locus,
and it does not prove the general-scheme preservation theorems, which remain
open in #554.

The second group records one affine calculation on one two-term free
representative. It proves nonzero degree-minus-one homology after scalar
extension and identifies that complex with the existing supported
K-projective pullback of that representative. It does not create a general
scheme-level derived-pullback theorem or assert a comparison with an
unformalized classical invariant. The final declarations compare its restricted
degree-minus-one homology with Mathlib's fixed-left, derived-second-factor Tor
and record the resulting nonzero Tor value for these concrete modules only. -/

#print axioms AlgebraicGeometry.DerivedCategory.Dqc.zmodTwoRing
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.zmodTwoRingMap
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.zmodTwoSchemeMap
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.zmodTwoRingMap_not_flat
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.zmodTwoSchemeMap_not_flat
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.zmodTwoRingMap_not_iso
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.zmodTwoAffinePullback
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.twoTermResolution
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.twoTermAugmentation
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.twoTermAugmentation_quasiIso
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.twoTermResolution_isStrictlyLE_zero
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.twoTermResolution_projective_X
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.kProjectiveRepresentative
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.boundedAboveProjectiveRepresentative
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.supportedAffineBoundedAboveProjectiveRepresentative
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.baseChangedResolution
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.affineKProjectivePullbackObject
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.affineKProjectivePullbackObjectIso
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.baseChangedResolution_homology_negOne_not_isZero
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.affineKProjectivePullbackObject_homology_negOne_not_isZero
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.supportedAffineBoundedAboveProjectiveRepresentative_homology_negOne_not_isZero
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.schemeModulePulledBackResolution
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.schemeModulePulledBackResolutionIso
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.schemeModulePulledBackResolution_homology_negOne_not_isZero
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.torOneIsoRestrictScalarsBaseChangedResolutionHomologyNegOne
#print axioms AlgebraicGeometry.DerivedCategory.Dqc.ZModTwoNonflatDerived.torOne_not_isZero

/-! ## Relative-perfect and universally-gluable scheme objects (#521)

Pseudo-coherence, local finite Tor amplitude over a base, relative
perfection and the universally-gluable refinement: properties of one
complex over one morphism. Audited here since 2026-09-13 (MO1.11,
#1322), when their owner became
`AlgebraicGeometry/DerivedCategory/Perfect/Relative.lean`. The
perfect-notion comparisons stay with the Moduli slice. -/

#print axioms AlgebraicGeometry.schemePseudoCoherent
#print axioms AlgebraicGeometry.schemePseudoCoherent_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.relativeOpenBaseChange
#print axioms AlgebraicGeometry.relativeOpenTo
#print axioms AlgebraicGeometry.relativeOpenTo_left
#print axioms AlgebraicGeometry.relativeOpenTo_isOpenImmersion
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.flatOverBase
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.lower
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.lower_le_upper
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.mem_openSubset
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.mk.inj
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.mk.sizeOf_spec
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.model
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.openSubset
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.represents
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.strictlyGE
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.strictlyLE
#print axioms AlgebraicGeometry.LocalFiniteTorAmplitudeChart.upper
#print axioms AlgebraicGeometry.schemeLocallyFiniteTorAmplitudeOver
#print axioms AlgebraicGeometry.schemeLocallyFiniteTorAmplitudeOver_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.schemeRelativePerfect
#print axioms AlgebraicGeometry.schemeRelativePerfect_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.SchemeRelativePerfectCategory
#print axioms AlgebraicGeometry.SchemeRelativePerfectCategory.exists_boundedCoherentRepresentative
#print axioms AlgebraicGeometry.SchemeRelativePerfectCategory.perfect_iff_compact
#print axioms AlgebraicGeometry.GeometricFiberModel
#print axioms AlgebraicGeometry.GeometricFiberModel.fiberComplex
#print axioms AlgebraicGeometry.GeometricFiberModel.fiberObject
#print axioms AlgebraicGeometry.GeometricFiberModel.flatOverBase
#print axioms AlgebraicGeometry.GeometricFiberModel.mk.inj
#print axioms AlgebraicGeometry.GeometricFiberModel.mk.sizeOf_spec
#print axioms AlgebraicGeometry.GeometricFiberModel.represents
#print axioms AlgebraicGeometry.GeometricFiberModel.totalModel
#print axioms AlgebraicGeometry.UniversallyGluableData
#print axioms AlgebraicGeometry.UniversallyGluableData.fiberModel
#print axioms AlgebraicGeometry.UniversallyGluableData.mk.inj
#print axioms AlgebraicGeometry.UniversallyGluableData.mk.sizeOf_spec
#print axioms AlgebraicGeometry.UniversallyGluableData.negativeExtVanishes
#print axioms AlgebraicGeometry.schemeUniversallyGluableRelativePerfect
#print axioms AlgebraicGeometry.UniversallyGluableData.ofIso
#print axioms AlgebraicGeometry.schemeUniversallyGluableRelativePerfect_isClosedUnderIsomorphisms
#print axioms AlgebraicGeometry.SchemeUniversallyGluableCategory
#print axioms AlgebraicGeometry.zeroModuleComplex
#print axioms AlgebraicGeometry.zeroModuleComplex_isZero
#print axioms AlgebraicGeometry.schemePseudoCoherent_zero
#print axioms AlgebraicGeometry.zeroLocalFiniteTorAmplitudeChart
#print axioms AlgebraicGeometry.schemeLocallyFiniteTorAmplitudeOver_zero
#print axioms AlgebraicGeometry.schemeRelativePerfect_zero
#print axioms AlgebraicGeometry.zeroGeometricFiberModel
#print axioms AlgebraicGeometry.universallyGluableDataZero
#print axioms AlgebraicGeometry.schemeUniversallyGluableRelativePerfect_zero
