/-
Geometric families slice of the AlgebraicGeometry audit. Scheme-derived
foundations use their geometry-owned namespaces; the remaining Dqc,
Fourier--Mukai, and stability-specific declarations retain staged namespaces
until their separate cutovers.
-/
import DerivedAlgGeo.AlgebraicGeometry.DerivedCategory
import DerivedAlgGeo.AlgebraicGeometry.StabilityCondition.Families
import DerivedAlgGeo.AlgebraicGeometry.StabilityCondition.FourierMukai
import DerivedAlgGeo.CategoryTheory.Triangulated.FourierMukai
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearYoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.LinearCoyoneda
import DerivedAlgGeo.CategoryTheory.Triangulated.GrothendieckGroup.EulerForm
import DerivedAlgGeo.LinearAlgebra
open CategoryTheory.Triangulated

/-! ## Scheme-derived and stability-specific realizations of family interfaces -/

#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.constant
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.ChargeProbe.ofScheme
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.ChargeProbe.ofScheme_isLocallyConstant_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.OpenLocusProbe.ofScheme
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.OpenLocusProbe.ofScheme_isOpen_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GenericSemistabilityProbe.ofScheme
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GenericSemistabilityProbe.ofScheme_isGenericallyOpen_iff
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.residue
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.residue_left
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.residue_hom
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.residueTo
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.residueTo_left
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.ResidueFiber
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.pullToResidue
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.pullK₀ToResidue
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.pullK₀ToResidue_of
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeSemistableLocusIndex
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeSemistableLocusIndex.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeSemistableLocusIndex.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeSemistableLocusIndex.baseChange
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeSemistableLocusIndex.phase
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeSemistableLocusIndex.object
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeGenericSemistableLocusIndex
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeGenericSemistableLocusIndex.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeGenericSemistableLocusIndex.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeGenericSemistableLocusIndex.index
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeGenericSemistableLocusIndex.genericPoint
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeSemistableLocus
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.mem_schemeSemistableLocus_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeSemistableOpenProbe
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeGenericSemistabilityProbe
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeSemistableOpenProbe_isOpen_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeGenericSemistabilityProbe_isGenericallyOpen_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.universalSchemeSemistableOpenness_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.universalSchemeGenericSemistabilityOpenness_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.mem_schemeSemistableLocus_iff_of_baseChange
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeSemistableLocus_eq_univ_of_phase
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeSemistableLocus_eq_empty_of_not_phase
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeSemistableLocus_isOpen
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.universalSchemeSemistableOpenness
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeGenericSemistabilityProbe_isGenericallyOpen
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.universalSchemeGenericSemistabilityOpenness
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.universalSchemeSemistableOpenness_constant
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.universalSchemeGenericSemistabilityOpenness_constant
#print axioms AlgebraicGeometry.DerivedCategory.SchemeDerivedCategory
#print axioms AlgebraicGeometry.DerivedCategory.SchemeBoundedDerivedCategory
#print axioms AlgebraicGeometry.DerivedCategory.SchemeDerivedCategory.Q
#print axioms AlgebraicGeometry.DerivedCategory.SchemeDerivedCategory.boundedInclusion
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.DerivedFiber
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.BoundedDerivedFiber
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.ResidueDerivedFiber
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.ResidueBoundedDerivedFiber
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.residueDerivedFiber_eq
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.residueBoundedDerivedFiber_eq
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.DerivedRealization
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.DerivedRealization.mk.inj
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.DerivedRealization.mk.sizeOf_spec
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.DerivedRealization.fiberEquivalence
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.DerivedRealization.residueFiberEquivalence
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.BoundedDerivedRealization
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.BoundedDerivedRealization.mk.inj
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.BoundedDerivedRealization.mk.sizeOf_spec
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.BoundedDerivedRealization.fiberEquivalence
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeTriangulatedFiberFamily.BoundedDerivedRealization.residueFiberEquivalence
#print axioms AlgebraicGeometry.DerivedCategory.Families.schemeModulesHasDerivedCategory
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.modulePullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.modulePullbackId
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.modulePullbackComp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.IsExactPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.IsExactPullback.preservesFiniteLimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.IsExactPullback.preservesFiniteColimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.modulePullback_preservesFiniteColimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.IsExactPullback.of_preservesFiniteLimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.isExactPullback_iff_preservesFiniteLimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.moduleStalkRingCocone
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.moduleStalkRingIsColimit
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.neighborhoodModuleStalkFunctor
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.presheafModuleStalkFunctor
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.moduleStalkFunctor
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.presheafModuleStalkToSheafificationApp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.presheafModuleStalkToSheafificationApp_isIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.presheafModuleStalkSheafificationIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.moduleStalkForgetIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.moduleStalkFunctor_preservesFiniteLimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.flatStalkMap_preservesFiniteLimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.flatPullbackStalkModel_preservesFiniteLimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.presheafModulePullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.neighborhoodRingHom
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.neighborhoodModulePullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.neighborhoodRingHom_comp_stalkCocone
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.constNeighborhoodPushforwardIsoApp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.constNeighborhoodPushforwardIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.neighborhoodModulePullbackStalkIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.modulePullbackStalkPresheafIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.presheafModulePullbackStalkIso
#print axioms ModuleCat.isoMk.congr_simp
#print axioms ModuleCat.restrictScalarsCongr.congr_simp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.moduleStalkFunctors_jointlyReflectIsomorphisms
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.preservesFiniteLimits_of_stalkwise
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PresheafPullbackStalkComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PresheafPullbackStalkComparison.iso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PresheafPullbackStalkComparison.mk.inj
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PresheafPullbackStalkComparison.mk.sizeOf_spec
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackStalkComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackStalkComparison.iso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackStalkComparison.mk.inj
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackStalkComparison.mk.sizeOf_spec
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PresheafPullbackStalkComparison.toPullbackStalkComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.pullbackStalkComparisonId
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackStalkComparison.comp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.modulePullback_preservesFiniteLimits_of_flat_of_stalkComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.isExactPullback_of_flat_of_stalkComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.isExactPullback_of_flat_of_presheafStalkComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.presheafPullbackStalkComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.isExactPullback_of_flat
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.isExactPullbackOfFlat
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.openImmersionPullbackStalkForgetIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.openImmersionPullbackStalk_preservesFiniteLimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.openImmersionModulePullback_preservesFiniteLimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.isExactPullback_of_isOpenImmersion
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.isExactPullbackOfIsOpenImmersion
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullback.congr_simp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullbackFactors
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.instCommShiftDerivedFiberDerivedPullbackInt
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.instIsTriangulatedDerivedFiberDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullK₀
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullK₀_of
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullToResidue
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullK₀ToResidue
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullK₀ToResidue_of
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.isExactPullbackId
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.isExactPullbackComp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackId
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackComp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.identityDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.compositeDerivedPullback

/-! ## Arbitrary left-derived scheme pullback -/

#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback.counit
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback.functor
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback.isLeftDerived
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback.mk.inj
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback.mk.sizeOf_spec
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback.congr
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback.exactComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback.identity
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.LeftDerivedPullback.ofExact

/-! ## Functorial pullback-acyclic resolutions -/

#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.resolution
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.comparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.comparison_quasiIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.pullback_inverts
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.resolved_comparison_isIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.mk.inj
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.mk.sizeOf_spec
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.derivedFunctor
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.derivedFactors
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.localizationComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.counit
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.outerComparisonIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.innerComparisonIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.counit_app_resolution_isIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.whiskeredLift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.lift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.whiskerLeft_lift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.whiskerLeft_lift_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.whiskeredLift_fac
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.whiskeredLift_fac_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.lift_fac
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.lift_fac_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.counit_hom_ext
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.isLeftDerived
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.toLeftDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.ofExact
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.exactComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.exactComparison_hom_counit
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.exactComparison_hom_counit_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.ofFlat
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.flatComparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.flatComparison_hom_counit
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PullbackAcyclicResolution.flatComparison_hom_counit_assoc

/-! ## Affine K-projective pullback -/

#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentDerivedEquivalence
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentDerivedEquivalence_functor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentDerivedEquivalence_inverse
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherent_kernel
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherent_isClosedUnderKernels
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherent_cokernel
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherent_isClosedUnderCokernels
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentSheavesInclusion
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentSheavesInclusion_additive
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentSheavesInclusion_preservesKernel
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentSheavesInclusion_preservesCokernel
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentSheavesInclusion_preservesFiniteLimits
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentSheavesInclusion_preservesFiniteColimits
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineTilde_preservesFiniteLimits
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentDerivedInclusion
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentDerivedInclusion_mem_dqc
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentDerivedToDqc
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineQuasicoherentDerivedToDqcCompInclusion
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineExtendScalars_additive
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveHomotopy
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.KProjectiveHomotopyCategory
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveHomotopyCategory_isKProjective
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveQh
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveQh_full
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveQh_faithful
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.KProjectiveDerivedCategory
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveQhEquivalence
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.KProjectiveHomotopyCategory.ofBoundedAboveProjectives
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveDerivedFunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveLocusDerivedFunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveLocusDerivedComparison
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.kProjectiveDerivedFunctorObjIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineKProjectivePullback
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineKProjectiveDerivedPullback
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineKProjectiveDerivedPullbackComparison
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineKProjectivePullbackObjIso

/-! ## Preserved affine bounded-above projective locus -/

#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveHomotopy
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedAboveProjectiveHomotopyCategory
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveHomotopy_le_kProjective
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveToKProjective
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveQh
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveHomotopyCategory_isKProjective
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveQh_full
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveQh_faithful
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedAboveProjectiveDerivedCategory
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveQhEquivalence
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.mapBoundedAboveProjectiveHomotopy
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.mapBoundedAboveProjectiveHomotopyCompIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveDerivedFunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveDerivedFunctorCompIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineExtendScalars_preservesProjectiveObjects
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveHomotopyPullback
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveHomotopyPullbackCompIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveDerivedPullback
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveDerivedPullbackCompIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.mapBoundedAboveProjectiveHomotopyIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.mapBoundedAboveProjectiveHomotopyIdIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveDerivedFunctorIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedAboveProjectiveDerivedFunctorIdIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveHomotopyPullbackIdIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveDerivedPullbackIdIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineExtendScalarsComplex_associativity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineExtendScalarsComplex_leftUnitality
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineExtendScalarsComplex_rightUnitality
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveHomotopyPullback_associativity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveHomotopyPullback_leftUnitality
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveHomotopyPullback_rightUnitality
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveHomotopyPseudofunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveDerivedPullback_associativity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveDerivedPullback_leftUnitality
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveDerivedPullback_rightUnitality
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveDerivedPseudofunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveQuasicoherentRealization
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveQuasicoherentRealization_full
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveQuasicoherentRealization_faithful
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.AffineBoundedAboveProjectiveQuasicoherentDerivedCategory
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveQuasicoherentEquivalence
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveDerivedPullback
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveDerivedPullbackCompIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveDerivedPullbackIdIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveDerivedPullback_associativity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveDerivedPullback_leftUnitality
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveDerivedPullback_rightUnitality
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveDerivedPseudofunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveDerivedToDqc
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveQuasicoherentEquivalenceCompToDqc
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.AffineBoundedAboveProjectiveModuliFiber
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveCorePullback
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveCorePullbackIdIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveCorePullbackCompIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineGeometricBoundedAboveProjectiveCorePseudofunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineBoundedAboveProjectiveModuliForget
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineFamilyCoordinateRingFunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.AffineFamilyCoordinateRing
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineFamilyToTestScheme
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineFamilyToTotalSpace
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineFamily_isPullback
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.AffineFamilyBoundedAboveProjectiveModuliFiber
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineFamilyBoundedAboveProjectivePullback
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineFamilyBoundedAboveProjectivePseudofunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineFamilyBoundedAboveProjectivePseudofunctor_map_toFunctor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.affineFamilyBoundedAboveProjectiveModuliForget
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackIdLocalized
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullbackId
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackCompLocalized
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullbackComp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullK₀_id
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullK₀_comp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullback_associativity
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullback_associativity_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullback_left_unitality
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullback_left_unitality_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullback_right_unitality
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullback_right_unitality_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackCongr
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackCongr.congr_simp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullbackCongr
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullbackCongr.congr_simp
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullback_left_unitality
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullback_left_unitality_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullback_right_unitality
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullback_right_unitality_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullback_associativity
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullback_associativity_assoc
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullbackFactors_commShift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackId_commShift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackComp_commShift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackIdLocalized_commShift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.complexPullbackCompLocalized_commShift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullbackId_commShift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.derivedPullbackComp_commShift
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackPreimageData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackPreimageData.preimageData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackPreimageData.preimage
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackPreimageData.identity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackPreimageData.preimage_identity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackPreimageData.comp
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackPreimageData.preimage_comp
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackInducingData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackInducingData.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackInducingData.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackInducingData.inducedTStructures
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackInducingData.identity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackInducingData.toPreimageData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.DerivedPullbackInducingData.toPreimageData_of_flat
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.baseChange
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.noetherian
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.regular
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.dimensionLEOne
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.hasDimensionOne
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.instIsNoetherianLeftSchemeBaseChange
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.instIsRegularLocalRingCarrierStalkCommRingCatPresheafLeftSchemeBaseChange
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.RegularCurveBaseChange.instKrullDimLEOfNatNatCarrierStalkCommRingCatPresheafLeftSchemeBaseChange
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.filtration
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.fiberFiltration
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.fiber_length
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.fiber_phase
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.fiberFactorIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.tower
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.length
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.factor
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.phase
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.phase_strictAnti
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.factor_semistable
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.fiberIndex
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.ofBaseChangeWitness
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.pullback
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.pullback_length
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.pullback_phase
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.pullbackFactorIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.restrictToFiber
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.restrictToFiber_length
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.restrictToFiber_phase
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.restrictToFiberFactorIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.pullback_comp_phase
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeRelativeHNFiltration.constant_nonempty
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeRelativeHNProblem
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.HasSchemeRelativeHNFiltrations
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.integratesAfterDedekindBaseChange_of_relativeHN
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.hasSchemeRelativeHNFiltrations_constant
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.integratesAfterDedekindBaseChange_relativeHN_constant

/-! ## Bounded coherent and perfect scheme-derived fibers

`schemePerfect` is the thick envelope of degree-zero finite locally free
coherent sheaves.  The pullback records below are contracts: clean axiom lists
certify their constructions and consequences, not the existence of a
geometric witness for every scheme morphism.
-/

#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeCoherentDerivedCategory
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBoundedCoherentDerivedCategory
#print axioms AlgebraicGeometry.DerivedCategory.Families.tStructureIsLE_of_retract
#print axioms AlgebraicGeometry.DerivedCategory.Families.tStructureIsGE_of_retract
#print axioms AlgebraicGeometry.DerivedCategory.Families.instIsStableUnderRetractsMinus_derivedAlgGeo
#print axioms AlgebraicGeometry.DerivedCategory.Families.instIsStableUnderRetractsPlus_derivedAlgGeo
#print axioms AlgebraicGeometry.DerivedCategory.Families.instIsStableUnderRetractsBounded_derivedAlgGeo
#print axioms AlgebraicGeometry.DerivedCategory.Families.mapHomologicalComplex_isStrictlyLE
#print axioms AlgebraicGeometry.DerivedCategory.Families.mapHomologicalComplex_isStrictlyGE
#print axioms AlgebraicGeometry.DerivedCategory.Families.mapDerivedCategory_isLE
#print axioms AlgebraicGeometry.DerivedCategory.Families.mapDerivedCategory_isGE
#print axioms AlgebraicGeometry.DerivedCategory.Families.mapDerivedCategory_bounded
#print axioms AlgebraicGeometry.DerivedCategory.Families.schemeFiniteLocallyFreeGenerator
#print axioms AlgebraicGeometry.DerivedCategory.Families.schemePerfect
#print axioms AlgebraicGeometry.DerivedCategory.Families.schemeFiniteLocallyFreeGenerator_le_bounded
#print axioms AlgebraicGeometry.DerivedCategory.Families.schemePerfect_le_bounded
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemePerfectDerivedCategory
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemePerfectDerivedCategory.ι
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemePerfectDerivedCategory.toBounded
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemePerfectDerivedCategory.structureSheaf_mem_generator
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemePerfectDerivedCategory.structureSheaf_mem
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemePerfectDerivedCategory.structureSheaf
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemePerfectDerivedCategory.instNonemptySchemeCoherentDerivedCategorySchemeFiniteLocallyFreeGenerator
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemePerfectDerivedCategory.instNonemptySchemeCoherentDerivedCategorySchemePerfect
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.BoundedCoherentDerivedFiber
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PerfectDerivedFiber
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.ResidueBoundedCoherentDerivedFiber
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.ResiduePerfectDerivedFiber
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.sheafPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.preservesFiniteLimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.preservesFiniteColimits
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.comparison
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.derivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.derivedFactors
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.commShift
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.isTriangulated
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.preservesBounded
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.coherentDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.instCommShiftSchemeCoherentDerivedCategoryLeftSchemeCoherentDerivedPullbackInt
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.instIsTriangulatedSchemeCoherentDerivedCategoryLeftSchemeCoherentDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.boundedCoherentDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.boundedCoherentDerivedPullbackCompInclusion
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PreservesPerfectPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.PreservesPerfectPullback.mapsGenerator
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.coherentDerivedPullback_preservesPerfect
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.perfectDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.perfectDerivedPullbackCompInclusion
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.GeometricDerivedPullbackIdentity
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.GeometricDerivedPullbackIdentity.boundedIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.GeometricDerivedPullbackIdentity.perfectIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.GeometricDerivedPullbackComposition
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.GeometricDerivedPullbackComposition.boundedIso
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.GeometricDerivedPullbackComposition.perfectIso

/-! ## Honest Dqc, bounded coherent, and perfect loci

`SchemeQuasicoherentDerivedCategory` is cut out inside the all-module-sheaf
derived category by quasi-coherence of every homology sheaf.  The concrete
coherent inclusion is proved to land in that locus.  The two final
identification propositions are intentionally uninhabited here: they name the
general-scheme equivalence and compact/perfect theorem still needed by A.14.
-/

#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeQuasicoherentCohomology
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.instIsClosedUnderIsomorphismsSchemeDerivedCategorySchemeQuasicoherentCohomology
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeQuasicoherentDerivedCategory
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeQuasicoherentDerivedCategory.ι
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeQuasicoherentDerivedCategory.mem_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.mapDerivedCategoryHomologyIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.coherentDerivedInclusion
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.coherentDerivedInclusion_mem_dqc
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.coherentDerivedToDqc
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.coherentDerivedToDqcCompInclusion
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeBoundedQuasicoherent
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.instIsClosedUnderIsomorphismsSchemeQuasicoherentDerivedCategorySchemeBoundedQuasicoherent
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBoundedQuasicoherentDerivedCategory
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBoundedQuasicoherentDerivedCategory.ι
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBoundedQuasicoherentDerivedCategory.mem_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeBoundedCoherentCohomology
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.instIsClosedUnderIsomorphismsSchemeQuasicoherentDerivedCategorySchemeBoundedCoherentCohomology
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBoundedCoherentDqcCategory
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemeBoundedCoherentCohomology_le_bounded
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.boundedCoherentDerivedToDqc
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBoundedCoherentDqcCategory.ι
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.perfectDerivedToDqc
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.schemePerfectInDqc
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDqcIdentification
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDqcIdentification.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDqcIdentification.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDqcIdentification.equivalence
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDqcIdentification.comparison
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.HasBoundedCoherentDqcIdentification
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.PerfectObjectsAreCompactInDqc

/-! ## Geometric bounded-coherent base change

This layer constructs the slicing preimage witness from the actual bounded
coherent pullback.  The presentable/Ind inducing theorem, its left adjoint,
zero-reflection, and phase-monad premises remain explicit inputs; none of the
records below assert openness or relative-HN existence.
-/

#print axioms CategoryTheory.Triangulated.Slicing.preimage.congr_simp
#print axioms AlgebraicGeometry.DerivedCategory.Families.schemeCoherentHasDerivedCategory
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.HasCoherentPullback.derivedAdditive
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.instAdditiveSchemeCoherentDerivedCategoryLeftSchemeCoherentDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.instAdditiveBoundedCoherentDerivedFiberBoundedCoherentDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.instCommShiftBoundedCoherentDerivedFiberBoundedCoherentDerivedPullbackInt
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.instIsTriangulatedBoundedCoherentDerivedFiberBoundedCoherentDerivedPullback
#print axioms AlgebraicGeometry.DerivedCategory.Families.SchemeBaseChange.instCommShiftBoundedCoherentDerivedFiberDerivedCategoryCohLeftSchemeHomFunctorBoundedCoherentDerivedPullbackCompInclusionInt
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackPreimageData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackPreimageData.preimageData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackPreimageData.preimage
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackPreimageData.identity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackPreimageData.preimage_identity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackPreimageData.comp
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackPreimageData.preimage_comp
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackInducingData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackInducingData.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackInducingData.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackInducingData.inducedTStructures
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackInducingData.identity
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeBaseChange.BoundedCoherentPullbackInducingData.toPreimageData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.fiberEquivalence
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.fiberEquivalenceFunctorCommShift
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.fiberEquivalenceCommShift
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.fiberEquivalenceIsTriangulated
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.pullbackIso
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.inversePreimageData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.inversePreimage
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.BoundedCoherentDerivedRealization.preimageData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.classMapCompatible
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.chargeCompatible
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.inducing
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.slicingCompatible
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.toFiberPreStabilityBaseChangeData
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.phase_iff
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.phase_iff_comp

/-! ## Finite-type openness and relative HN consequences

Finite type is the concrete conjunction of Mathlib's locally-of-finite-type
and quasi-compact morphism predicates.  The conclusions below are constructed
from `GeometricPreStabilityBaseChangeData`; no openness or relative-HN
existence proposition is an input.
-/

#print axioms AlgebraicGeometry.DerivedCategory.Families.IsFiniteTypeBaseChange
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeSemistableLocusIndex
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeSemistableLocusIndex.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeSemistableLocusIndex.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeSemistableLocusIndex.index
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeSemistableLocusIndex.finiteType
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeGenericSemistableLocusIndex
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeGenericSemistableLocusIndex.mk.inj
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeGenericSemistableLocusIndex.mk.sizeOf_spec
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeGenericSemistableLocusIndex.index
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeSchemeGenericSemistableLocusIndex.finiteType
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.finiteTypeRegularCurveEligible
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.finiteTypeSchemeSemistableLocus_isOpen
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.universalFiniteTypeSchemeSemistableOpenness
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.finiteTypeSchemeGenericSemistabilityProbe_isGenericallyOpen
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.universalFiniteTypeSchemeGenericSemistabilityOpenness
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.finiteTypeSchemeRelativeHNFiltration
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.hasFiniteTypeSchemeRelativeHNFiltrations
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.integratesAfterFiniteTypeRegularCurveBaseChange
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeGeometricConsequences
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeGeometricConsequences.semistableOpenness
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeGeometricConsequences.genericOpenness
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.FiniteTypeGeometricConsequences.relativeHN
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.GeometricPreStabilityBaseChangeData.finiteTypeConsequences

/-! ## `Dqc(X)` is a triangulated subcategory (#721)

Quasi-coherence is a weak Serre subcategory of `X.Modules` containing zero, on an
arbitrary scheme, so `DerivedCategory.cohomologyIn_isTriangulated` applies and the
inclusion into the all-sheaf derived category is a triangulated functor. Neither is
transported along an unproved equivalence.
-/

#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.instIsTriangulatedSchemeDerivedCategorySchemeQuasicoherentCohomology
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeQuasicoherentDerivedCategory.ι_isTriangulated

/-! ## The abelian-side inputs to `Dqc(X)`'s coproduct structure (#721)

Quasi-coherence is closed under isomorphism and under `ι`-indexed coproducts, and both
resolve in `Families/Dqc.lean`'s own context. The derived-category half of that bullet —
that `SchemeDerivedCategory X` has small coproducts and that `Hⁿ` preserves them — is
absent from Mathlib at this pin and is asserted nowhere.
-/

#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeQuasicoherentDerivedCategory.quasicoherent_isClosedUnderIsomorphisms
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeQuasicoherentDerivedCategory.quasicoherent_isClosedUnderCoproducts
#print axioms CategoryTheory.Triangulated.StabilityCondition.Families.SchemeQuasicoherentDerivedCategory.sigma_mem
