/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import Mathlib.Algebra.Homology.ShortComplex.ShortExact
import Mathlib.CategoryTheory.Abelian.CommSq
import Mathlib.CategoryTheory.ComposableArrows.Basic
import Mathlib.CategoryTheory.Limits.Shapes.Pullback.Iso

/-!
# Finite filtrations in an abelian category

This file records the common categorical root of finite filtrations.  `FiniteExactTower` owns
the successive short exact sequences; a `FiniteFiltration M` extends that parent with a proof
that its bottom is zero and a chosen identification of its top with `M`.

When a graded piece is itself filtered, `FiniteFiltration.pullbackTower` pulls its stages back
along the coarse quotient projection.  The endpoint comparison isomorphisms identify the new
tower with the adjacent coarse stages, providing the categorical splice data used by
almost-disconnected composition.

Keeping this root independent of schemes prevents geometric filtrations (for example, the
almost-disconnected filtrations of arXiv:2607.28411, Appendix B) from growing their own
incompatible tower type.
-/

open CategoryTheory Limits

universe v v₂ u u₂

namespace CategoryTheory

variable (C : Type u) [Category.{v} C] [HasZeroMorphisms C]

/-- A finite tower of successive short exact extensions.

This is the endpoint-free categorical parent of `FiniteFiltration`.  It is useful when a
filtration of a quotient is pulled back to a tower beginning at the kernel: that intermediate
tower does not itself begin at zero, so it must not be encoded as a second filtration type or by
putting a false endpoint condition into a structure field. -/
structure FiniteExactTower where
  /-- The number of graded pieces. -/
  length : ℕ
  /-- The objects `T₀, ..., Tₙ` in the tower. -/
  object : Fin (length + 1) → C
  /-- The inclusion `Tᵢ ⟶ Tᵢ₊₁`. -/
  inclusion : ∀ i : Fin length, object i.castSucc ⟶ object i.succ
  /-- The `i`th graded piece `Tᵢ₊₁/Tᵢ`. -/
  graded : Fin length → C
  /-- The quotient projection `Tᵢ₊₁ ⟶ Tᵢ₊₁/Tᵢ`. -/
  projection : ∀ i : Fin length, object i.succ ⟶ graded i
  /-- Consecutive maps compose to zero. -/
  zero : ∀ i, inclusion i ≫ projection i = 0
  /-- Each step realizes its named graded piece as the quotient. -/
  shortExact : ∀ i,
    (ShortComplex.mk (inclusion i) (projection i) (zero i)).ShortExact

/-- A finite filtration of an object by successive short exact sequences.

`object i.castSucc ⟶ object i.succ ⟶ graded i` is the `i`th short exact sequence.  The
endpoint data express `F₀ = 0` and `Fₙ = M` without making either equality definitional. -/
structure FiniteFiltration (M : C) extends FiniteExactTower C where
  /-- The bottom term is zero. -/
  initialIsZero : IsZero (object 0)
  /-- The top term is the filtered object. -/
  terminalIso : object (Fin.last length) ≅ M

namespace FiniteExactTower

variable {C : Type u} [Category.{v} C] [HasZeroMorphisms C]
variable {D : Type u₂} [Category.{v₂} D] [HasZeroMorphisms D]

/-- The short complex presenting the `i`th successive quotient. -/
def step (T : FiniteExactTower C) (i : Fin T.length) : ShortComplex C :=
  ShortComplex.mk (T.inclusion i) (T.projection i) (T.zero i)

theorem step_shortExact (T : FiniteExactTower C) (i : Fin T.length) :
    (T.step i).ShortExact :=
  T.shortExact i

/-- The composable-arrow diagram canonically generated by the successive inclusions. -/
noncomputable def diagram (T : FiniteExactTower C) : ComposableArrows C T.length :=
  ComposableArrows.mkOfObjOfMapSucc T.object T.inclusion

@[simp]
theorem diagram_obj (T : FiniteExactTower C) (i : Fin (T.length + 1)) :
    T.diagram.obj i = T.object i :=
  rfl

theorem diagram_map_succ (T : FiniteExactTower C) (i : Fin T.length) :
    T.diagram.map (homOfLE i.castSucc_le_succ) = T.inclusion i := by
  change (ComposableArrows.mkOfObjOfMapSucc T.object T.inclusion).map'
    i.val (i.val + 1) = T.inclusion ⟨i.val, i.isLt⟩
  exact ComposableArrows.mkOfObjOfMapSucc_map_succ
    T.object T.inclusion i.val i.isLt

/-- The canonical composite from any stage to the top of the tower. -/
noncomputable def toTop (T : FiniteExactTower C) (i : Fin (T.length + 1)) :
    T.object i ⟶ T.object (Fin.last T.length) :=
  T.diagram.map (homOfLE (Fin.le_last i))

@[simp]
theorem toTop_last (T : FiniteExactTower C) :
    T.toTop (Fin.last T.length) = 𝟙 _ := by
  apply T.diagram.map_id

theorem inclusion_toTop (T : FiniteExactTower C) (i : Fin T.length) :
    T.inclusion i ≫ T.toTop i.succ = T.toTop i.castSucc := by
  rw [← T.diagram_map_succ i]
  exact (T.diagram.map_comp
    (homOfLE i.castSucc_le_succ) (homOfLE (Fin.le_last i.succ))).symm

/-- Apply an exact functor to an endpoint-free exact tower. -/
def map (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G] : FiniteExactTower D where
  length := T.length
  object i := G.obj (T.object i)
  inclusion i := G.map (T.inclusion i)
  graded i := G.obj (T.graded i)
  projection i := G.map (T.projection i)
  zero i := by
    rw [← G.map_comp, T.zero i, G.map_zero]
  shortExact i := by
    change ((T.step i).map G).ShortExact
    exact (T.step_shortExact i).map_of_exact G

@[simp]
theorem map_length (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G] :
    (T.map G).length = T.length :=
  rfl

@[simp]
theorem map_object (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    (i : Fin ((T.map G).length + 1)) :
    (T.map G).object i = G.obj (T.object i) :=
  rfl

@[simp]
theorem map_graded (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    (i : Fin (T.map G).length) :
    (T.map G).graded i = G.obj (T.graded i) :=
  rfl

@[simp]
theorem map_id (T : FiniteExactTower C) : T.map (𝟭 C) = T := by
  cases T
  rfl

attribute [local instance] comp_preservesFiniteLimits comp_preservesFiniteColimits

@[simp]
theorem map_comp (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    {E : Type*} [Category E] [HasZeroMorphisms E] (H : D ⥤ E)
    [H.PreservesZeroMorphisms] [PreservesFiniteLimits H] [PreservesFiniteColimits H] :
    T.map (G ⋙ H) = (T.map G).map H := by
  cases T
  rfl

end FiniteExactTower

namespace FiniteFiltration

variable {C : Type u} [Category.{v} C] [HasZeroMorphisms C] {M : C}
variable {D : Type u₂} [Category.{v₂} D] [HasZeroMorphisms D]

/-- The short complex presenting the `i`th successive quotient. -/
def step (F : FiniteFiltration C M) (i : Fin F.length) : ShortComplex C :=
  F.toFiniteExactTower.step i

theorem step_shortExact (F : FiniteFiltration C M) (i : Fin F.length) :
    (F.step i).ShortExact :=
  F.toFiniteExactTower.step_shortExact i

instance inclusion_mono (F : FiniteFiltration C M) (i : Fin F.length) :
    Mono (F.inclusion i) :=
  (F.step_shortExact i).mono_f

instance projection_epi (F : FiniteFiltration C M) (i : Fin F.length) :
    Epi (F.projection i) :=
  (F.step_shortExact i).epi_g

/-- The composable-arrow diagram underlying a finite filtration. -/
noncomputable def diagram (F : FiniteFiltration C M) : ComposableArrows C F.length :=
  F.toFiniteExactTower.diagram

/-- The canonical map from a filtration stage to the filtered object. -/
noncomputable def toObject (F : FiniteFiltration C M) (i : Fin (F.length + 1)) :
    F.object i ⟶ M :=
  F.toFiniteExactTower.toTop i ≫ F.terminalIso.hom

theorem inclusion_toObject (F : FiniteFiltration C M) (i : Fin F.length) :
    F.inclusion i ≫ F.toObject i.succ = F.toObject i.castSucc := by
  rw [toObject, toObject, ← Category.assoc,
    F.toFiniteExactTower.inclusion_toTop]

@[simp]
theorem toObject_zero (F : FiniteFiltration C M) : F.toObject 0 = 0 :=
  F.initialIsZero.eq_of_src _ _

/-- Apply an exact functor to every term and every successive quotient of a finite filtration.

This is the common categorical operation used when a geometric filtration is pulled back by a
flat morphism: the geometric leaf only has to identify its pullback functor and the images of the
graded pieces.  Exactness stays here, rather than being rebuilt in each almost-disconnected or
stability-condition consumer. -/
def map (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G] :
    FiniteFiltration D (G.obj M) where
  toFiniteExactTower := F.toFiniteExactTower.map G
  initialIsZero := G.map_isZero F.initialIsZero
  terminalIso := G.mapIso F.terminalIso

@[simp]
theorem map_length (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G] :
    (F.map G).length = F.length :=
  rfl

@[simp]
theorem map_object (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    (i : Fin ((F.map G).length + 1)) :
    (F.map G).object i = G.obj (F.object i) :=
  rfl

@[simp]
theorem map_graded (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    (i : Fin (F.map G).length) :
    (F.map G).graded i = G.obj (F.graded i) :=
  rfl

@[simp]
theorem map_id (F : FiniteFiltration C M) : F.map (𝟭 C) = F := by
  cases F
  rfl

attribute [local instance] comp_preservesFiniteLimits comp_preservesFiniteColimits

@[simp]
theorem map_comp (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    {E : Type*} [Category E] [HasZeroMorphisms E] (H : D ⥤ E)
    [H.PreservesZeroMorphisms] [PreservesFiniteLimits H] [PreservesFiniteColimits H] :
    F.map (G ⋙ H) = (F.map G).map H := by
  cases F
  rfl

end FiniteFiltration

namespace FiniteFiltration

variable {C : Type u} [Category.{v} C] [Abelian C]

section PullbackTower

variable {X Q : C} (p : X ⟶ Q) [Epi p]
variable (F : FiniteFiltration C Q)

/-- The stage obtained by pulling a filtration stage back along an epimorphism. -/
noncomputable abbrev pullbackObject (i : Fin (F.length + 1)) : C :=
  pullback p (F.toObject i)

/-- The inclusion between two consecutive pulled-back stages. -/
noncomputable def pullbackInclusion (i : Fin F.length) :
    F.pullbackObject p i.castSucc ⟶ F.pullbackObject p i.succ :=
  pullback.lift (pullback.fst p (F.toObject i.castSucc))
    (pullback.snd p (F.toObject i.castSucc) ≫ F.inclusion i) (by
      simpa only [Category.assoc, F.inclusion_toObject] using
        (pullback.condition (f := p) (g := F.toObject i.castSucc)))

omit [Epi p] in
@[reassoc (attr := simp)]
theorem pullbackInclusion_fst (i : Fin F.length) :
    F.pullbackInclusion p i ≫ pullback.fst p (F.toObject i.succ) =
      pullback.fst p (F.toObject i.castSucc) :=
  pullback.lift_fst _ _ _

omit [Epi p] in
@[reassoc (attr := simp)]
theorem pullbackInclusion_snd (i : Fin F.length) :
    F.pullbackInclusion p i ≫ pullback.snd p (F.toObject i.succ) =
      pullback.snd p (F.toObject i.castSucc) ≫ F.inclusion i :=
  pullback.lift_snd _ _ _

noncomputable instance pullbackInclusion_mono (i : Fin F.length) :
    Mono (F.pullbackInclusion p i) := by
  letI : Mono (F.inclusion i) := (F.step_shortExact i).mono_f
  constructor
  intro Z f g h
  apply pullback.hom_ext
  · simpa only [Category.assoc, F.pullbackInclusion_fst p i] using
      h =≫ pullback.fst p (F.toObject i.succ)
  · rw [← cancel_mono (F.inclusion i)]
    simpa only [Category.assoc, F.pullbackInclusion_snd p i] using
      h =≫ pullback.snd p (F.toObject i.succ)

/-- The quotient projection from a pulled-back stage. -/
noncomputable def pullbackProjection (i : Fin F.length) :
    F.pullbackObject p i.succ ⟶ F.graded i :=
  pullback.snd p (F.toObject i.succ) ≫ F.projection i

noncomputable instance pullbackProjection_epi (i : Fin F.length) :
    Epi (F.pullbackProjection p i) := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  dsimp only [pullbackProjection]
  infer_instance

omit [Epi p] in
theorem pullback_zero (i : Fin F.length) :
    F.pullbackInclusion p i ≫ F.pullbackProjection p i = 0 := by
  rw [pullbackProjection, ← Category.assoc, F.pullbackInclusion_snd p i,
    Category.assoc, F.zero i, comp_zero]

omit [Epi p] in
theorem pullback_exact (i : Fin F.length) :
    (ShortComplex.mk (F.pullbackInclusion p i) (F.pullbackProjection p i)
      (F.pullback_zero p i)).Exact := by
  rw [ShortComplex.exact_iff_exact_up_to_refinements]
  intro A x hx
  have hx' : (x ≫ pullback.snd p (F.toObject i.succ)) ≫ F.projection i = 0 := by
    simpa only [pullbackProjection, Category.assoc] using hx
  obtain ⟨A', π, hπ, y, hy⟩ :=
    (F.step_shortExact i).exact.exact_up_to_refinements
      (x ≫ pullback.snd p (F.toObject i.succ)) hx'
  dsimp only [step, FiniteExactTower.step] at y hy
  change π ≫ x ≫ pullback.snd p (F.toObject i.succ) =
    y ≫ F.inclusion i at hy
  have hcompat :
      (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) ≫ p =
        y ≫ F.toObject i.castSucc := by
    calc
      (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) ≫ p =
          π ≫ x ≫ (pullback.fst p (F.toObject i.succ) ≫ p) := by simp
      _ = π ≫ x ≫
          (pullback.snd p (F.toObject i.succ) ≫ F.toObject i.succ) := by
            rw [pullback.condition]
      _ = (π ≫ x ≫ pullback.snd p (F.toObject i.succ)) ≫
          F.toObject i.succ := by simp
      _ = (y ≫ F.inclusion i) ≫ F.toObject i.succ := by rw [hy]
      _ = y ≫ F.toObject i.castSucc := by
        simpa only [Category.assoc] using y ≫= F.inclusion_toObject i
  let l : A' ⟶ F.pullbackObject p i.castSucc :=
    pullback.lift (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) y hcompat
  refine ⟨A', π, hπ, l, ?_⟩
  apply pullback.hom_ext
  · calc
      (π ≫ x) ≫ pullback.fst p (F.toObject i.succ) =
          π ≫ x ≫ pullback.fst p (F.toObject i.succ) := Category.assoc ..
      _ = l ≫ pullback.fst p (F.toObject i.castSucc) :=
        (pullback.lift_fst
          (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) y hcompat).symm
      _ = (l ≫ F.pullbackInclusion p i) ≫
          pullback.fst p (F.toObject i.succ) := by
            rw [Category.assoc, F.pullbackInclusion_fst p i]
  · calc
      (π ≫ x) ≫ pullback.snd p (F.toObject i.succ) =
          π ≫ x ≫ pullback.snd p (F.toObject i.succ) := Category.assoc ..
      _ = y ≫ F.inclusion i := hy
      _ = (l ≫ F.pullbackInclusion p i) ≫
          pullback.snd p (F.toObject i.succ) := by
            rw [Category.assoc, F.pullbackInclusion_snd p i]
            simpa only [Category.assoc, l] using ((pullback.lift_snd
              (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) y hcompat) =≫
                F.inclusion i).symm

/-- Pull a quotient filtration back along an epimorphism.

The result is an endpoint-free exact tower: its bottom is the kernel of `p`, while its top is
canonically isomorphic to `X`.  This is the actual refinement operation used when a coarse short
exact step is replaced by a filtration of its quotient. -/
noncomputable def pullbackTower : FiniteExactTower C where
  length := F.length
  object := F.pullbackObject p
  inclusion := F.pullbackInclusion p
  graded := F.graded
  projection := F.pullbackProjection p
  zero := F.pullback_zero p
  shortExact i := ShortComplex.ShortExact.mk' (F.pullback_exact p i)
    inferInstance inferInstance

@[simp]
theorem pullbackTower_length : (F.pullbackTower p).length = F.length :=
  rfl

@[simp]
theorem pullbackTower_object (i : Fin ((F.pullbackTower p).length + 1)) :
    (F.pullbackTower p).object i = pullback p (F.toObject i) :=
  rfl

@[simp]
theorem pullbackTower_graded (i : Fin (F.pullbackTower p).length) :
    (F.pullbackTower p).graded i = F.graded i :=
  rfl

/-- The bottom inclusion of the pullback tower, regarded as a kernel fork for `p`. -/
noncomputable def pullbackTowerInitialKernelFork : KernelFork p :=
  KernelFork.ofι (pullback.fst p (F.toObject 0)) (by
    rw [pullback.condition, F.toObject_zero, comp_zero])

/-- The bottom of the pullback tower is a kernel of `p`. -/
noncomputable def pullbackTowerInitialIsLimit :
    IsLimit (F.pullbackTowerInitialKernelFork p) :=
  KernelFork.IsLimit.ofι (pullback.fst p (F.toObject 0)) (by
    rw [pullback.condition, F.toObject_zero, comp_zero])
    (fun g hg ↦ pullback.lift g 0 (by rw [hg, zero_comp]))
    (fun _ _ ↦ pullback.lift_fst _ _ _)
    (fun g hg m hm ↦ by
      apply pullback.hom_ext
      · exact hm.trans (pullback.lift_fst g 0 (by rw [hg, zero_comp])).symm
      · exact F.initialIsZero.eq_of_tgt _ _)

/-- The top of the pullback tower is canonically the source of the epimorphism. -/
noncomputable def pullbackTowerTerminalIso :
    (F.pullbackTower p).object (Fin.last (F.pullbackTower p).length) ≅ X := by
  change pullback p (F.toObject (Fin.last F.length)) ≅ X
  letI : IsIso (F.toFiniteExactTower.toTop (Fin.last F.length)) := by
    rw [F.toFiniteExactTower.toTop_last]
    infer_instance
  letI : IsIso (F.toObject (Fin.last F.length)) := by
    dsimp only [toObject]
    infer_instance
  exact asIso (pullback.fst p (F.toObject (Fin.last F.length)))

@[simp]
theorem pullbackTowerTerminalIso_hom :
    (F.pullbackTowerTerminalIso p).hom =
      pullback.fst p (F.toObject (Fin.last F.length)) :=
  rfl

end PullbackTower

section StepRefinement

variable {M : C} (F : FiniteFiltration C M) (i : Fin F.length)
variable (R : FiniteFiltration C (F.graded i))

/-- The bottom of the lifted refinement is canonically the preceding coarse stage. -/
noncomputable def refinementInitialIso :
    (R.pullbackTower (F.projection i)).object 0 ≅ F.object i.castSucc := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  exact IsLimit.conePointUniqueUpToIso
    (R.pullbackTowerInitialIsLimit (F.projection i))
    (F.step_shortExact i).fIsKernel

/-- The top of the lifted refinement is canonically the following coarse stage. -/
noncomputable def refinementTerminalIso :
    (R.pullbackTower (F.projection i)).object
      (Fin.last (R.pullbackTower (F.projection i)).length) ≅ F.object i.succ := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  exact R.pullbackTowerTerminalIso (F.projection i)

/-- The initial comparison intertwines the lifted kernel inclusion and the coarse inclusion. -/
theorem refinementInitialIso_hom_inclusion :
    (refinementInitialIso F i R).hom ≫ F.inclusion i =
      pullback.fst (F.projection i) (R.toObject 0) := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  exact IsLimit.conePointUniqueUpToIso_hom_comp
    (R.pullbackTowerInitialIsLimit (F.projection i))
    (F.step_shortExact i).fIsKernel Limits.WalkingParallelPair.zero

end StepRefinement

end FiniteFiltration

end CategoryTheory
