/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import Mathlib.Algebra.Homology.ShortComplex.ShortExact
import Mathlib.CategoryTheory.Abelian.CommSq
import Mathlib.CategoryTheory.ComposableArrows.Basic
import Mathlib.CategoryTheory.Limits.Shapes.Pullback.Iso
import Mathlib.Data.Fin.Tuple.Basic
import Mathlib.Data.List.OfFn

/-!
# Finite filtrations in an abelian category

This file records the common categorical root of finite filtrations.  `FiniteExactTower` owns
the successive short exact sequences; a `FiniteFiltration M` extends that parent with a proof
that its bottom is zero and a chosen identification of its top with `M`.

When a graded piece is itself filtered, `FiniteFiltration.pullbackTower` pulls its stages back
along the coarse quotient projection.  The endpoint comparison isomorphisms identify the new
tower with the adjacent coarse stages, providing the categorical splice data used by
almost-disconnected composition. `FiniteExactTower.replaceSteps` assembles a family of such
replacement towers, and `FiniteFiltration.refineAll` supplies the abelian quotient-pullback
specialization.

Keeping this root independent of schemes prevents geometric filtrations (for example, the
almost-disconnected filtrations of arXiv:2607.28411, Appendix B) from growing their own
incompatible tower type.
-/

open CategoryTheory Limits

universe v v₂ u u₂

namespace CategoryTheory

variable (C : Type u) [Category.{v} C] [HasZeroMorphisms C]

/-- A finite tower of successive short exact extensions.

This is the endpoint-free categorical parent of `FiniteFiltration`.  It is useful when a
filtration of a quotient is pulled back to a tower beginning at the kernel: that intermediate
tower does not itself begin at zero, so it must not be encoded as a second filtration type or by
putting a false endpoint condition into a structure field. -/
structure FiniteExactTower where
  /-- The number of graded pieces. -/
  length : ℕ
  /-- The objects `T₀, ..., Tₙ` in the tower. -/
  object : Fin (length + 1) → C
  /-- The inclusion `Tᵢ ⟶ Tᵢ₊₁`. -/
  inclusion : ∀ i : Fin length, object i.castSucc ⟶ object i.succ
  /-- The `i`th graded piece `Tᵢ₊₁/Tᵢ`. -/
  graded : Fin length → C
  /-- The quotient projection `Tᵢ₊₁ ⟶ Tᵢ₊₁/Tᵢ`. -/
  projection : ∀ i : Fin length, object i.succ ⟶ graded i
  /-- Consecutive maps compose to zero. -/
  zero : ∀ i, inclusion i ≫ projection i = 0
  /-- Each step realizes its named graded piece as the quotient. -/
  shortExact : ∀ i,
    (ShortComplex.mk (inclusion i) (projection i) (zero i)).ShortExact

/-- A finite filtration of an object by successive short exact sequences.

`object i.castSucc ⟶ object i.succ ⟶ graded i` is the `i`th short exact sequence.  The
endpoint data express `F₀ = 0` and `Fₙ = M` without making either equality definitional. -/
structure FiniteFiltration (M : C) extends FiniteExactTower C where
  /-- The bottom term is zero. -/
  initialIsZero : IsZero (object 0)
  /-- The top term is the filtered object. -/
  terminalIso : object (Fin.last length) ≅ M

namespace FiniteExactTower

variable {C : Type u} [Category.{v} C] [HasZeroMorphisms C]
variable {D : Type u₂} [Category.{v₂} D] [HasZeroMorphisms D]

/-- The short complex presenting the `i`th successive quotient. -/
def step (T : FiniteExactTower C) (i : Fin T.length) : ShortComplex C :=
  ShortComplex.mk (T.inclusion i) (T.projection i) (T.zero i)

theorem step_shortExact (T : FiniteExactTower C) (i : Fin T.length) :
    (T.step i).ShortExact :=
  T.shortExact i

/-- The composable-arrow diagram canonically generated by the successive inclusions. -/
noncomputable def diagram (T : FiniteExactTower C) : ComposableArrows C T.length :=
  ComposableArrows.mkOfObjOfMapSucc T.object T.inclusion

@[simp]
theorem diagram_obj (T : FiniteExactTower C) (i : Fin (T.length + 1)) :
    T.diagram.obj i = T.object i :=
  rfl

theorem diagram_map_succ (T : FiniteExactTower C) (i : Fin T.length) :
    T.diagram.map (homOfLE i.castSucc_le_succ) = T.inclusion i := by
  change (ComposableArrows.mkOfObjOfMapSucc T.object T.inclusion).map'
    i.val (i.val + 1) = T.inclusion ⟨i.val, i.isLt⟩
  exact ComposableArrows.mkOfObjOfMapSucc_map_succ
    T.object T.inclusion i.val i.isLt

/-- The canonical composite from any stage to the top of the tower. -/
noncomputable def toTop (T : FiniteExactTower C) (i : Fin (T.length + 1)) :
    T.object i ⟶ T.object (Fin.last T.length) :=
  T.diagram.map (homOfLE (Fin.le_last i))

@[simp]
theorem toTop_last (T : FiniteExactTower C) :
    T.toTop (Fin.last T.length) = 𝟙 _ := by
  apply T.diagram.map_id

theorem inclusion_toTop (T : FiniteExactTower C) (i : Fin T.length) :
    T.inclusion i ≫ T.toTop i.succ = T.toTop i.castSucc := by
  rw [← T.diagram_map_succ i]
  exact (T.diagram.map_comp
    (homOfLE i.castSucc_le_succ) (homOfLE (Fin.le_last i.succ))).symm

/-- The ordered list of successive quotients in an exact tower. -/
def gradedObjects (T : FiniteExactTower C) : List C :=
  List.ofFn T.graded

/-- The initial segment ending at a chosen stage of an exact tower. -/
def take (T : FiniteExactTower C) (k : Fin (T.length + 1)) : FiniteExactTower C where
  length := k.val
  object j := T.object ⟨j.val, by omega⟩
  inclusion j := T.inclusion ⟨j.val, by omega⟩
  graded j := T.graded ⟨j.val, by omega⟩
  projection j := T.projection ⟨j.val, by omega⟩
  zero j := T.zero ⟨j.val, by omega⟩
  shortExact j := T.shortExact ⟨j.val, by omega⟩

@[simp]
theorem take_length (T : FiniteExactTower C) (k : Fin (T.length + 1)) :
    (T.take k).length = k.val :=
  rfl

@[simp]
theorem take_gradedObjects (T : FiniteExactTower C) (k : Fin (T.length + 1)) :
    (T.take k).gradedObjects = T.gradedObjects.take k.val := by
  apply List.ext_get
  · simp [gradedObjects, take]
    omega
  · intro n h₁ h₂
    simp [gradedObjects, take]

/-- The start of an initial segment agrees with the start of the original tower. -/
noncomputable def takeInitialIso (T : FiniteExactTower C) (k : Fin (T.length + 1)) :
    (T.take k).object 0 ≅ T.object 0 :=
  eqToIso (congrArg T.object (by apply Fin.ext; rfl))

/-- The end of an initial segment is its selected original stage. -/
noncomputable def takeTerminalIso (T : FiniteExactTower C) (k : Fin (T.length + 1)) :
    (T.take k).object (Fin.last (T.take k).length) ≅ T.object k :=
  eqToIso (congrArg T.object (by apply Fin.ext; rfl))

/-- The terminal segment beginning at a chosen stage of an exact tower. -/
def drop (T : FiniteExactTower C) (k : Fin (T.length + 1)) : FiniteExactTower C where
  length := T.length - k.val
  object j := T.object ⟨k.val + j.val, by omega⟩
  inclusion j := T.inclusion ⟨k.val + j.val, by omega⟩
  graded j := T.graded ⟨k.val + j.val, by omega⟩
  projection j := T.projection ⟨k.val + j.val, by omega⟩
  zero j := T.zero ⟨k.val + j.val, by omega⟩
  shortExact j := T.shortExact ⟨k.val + j.val, by omega⟩

@[simp]
theorem drop_length (T : FiniteExactTower C) (k : Fin (T.length + 1)) :
    (T.drop k).length = T.length - k.val :=
  rfl

@[simp]
theorem drop_gradedObjects (T : FiniteExactTower C) (k : Fin (T.length + 1)) :
    (T.drop k).gradedObjects = T.gradedObjects.drop k.val := by
  apply List.ext_get
  · simp [gradedObjects, drop]
  · intro n h₁ h₂
    simp [gradedObjects, drop]

/-- The start of a terminal segment is its selected original stage. -/
noncomputable def dropInitialIso (T : FiniteExactTower C) (k : Fin (T.length + 1)) :
    (T.drop k).object 0 ≅ T.object k :=
  eqToIso (congrArg T.object (by apply Fin.ext; rfl))

/-- The end of a terminal segment agrees with the end of the original tower. -/
noncomputable def dropTerminalIso (T : FiniteExactTower C) (k : Fin (T.length + 1)) :
    (T.drop k).object (Fin.last (T.drop k).length) ≅
      T.object (Fin.last T.length) :=
  eqToIso (congrArg T.object (by
    apply Fin.ext
    change k.val + (T.length - k.val) = T.length
    omega))

/-- Prepend one short exact step to an exact tower.

This is the primitive from which endpoint-compatible towers are concatenated. Adding at the
left edge keeps the `Fin` embeddings definitional, avoiding transports between the two distinct
right-edge embeddings `i.castSucc.succ` and `i.succ.castSucc`. -/
def prepend (T : FiniteExactTower C) {X G : C}
    (f : X ⟶ T.object 0) (g : T.object 0 ⟶ G) (zero : f ≫ g = 0)
    (shortExact : (ShortComplex.mk f g zero).ShortExact) : FiniteExactTower C where
  length := T.length + 1
  object := Fin.cons X T.object
  inclusion := Fin.cons f T.inclusion
  graded := Fin.cons G T.graded
  projection := Fin.cons g T.projection
  zero := Fin.cons zero T.zero
  shortExact := Fin.cons shortExact T.shortExact

@[simp]
theorem prepend_length (T : FiniteExactTower C) {X G : C}
    (f : X ⟶ T.object 0) (g : T.object 0 ⟶ G) (zero : f ≫ g = 0)
    (shortExact : (ShortComplex.mk f g zero).ShortExact) :
    (T.prepend f g zero shortExact).length = T.length + 1 :=
  rfl

private structure AppendData (T U : FiniteExactTower C) where
  tower : FiniteExactTower C
  length_eq : tower.length = T.length + U.length
  graded_eq : List.ofFn tower.graded = List.ofFn T.graded ++ List.ofFn U.graded
  initialIso : T.object 0 ≅ tower.object 0
  terminalIso : tower.object (Fin.last tower.length) ≅ U.object (Fin.last U.length)

/-- Recursive implementation of concatenation.

The implementation consumes the left tower one step at a time. Its private result packages the
two endpoint comparisons so that the public operation is total even when either tower has length
zero. -/
private noncomputable def appendData :
    (T U : FiniteExactTower C) →
      (T.object (Fin.last T.length) ≅ U.object 0) → AppendData T U
  | {
      length := 0, object := object, inclusion := inclusion, graded := graded,
      projection := projection, zero := zero, shortExact := shortExact }, U, seam => {
        tower := U
        length_eq := by simp
        graded_eq := by simp
        initialIso := seam
        terminalIso := Iso.refl _ }
  | {
      length := n + 1, object := object, inclusion := inclusion, graded := graded,
      projection := projection, zero := zero, shortExact := shortExact }, U, seam => by
      let tail : FiniteExactTower C := {
        length := n
        object := Fin.tail object
        inclusion := Fin.tail inclusion
        graded := Fin.tail graded
        projection := Fin.tail projection
        zero := Fin.tail zero
        shortExact := Fin.tail shortExact }
      let tailSeam : tail.object (Fin.last tail.length) ≅ U.object 0 := by
        dsimp only [tail, Fin.tail]
        refine (eqToIso ?_).trans seam
        congr 1
      let D := appendData tail U tailSeam
      let e : object 1 ≅ D.tower.object 0 := D.initialIso
      let f : object 0 ⟶ D.tower.object 0 := inclusion 0 ≫ e.hom
      let g : D.tower.object 0 ⟶ graded 0 := e.inv ≫ projection 0
      let z : f ≫ g = 0 := by
        dsimp only [f, g]
        simp [Category.assoc]
        exact zero 0
      let stepIso :
          ShortComplex.mk (inclusion 0) (projection 0) (zero 0) ≅
            ShortComplex.mk f g z :=
        ShortComplex.isoMk (Iso.refl _) e (Iso.refl _)
          (by simp [f]) (by simp [g])
      let h : (ShortComplex.mk f g z).ShortExact :=
        ShortComplex.shortExact_of_iso stepIso (shortExact 0)
      let V := D.tower.prepend f g z h
      exact {
        tower := V
        length_eq := by
          dsimp only [V, prepend]
          rw [D.length_eq]
          dsimp only [tail]
          omega
        graded_eq := by
          dsimp only [V, prepend]
          rw [List.ofFn_cons, D.graded_eq]
          dsimp only [tail]
          rw [← Fin.cons_self_tail graded, List.ofFn_cons, List.cons_append]
          simp
        initialIso := Iso.refl _
        terminalIso := by simpa [V, prepend] using D.terminalIso }
termination_by T => T.length

/-- Concatenate two exact towers along an isomorphism from the left endpoint to the right start.

The result contains the graded pieces of `T`, followed by those of `U`. The seam is an
isomorphism rather than an equality because pulled-back quotient filtrations meet their adjacent
coarse stages canonically only up to isomorphism. -/
noncomputable def append (T U : FiniteExactTower C)
    (seam : T.object (Fin.last T.length) ≅ U.object 0) : FiniteExactTower C :=
  (appendData T U seam).tower

@[simp]
theorem append_length (T U : FiniteExactTower C)
    (seam : T.object (Fin.last T.length) ≅ U.object 0) :
    (T.append U seam).length = T.length + U.length :=
  (appendData T U seam).length_eq

@[simp]
theorem append_gradedObjects (T U : FiniteExactTower C)
    (seam : T.object (Fin.last T.length) ≅ U.object 0) :
    (T.append U seam).gradedObjects = T.gradedObjects ++ U.gradedObjects :=
  (appendData T U seam).graded_eq

/-- The start of a concatenation is canonically the start of its left tower. -/
noncomputable def appendInitialIso (T U : FiniteExactTower C)
    (seam : T.object (Fin.last T.length) ≅ U.object 0) :
    T.object 0 ≅ (T.append U seam).object 0 :=
  (appendData T U seam).initialIso

/-- The end of a concatenation is canonically the end of its right tower. -/
noncomputable def appendTerminalIso (T U : FiniteExactTower C)
    (seam : T.object (Fin.last T.length) ≅ U.object 0) :
    (T.append U seam).object (Fin.last (T.append U seam).length) ≅
      U.object (Fin.last U.length) :=
  (appendData T U seam).terminalIso

private structure ReplaceStepsData (T : FiniteExactTower C)
    (R : ∀ _ : Fin T.length, FiniteExactTower C) where
  tower : FiniteExactTower C
  length_eq : tower.length = (List.ofFn fun i => (R i).length).sum
  graded_eq : tower.gradedObjects =
    (List.ofFn fun i => (R i).gradedObjects).flatten
  initialIso : T.object 0 ≅ tower.object 0
  terminalIso : tower.object (Fin.last tower.length) ≅
    T.object (Fin.last T.length)

/-- Recursive implementation of simultaneous step replacement.

The recursion removes the first coarse step, recursively replaces the tail, and joins the first
replacement tower to that result. Keeping the endpoint comparisons in the private result makes
the public operation uniform for empty coarse towers and zero-length replacement towers. -/
private noncomputable def replaceStepsData :
    (T : FiniteExactTower C) →
      (R : ∀ _ : Fin T.length, FiniteExactTower C) →
      (∀ i, (R i).object 0 ≅ T.object i.castSucc) →
      (∀ i, (R i).object (Fin.last (R i).length) ≅ T.object i.succ) →
      ReplaceStepsData T R
  | {
      length := 0, object := object, inclusion := inclusion, graded := graded,
      projection := projection, zero := zero, shortExact := shortExact }, R, start, finish => {
        tower := {
          length := 0, object := object, inclusion := inclusion, graded := graded,
          projection := projection, zero := zero, shortExact := shortExact }
        length_eq := by simp
        graded_eq := by simp [gradedObjects]
        initialIso := Iso.refl _
        terminalIso := Iso.refl _ }
  | {
      length := n + 1, object := object, inclusion := inclusion, graded := graded,
      projection := projection, zero := zero, shortExact := shortExact }, R, start, finish => by
      let tail : FiniteExactTower C := {
        length := n
        object := Fin.tail object
        inclusion := Fin.tail inclusion
        graded := Fin.tail graded
        projection := Fin.tail projection
        zero := Fin.tail zero
        shortExact := Fin.tail shortExact }
      let tailR : ∀ j : Fin tail.length, FiniteExactTower C :=
        fun j => R j.succ
      let tailStart : ∀ j, (tailR j).object 0 ≅ tail.object j.castSucc := fun j =>
        (start j.succ).trans (eqToIso (congrArg object (by apply Fin.ext; rfl)))
      let tailFinish : ∀ j,
          (tailR j).object (Fin.last (tailR j).length) ≅ tail.object j.succ := fun j =>
        (finish j.succ).trans (eqToIso (congrArg object (by apply Fin.ext; rfl)))
      let D := replaceStepsData tail tailR tailStart tailFinish
      let first := R 0
      let seam : first.object (Fin.last first.length) ≅ D.tower.object 0 :=
        (finish 0).trans
          ((eqToIso (congrArg object (by apply Fin.ext; rfl))).trans D.initialIso)
      let result := first.append D.tower seam
      exact {
        tower := result
        length_eq := by
          dsimp only [result]
          rw [append_length, D.length_eq]
          rw [← Fin.cons_self_tail (fun i => (R i).length), List.ofFn_cons]
          simp only [List.sum_cons]
          rfl
        graded_eq := by
          dsimp only [result]
          rw [append_gradedObjects, D.graded_eq]
          rw [← Fin.cons_self_tail (fun i => (R i).gradedObjects), List.ofFn_cons]
          simp only [List.flatten_cons]
          rfl
        initialIso := (start 0).symm.trans (first.appendInitialIso D.tower seam)
        terminalIso := (first.appendTerminalIso D.tower seam).trans D.terminalIso }
termination_by T => T.length

/-- Simultaneously replace every step of an exact tower by an endpoint-compatible exact tower.

This is the many-step parent of `FiniteFiltration.refineStep`. It is deliberately owned by
`FiniteExactTower`: geometric consumers provide replacement towers, while their concatenation,
ordering, and endpoint bookkeeping remain common categorical infrastructure. -/
noncomputable def replaceSteps (T : FiniteExactTower C)
    (R : ∀ _ : Fin T.length, FiniteExactTower C)
    (start : ∀ i, (R i).object 0 ≅ T.object i.castSucc)
    (finish : ∀ i,
      (R i).object (Fin.last (R i).length) ≅ T.object i.succ) :
    FiniteExactTower C :=
  (replaceStepsData T R start finish).tower

@[simp]
theorem replaceSteps_length (T : FiniteExactTower C)
    (R : ∀ _ : Fin T.length, FiniteExactTower C)
    (start : ∀ i, (R i).object 0 ≅ T.object i.castSucc)
    (finish : ∀ i,
      (R i).object (Fin.last (R i).length) ≅ T.object i.succ) :
    (T.replaceSteps R start finish).length =
      (List.ofFn fun i => (R i).length).sum :=
  (replaceStepsData T R start finish).length_eq

@[simp]
theorem replaceSteps_gradedObjects (T : FiniteExactTower C)
    (R : ∀ _ : Fin T.length, FiniteExactTower C)
    (start : ∀ i, (R i).object 0 ≅ T.object i.castSucc)
    (finish : ∀ i,
      (R i).object (Fin.last (R i).length) ≅ T.object i.succ) :
    (T.replaceSteps R start finish).gradedObjects =
      (List.ofFn fun i => (R i).gradedObjects).flatten :=
  (replaceStepsData T R start finish).graded_eq

/-- The simultaneous replacement starts at the original tower's initial object. -/
noncomputable def replaceStepsInitialIso (T : FiniteExactTower C)
    (R : ∀ _ : Fin T.length, FiniteExactTower C)
    (start : ∀ i, (R i).object 0 ≅ T.object i.castSucc)
    (finish : ∀ i,
      (R i).object (Fin.last (R i).length) ≅ T.object i.succ) :
    T.object 0 ≅ (T.replaceSteps R start finish).object 0 :=
  (replaceStepsData T R start finish).initialIso

/-- The simultaneous replacement ends at the original tower's terminal object. -/
noncomputable def replaceStepsTerminalIso (T : FiniteExactTower C)
    (R : ∀ _ : Fin T.length, FiniteExactTower C)
    (start : ∀ i, (R i).object 0 ≅ T.object i.castSucc)
    (finish : ∀ i,
      (R i).object (Fin.last (R i).length) ≅ T.object i.succ) :
    (T.replaceSteps R start finish).object
        (Fin.last (T.replaceSteps R start finish).length) ≅
      T.object (Fin.last T.length) :=
  (replaceStepsData T R start finish).terminalIso

/-- Apply an exact functor to an endpoint-free exact tower. -/
def map (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G] : FiniteExactTower D where
  length := T.length
  object i := G.obj (T.object i)
  inclusion i := G.map (T.inclusion i)
  graded i := G.obj (T.graded i)
  projection i := G.map (T.projection i)
  zero i := by
    rw [← G.map_comp, T.zero i, G.map_zero]
  shortExact i := by
    change ((T.step i).map G).ShortExact
    exact (T.step_shortExact i).map_of_exact G

@[simp]
theorem map_length (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G] :
    (T.map G).length = T.length :=
  rfl

@[simp]
theorem map_object (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    (i : Fin ((T.map G).length + 1)) :
    (T.map G).object i = G.obj (T.object i) :=
  rfl

@[simp]
theorem map_graded (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    (i : Fin (T.map G).length) :
    (T.map G).graded i = G.obj (T.graded i) :=
  rfl

@[simp]
theorem map_id (T : FiniteExactTower C) : T.map (𝟭 C) = T := by
  cases T
  rfl

attribute [local instance] comp_preservesFiniteLimits comp_preservesFiniteColimits

@[simp]
theorem map_comp (T : FiniteExactTower C) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    {E : Type*} [Category E] [HasZeroMorphisms E] (H : D ⥤ E)
    [H.PreservesZeroMorphisms] [PreservesFiniteLimits H] [PreservesFiniteColimits H] :
    T.map (G ⋙ H) = (T.map G).map H := by
  cases T
  rfl

end FiniteExactTower

namespace FiniteFiltration

variable {C : Type u} [Category.{v} C] [HasZeroMorphisms C] {M : C}
variable {D : Type u₂} [Category.{v₂} D] [HasZeroMorphisms D]

/-- The short complex presenting the `i`th successive quotient. -/
def step (F : FiniteFiltration C M) (i : Fin F.length) : ShortComplex C :=
  F.toFiniteExactTower.step i

theorem step_shortExact (F : FiniteFiltration C M) (i : Fin F.length) :
    (F.step i).ShortExact :=
  F.toFiniteExactTower.step_shortExact i

instance inclusion_mono (F : FiniteFiltration C M) (i : Fin F.length) :
    Mono (F.inclusion i) :=
  (F.step_shortExact i).mono_f

instance projection_epi (F : FiniteFiltration C M) (i : Fin F.length) :
    Epi (F.projection i) :=
  (F.step_shortExact i).epi_g

/-- The composable-arrow diagram underlying a finite filtration. -/
noncomputable def diagram (F : FiniteFiltration C M) : ComposableArrows C F.length :=
  F.toFiniteExactTower.diagram

/-- The canonical map from a filtration stage to the filtered object. -/
noncomputable def toObject (F : FiniteFiltration C M) (i : Fin (F.length + 1)) :
    F.object i ⟶ M :=
  F.toFiniteExactTower.toTop i ≫ F.terminalIso.hom

theorem inclusion_toObject (F : FiniteFiltration C M) (i : Fin F.length) :
    F.inclusion i ≫ F.toObject i.succ = F.toObject i.castSucc := by
  rw [toObject, toObject, ← Category.assoc,
    F.toFiniteExactTower.inclusion_toTop]

@[simp]
theorem toObject_zero (F : FiniteFiltration C M) : F.toObject 0 = 0 :=
  F.initialIsZero.eq_of_src _ _

/-- Apply an exact functor to every term and every successive quotient of a finite filtration.

This is the common categorical operation used when a geometric filtration is pulled back by a
flat morphism: the geometric leaf only has to identify its pullback functor and the images of the
graded pieces.  Exactness stays here, rather than being rebuilt in each almost-disconnected or
stability-condition consumer. -/
def map (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G] :
    FiniteFiltration D (G.obj M) where
  toFiniteExactTower := F.toFiniteExactTower.map G
  initialIsZero := G.map_isZero F.initialIsZero
  terminalIso := G.mapIso F.terminalIso

@[simp]
theorem map_length (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G] :
    (F.map G).length = F.length :=
  rfl

@[simp]
theorem map_object (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    (i : Fin ((F.map G).length + 1)) :
    (F.map G).object i = G.obj (F.object i) :=
  rfl

@[simp]
theorem map_graded (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    (i : Fin (F.map G).length) :
    (F.map G).graded i = G.obj (F.graded i) :=
  rfl

@[simp]
theorem map_id (F : FiniteFiltration C M) : F.map (𝟭 C) = F := by
  cases F
  rfl

attribute [local instance] comp_preservesFiniteLimits comp_preservesFiniteColimits

@[simp]
theorem map_comp (F : FiniteFiltration C M) (G : C ⥤ D) [G.PreservesZeroMorphisms]
    [PreservesFiniteLimits G] [PreservesFiniteColimits G]
    {E : Type*} [Category E] [HasZeroMorphisms E] (H : D ⥤ E)
    [H.PreservesZeroMorphisms] [PreservesFiniteLimits H] [PreservesFiniteColimits H] :
    F.map (G ⋙ H) = (F.map G).map H := by
  cases F
  rfl

/-- Replace every step of a filtration by an endpoint-compatible exact tower.

The endpoint-free work is delegated to `FiniteExactTower.replaceSteps`; this specialization only
transports the zero bottom and the chosen identification of the top with the filtered object. -/
noncomputable def replaceSteps (F : FiniteFiltration C M)
    (R : ∀ _ : Fin F.length, FiniteExactTower C)
    (start : ∀ i, (R i).object 0 ≅ F.object i.castSucc)
    (finish : ∀ i,
      (R i).object (Fin.last (R i).length) ≅ F.object i.succ) :
    FiniteFiltration C M where
  toFiniteExactTower := F.toFiniteExactTower.replaceSteps R start finish
  initialIsZero := IsZero.of_iso F.initialIsZero
    (F.toFiniteExactTower.replaceStepsInitialIso R start finish).symm
  terminalIso :=
    (F.toFiniteExactTower.replaceStepsTerminalIso R start finish).trans F.terminalIso

@[simp]
theorem replaceSteps_length (F : FiniteFiltration C M)
    (R : ∀ _ : Fin F.length, FiniteExactTower C)
    (start : ∀ i, (R i).object 0 ≅ F.object i.castSucc)
    (finish : ∀ i,
      (R i).object (Fin.last (R i).length) ≅ F.object i.succ) :
    (F.replaceSteps R start finish).length =
      (List.ofFn fun i => (R i).length).sum :=
  F.toFiniteExactTower.replaceSteps_length R start finish

@[simp]
theorem replaceSteps_gradedObjects (F : FiniteFiltration C M)
    (R : ∀ _ : Fin F.length, FiniteExactTower C)
    (start : ∀ i, (R i).object 0 ≅ F.object i.castSucc)
    (finish : ∀ i,
      (R i).object (Fin.last (R i).length) ≅ F.object i.succ) :
    (F.replaceSteps R start finish).toFiniteExactTower.gradedObjects =
      (List.ofFn fun i => (R i).gradedObjects).flatten :=
  F.toFiniteExactTower.replaceSteps_gradedObjects R start finish

/-- Replace one step of a filtration by an endpoint-compatible exact tower.

The prefix and suffix come from the original filtration; the replacement tower supplies all
steps between the adjacent coarse stages. This generic categorical operation is the common
consumer of quotient pullback towers and does not depend on schemes or on the geometry of the
graded pieces. -/
noncomputable def spliceStep (F : FiniteFiltration C M) (i : Fin F.length)
    (T : FiniteExactTower C)
    (initialIso : T.object 0 ≅ F.object i.castSucc)
    (terminalIso : T.object (Fin.last T.length) ≅ F.object i.succ) :
    FiniteFiltration C M := by
  let P := F.toFiniteExactTower.take i.castSucc
  let S := F.toFiniteExactTower.drop i.succ
  let leftSeam : P.object (Fin.last P.length) ≅ T.object 0 :=
    (F.toFiniteExactTower.takeTerminalIso i.castSucc).trans initialIso.symm
  let left := P.append T leftSeam
  let rightSeam : left.object (Fin.last left.length) ≅ S.object 0 :=
    ((P.appendTerminalIso T leftSeam).trans terminalIso).trans
      (F.toFiniteExactTower.dropInitialIso i.succ).symm
  let result := left.append S rightSeam
  let startIso : F.object 0 ≅ result.object 0 :=
    (((F.toFiniteExactTower.takeInitialIso i.castSucc).symm.trans
      (P.appendInitialIso T leftSeam))).trans (left.appendInitialIso S rightSeam)
  exact {
    toFiniteExactTower := result
    initialIsZero := IsZero.of_iso F.initialIsZero startIso.symm
    terminalIso := ((left.appendTerminalIso S rightSeam).trans
      (F.toFiniteExactTower.dropTerminalIso i.succ)).trans F.terminalIso }

@[simp]
theorem spliceStep_length (F : FiniteFiltration C M) (i : Fin F.length)
    (T : FiniteExactTower C)
    (initialIso : T.object 0 ≅ F.object i.castSucc)
    (terminalIso : T.object (Fin.last T.length) ≅ F.object i.succ) :
    (F.spliceStep i T initialIso terminalIso).length = F.length - 1 + T.length := by
  simp only [spliceStep, FiniteExactTower.append_length]
  dsimp only [FiniteExactTower.take, FiniteExactTower.drop]
  change (i.val + T.length) + (F.length - (i.val + 1)) = F.length - 1 + T.length
  omega

@[simp]
theorem spliceStep_gradedObjects (F : FiniteFiltration C M) (i : Fin F.length)
    (T : FiniteExactTower C)
    (initialIso : T.object 0 ≅ F.object i.castSucc)
    (terminalIso : T.object (Fin.last T.length) ≅ F.object i.succ) :
    (F.spliceStep i T initialIso terminalIso).toFiniteExactTower.gradedObjects =
      F.toFiniteExactTower.gradedObjects.take i.val ++ T.gradedObjects ++
        F.toFiniteExactTower.gradedObjects.drop (i.val + 1) := by
  simp only [spliceStep, FiniteExactTower.append_gradedObjects,
    FiniteExactTower.take_gradedObjects, FiniteExactTower.drop_gradedObjects]
  simp only [Fin.val_castSucc, Fin.val_succ]

end FiniteFiltration

namespace FiniteFiltration

variable {C : Type u} [Category.{v} C] [Abelian C]

section PullbackTower

variable {X Q : C} (p : X ⟶ Q) [Epi p]
variable (F : FiniteFiltration C Q)

/-- The stage obtained by pulling a filtration stage back along an epimorphism. -/
noncomputable abbrev pullbackObject (i : Fin (F.length + 1)) : C :=
  pullback p (F.toObject i)

/-- The inclusion between two consecutive pulled-back stages. -/
noncomputable def pullbackInclusion (i : Fin F.length) :
    F.pullbackObject p i.castSucc ⟶ F.pullbackObject p i.succ :=
  pullback.lift (pullback.fst p (F.toObject i.castSucc))
    (pullback.snd p (F.toObject i.castSucc) ≫ F.inclusion i) (by
      simpa only [Category.assoc, F.inclusion_toObject] using
        (pullback.condition (f := p) (g := F.toObject i.castSucc)))

omit [Epi p] in
@[reassoc (attr := simp)]
theorem pullbackInclusion_fst (i : Fin F.length) :
    F.pullbackInclusion p i ≫ pullback.fst p (F.toObject i.succ) =
      pullback.fst p (F.toObject i.castSucc) :=
  pullback.lift_fst _ _ _

omit [Epi p] in
@[reassoc (attr := simp)]
theorem pullbackInclusion_snd (i : Fin F.length) :
    F.pullbackInclusion p i ≫ pullback.snd p (F.toObject i.succ) =
      pullback.snd p (F.toObject i.castSucc) ≫ F.inclusion i :=
  pullback.lift_snd _ _ _

noncomputable instance pullbackInclusion_mono (i : Fin F.length) :
    Mono (F.pullbackInclusion p i) := by
  letI : Mono (F.inclusion i) := (F.step_shortExact i).mono_f
  constructor
  intro Z f g h
  apply pullback.hom_ext
  · simpa only [Category.assoc, F.pullbackInclusion_fst p i] using
      h =≫ pullback.fst p (F.toObject i.succ)
  · rw [← cancel_mono (F.inclusion i)]
    simpa only [Category.assoc, F.pullbackInclusion_snd p i] using
      h =≫ pullback.snd p (F.toObject i.succ)

/-- The quotient projection from a pulled-back stage. -/
noncomputable def pullbackProjection (i : Fin F.length) :
    F.pullbackObject p i.succ ⟶ F.graded i :=
  pullback.snd p (F.toObject i.succ) ≫ F.projection i

noncomputable instance pullbackProjection_epi (i : Fin F.length) :
    Epi (F.pullbackProjection p i) := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  dsimp only [pullbackProjection]
  infer_instance

omit [Epi p] in
theorem pullback_zero (i : Fin F.length) :
    F.pullbackInclusion p i ≫ F.pullbackProjection p i = 0 := by
  rw [pullbackProjection, ← Category.assoc, F.pullbackInclusion_snd p i,
    Category.assoc, F.zero i, comp_zero]

omit [Epi p] in
theorem pullback_exact (i : Fin F.length) :
    (ShortComplex.mk (F.pullbackInclusion p i) (F.pullbackProjection p i)
      (F.pullback_zero p i)).Exact := by
  rw [ShortComplex.exact_iff_exact_up_to_refinements]
  intro A x hx
  have hx' : (x ≫ pullback.snd p (F.toObject i.succ)) ≫ F.projection i = 0 := by
    simpa only [pullbackProjection, Category.assoc] using hx
  obtain ⟨A', π, hπ, y, hy⟩ :=
    (F.step_shortExact i).exact.exact_up_to_refinements
      (x ≫ pullback.snd p (F.toObject i.succ)) hx'
  dsimp only [step, FiniteExactTower.step] at y hy
  change π ≫ x ≫ pullback.snd p (F.toObject i.succ) =
    y ≫ F.inclusion i at hy
  have hcompat :
      (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) ≫ p =
        y ≫ F.toObject i.castSucc := by
    calc
      (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) ≫ p =
          π ≫ x ≫ (pullback.fst p (F.toObject i.succ) ≫ p) := by simp
      _ = π ≫ x ≫
          (pullback.snd p (F.toObject i.succ) ≫ F.toObject i.succ) := by
            rw [pullback.condition]
      _ = (π ≫ x ≫ pullback.snd p (F.toObject i.succ)) ≫
          F.toObject i.succ := by simp
      _ = (y ≫ F.inclusion i) ≫ F.toObject i.succ := by rw [hy]
      _ = y ≫ F.toObject i.castSucc := by
        simpa only [Category.assoc] using y ≫= F.inclusion_toObject i
  let l : A' ⟶ F.pullbackObject p i.castSucc :=
    pullback.lift (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) y hcompat
  refine ⟨A', π, hπ, l, ?_⟩
  apply pullback.hom_ext
  · calc
      (π ≫ x) ≫ pullback.fst p (F.toObject i.succ) =
          π ≫ x ≫ pullback.fst p (F.toObject i.succ) := Category.assoc ..
      _ = l ≫ pullback.fst p (F.toObject i.castSucc) :=
        (pullback.lift_fst
          (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) y hcompat).symm
      _ = (l ≫ F.pullbackInclusion p i) ≫
          pullback.fst p (F.toObject i.succ) := by
            rw [Category.assoc, F.pullbackInclusion_fst p i]
  · calc
      (π ≫ x) ≫ pullback.snd p (F.toObject i.succ) =
          π ≫ x ≫ pullback.snd p (F.toObject i.succ) := Category.assoc ..
      _ = y ≫ F.inclusion i := hy
      _ = (l ≫ F.pullbackInclusion p i) ≫
          pullback.snd p (F.toObject i.succ) := by
            rw [Category.assoc, F.pullbackInclusion_snd p i]
            simpa only [Category.assoc, l] using ((pullback.lift_snd
              (π ≫ x ≫ pullback.fst p (F.toObject i.succ)) y hcompat) =≫
                F.inclusion i).symm

/-- Pull a quotient filtration back along an epimorphism.

The result is an endpoint-free exact tower: its bottom is the kernel of `p`, while its top is
canonically isomorphic to `X`.  This is the actual refinement operation used when a coarse short
exact step is replaced by a filtration of its quotient. -/
noncomputable def pullbackTower : FiniteExactTower C where
  length := F.length
  object := F.pullbackObject p
  inclusion := F.pullbackInclusion p
  graded := F.graded
  projection := F.pullbackProjection p
  zero := F.pullback_zero p
  shortExact i := ShortComplex.ShortExact.mk' (F.pullback_exact p i)
    inferInstance inferInstance

@[simp]
theorem pullbackTower_length : (F.pullbackTower p).length = F.length :=
  rfl

@[simp]
theorem pullbackTower_object (i : Fin ((F.pullbackTower p).length + 1)) :
    (F.pullbackTower p).object i = pullback p (F.toObject i) :=
  rfl

@[simp]
theorem pullbackTower_graded (i : Fin (F.pullbackTower p).length) :
    (F.pullbackTower p).graded i = F.graded i :=
  rfl

@[simp]
theorem pullbackTower_gradedObjects :
    (F.pullbackTower p).gradedObjects = F.toFiniteExactTower.gradedObjects :=
  rfl

/-- The bottom inclusion of the pullback tower, regarded as a kernel fork for `p`. -/
noncomputable def pullbackTowerInitialKernelFork : KernelFork p :=
  KernelFork.ofι (pullback.fst p (F.toObject 0)) (by
    rw [pullback.condition, F.toObject_zero, comp_zero])

/-- The bottom of the pullback tower is a kernel of `p`. -/
noncomputable def pullbackTowerInitialIsLimit :
    IsLimit (F.pullbackTowerInitialKernelFork p) :=
  KernelFork.IsLimit.ofι (pullback.fst p (F.toObject 0)) (by
    rw [pullback.condition, F.toObject_zero, comp_zero])
    (fun g hg ↦ pullback.lift g 0 (by rw [hg, zero_comp]))
    (fun _ _ ↦ pullback.lift_fst _ _ _)
    (fun g hg m hm ↦ by
      apply pullback.hom_ext
      · exact hm.trans (pullback.lift_fst g 0 (by rw [hg, zero_comp])).symm
      · exact F.initialIsZero.eq_of_tgt _ _)

/-- The top of the pullback tower is canonically the source of the epimorphism. -/
noncomputable def pullbackTowerTerminalIso :
    (F.pullbackTower p).object (Fin.last (F.pullbackTower p).length) ≅ X := by
  change pullback p (F.toObject (Fin.last F.length)) ≅ X
  letI : IsIso (F.toFiniteExactTower.toTop (Fin.last F.length)) := by
    rw [F.toFiniteExactTower.toTop_last]
    infer_instance
  letI : IsIso (F.toObject (Fin.last F.length)) := by
    dsimp only [toObject]
    infer_instance
  exact asIso (pullback.fst p (F.toObject (Fin.last F.length)))

@[simp]
theorem pullbackTowerTerminalIso_hom :
    (F.pullbackTowerTerminalIso p).hom =
      pullback.fst p (F.toObject (Fin.last F.length)) :=
  rfl

end PullbackTower

section StepRefinement

variable {M : C} (F : FiniteFiltration C M) (i : Fin F.length)
variable (R : FiniteFiltration C (F.graded i))

/-- The bottom of the lifted refinement is canonically the preceding coarse stage. -/
noncomputable def refinementInitialIso :
    (R.pullbackTower (F.projection i)).object 0 ≅ F.object i.castSucc := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  exact IsLimit.conePointUniqueUpToIso
    (R.pullbackTowerInitialIsLimit (F.projection i))
    (F.step_shortExact i).fIsKernel

/-- The top of the lifted refinement is canonically the following coarse stage. -/
noncomputable def refinementTerminalIso :
    (R.pullbackTower (F.projection i)).object
      (Fin.last (R.pullbackTower (F.projection i)).length) ≅ F.object i.succ := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  exact R.pullbackTowerTerminalIso (F.projection i)

/-- The initial comparison intertwines the lifted kernel inclusion and the coarse inclusion. -/
theorem refinementInitialIso_hom_inclusion :
    (refinementInitialIso F i R).hom ≫ F.inclusion i =
      pullback.fst (F.projection i) (R.toObject 0) := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  exact IsLimit.conePointUniqueUpToIso_hom_comp
    (R.pullbackTowerInitialIsLimit (F.projection i))
    (F.step_shortExact i).fIsKernel Limits.WalkingParallelPair.zero

/-- Refine one graded quotient by pulling its filtration back to the adjacent coarse stages and
splicing that exact tower into the original filtration. -/
noncomputable def refineStep : FiniteFiltration C M := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  exact F.spliceStep i (R.pullbackTower (F.projection i))
    (refinementInitialIso F i R) (refinementTerminalIso F i R)

@[simp]
theorem refineStep_length :
    (refineStep F i R).length = F.length - 1 + R.length := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  simp [refineStep]

@[simp]
theorem refineStep_gradedObjects :
    (refineStep F i R).toFiniteExactTower.gradedObjects =
      F.toFiniteExactTower.gradedObjects.take i.val ++
        R.toFiniteExactTower.gradedObjects ++
          F.toFiniteExactTower.gradedObjects.drop (i.val + 1) := by
  letI : Epi (F.projection i) := (F.step_shortExact i).epi_g
  simp [refineStep]

end StepRefinement

section AllStepsRefinement

variable {M : C} (F : FiniteFiltration C M)
variable (R : ∀ i : Fin F.length, FiniteFiltration C (F.graded i))

/-- Refine every graded quotient of a filtration at once.

For each coarse step, its quotient filtration is pulled back to an exact tower between the
adjacent coarse stages. `FiniteExactTower.replaceSteps` then concatenates those lifted towers in
coarse-step order. This is the categorical refinement used in the composition argument for
almost-disconnected morphisms. -/
noncomputable def refineAll : FiniteFiltration C M :=
  F.replaceSteps
    (fun i => (R i).pullbackTower (F.projection i))
    (fun i => refinementInitialIso F i (R i))
    (fun i => refinementTerminalIso F i (R i))

@[simp]
theorem refineAll_length :
    (refineAll F R).length = (List.ofFn fun i => (R i).length).sum := by
  simp [refineAll]

@[simp]
theorem refineAll_gradedObjects :
    (refineAll F R).toFiniteExactTower.gradedObjects =
      (List.ofFn fun i => (R i).toFiniteExactTower.gradedObjects).flatten := by
  simp [refineAll]

end AllStepsRefinement

end FiniteFiltration

end CategoryTheory
