import DerivedAlgGeo.CategoryTheory.Linear.Opposite
import DerivedAlgGeo.CategoryTheory.Linear.Adjunction
import DerivedAlgGeo.CategoryTheory.Linear.SerreFunctor
import DerivedAlgGeo.CategoryTheory.Linear.Yoneda
