import DerivedAlgGeo.CategoryTheory.SpectralSequence.FilteredComplexSpectralObject
import DerivedAlgGeo.CategoryTheory.SpectralSequence.FilteredTotalComplex
import DerivedAlgGeo.CategoryTheory.SpectralSequence.FilteredTotalComplexAdjacent
import DerivedAlgGeo.CategoryTheory.SpectralSequence.ExtendHomologyNaturality
import DerivedAlgGeo.CategoryTheory.SpectralSequence.FilteredTotalComplexFirstPageDifferential
import DerivedAlgGeo.CategoryTheory.SpectralSequence.TotalFlipNaturality
import DerivedAlgGeo.CategoryTheory.SpectralSequence.TotalQuasiIso

/-! # Spectral-sequence infrastructure

Filtered complexes, column-filtered total complexes, and their spectral
objects in arbitrary abelian categories.
-/
