/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import Mathlib.AlgebraicGeometry.Morphisms.Smooth
import DerivedAlgGeo.AlgebraicGeometry.Sites.Comparison
import DerivedAlgGeo.AlgebraicGeometry.Stacks.Representable

/-!
# Fppf and étale stack descent

The stack layer of this repository was built over the big *Zariski* site:
`representableZariskiStack` and everything in
`DerivedAlgGeo.AlgebraicGeometry.Stacks.Algebraic` asks only for effective
descent along Zariski covers.  The standard definition of an algebraic stack
asks for descent along fppf covers, or equivalently for the étale
formulation, and Zariski descent does not imply either: the finer topologies
have covering families the Zariski topology does not.

This file raises the descent level for representable stacks:

* `representableFppfStack` and `representableEtaleStack`, whose stack
  condition is Mathlib's fpqc descent theorem for representable presheaves,
  restricted along `Scheme.fppfTopology ≤ Scheme.fpqcTopology` and
  `Scheme.etaleTopology ≤ Scheme.fppfTopology`;
* `Scheme.Cover.toStackCover`, turning any Mathlib `P`-cover into an
  explicitly indexed covering family, with its fppf, smooth-surjective and
  étale specializations;
* effective Čech descent along a single faithfully flat morphism locally of
  finite presentation, which the Zariski layer cannot express because such a
  morphism need not be a monomorphism;
* the comparisons identifying the existing Zariski layer and the new étale
  layer as restrictions of the fppf layer.

## What this file does not do

It does not define, construct, or assert an algebraic stack, and nothing here
should be read as progress toward one beyond the descent level itself.  Two
of the three prerequisites recorded for `stability-families-e15-2` are
untouched: the diagonal in `Stacks.Algebraic` is still represented by
*schemes* rather than by algebraic spaces, and the atlas and diagonal of the
full universally-gluable relative-perfect moduli stack are not constructed.
No statement about that moduli stack is made here: every stack below is
representable.
-/

namespace AlgebraicGeometry

open CategoryTheory Opposite

noncomputable section

universe u

/-! ## Covering families for a morphism-property topology -/

/-- Every Mathlib `P`-cover of a scheme is an explicitly indexed covering
family for the Grothendieck topology generated by `P`. -/
@[simps index obj hom]
def Scheme.Cover.toStackCover {P : MorphismProperty Scheme.{u}} {S : Scheme.{u}}
    (𝒰 : S.Cover (Scheme.precoverage P)) :
    StackInGroupoids.Cover (J := Scheme.grothendieckTopology P) S where
  index := 𝒰.I₀
  obj := 𝒰.X
  hom := 𝒰.f
  mem := 𝒰.mem_grothendieckTopology

/-- A faithfully flat morphism locally of finite presentation is a one-element
fppf covering family. -/
def Scheme.fppfCover {X Y : Scheme.{u}} (f : X ⟶ Y)
    [Flat f] [Surjective f] [LocallyOfFinitePresentation f] :
    StackInGroupoids.Cover (J := Scheme.fppfTopology.{u}) Y :=
  (f.cover (P := @Flat ⊓ @LocallyOfFinitePresentation) ⟨‹_›, ‹_›⟩).toStackCover

/-- A smooth surjection is a one-element fppf covering family, because a
smooth morphism is flat and locally of finite presentation.

This is the bridge between the smooth-surjective atlas data already recorded
in `DerivedAlgGeo.AlgebraicGeometry.Stacks.Algebraic` and the fppf descent
level.  It says that such an atlas is a cover in the right topology; it says
nothing about the existence of an atlas for any particular stack. -/
def Scheme.fppfCoverOfSmoothSurjective {X Y : Scheme.{u}} (f : X ⟶ Y)
    [Smooth f] [Surjective f] :
    StackInGroupoids.Cover (J := Scheme.fppfTopology.{u}) Y :=
  Scheme.fppfCover f

/-- An étale surjection is a one-element étale covering family. -/
def Scheme.etaleCover {X Y : Scheme.{u}} (f : X ⟶ Y) [Etale f] [Surjective f] :
    StackInGroupoids.Cover (J := Scheme.etaleTopology.{u}) Y :=
  (f.cover (P := @Etale) ‹_›).toStackCover

/-- Every big-Zariski covering family is an fppf covering family, with the
same index type and the same arrows. -/
abbrev zariskiCoverToFppf {S : Scheme.{u}}
    (U : StackInGroupoids.Cover (J := Scheme.zariskiTopology.{u}) S) :
    StackInGroupoids.Cover (J := Scheme.fppfTopology.{u}) S :=
  U.ofLE Scheme.zariskiTopology_le_fppfTopology

/-- Every big-Zariski covering family is an étale covering family. -/
abbrev zariskiCoverToEtale {S : Scheme.{u}}
    (U : StackInGroupoids.Cover (J := Scheme.zariskiTopology.{u}) S) :
    StackInGroupoids.Cover (J := Scheme.etaleTopology.{u}) S :=
  U.ofLE Scheme.zariskiTopology_le_etaleTopology

/-! ## Representable stacks at the fppf and étale levels -/

/-- The big-fppf stack represented by a scheme `X`.

The descent condition is genuinely stronger than the one carried by
`representableZariskiStack`: it is Mathlib's fpqc descent theorem for
representable presheaves, restricted to fppf coverings. -/
def representableFppfStack (X : Scheme.{u}) :
    StackInGroupoids Scheme.{u} Scheme.fppfTopology :=
  stackInGroupoidsOfSheaf Scheme.fppfTopology (yoneda.obj X)
    (GrothendieckTopology.Subcanonical.isSheaf_of_isRepresentable
      (J := Scheme.fppfTopology.{u}) (yoneda.obj X))

/-- The big-étale stack represented by a scheme `X`. -/
def representableEtaleStack (X : Scheme.{u}) :
    StackInGroupoids Scheme.{u} Scheme.etaleTopology :=
  stackInGroupoidsOfSheaf Scheme.etaleTopology (yoneda.obj X)
    (GrothendieckTopology.Subcanonical.isSheaf_of_isRepresentable
      (J := Scheme.etaleTopology.{u}) (yoneda.obj X))

@[simp]
theorem representableFppfStack_presheaf (X : Scheme.{u}) :
    (representableFppfStack X).presheaf = (representableZariskiStack X).presheaf :=
  rfl

@[simp]
theorem representableEtaleStack_presheaf (X : Scheme.{u}) :
    (representableEtaleStack X).presheaf = (representableZariskiStack X).presheaf :=
  rfl

/-- The étale level is the restriction of the fppf level along
`Scheme.etaleTopology ≤ Scheme.fppfTopology`. -/
theorem representableEtaleStack_eq_ofLE (X : Scheme.{u}) :
    representableEtaleStack X =
      (representableFppfStack X).ofLE Scheme.etaleTopology_le_fppfTopology :=
  rfl

/-- The existing big-Zariski layer is the restriction of the fppf level.

The implication runs one way only.  This recovers the Zariski statement from
the fppf one and gives no transport in the other direction, which is why the
fppf level had to be proved rather than derived from the Zariski layer. -/
theorem representableZariskiStack_eq_ofLE (X : Scheme.{u}) :
    representableZariskiStack X =
      (representableFppfStack X).ofLE Scheme.zariskiTopology_le_fppfTopology :=
  rfl

/-- A morphism `T ⟶ X`, as an object of the fppf stack represented by `X`.
The fiber categories are literally those of the Zariski layer. -/
def representableFppfObject {X T : Scheme.{u}} (f : T ⟶ X) :
    (representableFppfStack X).presheaf.obj (.mk (op T)) :=
  Discrete.mk f

@[simp]
theorem representableFppfObject_eq {X T : Scheme.{u}} (f : T ⟶ X) :
    representableFppfObject f = representableZariskiObject f :=
  rfl

/-! ## Effective fppf and étale descent -/

/-- Effective Čech descent for a representable fppf stack along an arbitrary
fppf covering family. -/
def representableFppfCechDescentEquivalence (X : Scheme.{u}) {S : Scheme.{u}}
    (U : StackInGroupoids.Cover (J := Scheme.fppfTopology.{u}) S) :
    (representableFppfStack X).presheaf.obj (.mk (op S)) ≌
      (representableFppfStack X).CechDescent U :=
  (representableFppfStack X).cechDescentEquivalence U

/-- Effective Čech descent for a representable étale stack along an arbitrary
étale covering family. -/
def representableEtaleCechDescentEquivalence (X : Scheme.{u}) {S : Scheme.{u}}
    (U : StackInGroupoids.Cover (J := Scheme.etaleTopology.{u}) S) :
    (representableEtaleStack X).presheaf.obj (.mk (op S)) ≌
      (representableEtaleStack X).CechDescent U :=
  (representableEtaleStack X).cechDescentEquivalence U

/-- Effective descent along a single faithfully flat morphism locally of
finite presentation.

This is the case the big-Zariski layer cannot express: `f` is not required to
be an open immersion, or even a monomorphism. -/
def representableFppfDescentAlong (X : Scheme.{u}) {Y Z : Scheme.{u}} (f : Z ⟶ Y)
    [Flat f] [Surjective f] [LocallyOfFinitePresentation f] :
    (representableFppfStack X).presheaf.obj (.mk (op Y)) ≌
      (representableFppfStack X).CechDescent (Scheme.fppfCover f) :=
  (representableFppfStack X).cechDescentEquivalence _

/-- Effective descent along a single smooth surjection. -/
def representableFppfDescentAlongSmoothSurjective (X : Scheme.{u})
    {Y Z : Scheme.{u}} (f : Z ⟶ Y) [Smooth f] [Surjective f] :
    (representableFppfStack X).presheaf.obj (.mk (op Y)) ≌
      (representableFppfStack X).CechDescent
        (Scheme.fppfCoverOfSmoothSurjective f) :=
  (representableFppfStack X).cechDescentEquivalence _

/-- Effective descent along a single étale surjection. -/
def representableEtaleDescentAlong (X : Scheme.{u}) {Y Z : Scheme.{u}} (f : Z ⟶ Y)
    [Etale f] [Surjective f] :
    (representableEtaleStack X).presheaf.obj (.mk (op Y)) ≌
      (representableEtaleStack X).CechDescent (Scheme.etaleCover f) :=
  (representableEtaleStack X).cechDescentEquivalence _

/-- Morphisms of a representable fppf stack satisfy descent: restriction to an
fppf cover is fully faithful. -/
def representableFppfFullyFaithfulToCechDescent (X : Scheme.{u}) {S : Scheme.{u}}
    (U : StackInGroupoids.Cover (J := Scheme.fppfTopology.{u}) S) :
    ((representableFppfStack X).toCechDescent U).FullyFaithful :=
  (representableFppfStack X).fullyFaithfulToCechDescent U

/-- Objects of a representable fppf stack satisfy effective descent: every
fppf Čech descent datum comes from an object over the base. -/
theorem representableFppfEssSurjToCechDescent (X : Scheme.{u}) {S : Scheme.{u}}
    (U : StackInGroupoids.Cover (J := Scheme.fppfTopology.{u}) S) :
    ((representableFppfStack X).toCechDescent U).EssSurj :=
  (representableFppfStack X).essSurjToCechDescent U

end

end AlgebraicGeometry
