/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.ProjectiveSpectrum.Modules.ChartScalar
import DerivedAlgGeo.AlgebraicGeometry.Modules.Coherent.AffineChart

/-!
# A coherent sheaf is generated on a degree-one chart by finitely many sections

Step 2 of Serre's global generation (`#586`). On the chart `D₊(g)` of a degree-one element, a
coherent `F` is generated by finitely many sections over the whole chart: near every point of every
open inside `D₊(g)`, every section of `F` is a structure-sheaf combination of their restrictions.

## Where the finiteness comes from, and where it is spent

`D₊(g)` is `Spec A_{(g)}`, and `moduleFinite_globalSections` makes the chart's module of sections
finitely generated from finite presentation alone -- no Noetherian hypothesis, as
`Modules/Coherent/AffineChart.lean` records. A finite spanning set of that module is the family.

That the family generates *locally*, and not merely spans the global sections of the chart, is the
affine extension lemma: a section over a smaller basic open `D₊(g) ⊓ D₊(f)`, multiplied by a power
of `f / gᵉ`, extends to the chart (`exists_pow_smul_eq_res_chart`), where it is a combination of the
spanning set; and `f / gᵉ` is invertible on `D₊(g) ⊓ D₊(f)` (`fracSection_mul_fracSection_symm`),
so the section itself is a combination there.

## The neighbourhood is a positive-degree basic open

Basic opens `D₊(r)`, `r : A` arbitrary, form a basis of `Proj 𝒜`, but the chart lemmas need a
*homogeneous* `r` of *positive* degree. `basicOpen_eq_union_of_projection` splits `D₊(r)` into the
basic opens of its homogeneous components, and multiplying the component by `g` -- which does not
move the open outside `D₊(g)`, because `D₊(f g) = D₊(f) ⊓ D₊(g)` -- raises the degree above zero.
`exists_mem_basicOpen_le` packages that.

## Scope

One chart. The family is stated over the chart's image `awayι ''ᵁ ⊤`, taken as a variable pinned
by an equation in the style of `ChartProj.lean`, so that a caller instantiates it at `D₊(g)`
without transporting sections. The cover, the twist, and the surjection are in
`GlobalGeneration.lean`.
-/

noncomputable section

open CategoryTheory Opposite SetLike TopCat TopologicalSpace

namespace AlgebraicGeometry.Proj

universe u

variable {A σA : Type u} [CommRing A] [SetLike σA A] [AddSubgroupClass σA A]
variable (𝒜 : ℕ → σA) [GradedRing 𝒜]

/-- **A point of an open inside `D₊(g)` has a positive-degree basic-open neighbourhood in it.**

The basis of `Proj 𝒜` supplies `D₊(r) ∋ x` inside `U` for some `r : A`; a homogeneous component of
`r` still has `x` in its basic open (`basicOpen_eq_union_of_projection`); and multiplying that
component by `g` makes the degree positive while cutting the open down to `D₊(g)`. -/
theorem exists_mem_basicOpen_le {g : A} (hg : g ∈ 𝒜 1) (U : (Proj 𝒜).Opens)
    (x : Proj 𝒜) (hx : x ∈ U) (hxg : x ∈ ProjectiveSpectrum.basicOpen 𝒜 g) :
    ∃ (e : ℕ) (f : A) (_ : f ∈ 𝒜 e), 0 < e ∧ x ∈ ProjectiveSpectrum.basicOpen 𝒜 f ∧
      ProjectiveSpectrum.basicOpen 𝒜 f ≤ U := by
  obtain ⟨v, ⟨r, rfl⟩, hxv, hvU⟩ :=
    (ProjectiveSpectrum.isTopologicalBasis_basic_opens 𝒜).exists_subset_of_mem_open hx U.isOpen
  have hxr : x ∈ ProjectiveSpectrum.basicOpen 𝒜 r := hxv
  rw [ProjectiveSpectrum.basicOpen_eq_union_of_projection] at hxr
  obtain ⟨i, hxi⟩ := Opens.mem_iSup.mp hxr
  have hmem : GradedRing.proj 𝒜 i r ∈ 𝒜 i := by
    rw [GradedRing.proj_apply]
    exact SetLike.coe_mem _
  refine ⟨i + 1, GradedRing.proj 𝒜 i r * g, SetLike.mul_mem_graded hmem hg, Nat.succ_pos i,
    ?_, ?_⟩
  · rw [ProjectiveSpectrum.basicOpen_mul]
    exact ⟨hxi, hxg⟩
  · rw [ProjectiveSpectrum.basicOpen_mul]
    refine inf_le_left.trans ((le_iSup (fun j => ProjectiveSpectrum.basicOpen 𝒜
      (GradedRing.proj 𝒜 j r)) i).trans ?_)
    rw [← ProjectiveSpectrum.basicOpen_eq_union_of_projection]
    exact hvU

/-- **Finitely many sections over `D₊(g)` generate a coherent sheaf there.**

For `F` coherent and `g` of degree one, there is a finite family of sections of `F` over the chart
such that, near every point of every open `U` inside the chart, every section of `F` over `U` is a
structure-sheaf combination of the family's restrictions.

The chart is `awayι ''ᵁ ⊤`, pinned to the caller's spelling by `hW` as in `ChartProj.lean`. The
family is a finite spanning set of the chart's module of sections; local generation is the affine
extension lemma followed by inverting the chart scalar `(f / gᵉ)ⁿ`, which is a unit on the
positive-degree basic open `D₊(g) ⊓ D₊(f)` that `exists_mem_basicOpen_le` finds around the
point. -/
theorem exists_finite_generators_of_isCoherent (F : (Proj 𝒜).Modules)
    (hF : Scheme.Modules.IsCoherent (Proj 𝒜) F) {g : A} (hg : g ∈ 𝒜 1)
    {W : (Proj 𝒜).Opens} (hW : awayι 𝒜 g hg Nat.one_pos ''ᵁ ⊤ = W) :
    ∃ (κ : Type u) (_ : Fintype κ) (s : κ → Γ(F, W)),
      ∀ (U : (Proj 𝒜).Opens) (hUW : U ≤ W) (u : Γ(F, U)) (x : Proj 𝒜), x ∈ U →
        ∃ (V : (Proj 𝒜).Opens) (hVU : V ≤ U), x ∈ V ∧ ∃ c : κ → Γ(Proj 𝒜, V),
          F.presheaf.map (homOfLE hVU).op u
            = ∑ a, c a • F.presheaf.map (homOfLE (hVU.trans hUW)).op (s a) := by
  classical
  subst hW
  have hMfp : SheafOfModules.IsFinitePresentation.{u, u, u} (awayRestrict 𝒜 F hg Nat.one_pos) :=
    Scheme.Modules.IsCoherent.restrict_of_isOpenImmersion (awayι 𝒜 g hg Nat.one_pos) F hF
  haveI hFqc : SheafOfModules.IsQuasicoherent.{u, u, u}
      (show SheafOfModules (Proj 𝒜).ringCatSheaf from F) := by
    haveI : SheafOfModules.IsFinitePresentation.{u, u, u}
      (show SheafOfModules (Proj 𝒜).ringCatSheaf from F) := hF
    infer_instance
  haveI hfin : Module.Finite (HomogeneousLocalization.Away 𝒜 g)
      (moduleSpecΓFunctor.obj (awayRestrict 𝒜 F hg Nat.one_pos)) :=
    Scheme.Modules.moduleFinite_globalSections _ hMfp
  obtain ⟨T, hT⟩ := Module.finite_def.mp hfin
  refine ⟨T, inferInstance, fun a => (a.1 : Γ(F, awayι 𝒜 g hg Nat.one_pos ''ᵁ ⊤)), ?_⟩
  intro U hUW u x hx
  have hxg : x ∈ ProjectiveSpectrum.basicOpen 𝒜 g := by
    have hxW := hUW hx
    rwa [awayι_image_top] at hxW
  obtain ⟨e, f, hf, he, hxf, hfU⟩ := exists_mem_basicOpen_le 𝒜 hg U x hx hxg
  -- the chart's basic open of `f / gᵉ`, as an open of `Proj 𝒜`
  set V : (Proj 𝒜).Opens := awayι 𝒜 g hg Nat.one_pos ''ᵁ
    PrimeSpectrum.basicOpen (HomogeneousLocalization.Away.isLocalizationElem hg hf) with hVdef
  have hVeq : V = basicOpen 𝒜 g ⊓ basicOpen 𝒜 f := awayι_image_basicOpen 𝒜 hg Nat.one_pos hf he
  have hVU : V ≤ U := by
    rw [hVeq]
    exact inf_le_right.trans hfU
  have hxV : x ∈ V := by
    rw [hVeq]
    exact ⟨hxg, hxf⟩
  have hVf : V ≤ ProjectiveSpectrum.basicOpen 𝒜 f := by
    rw [hVeq]
    exact inf_le_right
  refine ⟨V, hVU, hxV, ?_⟩
  -- extend the restricted section across the chart, at the price of the chart scalar
  obtain ⟨n, t, ht⟩ := exists_pow_smul_eq_res_chart 𝒜 F hf hg Nat.one_pos
    (show (modulesSpecToSheaf.obj (awayRestrict 𝒜 F hg Nat.one_pos)).presheaf.obj
      (op (PrimeSpectrum.basicOpen (HomogeneousLocalization.Away.isLocalizationElem hg hf))) from
      F.presheaf.map (homOfLE hVU).op u)
  -- the chart scalar and its inverse on `D₊(g) ⊓ D₊(f)`
  set φ : Γ(Proj 𝒜, V) := isLocalizationFrac 𝒜 hf hg n (awayι_image_le 𝒜 hg Nat.one_pos _)
    with hφ
  have ht' : φ • F.presheaf.map (homOfLE hVU).op u
      = F.presheaf.map (homOfLE (hVU.trans hUW)).op
        (show Γ(F, awayι 𝒜 g hg Nat.one_pos ''ᵁ ⊤) from t) :=
    (ht.trans (isLocalizationElem_pow_smul_eq 𝒜 F hf hg Nat.one_pos n _)).symm
  have hVb : V ≤ ProjectiveSpectrum.basicOpen 𝒜 ((f ^ 1) ^ n) :=
    hVf.trans ((basicOpen_le_basicOpen_pow 𝒜 f 1).trans (basicOpen_le_basicOpen_pow 𝒜 (f ^ 1) n))
  set ψ : Γ(Proj 𝒜, V) := fracSection 𝒜 (pow_mem_smul 𝒜 (SetLike.pow_mem_graded e hg) n)
    (pow_mem_smul 𝒜 (pow_mem_smul 𝒜 hf 1) n) hVb with hψ
  have hψφ : ψ * φ = 1 :=
    fracSection_mul_fracSection_symm 𝒜 (pow_mem_smul 𝒜 (SetLike.pow_mem_graded e hg) n)
      (pow_mem_smul 𝒜 (pow_mem_smul 𝒜 hf 1) n) hVb _
  -- the extension is a combination of the spanning set
  have htmem : (show moduleSpecΓFunctor.obj (awayRestrict 𝒜 F hg Nat.one_pos) from t) ∈
      Submodule.span (HomogeneousLocalization.Away 𝒜 g)
        (T : Set (moduleSpecΓFunctor.obj (awayRestrict 𝒜 F hg Nat.one_pos))) :=
    hT ▸ Submodule.mem_top
  obtain ⟨c, -, hc₀⟩ := Submodule.mem_span_finset.mp htmem
  have hc : ∑ a : T, c a.1 • a.1 = t :=
    (Finset.sum_coe_sort T (fun a => c a • a)).trans hc₀
  -- the chart ring's scalars, read on `Proj 𝒜`
  set r : T → Γ(Proj 𝒜, V) := fun a =>
    ((Proj 𝒜).presheaf.map (homOfLE (awayι_image_le 𝒜 hg Nat.one_pos _)).op).hom
      ((awayToSection 𝒜 g).hom (c a.1)) with hr
  refine ⟨fun a => ψ * r a, ?_⟩
  -- `t|_V` is the restricted combination, with the chart's scalars read on `Proj 𝒜`
  have hB : PrimeSpectrum.basicOpen (HomogeneousLocalization.Away.isLocalizationElem hg hf)
      ≤ (⊤ : (Spec (chartRing 𝒜 g)).Opens) := le_top
  have hres : F.presheaf.map (homOfLE (hVU.trans hUW)).op
      (show Γ(F, awayι 𝒜 g hg Nat.one_pos ''ᵁ ⊤) from t)
      = ∑ a : T, r a • F.presheaf.map (homOfLE (hVU.trans hUW)).op
          (a.1 : Γ(F, awayι 𝒜 g hg Nat.one_pos ''ᵁ ⊤)) := by
    have h1 : (modulesSpecToSheaf.obj (awayRestrict 𝒜 F hg Nat.one_pos)).presheaf.map
        (homOfLE hB).op t
        = ∑ a : T, (modulesSpecToSheaf.obj (awayRestrict 𝒜 F hg Nat.one_pos)).presheaf.map
          (homOfLE hB).op (c a.1 • a.1) :=
      (congrArg (fun z => (modulesSpecToSheaf.obj (awayRestrict 𝒜 F hg Nat.one_pos)).presheaf.map
        (homOfLE hB).op z) hc).symm.trans (map_sum _ _ _)
    refine h1.trans (Finset.sum_congr rfl fun a _ => ?_)
    exact (map_smul _ (c a.1) a.1).trans (chart_smul_eq 𝒜 F hg Nat.one_pos (c a.1) _)
  -- `u|_V = ψ • (φ • u|_V) = ψ • t|_V`
  calc F.presheaf.map (homOfLE hVU).op u
      = (ψ * φ) • F.presheaf.map (homOfLE hVU).op u := by rw [hψφ, one_smul]
    _ = ψ • (φ • F.presheaf.map (homOfLE hVU).op u) := mul_smul _ _ _
    _ = ψ • F.presheaf.map (homOfLE (hVU.trans hUW)).op
        (show Γ(F, awayι 𝒜 g hg Nat.one_pos ''ᵁ ⊤) from t) := by rw [ht']
    _ = ψ • ∑ a : T, r a • F.presheaf.map (homOfLE (hVU.trans hUW)).op
        (a.1 : Γ(F, awayι 𝒜 g hg Nat.one_pos ''ᵁ ⊤)) := by rw [hres]
    _ = ∑ a : T, (ψ * r a) • F.presheaf.map (homOfLE (hVU.trans hUW)).op
        (a.1 : Γ(F, awayι 𝒜 g hg Nat.one_pos ''ᵁ ⊤)) := by
      rw [Finset.smul_sum]
      exact Finset.sum_congr rfl fun a _ => smul_smul _ _ _

end AlgebraicGeometry.Proj
