/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.AlgebraicGeometry.ProjectiveSpectrum.Modules.GlueUniform
import DerivedAlgGeo.AlgebraicGeometry.ProjectiveSpectrum.Modules.TwistGenerated
import DerivedAlgGeo.AlgebraicGeometry.ProjectiveSpectrum.Modules.TwistApp
import DerivedAlgGeo.AlgebraicGeometry.ProjectiveSpectrum.Modules.ChartGeneration
import DerivedAlgGeo.AlgebraicGeometry.Modules.LocalCombination
import DerivedAlgGeo.Algebra.Category.ModuleCat.Sheaf.GeneratingSections

/-!
# Serre's theorem: a coherent sheaf on `Proj` is generated by global sections after a twist

**Hartshorne II.5.17 / EGA II 2.7.9, in the global-generation form.** For `𝒜` generated over
`𝒜 0` by finitely many elements of degree one and `F` coherent on `Proj 𝒜`, there is an `N` such
that `F(N) = F ⊗ O(N)` is a quotient of a finite free sheaf: `free I ↠ F(N)`, equivalently `F(N)`
has finitely many generating sections.

This closes `#586`, and it is the first place in the tree where Serre's theorem itself is proved,
as opposed to the section-extension lemma (`Glue.lean`, Hartshorne II.5.14(a)) that
`exists_globalSection_twistBy` is. Nothing here assumes global generation, a resolution property,
or an instance supplying the surjection: the inputs are coherence of `F`, finiteness of the
degree-one generating set, and nothing else.

## The argument

Three layers, each already in the tree, joined here:

1. **Chart generators** (`ChartGeneration.lean`). On each chart `D₊(gᵢ)`, coherence gives finitely
   many sections `sᵢ,ₐ` of `F` over the chart that generate `F` locally there.
2. **One twist for all of them** (`GlueUniform.lean`). Each `sᵢ,ₐ`, multiplied by `gᵢᴺ`, extends
   to a global section `σᵢ,ₐ` of `F(N)`, with a *single* `N` serving every chart and every
   generator. This is where the uniform exponent, not a maximum of per-section exponents, is
   essential -- see that file for why raising an exponent after the fact is unavailable.
3. **The `O(N)` factor** (`TwistGenerated.lean`). On `D₊(gᵢ)`, every section of `O(N)` is locally
   a multiple of `gᵢᴺ / 1`, so every pure tensor `t ⊗ w` is locally `(r • t) ⊗ (gᵢᴺ / 1)`, hence a
   combination of the `twistBy gᵢᴺ` of the chart generators, hence of the `σᵢ,ₐ`.

A section of the sheafified tensor product is locally a finite sum of pure tensors
(`exists_eq_sum_tmulSection`), so `IsLocalCombination` closes the sum, and its epimorphism
criterion closes the theorem.

## Why `F(N)` and not `⊕ O(-N) ↠ F`

The two forms are equivalent once `F(N)(-N) ≅ F`, and that isomorphism is not available for an
arbitrary `F`: `TensorTwist.lean` records that the tensor associator of the tree needs invertible
outer factors, and `#806` tracks the tensor inverse of `O(N)`. The statement proved here is the one
Hartshorne II.5.17 states first, and the passage to `⊕ O(-N) ↠ F` is one tensor with `O(-N)`
once that inverse lands. Nothing about the surjection changes.

## The exponent is `1 * N`

`exists_globalSection_twistBy_uniform` twists by `f ^ N` at degree `e * N` for generators of
degree `e`; here `e = 1`, and `1 * N` is not definitionally `N`. The theorem is therefore stated
with an existential `N` and instantiated at `1 * N₀`, and the two spellings `gᵢ ^ N₀` and
`gᵢ ^ (1 * N₀)` of the twisting element are reconciled by `twistBy_congr` rather than by rewriting
inside a dependent type.
-/

noncomputable section

open CategoryTheory Opposite SetLike TopCat TopologicalSpace

namespace AlgebraicGeometry.Proj

universe u

variable {A σA : Type u} [CommRing A] [SetLike σA A] [AddSubgroupClass σA A]
variable (𝒜 : ℕ → σA) [GradedRing 𝒜]

/-- **A pure tensor of `F ⊗ O(N)` is locally a combination of the twisted chart generators.**

Near a point of `D₊(g)`, the `O(N)` factor is a multiple of `gᴺ / 1`
(`exists_smul_sectionOfMem_eq_res`), so the pure tensor is `(r • t) ⊗ (gᴺ / 1)`; the chart
generators write `r • t` as a combination (`hs`); and `sₐ ⊗ (gᴺ / 1)` is `twistBy gᴺ` applied to
`sₐ` (`twistBy_app`). The scalars are carried onto the first factor by `smul_tmulSection_left`.

The family is given with its local-generation property as a hypothesis, in the exact shape
`exists_finite_generators_of_isCoherent` produces it, so that the choice of generators is made
once in the main theorem and not again here. -/
theorem exists_res_tmulSection_eq_sum (F : (Proj 𝒜).Modules) {g : A} (hg : g ∈ 𝒜 1)
    {κ : Type u} [Fintype κ] (s : κ → Γ(F, basicOpen 𝒜 g))
    (hs : ∀ (U : (Proj 𝒜).Opens) (hUW : U ≤ basicOpen 𝒜 g) (u : Γ(F, U)) (x : Proj 𝒜),
      x ∈ U → ∃ (V : (Proj 𝒜).Opens) (hVU : V ≤ U), x ∈ V ∧ ∃ c : κ → Γ(Proj 𝒜, V),
        F.presheaf.map (homOfLE hVU).op u
          = ∑ b, c b • F.presheaf.map (homOfLE (hVU.trans hUW)).op (s b))
    (N : ℕ) {V : (Proj 𝒜).Opens} (t : Γ(F, V)) (w : Γ(twistingSheaf 𝒜 (N : ℤ), V))
    (x : Proj 𝒜) (hxV : x ∈ V) (hxg : x ∈ ProjectiveSpectrum.basicOpen 𝒜 g) :
    ∃ (W : (Proj 𝒜).Opens) (hWV : W ≤ V) (hWg : W ≤ basicOpen 𝒜 g), x ∈ W ∧
      ∃ c : κ → Γ(Proj 𝒜, W),
        (Scheme.Modules.tensorObj F (twistingSheaf 𝒜 (N : ℤ))).presheaf.map (homOfLE hWV).op
            (Scheme.Modules.tmulSection F (twistingSheaf 𝒜 (N : ℤ)) (op V) t w)
          = ∑ b, c b • (Scheme.Modules.tensorObj F (twistingSheaf 𝒜 (N : ℤ))).presheaf.map
              (homOfLE hWg).op
              (Scheme.Modules.Hom.app (twistBy 𝒜 N (pow_mem_deg 𝒜 hg N) F)
                (basicOpen 𝒜 g) (s b)) := by
  obtain ⟨W₁, hW₁V, hxW₁, r, hr⟩ := exists_smul_sectionOfMem_eq_res 𝒜 hg N w x hxV hxg
  obtain ⟨W₂, hW₂, hxW₂, c, hc⟩ := hs (W₁ ⊓ basicOpen 𝒜 g) inf_le_right
    (F.presheaf.map (homOfLE (inf_le_left : W₁ ⊓ basicOpen 𝒜 g ≤ W₁)).op
      (r • F.presheaf.map (homOfLE hW₁V).op t)) x ⟨hxW₁, hxg⟩
  have hW₂W₁ : W₂ ≤ W₁ := hW₂.trans inf_le_left
  have hW₂g : W₂ ≤ basicOpen 𝒜 g := hW₂.trans inf_le_right
  refine ⟨W₂, hW₂W₁.trans hW₁V, hW₂g, hxW₂, c, ?_⟩
  -- the section of `F` that the generators write out
  have hu : F.presheaf.map (homOfLE hW₂).op
      (F.presheaf.map (homOfLE (inf_le_left : W₁ ⊓ basicOpen 𝒜 g ≤ W₁)).op
        (r • F.presheaf.map (homOfLE hW₁V).op t))
      = (Proj 𝒜).presheaf.map (homOfLE hW₂W₁).op r •
          F.presheaf.map (homOfLE (hW₂W₁.trans hW₁V)).op t := by
    rw [Scheme.Modules.resSection_trans, Scheme.Modules.resSection_smul,
      Scheme.Modules.resSection_trans]
  rw [hu] at hc
  -- the `O(N)` factor, restricted to `W₂`, is `(r|_{W₂}) • gᴺ / 1`
  have hw : (twistingSheaf 𝒜 (N : ℤ)).presheaf.map (homOfLE (hW₂W₁.trans hW₁V)).op w
      = (Proj 𝒜).presheaf.map (homOfLE hW₂W₁).op r •
          (show Γ(twistingSheaf 𝒜 (N : ℤ), W₂) from
            sectionOfMem 𝒜 𝒜 W₂ N (pow_mem_deg 𝒜 hg N)) := by
    rw [← Scheme.Modules.resSection_trans _ hW₁V hW₂W₁ w, ← hr,
      Scheme.Modules.resSection_smul]
    exact congrArg (fun z => (Proj 𝒜).presheaf.map (homOfLE hW₂W₁).op r • z)
      (res_sectionOfMem 𝒜 𝒜 hW₂W₁ N (pow_mem_deg 𝒜 hg N))
  rw [Scheme.Modules.res_tmulSection, hw, ← Scheme.Modules.smul_tmulSection,
    Scheme.Modules.smul_tmulSection_left, hc, Scheme.Modules.tmulSection_finset_sum_left]
  refine Finset.sum_congr rfl fun b _ => ?_
  rw [← Scheme.Modules.smul_tmulSection_left]
  have h3 := twistBy_app 𝒜 N (pow_mem_deg 𝒜 hg N) F (op W₂)
    (F.presheaf.map (homOfLE hW₂g).op (s b))
  exact congrArg (fun z => c b • z) (h3.symm.trans
    (Scheme.Modules.homApp_res (twistBy 𝒜 N (pow_mem_deg 𝒜 hg N) F) hW₂g (s b)).symm)

/-- **A sum over a sigma type supported on one fiber is the sum over that fiber.** -/
private theorem sum_sigma_eq_of_support {ι : Type*} [Fintype ι] [DecidableEq ι]
    {κ : ι → Type*} [∀ i, Fintype (κ i)] {G : Type*} [AddCommMonoid G] (i : ι)
    (f : (Σ j, κ j) → G) (c : κ i → G) (hf : ∀ b : κ i, f ⟨i, b⟩ = c b)
    (hf0 : ∀ a : Σ j, κ j, a.1 ≠ i → f a = 0) :
    ∑ a, f a = ∑ b, c b := by
  rw [Fintype.sum_sigma, Finset.sum_eq_single i]
  · exact Finset.sum_congr rfl fun b _ => hf b
  · intro j _ hj
    exact Finset.sum_eq_zero fun b _ => hf0 ⟨j, b⟩ hj
  · intro h
    exact absurd (Finset.mem_univ i) h

/-- **Serre's theorem, in the global-generation form: `F(N)` is a quotient of a finite free
sheaf for `N` large.**

For `𝒜` generated over `𝒜 0` by finitely many degree-one elements `g i` and `F` coherent on
`Proj 𝒜`, there are `N` and a finite `I` with an epimorphism `free I ↠ F ⊗ O(N)`.

Hartshorne II.5.17 / EGA II 2.7.9. The hypotheses are exactly the ones the chart lemmas take:
coherence, and the degree-one generating family with its finiteness. No global-generation or
resolution hypothesis enters anywhere, and no instance supplies the surjection. The index `I` is
the disjoint union over the charts of the chart generators, and `N` is the uniform exponent of
`exists_globalSection_twistBy_uniform`. -/
theorem exists_epi_free_tensorTwist (F : (Proj 𝒜).Modules)
    (hF : Scheme.Modules.IsCoherent (Proj 𝒜) F)
    {ι : Type u} [Finite ι] {g : ι → A} (hg : ∀ i, g i ∈ 𝒜 1)
    (hcov : Algebra.adjoin (𝒜 0) (Set.range g) = ⊤) :
    ∃ (N : ℕ) (I : Type u) (_ : Finite I)
      (p : SheafOfModules.free.{u} I ⟶ (show SheafOfModules (Proj 𝒜).ringCatSheaf from
        Scheme.Modules.tensorObj F (twistingSheaf 𝒜 (N : ℤ)))), Epi p := by
  classical
  cases nonempty_fintype ι
  haveI hFqc : SheafOfModules.IsQuasicoherent.{u, u, u}
      (show SheafOfModules (Proj 𝒜).ringCatSheaf from F) := by
    haveI : SheafOfModules.IsFinitePresentation.{u, u, u}
      (show SheafOfModules (Proj 𝒜).ringCatSheaf from F) := hF
    infer_instance
  -- finitely many generators on each chart
  choose κ hκ s hs using fun i =>
    exists_finite_generators_of_isCoherent 𝒜 F hF (hg i) (awayι_image_top 𝒜 (hg i) Nat.one_pos)
  letI : ∀ i, Fintype (κ i) := hκ
  -- one twist exponent carrying every generator of every chart to a global section
  obtain ⟨N, hN⟩ := exists_globalSection_twistBy_uniform 𝒜 F hg hcov
    (κ := Σ i, κ i) (f := fun a => g a.1) (fun a => hg a.1) Nat.one_pos (fun a => s a.1 a.2)
  choose σ hσ using hN
  refine ⟨1 * N, Σ i, κ i, inferInstance,
    (show SheafOfModules (Proj 𝒜).ringCatSheaf from
      Scheme.Modules.tensorObj F (twistingSheaf 𝒜 ((1 * N : ℕ) : ℤ))).freeHomEquiv.symm
      (fun a => Scheme.Modules.sectionsOfTop _ (σ a)), ?_⟩
  apply Scheme.Modules.epi_freeHomEquiv_symm_of_isLocalCombination
  intro U t x hx
  have hcover : ⨆ i, basicOpen 𝒜 (g i) = ⊤ :=
    iSup_basicOpen_eq_top' 𝒜 g (fun i => ⟨1, hg i⟩) hcov
  -- a section of the sheafified tensor is locally a finite sum of pure tensors
  obtain ⟨V₁, hV₁U, hxV₁, S, hS⟩ := Scheme.Modules.exists_eq_sum_tmulSection F
    (twistingSheaf 𝒜 ((1 * N : ℕ) : ℤ)) t x hx
  -- every pure tensor is locally a combination of the `σ`
  have hpure : ∀ p : Γ(F, V₁) × Γ(twistingSheaf 𝒜 ((1 * N : ℕ) : ℤ), V₁),
      Scheme.Modules.IsLocalCombination _ σ
        (Scheme.Modules.tmulSection F (twistingSheaf 𝒜 ((1 * N : ℕ) : ℤ)) (op V₁) p.1 p.2) := by
    intro p y hy
    have hy' : y ∈ ⨆ i, basicOpen 𝒜 (g i) := by
      rw [hcover]
      exact Opens.mem_top y
    obtain ⟨i, hyi⟩ := Opens.mem_iSup.mp hy'
    obtain ⟨W, hWV, hWg, hyW, c, hc⟩ :=
      exists_res_tmulSection_eq_sum 𝒜 F (hg i) (s i) (hs i) (1 * N) p.1 p.2 y hy hyi
    refine ⟨W, hWV, hyW, fun a => if h : a.1 = i then c (h ▸ a.2) else 0, ?_⟩
    rw [hc]
    symm
    refine sum_sigma_eq_of_support i _ _ (fun b => ?_) (fun a ha => ?_)
    · have hres := (Scheme.Modules.resSection_trans _ (le_top (a := basicOpen 𝒜 (g i))) hWg
        (σ ⟨i, b⟩)).symm
      have hσ' := hσ ⟨i, b⟩
      dsimp only at hσ' ⊢
      rw [dif_pos rfl, hres, hσ', twistBy_congr 𝒜 (1 * N)
        (congrArg (fun k => g i ^ k) (one_mul N).symm) (pow_mem_mul 𝒜 (hg i) N)
        (pow_mem_deg 𝒜 (hg i) (1 * N)) F]
    · dsimp only
      rw [dif_neg ha, zero_smul]
  have hsum := Scheme.Modules.IsLocalCombination.finset_sum (σ := σ) S _ (fun p _ => hpure p)
  obtain ⟨W, hWV₁, hxW, c, hc⟩ := hsum x hxV₁
  refine ⟨W, hWV₁.trans hV₁U, hxW, c, ?_⟩
  rw [← Scheme.Modules.resSection_trans _ hV₁U hWV₁ t, hS, hc]

/-- **Serre's theorem, phrased through `GeneratingSections`: `F(N)` has finitely many generating
sections for `N` large.** -/
theorem exists_generatingSections_tensorTwist (F : (Proj 𝒜).Modules)
    (hF : Scheme.Modules.IsCoherent (Proj 𝒜) F)
    {ι : Type u} [Finite ι] {g : ι → A} (hg : ∀ i, g i ∈ 𝒜 1)
    (hcov : Algebra.adjoin (𝒜 0) (Set.range g) = ⊤) :
    ∃ (N : ℕ) (σ : (show SheafOfModules (Proj 𝒜).ringCatSheaf from
      Scheme.Modules.tensorObj F (twistingSheaf 𝒜 (N : ℤ))).GeneratingSections),
      SheafOfModules.GeneratingSections.IsFiniteType.{u, u, u} σ := by
  obtain ⟨N, I, hI, p, hp⟩ := exists_epi_free_tensorTwist 𝒜 F hF hg hcov
  exact ⟨N, SheafOfModules.GeneratingSections.ofFreeEpi _ p, inferInstance⟩

end AlgebraicGeometry.Proj
